### ISSUE TITLE
Omit system call name if not useful for e.g. int3 instruction

### ISSUE THREAD

**Issue by martinclauss** [pwndbg/pwndbg#1020]
When debugging a program that itself contains an `int3` instruction the following output might be generated:

```
 ► 0x555555555361 <main+49>    int3    <SYS_write>
```

in the `[ DISASM ]` section. `SYS_write` does not make any sense and might be confusing since `int3` is just a simple instructions that has no interpretation for `RAX` but this is done here. Maye it is possible to check the type of the `int` instruction (https://www.felixcloutier.com/x86/intn:into:int3:int1) and just omit the system call name in those cases.

Best regards

**Comment by disconnect3d** [comment]
Hey,

Thanks for reporting this. This is the code that is related to this issue:
https://github.com/pwndbg/pwndbg/blob/ee1f0e493c19d87d223b0970f9edfa88e880053a/pwndbg/arguments.py#L53-L64

We determine the instruction types by disassembling them with the [capstone engine](https://www.capstone-engine.org/) (4.x currently) and for `int3` and `int 0x80` and `syscall` instructions it always return just one group: the interrupt group. So it sadly does not recognize the syscall interrupts by itself. I have added an issue for them in https://github.com/capstone-engine/capstone/issues/1896 but I am not sure if it ever gets added (as in: does it make sense to add it? Are other architectures using it? Etc.).

Fwiw this capstone behavior can also be soon with its [`cstool`](https://github.com/capstone-engine/capstone/tree/master/cstool) utility (install via `apt install capstone-tool`) and `pwntools` (install via `pip install pwntools`):
```
$ cstool -d x64 0x`pwn asm -f hex "int3"`
0  cc                                int3	
	Prefix:0x00 0x00 0x00 0x00 
	Opcode:0xcc 0x00 0x00 0x00 
	rex: 0x0
	addr_size: 8
	modrm: 0x0
	disp: 0x0
	sib: 0x0
	Groups: int 

$ cstool -d x64 0x`pwn asm -f hex "int 0x80"`
0  cd 80                              int	0x80
	Prefix:0x00 0x00 0x00 0x00 
	Opcode:0xcd 0x00 0x00 0x00 
	rex: 0x0
	addr_size: 8
	modrm: 0x0
	disp: 0x0
	sib: 0x0
	imm_count: 1
		imms[1]: 0x80
	op_count: 1
		operands[0].type: IMM = 0x80
		operands[0].size: 8
	Groups: int 

$ cstool -d x64 0x`pwn asm -f hex "syscall"`
0  0f 05                              syscall	
	Prefix:0x00 0x00 0x00 0x00 
	Opcode:0x0f 0x05 0x00 0x00 
	rex: 0x0
	addr_size: 8
	modrm: 0x0
	disp: 0x0
	sib: 0x0
	Groups: int 
```

So what can we do? We could add something like this into the `get_syscall_name` function:
```python
if pwndbg.current.arch in ('i386', 'x86-64') and instruction not in (int80, syscall):
    return
```

And I think I will just add it... :)

**Comment by martinclauss** [comment]
Awesome, thanks a lot for looking into it :) I think this is a good workaround for now (in the end it's a minor thing but you know... ^^). And let's see if the capstone people are interested ;) Thanks again for your time and effort!

**Comment by disconnect3d** [comment]
Added
