### ISSUE TITLE
ERROR: GDB exited unexpectedly. Debugging will now abort.

### ISSUE THREAD

**Issue by wallds** [pwndbg/pwndbg#1026]
### Description
![image](https://user-images.githubusercontent.com/12907032/176160071-6880e656-07de-4f27-91e2-ef1c09076cd4.png)

I tested the original GDB and GEF, it works fine.
It seems to be a problem with UBUNTU-22.04 LTS, which works fine on UBUNTU-20.04.4 LTS.
### Steps to reproduce

set a breakpoint and run it.

### My setup
```
pwndbg> version
Gdb:      12.0.90
Python:   3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]
Pwndbg:   1.1.0 build: f2fcc95
Capstone: 5.0.1280
Unicorn:  2.0.7
```
WSL UBUNTU-22.04 LTS

**Comment by disconnect3d** [comment]
Huh. Can you maybe try investigate it what it can be? Can you try setting `set debug-events on` or add prints to some functions to see where it comes from? 

Do you know if it works out of WSL on that Ubuntu version? I don't have Windows machine nearby to test WSL.

**Comment by wallds** [comment]
Thank you for your reply. 

[debug_events_log.txt](https://github.com/pwndbg/pwndbg/files/9000688/debug_events_log.txt)

![image](https://user-images.githubusercontent.com/12907032/176171805-8e6df139-57dc-40fb-aa79-3cb35c849121.png)

**Comment by disconnect3d** [comment]
Hm... can you try disabling some functionality/commenting out files or adding prints to see if it is about them?

**Comment by wallds** [comment]
https://github.com/pwndbg/pwndbg/blob/f2fcc95c64f97f6fa27c0b4d845c806b152ed30b/pwndbg/__init__.py#L140
![1](https://user-images.githubusercontent.com/12907032/178386477-f161593f-cbab-4d9d-bddb-11c96981ac47.gif)

Thanks for your guidance, I found the code that triggered the problem, but it seems to be a problem with `GDB` or `vscode-cpptools`.
