### ISSUE TITLE
aarch64 miss x30 register

### ISSUE THREAD

**Issue by junknet** [pwndbg/pwndbg#1039]
pwndbg version 2022.01.05-1
OS: Linux junknet-manjaro 5.15.53-1-MANJARO #1 SMP PREEMPT Thu Jul 7 16:56:55 UTC 2022 x86_64 GNU/Linux
![2022-07-19_12-26](https://user-images.githubusercontent.com/55597646/179664887-d42b3d08-3462-42d7-a503-8d3df7fef612.png)
![2022-07-19_12-27](https://user-images.githubusercontent.com/55597646/179664912-96b87500-d254-4b46-896f-f9c1df44d28b.png)

**Comment by disconnect3d** [comment]
Btw what's the exact CPU? Is that X30 some kind of special register?

This can be fixed easily by adding 'x30' here: https://github.com/pwndbg/pwndbg/blob/8cc0ab8b48c8a4d020c4b9215355cdc6f30eb0f3/pwndbg/regs.py#L106-L118

**Comment by junknet** [comment]
> 
CPU: Snapdragon 855
X29 == fp
X30 == lr 
X31 == sp

**Comment by junknet** [comment]
> 

CPU: Snapdragon 855
X29 == fp
X30 == lr
X31 == sp

**Comment by disconnect3d** [comment]
@junknet can you just add it to the regs spec? Also are all other ARM64 having this reg?

**Comment by junknet** [comment]
> @junknet can you just add it to the regs spec? Also are all other ARM64 having this reg?

Yes, this is the register used by the AARCH64 instruction set (RET).
This is my modification and effect drawing.
![2022-07-30_16-28](https://user-images.githubusercontent.com/55597646/181898649-151a440d-2dad-4143-93b2-4d68cf47c411.png)
![2022-07-30_16-28_1](https://user-images.githubusercontent.com/55597646/181898753-67748012-f5bf-4b33-a0f4-5710d220927d.png)

**Comment by disconnect3d** [comment]
@junknet Sure, let's add X30 to the list.

But, does it make sense to display X29 separately if it is the same register as SP?

**Comment by disconnect3d** [comment]
Added in https://github.com/pwndbg/pwndbg/commit/d2b2523695a19b85487b91659668b7a94e84dc6c

Shall we close this issue? WDYT about X29?

**Comment by disconnect3d** [comment]
We could maybe add a TIP informing about it here: https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/tips.py#L3-L9 :D

**Comment by junknet** [comment]
>  @disconnect3d 

This is the effect of not modifying X29.
![2022-08-07_09-41](https://user-images.githubusercontent.com/55597646/183271459-2a6cf843-6af2-4586-8e8e-e672784a56eb.png)
![2022-08-07_09-40](https://user-images.githubusercontent.com/55597646/183271462-8d5cb305-9a07-48d7-9977-fb35b7213c34.png)

X28 x29 x30 display order error.
So I just annotated "frame   = 'x29',"

**Comment by disconnect3d** [comment]
@junknet Fixed in #1054. Thanks for reporting this and looking into it!
