### ISSUE TITLE
Option for `find_fast_chunk` to find aligned chunks

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#1041]
When I'm looking for a fastbin chunk to free, I need to make sure it's aligned. More generally, I want the chunk returned by `find_fast_chunk` to satisfy all the constraints checked by `try_free`. It'd be useful if there was an option that only returned fastbin chunks that could be freed without failing any glibc checks.

**Comment by disconnect3d** [comment]
@gsingh93 can you add the code related to it to our heap code? also, u should probably rely on the latest heap PR (we will merge it soon)
