### ISSUE TITLE
Cleanup the $heap_base feature

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#1060]
Adding some cleanup suggestions for the $heap_base feature from #1051:
```
- Check if the user has already set a convenience variable of the same name, either with init-if-undefined or gdb.convenience_variable("heap_base"). This way we won't break user scripts.
- Consider using gdb.set_convenience_variable("heap_base", <value>) in place of gdb.execute()
- Perhaps $heap_base could be populated on heap initialization, rather than after running one specific heap command
```

Also would be good to add some docs about this feature.

**Comment by disconnect3d** [comment]
FWIW the `gdb.set_convenience_variable` API function was added in GDB 8.2.

This can be seen in 8.2 release notes:
* https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blob_plain;f=gdb/NEWS;hb=gdb-8.2-release
* or by checking up the versions the exact commit that added convenience variable API landed: https://github.com/bminor/binutils-gdb/commit/7729052b5377bfbf1c5ec5eaab59dd5071d4c5b1

**Comment by gsingh93** [comment]
I think this feature got removed during some of the heap refactoring. @CptGibbon can you confirm?

**Comment by CptGibbon** [comment]
Oh let me check the blame
Yes it got removed in f71a4aa65d8a1d4c0bc82848fab2ce65c23e3f77 when the `heap` command was refactored (by me), apologies 😳

**Comment by disconnect3d** [comment]
Fwiw one can read heap base as:
```
pwndbg> p/x $base("heap")
$2 = 0x555555577000
```

**Comment by disconnect3d** [comment]
Also if we really want to add `$heap_base` I'd name it just `$heap`.

**Comment by gsingh93** [comment]
`$base` works for me
