### ISSUE TITLE
Split production and dev dependencies

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#1077]
Our installer currently installs whatever packages are listed in requirements.txt. However, at some point we put `pytest` there and we then updated and freezed all dependencies.

There are two issues here:
1 Obviously, installing test dependencies for user installation is bad. 
2. Some of those packages may not be installable on Ubuntu 18.04 that still gets security updates. We want to support it and make sure it works properly. I'm not sure what are all of those packages yet, but so far it has been testing packages that did not work.

**Comment by disconnect3d** [comment]
Just to be sure: all tests deps should be installed by the `./setup-test-tools.sh` script.

**Comment by gsingh93** [comment]
FYI, seems like we also need to `pip install coverage` as a test dependency.

**Comment by disconnect3d** [comment]
This has been done in https://github.com/pwndbg/pwndbg/commit/2bde0cc1d80860a4f4662baad9b256d9885a1bf9 and a future commit
