### ISSUE TITLE
It should be possible to filter tests run in ./tests.sh and run them with pdb

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#1085]
The `./tests.sh` should allow for two additional arguments:
* `<test-name-regex>` to filter the tests that will be run by part of their name
* `--pdb` to enable the `--pdb` flag in `pytests_launcher.py` here:
https://github.com/pwndbg/pwndbg/blob/b51b07de77c687bc513f1f30e7134c40f01afb2b/pytests_launcher.py#L15-L16

Both of those flags should be optional. They will allow for faster testing of things locally :).

Oh, and `tests.sh` should probably support `-h` and `--help` :D.

**Comment by artcz** [comment]
o/

**Comment by disconnect3d** [comment]
Added in https://github.com/pwndbg/pwndbg/pull/1092
