### ISSUE TITLE
unhashable type: 'dict' with telescope

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#111]
Run `gdb /bin/ls`, then `start`, then run the following commands

```
pwndbg> pi 0x50
80
pwndbg> telescope $rsp-0x50
00:0000│   0x7fffffffe1a8 —▸ 0x755e871f
01:0008│   0x7fffffffe1b0 —▸ 0xa95
02:0010│   0x7fffffffe1b8 —▸ 0x755e91a8
03:0018│   0x7fffffffe1c0 —▸ 0x240ae755e91a8
04:0020│   0x7fffffffe1c8 ◂— 0x7ffff7ddecc8 (_dl_start+648) —▸ mov    rbx, rax
05:0028│   0x7fffffffe1d0 —▸ 0x240ae
06:0030│   0x7fffffffe1d8 —▸ 0x0
07:0038│   0x7fffffffe1e0 —▸ 0x240ae
pwndbg> telescope $rsp-80.0
unhashable type: 'dict'
00:0000│ rsp  0x7fffffffe1f8 ◂— 0x7ffff7dea0cd (call_init.part+93) —▸ mov    rdx, qword ptr [rbx + 0x108]
01:0008│      0x7fffffffe200 —▸ 0x6
02:0010│      0x7fffffffe208 —▸ 0x1
03:0018│      0x7fffffffe210 ◂— 0x7fffffffe278 ◂— 0x7fffffffe4bf —▸ 0x736c2f6e69622f /* '/bin/ls' */
04:0020│      0x7fffffffe218 ◂— 0x7fffffffe288 ◂— 0x7fffffffe4c7 —▸ 'XDG_SESSION_ID=...'
05:0028│      0x7fffffffe220 ◂— 0x7ffff7ffe1c8 —▸ 0x0
06:0030│      0x7fffffffe228 ◂— 0x7ffff7dea1f3 (_dl_init_internal+115) —▸ jmp    0x7ffff7dea1c8
07:0038│      0x7fffffffe230 —▸ 0x0
```

The output should be the same, but it's not. Also, there's the error "unhashable type: dict"

**Comment by disconnect3d** [comment]
The telescope command gets weird arguments (see screenshot below) - it can be seen after adding prints to it:
```python
@pwndbg.commands.ParsedCommand
@pwndbg.commands.OnlyWhenRunning
def telescope(address=None, count=telescope_lines, to_string=False):
    """
    Recursively dereferences pointers starting at the specified address
    ($sp by default)
    """
    print(address, count, to_string)
    address = int(address if address else pwndbg.regs.sp) & pwndbg.arch.ptrmask
    count   = int(count) & pwndbg.arch.ptrmask
    print(address, count, to_string)
    delimiter = T.delimiter(offset_delimiter)
    separator = T.separator(offset_separator)
```

![pwndbg](https://cloud.githubusercontent.com/assets/10009354/18685230/6e94d9a8-7f77-11e6-84ad-5897f91731a2.png)

After some more digging I have found that the exception is thrown in `pwndbg/commands/__init__.py` in `fix` function when `pwndbg.regs.fix(arg)` is called. The `arg` is just a string of `$rsp-80.0` in there.

Lets look over `pwndbg.regs.fix`:
```python
    def fix(self, expression):
        for regname in set(self.all + ['sp','pc']):
            expression = re.sub(r'\$?\b%s\b' % regname, r'$'+regname, expression)
        return expression
```

The expression in there is just the string `$rsp-80.0`. The exception is thrown on `set(self.all + ['sp', 'pc'])`.
The `self.all` in there is `['rip', 'rsp', 'rbp', {'eflags': {'SF': 7, 'CF': 0, 'DF': 10, 'ZF': 6, 'PF': 2, 'OF': 11, 'IF': 9, 'AF': 4}}, 'rax', 'rbx', 'rcx', 'rdx', 'rdi', 'rsi', 'r8', 'r9', 'r10', 'r11', 'r12', 'r13', 'r14', 'r15', 'cs', 'ss', 'ds', 'es', 'fs', 'gs', 'fsbase', 'gsbase', 'ax', 'ah', 'al', 'bx', 'bh', 'bl', 'cx', 'ch', 'cl', 'dx', 'dh', 'dl', 'dil', 'sil', 'spl', 'bpl', 'di', 'si', 'bp', 'sp', 'ip']`.

So here is the unwanted dict.

What is a bit weird for me, why does the `self.all` is a list and not a set?

As we can see below, it seems to be referencing a set:
```
dc@dc:~/pwndbg$ git grep "[.]all"
pwndbg/emu/emulator.py:        if reg in self.regs.all:
pwndbg/regs.py:        self.all = set(i for i in misc) | set(flags) | set(self.common)
pwndbg/regs.py:        self.all -= {None}
pwndbg/regs.py:        for r in self.all:
pwndbg/regs.py:        for regname in set(self.all + ['sp','pc']):
pwndbg/regs.py:        for regname in self.all:
```

@zachriggle Any suggestions on how to fix that? Either something with `self.all` must be fixed or the proper names must be retrieved from dict.

If all the names should be retrieved from dict, maybe this is the solution (maybe is a better way to do that):
```python
In [17]: a = ['a','b', {'x': {'c': 1, 'd': 2}}]

In [18]: b = chain.from_iterable(chain.from_iterable((i if isinstance(i, str) else (j.keys() for j in i.values()) for i in a)))

In [19]: list(b)
Out[19]: ['a', 'b', 'c', 'd']
```

By the way, after changing `self.all` into `['rsp']` just for a sake of checking what will happen, a proper gdb(?) error occured:
```
Argument to arithmetic operation not a number or boolean.
```

**Comment by zachriggle** [comment]
Hmm, I'm not sure why `eflags` is showing up that way.  It seems that I can just fix that, no?  `.all` is just supposed to be register names.

**Comment by disconnect3d** [comment]
@zachriggle The result:
```
pwndbg> telescope $rsp-80.0
Argument to arithmetic operation not a number or boolean.
00:0000│ rsp  0x7fffffffe2b8 ◂— 0x7ffff7de958d (call_init.part+93) —▸ mov    rdx, qword ptr [r14 + 0x108]
01:0008│      0x7fffffffe2c0 —▸ 0x7
02:0010│      0x7fffffffe2c8 —▸ 0x1
03:0018│      0x7fffffffe2d0 ◂— 0x7fffffffe338 ◂— 0x7fffffffe59a —▸ 0x736c2f6e69622f /* '/bin/ls' */
04:0020│      0x7fffffffe2d8 ◂— 0x7fffffffe348 ◂— 0x7fffffffe5a2 —▸ 'ORBIT_SOCKETDIR...'
05:0028│      0x7fffffffe2e0 ◂— 0x7ffff7ffe188 —▸ 0x0
06:0030│      0x7fffffffe2e8 ◂— 0x7ffff7de96db (_dl_init+139) —▸ jmp    0x7ffff7de96b0
07:0038│      0x7fffffffe2f0 —▸ 0x0
pwndbg> telescope $rsp-0x50
00:0000│   0x7fffffffe268 —▸ 0x0
... ↓
02:0010│   0x7fffffffe278 —▸ 0x10000004
03:0018│   0x7fffffffe280 —▸ 0x0
04:0020│   0x7fffffffe288 —▸ 0x1
05:0028│   0x7fffffffe290 —▸ 0x0
06:0030│   0x7fffffffe298 —▸ 0x1
07:0038│   0x7fffffffe2a0 ◂— 0x7ffff6f65b60 (__pthread_init_array) ◂— 0x7ffff6d5f9b0 (elision_init) —▸ sub    rsp, 8
pwndbg> 
```

Maybe we shouldn't show anything when an exception is thrown?

**Comment by zachriggle** [comment]
@disconnect3d: I'd rather have it show errors that we can fix than fail silently in weird ways :-\

**Comment by disconnect3d** [comment]
Oh, I meant to stop showing the weird output - just leave it with bare `Argument to arithmetic operation not a number or boolean.` (or even fix that to work with float/double values).

**Comment by zachriggle** [comment]
There's no way around the output.  It cannot be squelched, as it's a GDB-internal error.


```
pwndbg> p $rsp-80.0
Argument to arithmetic operation not a number or boolean.
```

The same is effectively invoked here: 
This is the line that raises that error message: https://github.com/pwndbg/pwndbg/blob/ced1734e526ee0c9a6f90186836fef80a792052e/pwndbg/commands/__init__.py#L87

```py
    try:
        parsed = gdb.parse_and_eval(arg)
        return parsed
    except Exception:
        pass
```

However, it's already wrapped in an exception handler --- there's nothing more that can be added.  I think we're just at the whim and will of GDB here.

**Comment by zachriggle** [comment]
(Deleted my previous, incorrect comment)

**Comment by zachriggle** [comment]
So the reason that `telescope $rsp-80.0` works, but incorrectly, is that `telescope` without any arguments prints from `$rsp`.

We hit the error case and `fix` correctly returns `None`.  However, `pwndbg.commands.telescope.telescope()` treats a `None` first argument to imply no argument was provided.

We can squelch the errors by setting `pwndbg.commands._ParsedCommand.quiet=True`.

**Comment by zachriggle** [comment]
I suppose at that point, the issue becomes whether `pwndbg.commands.fix` should return `None` or raise the exception

**Comment by zachriggle** [comment]
Nah, that's even worse.  If we raise the exception we get roughly equivalent output, twice.

```
pwndbg> telescope $sp-80.0
Python Exception <class 'gdb.error'> Argument to arithmetic operation not a number or boolean.:
Error occurred in Python command: Argument to arithmetic operation not a number or boolean.
```

**Comment by zachriggle** [comment]
Ultimately, I think the reason for this even existing is the default radix of `0x10`, which required @gsingh93 to use decimal.

This was fixed in two ways:

- The default radix is no longer changed as of the most recent release (`p/x 11` prints `0xb`)
- Decimal radix can be manually selected via `0d1234`

Since the original issue is resolved ("unhashable dict") and I think I've provided a work-around for the reason it even came up (use `0d80` instead of `80.`, or use a decimal radix -- which is now the default -- I'm closing this issue).
