### ISSUE TITLE
Error: No auxiliary vector found, or failed reading it. (<class 'gdb.error'>) and the weird vmmap question

### ISSUE THREAD

**Issue by Erebua** [pwndbg/pwndbg#1110]
### Description
Error: No auxiliary vector found, or failed reading it. (<class 'gdb.error'>) in https://github.com/pwndbg/pwndbg/issues/954

I have met a weird vmmap after [#1107](https://github.com/pwndbg/pwndbg/pull/1107)
output like this
```
pwndbg> vmmap
LEGEND: STACK | HEAP | CODE | DATA | RWX | RODATA
       0x0       0x5a r--p       5a d38    .comment
      0x5a       0x5a r--p        0 d92    .mdebug.abi32
  0x4000f4   0x400108 rw-p       14 f4     .interp
  0x400108   0x400120 rw-p       18 108    .reginfo
  0x400120   0x400218 rw-p       f8 120    .dynamic
  0x400218   0x4002c4 rw-p       ac 218    .hash
  0x4002c4   0x400444 rw-p      180 2c4    .dynsym
  0x400444   0x40054a rw-p      106 444    .dynstr
  0x40054a   0x40057a rw-p       30 54a    .gnu.version
  0x40057c   0x40059c rw-p       20 57c    .gnu.version_r
  0x40059c   0x400624 r-xp       88 59c    .init
  0x400630   0x400a30 r-xp      400 630    .text
  0x400a30   0x400ab0 r-xp       80 a30    .MIPS.stubs
  0x400ab0   0x400b08 r-xp       58 ab0    .fini
  0x400b10   0x400c90 rw-p      180 b10    .rodata
  0x400c90   0x400c94 rw-p        4 c90    .eh_frame
  0x440c94   0x440c9c -w-p        8 c94    .ctors
  0x440c9c   0x440ca4 -w-p        8 c9c    .dtors
  0x440ca4   0x440ca8 -w-p        4 ca4    .jcr
  0x440cb0   0x440cd0 -w-p       20 cb0    .data
  0x440cd0   0x440cd4 -w-p        4 cd0    .rld_map
  0x440ce0   0x440d34 -w-p       54 ce0    .got
  0x440d34   0x440d38 -w-p        4 d34    .sdata
  0x440d40   0x440d60 ---p       20 d38    .bss
0x7743e000 0x77443000 rwxp     5000 0      <explored>
0x7f776000 0x7fb77000 rwxp   401000 0      <explored>

```

### Steps to reproduce
This is my [vmware_file](https://drive.google.com/file/d/1MSm-rjIS0bxGVta5bGpp2k2iTUVgCO6d/view) which has this issue.(snapshot)
user: iot
password: attify

I use this shell to start qemu-system-mipsel
path : /home/iot/Desktop/mipsel/start.sh
```
#!/bin/bash
sudo qemu-system-mipsel \
    -M malta -kernel vmlinux-3.2.0-4-4kc-malta \
    -hda debian_squeeze_mipsel_standard.qcow2 \
    -append "root=/dev/sda1 console=tty0" \
    -net nic,macaddr=00:16:3e:00:00:01 \
    -net tap
```
`vmlinux-3.2.0-4-4kc-malta` and `debian_squeeze_mipsel_standard.qcow2`  is from https://people.debian.org/~aurel32/qemu/mipsel/

then upload my file to qemu
```
scp -r /home/iot/Desktop/dvrf/squashfs-root root@192.168.134.143:/root/
scp gdbserver root@192.168.134.143:/root/squashfs-root
```
`squashfs-root` is from https://github.com/praetorian-inc/DVRF/blob/master/Firmware/DVRF_v03.bin
```
binwalk -Me ./DVRF_v03.bin
```

in the qemu-system-mipsel
```
cd /root/squashfs-root
chroot . ./gdbserver 192.168.134.142:6666 ./pwnable/Intro/stack_bof_01 "aaaa"
#this ip is attifyos
```

attifyos
```
gdb-multiarch
set arch mips
target remote 192.168.134.143:6666
vmmap
#this ip is qemu-system-mipsel
```
### My setup

gdbserver
```
GNU gdbserver 6.8
configured as "mipsel-linux-uclibc"
```

pwndbg
```
Gdb:      8.1.1
Python:   3.6.9 (default, Nov  7 2019, 10:44:02)  [GCC 8.3.0]
Pwndbg:   1.1.1
Capstone: 4.0.1024
Unicorn:  2.0.7
```

**Comment by syheliel** [comment]
Can you run `info auxv` in gdb and list the output? #1107 doesn't bring some changes to the execution.

**Comment by disconnect3d** [comment]
@Erebua 
> squashfs-root is from https://github.com/praetorian-inc/DVRF/blob/master/Firmware/DVRF_v03.bin
> binwalk -Me ./DVRF_v03.bin

This command does produce only an empty squashfs-root directory, so I can't get the gdbserver from it, can you upload the squashfs-root somewhere?

**Comment by Erebua** [comment]
> @Erebua
> 
> > squashfs-root is from https://github.com/praetorian-inc/DVRF/blob/master/Firmware/DVRF_v03.bin
> > binwalk -Me ./DVRF_v03.bin
> 
> This command does produce only an empty squashfs-root directory, so I can't get the gdbserver from it, can you upload the squashfs-root somewhere?

https://drive.google.com/file/d/14teHPw0L8JM51d0cNCI7acu7I8YEA36r/view?usp=sharing

**Comment by Erebua** [comment]
> info auxv

:(
```
pwndbg> info auxv
No auxiliary vector found, or failed reading it.

```

**Comment by syheliel** [comment]
It seems like a bug of gdb. I'm not sure if it is a desired behavior. You can report the bug in https://sourceware.org/bugzilla/

**Comment by syheliel** [comment]
Also, try to upgrade your gdb. The lastest gdb is 12.x now

**Comment by Erebua** [comment]
> Also, try to upgrade your gdb. The lastest gdb is 12.x now

I updated my gdb version to 12.09 and I tried `echo 0 > /proc/sys/kernel/randomize_va_space`.But it didn't work.
Anyway, thank you for your help

```
Gdb:      12.0.90
Python:   3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
Pwndbg:   1.1.1 build: 2d483fc
Capstone: 4.0.1024
Unicorn:  2.0.0
```

**Comment by disconnect3d** [comment]
@syheliel I think it is not a GDB bug. There are some valid reasons like "no stack available" and there may be others for GDB to not be able to return the AUXV information to you. See https://github.com/bminor/binutils-gdb/blob/d17823bfd35adb4caf3724512c3cd40a5a66402e/gdb/auxv.c#L576-L590

@Erebua One last thing related to the qemu-system environment: any help how to setup the network properly so I can connect to within the VM from my host? The flags you provided do not seem to work for me :/

**Comment by Erebua** [comment]
> @syheliel I think it is not a GDB bug. There are some valid reasons like "no stack available" and there may be others for GDB to not be able to return the AUXV information to you. See https://github.com/bminor/binutils-gdb/blob/d17823bfd35adb4caf3724512c3cd40a5a66402e/gdb/auxv.c#L576-L590
> 
> @Erebua One last thing related to the qemu-system environment: any help how to setup the network properly so I can connect to within the VM from my host? The flags you provided do not seem to work for me :/

@disconnect3d Here it's my network [configuration](https://64.112.41.197/qemu-system_network.html).

**Comment by Erebua** [comment]
@disconnect3d I found a new version of [dvrf ](https://github.com/b1ack0wl/DVRF)yesterday, then I tried to debug it with qemu-system.But the vmmap is still not work at all.Anyway I can get libc_base now.(I don't know why the libc_base_address shown below is wrong).
```
pwndbg> vmmap
LEGEND: STACK | HEAP | CODE | DATA | RWX | RODATA
       0x0       0x5a r--p       5a be4    .comment
      0x5a       0x5a r--p        0 c3e    .mdebug.abi32
  0x4000f4   0x400108 rw-p       14 f4     .interp
  0x400108   0x400120 rw-p       18 108    .reginfo
  0x400120   0x400220 rw-p      100 120    .dynamic
  0x400220   0x4002c8 rw-p       a8 220    .hash
  0x4002c8   0x400438 rw-p      170 2c8    .dynsym
  0x400438   0x400547 rw-p      10f 438    .dynstr
  0x400548   0x400576 rw-p       2e 548    .gnu.version
  0x400578   0x400598 rw-p       20 578    .gnu.version_r
  0x400598   0x400620 r-xp       88 598    .init
  0x400620   0x4009c0 r-xp      3a0 620    .text
  0x4009c0   0x400a30 r-xp       70 9c0    .MIPS.stubs
  0x400a30   0x400a88 r-xp       58 a30    .fini
  0x400a90   0x400b40 rw-p       b0 a90    .rodata
  0x400b40   0x400b44 rw-p        4 b40    .eh_frame
  0x440b44   0x440b4c -w-p        8 b44    .ctors
  0x440b4c   0x440b54 -w-p        8 b4c    .dtors
  0x440b54   0x440b58 -w-p        4 b54    .jcr
  0x440b60   0x440b80 -w-p       20 b60    .data
  0x440b80   0x440b84 -w-p        4 b80    .rld_map
  0x440b90   0x440be0 -w-p       50 b90    .got
  0x440be0   0x440be4 -w-p        4 be0    .sdata
  0x440bf0   0x440c10 ---p       20 be4    .bss
0x77603000 0x77733000 rwxp   130000 0      <explored>
0x7772e000 0x77733000 rwxp     5000 0      <explored>
0x77771000 0x77774000 rwxp     3000 0      <explored>
0x7f6d5000 0x7fcfc000 rwxp   627000 0      <explored>
0x7fad3000 0x7fed5000 rwxp   402000 0      <explored>
pwndbg> info sharedlibrary 
From        To          Syms Read   Shared Object Library
0x7772ea80  0x77732800  Yes (*)     target:/lib/ld-uClibc.so.0
0x776d4580  0x776ea140  Yes (*)     target:/usr/lib/libbcmcrypto.so
0x77684b00  0x77691c20  Yes (*)     target:/lib/libgcc_s.so.1
0x77609710  0x7763a8a0  Yes (*)     target:/lib/libc.so.0
(*): Shared library is missing debugging information.
pwndbg> info auxv
No auxiliary vector found, or failed reading it.
pwndbg> p &memset
$1 = (<text variable, no debug info> *) 0x7761ee10 <memset>
pwndbg> python
>hex(0x7761ee10 - 0x1be10)
```

**Comment by disconnect3d** [comment]
Fwiw regarding "I don't know why the libc_base_address shown below is wrong" if you are referring to the output of `info sharedlibrary`, then this is fetched via GDB. I suspect it does some weird tricks to detect those libs and that is why it may have so weird `From` and `To` values.

Also, any chance you can check how all this works on latest Pwndbg versions? We made some changes to vmmap and other places and maybe this issue was fixed?

(It would be awesome to have some easier way of reproducing this...)

**Comment by Erebua** [comment]
> Fwiw regarding "I don't know why the libc_base_address shown below is wrong" if you are referring to the output of `info sharedlibrary`, then this is fetched via GDB. I suspect it does some weird tricks to detect those libs and that is why it may have so weird `From` and `To` values.
> 
> Also, any chance you can check how all this works on latest Pwndbg versions? We made some changes to vmmap and other places and maybe this issue was fixed?
> 
> (It would be awesome to have some easier way of reproducing this...)

It seems like a bug in the AttifyOS(Linux attifyos 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux).Pwndbg gave me the correct respone with the command vmmap when I used the same version of gdb and pwndbg in Ubuntu20.04 ot do the same thing.It may also be the qemu affection.Anyway I don't think it's a bug of pwndbg, it's just some environment variable or tools affected it.At last , thank you for the help:)
