### ISSUE TITLE
`heap` & `malloc_chunk` commands are tightly coupled

### ISSUE THREAD

**Issue by CptGibbon** [pwndbg/pwndbg#1136]
## Description
pwndbg's `heap` command is a wrapper around its `malloc_chunk` command, in contrast to `vis_heap_chunks` which uses its own logic to read & print heap data.

`heap`'s reliance on `malloc_chunk` can lead to some unexpected behavior:

### `heap` prints zero-size chunks
![heap prints zero size chunks](https://user-images.githubusercontent.com/16000770/189243135-1e9b222a-451f-4c0a-8b76-ccf3cb5908c7.jpg)

Some might consider this useful though, perhaps it's worth discussing whether `heap` should ignore corrupt zero-size chunks by default, produce a warning etc.

### `heap` can read off the end of a heap
![heap reads off end of heap](https://user-images.githubusercontent.com/16000770/189243630-f9e86598-fccf-45ec-9679-407ea1e2689e.jpg)

Since `malloc_chunk` has no context beyond the address you give it, it will attempt to read whatever is there. In some cases, this can lead to `heap` attempting to print chunks from unmapped memory (e.g. when printing an exhausted heap).

This one is probably fixable in the `heap` command code, `vis_heap_chunks` contains a guard against this behavior that could serve as a template: https://github.com/pwndbg/pwndbg/blob/bf37c03d8de94c9ea629fd7ad2125695c693c288/pwndbg/commands/heap.py#L667-L670

### `malloc_chunk` isn't context-aware
By this I mean it doesn't know anything about the chunk you're trying to print (such as its parent heap or arena). `malloc_chunk` attempts to gather this information each time it's invoked by `heap`, which means it's finding a chunk's heap & arena once for **every chunk** on the heap being printed. This can lead to situations where `malloc_chunk` considers chunks on the same heap belonging to different arenas, shown below (`[DEBUG]` lines are my own and not part of the default `heap` command output):

![heap command issue](https://user-images.githubusercontent.com/16000770/189244628-bcb7fbb6-f024-464a-85e5-d1e0e575de8f.jpg)

The correct arena for these chunks is the one at `0x7ffff0000020`, but the main arena (underlined in green) is incorrectly used intermittently. This has a further side effect of `malloc_chunk` (and therefore `heap`) not annotating some top chunks and free chunks, also shown in the screenshot above.

### Possible solution
This last issue is a tough one, since it's rooted in the problem of determining a chunk's parent heap & arena from a single address, which is harder than it sounds and may require a heuristic approach. For now, decoupling the `heap` and `malloc_chunk` commands by separating out the printing logic into a private class method could help, along with some bounds checking in `heap` to address the 2nd issue.

**Comment by gsingh93** [comment]
This doesn't address all of your points, but I'd suggest we move logic regarding iteration over the heap into the heap class itself, like this: https://github.com/gsingh93/pwndbg/blob/0268e3196468c0e6d72452a527ab3bf5e6fd1293/pwndbg/commands/heap.py#L125-L126

Any bounds checking in `vis_heap_chunks` will then be reused in the `heap` command.

> it's finding a chunk's heap & arena once for every chunk on the heap being printed. This can lead to situations where malloc_chunk considers chunks on the same heap belonging to different arenas

I'm not an expert on this area, so I don't quite follow the reason why finding the heap and arena for every chunk would lead to having the wrong arena. Could you elaborate on that?

**Comment by CptGibbon** [comment]
>I'd suggest we move logic regarding iteration over the heap into the heap class itself

Agreed.

>why finding the heap and arena for every chunk would lead to having the wrong arena

In this specific case `get_arena_for_chunk()` (called by `malloc_chunk`) is relying on a chunk flag to determine arena ownership, but that flag isn't consistently set. There are also myriad other reasons that finding a chunk's parent arena is difficult.

`heap` could also be more efficient, there's no need to locate a parent arena more than once.
