### ISSUE TITLE
GLIBC_TUNABLES can confuse some heap commands

### ISSUE THREAD

**Issue by CptGibbon** [pwndbg/pwndbg#1143]
### Description
If GLIBC's `GLIBC_TUNABLES` [environment variable](https://www.gnu.org/software/libc/manual/html_node/Tunables.html) is set, ld copies its contents to memory requested via `sbrk()` during program initialization.

Because malloc's main arena also relies on `sbrk()` to request memory, the start of the main arena's heap is determined by the length of the `GLIBC_TUNABLES` string rounded up to the architecture's chunk alignment.

Importantly `mp_.sbrk_base` *isn't* rounded up, this affects some of pwndbg's heap commands such as `vis_heap_chunks` and `heap` because they rely on `mp_.sbrk_base` to find the start of the main arena's heap. Below is an example of how this issue can manifest:

![glibc tunables issue](https://user-images.githubusercontent.com/16000770/189514558-8269ff6d-38c4-419b-8910-e3b8a8f9cb11.jpg)

After setting the `GLIBC_TUNABLES` environment variable via GDB, the above program requests a single 0x20-size chunk. The `GLIBC_TUNABLES` string starts at the beginning of the `[heap]` region, followed by the main arena's heap at address `0x555555559020` which contains a tcache and 0x20-size chunk. Note that `mp_.sbrk_base` points to the end of the `GLIBC_TUNABLES` string, causing incorrect `vis_heap_chunks` and `heap` output. Be aware when testing this that later versions of GLIBC will reject incorrectly named tunables.

### Possible solution
When determining the start address of the main arena's heap, rounding `mp_.sbrk_base` up to the appropriate chunk alignment for the target architecture could mitigate this issue.

**Comment by disconnect3d** [comment]
This behavior can also be observed with our unit tests! :)

Running `GLIBC_TUNABLES='LMAO' ./tests.sh` will result in `test_try_free_double_free_tcache`, `test_heap_bins` failing and the `test_vis_heap_chunk_command` on halting/freezing the test (its probably executing something and would end up if I didn't CTRL+C it?). Example:

```
_________________________________________________________ test_try_free_double_free_tcache _________________________________________________________

start_binary = <function start_binary.<locals>._start_binary at 0x7fc517a60c80>

    def test_try_free_double_free_tcache(start_binary):
        chunks = setup_heap(start_binary, 5)

        result = gdb.execute("try_free {}".format(hex(chunks["a"])), to_string=True)
>       assert "Will do checks for tcache double-free" in result
E       AssertionError: assert 'Will do checks for tcache double-free' in 'General checks\nTcache checks\nFastbin checks\n----------\nAll checks passed!\n'

chunks     = {'a': 2126528,
 'b': 2126592,
 'c': 2126656,
 'd': 2126720,
 'e': 2130736,
 'f': 2134752,
 'g': 2138768}
result     = ('General checks\n'
 'Tcache checks\n'
 'Fastbin checks\n'
 '----------\n'
 'All checks passed!\n')
start_binary = <function start_binary.<locals>._start_binary at 0x7fc517a60c80>

tests/test_heap.py:133: AssertionError
```
