### ISSUE TITLE
Make it easier to work with PIE binaries

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#1144]
Currently, `pwndbg` supports the `breakrva` command for setting breakpoints at a particular offset in a PIE binary. Because this is a custom command, it's missing out on some other breakpoint features GDB provides, like temporary breakpoints, breakpoint commands, conditional breakpoints, etc.

There are other things that are useful to do in a PIE binary where the `breakrva` command can't be used, like using `x` to examine some global memory.

One way to achieve this would be set a variable (i.e. `$binary_base` or something similar) when the file is loaded so that future commands can do `x $binary_base+0x100` to read relative to that base. We already set a `$heap_base` variable, and we could extend this even further to other mappings (i.e. `$libc_base`, etc.).

**Comment by disconnect3d** [comment]
GEF also has sth around that. iirc they have some custom bp related commands for that. Pls look at it as well and document it here.

**Comment by disconnect3d** [comment]
FWIW: function vs variable - I sometimes would be happy to be able to do sth like `break * ($vmmap("libchicken.so")+0x1234)` aka: set a bp in runtime determining the first vmmap of libchicken and offseting off that.

Ofc one could do this via `pi gdb.execute("bp *0x%x" % (next(v for v in pwndbg.vmmap.get() if "libchicken" in v.objfile) + 0x1234)` but meh.

Variables would not play nicely for that since there may be tons of libs/vmmaps. But maybe that's another thing.

**Comment by gsingh93** [comment]
I think that syntax could work. I don't like functions for things like this just because it's easy to add a variable in anywhere in the expression, but I think in this case it makes given that we want to be able to get the base address of any mapping.

**Comment by disconnect3d** [comment]
So maybe let's go with variables for known mappings and use short names for them?:
```
$base
$heap
$libc
$ldso
```

Any other useful ones? Also not sure if `$ldso` is so often used.

**Comment by gsingh93** [comment]
I think ld.so is starting to get used a bit more often nowadays, but I think it's fine to only have the first three in the list, and then as people ask for shorter ways of writing other mappings we can add them.

**Comment by gsingh93** [comment]
I guess when this gets implemented, we can remove the `$heap_base` stuff: https://github.com/pwndbg/pwndbg/issues/1060

**Comment by gsingh93** [comment]
I wonder if we can fix some of the issues with `breakrva` mentioned in the initial post by subclassing gdb.Breakpoint?

**Comment by disconnect3d** [comment]
We have `$base` and `$rebase`. I believe we can close this now as finished? @gsingh93 

<img width="761" alt="image" src="https://github.com/user-attachments/assets/1e9b161f-475c-4988-9dd2-1017c2c23ed3">

**Comment by disconnect3d** [comment]
Please reopen if u think we can do more on here.
