### ISSUE TITLE
the context did not print out LR ( link register) while debugging ARM binary

### ISSUE THREAD

**Issue by bruce30262** [pwndbg/pwndbg#115]
<img width="317" src="https://cloud.githubusercontent.com/assets/4478350/18794874/4ee57eda-81f4-11e6-9e25-df1126e3b616.png">  
  
As you can see in the picture, pwndbg did not print out the link register ( r14 ) while debugging the ARM binary . I thought it was supposed to print out the same content as the `i r` command ?

**Comment by zachriggle** [comment]
It's not intended to print out the same contents as anything in particular.

The link register is not normally needed in the register context, and is generally more applicable to the stack context or something like that.

I'm not sure that adding what is effectively "the return address register" to the print-out is useful in the general case, but it'd be fine if a `config` point were added for it.

**Comment by bruce30262** [comment]
@zachriggle agree. From my experience sometimes the LR register are used to store some local variables ( like the [binary](https://github.com/ctfs/write-ups-2016/blob/master/mma-ctf-2nd-2016/pwn/candy-store-300/candystore) I use to demonstrate the issue), that's why I would like to inspect the register context during the debug session.  
Anyway I see @dqi has already done the modification (thanks man!), guess I'll just add the configuration in my `.gdbinit`

**Comment by zachriggle** [comment]
I think this is done via #127
