### ISSUE TITLE
Show instruction operand values in the disassembly

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#1152]
For instructions like `cmp    qword ptr [rbp - 0x28], rax`, it would be nice if the disassembly actually showed the two values we were comparing.

There are probably various other instructions where this could be useful, like arithmetic instructions.

**Comment by disconnect3d** [comment]
That's a really good feature I'd be happy if someone wanted to add it. We should probably revamp/rewrite the current display enhancer module/logic and improve it in this and other ways.

**Comment by disconnect3d** [comment]
Somehow relevant: https://github.com/capstone-engine/capstone/issues/2133

**Comment by gsingh93** [comment]
My guess is #2001 fixed this, but I haven't really used it much yet. Can you confirm @disconnect3d?

**Comment by disconnect3d** [comment]
Yes, #2001 implemented it, at least for X86-64. I think we can close this issue. (We don't need to keep it open just bcoz other archs do not support it).

<img width="970" alt="image" src="https://github.com/pwndbg/pwndbg/assets/10009354/ec0629db-5f2e-4293-823c-6ca643b1ba7e">

<img width="1193" alt="image" src="https://github.com/pwndbg/pwndbg/assets/10009354/64174727-f96b-41df-b9c9-369acd5c2ba2">

Closing.
