### ISSUE TITLE
Add flake8-builtins to CI

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#1181]
We often shadow builtins with our own variables in the code, and this can lead to unexpected bugs. Let's add https://pypi.org/project/flake8-builtins/ to the CI to catch these.

**Comment by syheliel** [comment]
It's latest release is May,2020. Maybe it's not stable enough, see the [issue](https://github.com/gforcada/flake8-builtins/issues)

**Comment by gsingh93** [comment]
I think it should be fine. The author is still around responding to issues, even though he doesn't have time to fix them. The code is really simple, so worst case we can fork it and I'm fine with maintaining it. I've already put up a PR for a feature that would be useful: https://github.com/gforcada/flake8-builtins/pull/80

And I've integrated it here, just waiting for the PR to be merged: https://github.com/pwndbg/pwndbg/commit/213ec8a96a101e8359520d9918e87fd4bd1c14e4
