### ISSUE TITLE
Add `vermin` to CI

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#1182]
This project does a pretty good job of detecting all the Python features you're using and outputting the minimum version required: https://github.com/netromdk/vermin

We should add this to CI so we don't accidentally break Python 3.7 with some new features we use.

**Comment by mazfil** [comment]
Hey @gsingh93 id like to have a go at implementing this into the CI.
Could you assign it to me? Thanks.

**Comment by gsingh93** [comment]
Awesome! The steps for this include:
- Adding vermin to dev-requirements.txt
- Updating `lint.sh` to call it
- Assert that the minimum reported version is 3.6
- Test on your fork whether the lint checks pass with the current `dev` branch, but then fail if you add some newer feature (note that CI jobs will show up as failed on your fork because of code coverage issues, but the lints/tests should run fine before that).

**Comment by mazfil** [comment]
@gsingh93 is the minimum reported version of the `dev` branch currently 3.6? Running vermin in the project returns a minimum reported version of 3.10.
Are there any files we're excluding?

**Comment by gsingh93** [comment]
You'll need to do this for a few of the capstone lines for now, I plan to fix this properly in the future: https://github.com/netromdk/vermin/issues/103#issuecomment-1254536305
