### ISSUE TITLE
Stop ignoring F841 flake8 warnings (unused variables)

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#1183]
When we added `flake8`, we had to ignore some existing warnings because it was too much work at the time to fix them, and we wanted to get `flake8` on the CI so future errors would be prevented. We need to go back and fix some of these so we can start running them on the CI, like F841: local variable name is assigned to but never used.

**Comment by jetchirag** [comment]
Was working on this but I think we can close this due to #1696

**Comment by gsingh93** [comment]
`ruff` also runs flake8 checks, you can see that F841 is still being ignored in the `tool.ruff` config.
