### ISSUE TITLE
Add config option to show EFLAGS in register context section

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#1191]
Sometimes it's useful to see the value of EFLAGS, when doing some complicated ROP that depends on conditional jumps. It would be good to be able to have a config option (off by default) that shows the value of this in the registers section.

**Comment by gsingh93** [comment]
Turns out this already exists :)
```
set show-flags on
```

**Comment by disconnect3d** [comment]
@gsingh93 shall we add it to `tips`? :)

Also: shall `pwndbg` command inform about interesting pwndbg configurations like this one?

**Comment by gsingh93** [comment]
Adding it to tips makes sense. I don't think the `pwndbg` command should call out any particular options, but maybe it should call out near the bottom or the top that you can see all the config options by typing `config`. Also, if we do this it will help with discoverability: https://github.com/pwndbg/pwndbg/issues/1199
