### ISSUE TITLE
Run the `display` command after `context`

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#1194]
I don't know how difficult this will be to implement, but I like to use the `display` command to print out some information every time I step instructions. But because this gets printed first, the output of context always scrolls the screen down, so I have to scroll up to see it.

If we can find a way to run the `display` commands after `context`, that would be a quick fix.

An alternative approach would be to add a new `context` section, and we can either put `display` commands there or have some new command to add commands to that if it's difficult to hook `display`.

**Comment by disconnect3d** [comment]
Does GEF allow for that? Maybe we have sth incorrect with prompt hook events.

Maybe related:
* https://github.com/pwndbg/pwndbg/blob/6d573290ac839567e0dcb3b0fb20ec66ce45e6f6/pwndbg/gdblib/prompt.py#L85-L90
* https://github.com/pwndbg/pwndbg/blob/77380eb63c6cfdb721f2a2c4448f9d544fa03bd7/pwndbg/gdblib/events.py#L98-L100

**Comment by gsingh93** [comment]
Wow. This exists already:
```
pwndbg> cwatch execute 'x/10i $rip'
pwndbg> context
```
<img width="884" alt="image" src="https://user-images.githubusercontent.com/1012677/193754115-3155a4c6-1a67-44ea-89cd-4c38d7de8a9a.png">
