### ISSUE TITLE
Add `telescope --frame`

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#1195]
It'd be nice to have a `telescope` command that prints out the stack frame, from `rsp` to `rbp`. Obviously this only works if the program actually uses a frame pointer.

It would be equivalent to this:
```
pwndbg> p ($rbp-$rsp)/8 + 1
$5 = 9
pwndbg> telescope $rsp $$
00:0000│ rsp 0x7ffe5f4951a0 ◂— 0x300000001
01:0008│     0x7ffe5f4951a8 —▸ 0x7ffe5f495220 ◂— 0x170c94ca0
02:0010│     0x7ffe5f4951b0 —▸ 0x7f6870c96168 —▸ 0x563e09600000 ◂— jg     0x563e09600047
03:0018│     0x7ffe5f4951b8 ◂— 0xf0
04:0020│ rsi 0x7ffe5f4951c0 ◂— 0xb1ed2074ada5ce5
05:0028│     0x7ffe5f4951c8 ◂— 0xda37756c736484c1
06:0030│     0x7ffe5f4951d0 —▸ 0x7ffe5f4951fe ◂— 0x563e096013e00000
07:0038│     0x7ffe5f4951d8 ◂— 0x56657596c3d91600
08:0040│ rbp 0x7ffe5f4951e0 —▸ 0x7ffe5f495200 —▸ 0x563e096013e0 ◂— push   r15
```

**Comment by disconnect3d** [comment]
Shall this be in `telescope`? We also have a `stack` command

**Comment by gsingh93** [comment]
We discussed this on discord, it's probably best to either alias `stack` to `telescope`, or just remove `stack` (after displaying a deprecation warning for a few months).

**Comment by disconnect3d** [comment]
FWIW the `stack` command:
```
user@user:~/pwndbg$ rg 'def stack' -A5
pwndbg/commands/telescope.py
216:def stack(count, offset):
217-    ptrsize = pwndbg.gdblib.typeinfo.ptrsize
218-    telescope.repeat = stack.repeat
219-    telescope(address=pwndbg.gdblib.regs.sp + offset * ptrsize, count=count)
```

So it takes `<count> <offset>` and calls `telescope $rsp+(8*offset) count` (where 8 is arch.ptrsize, so differs on x86).

I'm fine with deprecating `stack` and removing it in the future.
