### ISSUE TITLE
Heap chain corruption check is incorrect for long free lists

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#1196]
Debugging this code with pwndbg and running the `bins` command shows the wrong output for the unsorted bin.
```c
int main() {
  char* chunks[20] = {0};
  for (int i = 0; i < 20; i ++) {
    chunks[i] = malloc(0x500);

    // padding
    malloc(0x20);
  }

  for (int i = 0; i < 20; i ++) {
    free(chunks[i]);
  }
}
```

After executing free around 8 or 9 times, the unsorted bin still looks fine:
```
unsortedbin
all: 0x55555555b210 —▸ 0x55555555acd0 —▸ 0x55555555a790 —▸ 0x55555555a250 —▸ 0x555555559d10 ◂— ...
```

But then executing it again shows this:
```
all [corrupted]
FD: 0x55555555b750 —▸ 0x55555555b210 —▸ 0x55555555acd0 —▸ 0x55555555a790 —▸ 0x55555555a250 ◂— ...
BK: 0x555555559290 —▸ 0x5555555597d0 —▸ 0x555555559d10 —▸ 0x55555555a250 —▸ 0x55555555a790 ◂— ...
```

**Comment by CptGibbon** [comment]
This appears to be tied to `heap_chain_limit`, defined below:
https://github.com/pwndbg/pwndbg/blob/3c8ee9bb37d670bf2c161c7a45bb0c3fbadc664e/pwndbg/heap/__init__.py#L22-L23
Which is used in `bin_at`:
https://github.com/pwndbg/pwndbg/blob/3c8ee9bb37d670bf2c161c7a45bb0c3fbadc664e/pwndbg/heap/ptmalloc.py#L570-L578

**Comment by CptGibbon** [comment]
It boils down to the fact that you can't check incomplete fd & bk lists against each other for corruption. One course of action could be to print a warning that pwndbg can't do a corruption check when the bin dereference limit is reached?

**Comment by gsingh93** [comment]
Not an expert in how this works, but I have two ideas:
- We can have different limits for the number of chain elements to display vs. the number of chain elements to check. We can only display 8 elements, but check 32 (for example) without any major hit to performance. If we hit that second limit (which could also be a user config option), we could print a warning like you suggest, and even mention the user can increase this limit if they want
- Can we do the check in a way similar to how it's done in the actual libc code? Instead of attempting to traverse the entire chain, can we just check if `victim->bk->fd = victim`?

**Comment by CptGibbon** [comment]
> We can only display 8 elements, but check 32 (for example)...
If we hit that second limit (which could also be a user config option), we could print a warning...

I think this is a sensible approach 👍

>Can we just check if victim->bk->fd = victim?

Could do, but this only checks a couple of chunks.
I feel like it's useful to know about an entire list's integrity, since a single call to malloc might end up checking every chunk in a list e.g. unsortedbin searches.
