### ISSUE TITLE
`leakfind` should default to `$sp`

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#1210]
The first argument to `leakfind` is required, but it should just default to `$sp` like `probeleak` does.

**Comment by amoghrajesh** [comment]
@gsingh93 I can work on this issue. Can you refer to me how `probeleak` works and i can do it

**Comment by gsingh93** [comment]
Thanks! This should be pretty easy. If you take a look at `commands/probeleak.py`, you can see the `address` argument uses `nargs` and `default`. We just need to do the same thing in `commands/leakfind.py`.

**Comment by amoghrajesh** [comment]
@gsingh93 in that case can you assign this to me?

**Comment by amoghrajesh** [comment]
@gsingh93 I have raised a PR https://github.com/pwndbg/pwndbg/pull/1218. Could you please help in reviews?
