### ISSUE TITLE
Run tests on Arch Linux

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#1212]
Debian and Arch are our most used distros after Ubuntu. It would be good to run the CI tests on those distros as well. While Github doesn't support this natively, we can probably get around this with Docker.

Although, I don't think Arch failing should be a blocker for any PRs. I don't want to make contributing to the project significantly harder, so if we see that Arch breaks, we can just file an issue and follow up on it later.

**Comment by gsingh93** [comment]
I've changed the title of this task to focus on adding testing support for Arch Linux, as Debian support will be added as part of #1328.

**Comment by Xeonacid** [comment]
Hi, I'd like to work on this. Could you assign it to me?

**Comment by disconnect3d** [comment]
@Xeonacid You don't need to be assigned to work on something, you can just send PR ;). Anyway, assigned you :).
