### ISSUE TITLE
Adding pwndbg to GDB shipped with the Android NDK

### ISSUE THREAD

**Issue by tanis2000** [pwndbg/pwndbg#122]
I tried to add pwndbg to the Python libs shipped with Android NDK so that I could use it with the GDB client included in the NDK, but I failed miserably.

When running setup.sh I get the following error:

```
MacBookPro-Valerio:pwndbg tanis$ ./setup.sh
+ uname
+ grep -i Linux
+ git submodule update --init --recursive
++ gdb -batch -q --nx -ex 'pi import platform; print(".".join(platform.python_version_tuple()[:2]))'
+ PYVER=2.7
++ gdb -batch -q --nx -ex 'pi import sys; print(sys.executable)'
+ PYTHON=/Volumes/Android/buildbot/src/android/ndk-r12-release/out/build/buildhost/darwin-x86_64/install/host-tools/bin/python
+ PYTHON=/Volumes/Android/buildbot/src/android/ndk-r12-release/out/build/buildhost/darwin-x86_64/install/host-tools/bin/python2.7
++ gdb -batch -q --nx -ex 'pi import site; print(site.getsitepackages()[0])'
+ SITE_PACKAGES=/Users/tanis/Documents/android-ndk/prebuilt/darwin-x86_64/bin/../lib/python2.7/site-packages
+ sudo /Volumes/Android/buildbot/src/android/ndk-r12-release/out/build/buildhost/darwin-x86_64/install/host-tools/bin/python2.7 -m pip install --target /Users/tanis/Documents/android-ndk/prebuilt/darwin-x86_64/bin/../lib/python2.7/site-packages -Ur requirements.txt
Password:
sudo: /Volumes/Android/buildbot/src/android/ndk-r12-release/out/build/buildhost/darwin-x86_64/install/host-tools/bin/python2.7: command not found
```

I guess it's extracting the path of Python from GDB so that it turns out to be ` /Volumes/Android/buildbot/src/android/ndk-r12-release/out/build/buildhost/darwin-x86_64/install/host-tools/bin/python2.7` but that's not the correct place. On top of that, the Python2.7 interpreter that comes with the Android NDK doesn't include pip or any other librari in site-target.

Is there any way to accomplish this manually? Cheers!

**Comment by zachriggle** [comment]
Nope.  ¯\_(ツ)_/¯

Also, don't use the GDB that comes with the NDK, it's frequently broken (e.g. GDB 7.10 had a bunch of ARM bugs).

Also, macOS is not supported for Pwndbg.  Anything that works is a happy accident, and there are no plans to support macOS. 

If you *must* use Mac OS, I recommend `$ brew install gdb --with-all-targets --with-python`, and use that `gdb`.
