### ISSUE TITLE
Error in the `search` command

### ISSUE THREAD

**Issue by bruce30262** [pwndbg/pwndbg#123]
The `search` command appears to have some issues while searching signed integer data  
For example while debugging a x86 program:
```
pwndbg> search -4 0xf7eebf83
Traceback (most recent call last):
  File "/home/bruce30262/pwndbg/pwndbg/commands/__init__.py", line 57, in __call__
    return self.function(*args, **kwargs)
  File "/home/bruce30262/pwndbg/pwndbg/commands/__init__.py", line 162, in _ArgparsedCommand
    return function(**vars(args))
  File "/home/bruce30262/pwndbg/pwndbg/commands/__init__.py", line 115, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/home/bruce30262/pwndbg/pwndbg/commands/search.py", line 112, in search
    value = struct.pack(fmt, value)
struct.error: argument out of range
```
This is because `pwndbg.commands.fix_int(value)` returns `-135348349` instead of an unsigned integer, and the packing format in [search.py](https://github.com/pwndbg/pwndbg/blob/b1892b27741a478cd5361061b0b4dda9ef46d02e/pwndbg/commands/search.py#L106) only support the unsigned data type, causing the error.  
Commands like  `search -4 -- -100` will also cause the same error.  
Kind of curious why it only support the unsigned data type though. It might need some additional check for the appropriate packing format.

**Comment by zachriggle** [comment]
The unsigned data type is a result of the `inthook` code.  The `command` module takes the `gdb.Value()` that you provide and turns it into an unsigned integer via `.cast()`.

In any case, it looks like the correct course is to mask it against `arch.ptrmask`
