### ISSUE TITLE
Add support to malloc_chunk for dumping the entire chunk, including the data

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#1238]
It would be useful if there was a flag for `malloc_chunk` (maybe `--dump`?) that would print a hexdump of the chunk bytes after printing the chunk header information. This would allow me to see all the information about a chunk and its data in a single command, without needing to calculate how many bytes to dump myself.

**Comment by pogen300** [comment]
Hi @gsingh93, I'd like to work on this enhancement. Can you assign it to me?

**Comment by gsingh93** [comment]
@pogen300 Thanks! I've assigned it to you, let me know here or on Discord if you need any help.

**Comment by CptGibbon** [comment]
Isn't this just `vis_heap_chunks 1 <address>`?

**Comment by gsingh93** [comment]
I haven't tried it, but I want the header metadata *and* the hexdump of the body.

Although, maybe there's an opportunity to unify some code here...

**Comment by pogen300** [comment]
@gsingh93 Thanks, I just joined the discord server.

**Comment by CptGibbon** [comment]
Indeed with `vis_heap_chunks` you get everything.

Although I agree there's almost certainly a chance to unify some code. I'm hoping that soon the `Chunk` class will be home all the chunk printing logic.

**Comment by disconnect3d** [comment]
@pogen300 any progress on that?

**Comment by pogen300** [comment]
> @pogen300 any progress on that?

Hi, I have made some contributions to this issue weeks ago, but haven't worked on it since my last PR was accepted. it's been particularly busy for me these days with final exams and research project at uni. So feel free to assign it to someone else.

**Comment by Unknownsentinel193** [comment]
Hi, Can you please assign this to me.
