### ISSUE TITLE
`telescope -r` should always display the input address

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#1240]
`telescope -r addr` will skip displaying `addr` if the value at that address is equal to the previous few values:
```
pwndbg> p &target_address
$1 = (unsigned long *) 0x5555555582a0 <target_address>
pwndbg> telescope -r &target_address
00:0000│     0x555555558208 (buf+360) ◂— 0x0
... ↓        4 skipped
05:0028│ rax 0x555555558230 (buf+400) ◂— 0x80
06:0030│     0x555555558238 (buf+408) ◂— 0x0
... ↓        13 skipped
```
We should make this command always display the address that the user asked for:
```
pwndbg> telescope -r &target_address
00:0000│     0x555555558208 (buf+360) ◂— 0x0
... ↓        4 skipped
05:0028│ rax 0x555555558230 (buf+400) ◂— 0x80
06:0030│     0x555555558238 (buf+408) ◂— 0x0
... ↓        12 skipped
13:0098│     0x5555555582a0 (target_address) ◂— 0x0
```

**Comment by lonnywong** [comment]
I found that telescope behaves strangely if `set history remove-duplicates unlimited`.

The `check_repeated` depends on the history of gdb. 
https://github.com/pwndbg/pwndbg/blob/e456b317d7d9c3767ebf45b907d31178c3418d3e/pwndbg/commands/__init__.py#L113-L148

If `remove-duplicates` is set, the `check_repeated` is not working normally. That's what I mentioned in https://github.com/pwndbg/pwndbg/issues/1072#issuecomment-1274925956

I can't find another way to implement the `check_repeated`. I'm removing the `set history remove-duplicates unlimited` from my `~/.gdbinit`.

**Comment by disconnect3d** [comment]
I'd say we should handle the two cases as separate bugs:
1. The `telescope -r` should always include/display the input address (and not collapse it if its value is the same as previous few ones)
2. The `telescope` behavior when `set history remove-duplicates unlimited` is on should be investigated further I guess.
