### ISSUE TITLE
Convert `ida_script.py` to Python 3

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#1250]
IDA no longer supports Python 2. We should convert the script to Python 3, and then remove the dependency on `future` in the `requirements.txt`.

It may already work in Python 3, but since it's importing from `__future__`, I'm not sure, and I don't know how to test this.

**Comment by bhavana-263** [comment]
hi sir can you assign this issue to me @gsingh93

**Comment by mgorny** [comment]
I think the dependency on `future` can be removed right now. `__future__` is built-in in Python, and is not related to the `future` package on PyPI (that's imported as `future`, without underscores).
