### ISSUE TITLE
Add a command to skip the last breakpoint a certain number of times

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#1257]
GDB has the `ignore` command to skip breakpoints a certain number of times, i.e. `ignore 4 2` skips breakpoint 4 two times, and then breaks on it the third time.

This works fine when I'm at the GDB prompt and can figure out which breakpoints have which numbers, but it's annoying in a GDB script, where after I set a breakpoint, I have to count the total breakpoints set so far to get the right breakpoint number to pass to `ignore`.

It would be useful if there was a command to call ignore on the last breakpoint that was set, i.e. `ignorelast 2` would ignore the last breakpoint that was set two times.

**Comment by disconnect3d** [comment]
This could always parse the output of `gdb.execute("info break", to_string=True)`:
```
pwndbg> i b
Num     Type           Disp Enb Address            What
2       breakpoint     keep y   0x00007ffff7fe32b3 <_start+3>
3       breakpoint     del  y   0x00007ffff7fe32c6 <_dl_start_user+14>
```

Or better, use the `gdb.breakpoints()` function:
```
In [4]: gdb.breakpoints()
Out[4]: (<gdb.Breakpoint at 0x7fa7cfa22820>, <gdb.Breakpoint at 0x7fa7cfa513b0>)

In [5]: [bp.number for bp in gdb.breakpoints()]
Out[5]: [2, 3]

In [6]: max(bp.number for bp in gdb.breakpoints())
Out[6]: 3
```

The latest set breakpoint should always have the biggest number.

And we can set the ignore count from Python API too:
```
pwndbg> ignore 2 10
Will ignore next 10 crossings of breakpoint 2.
pwndbg> ipi

In [1]: bp = next(bp for bp in gdb.breakpoints() if bp.number == 2)

In [2]: bp.number
Out[2]: 2

In [3]: bp
Out[3]: <gdb.Breakpoint at 0x7fa7cfa22820>

In [4]: bp.condition

In [5]: bp.enabled
Out[5]: True

In [6]: bp.silent
Out[6]: False

In [7]: bp.expression

In [8]: bp.hit_count
Out[8]: 0

In [9]: bp.ignore_count
Out[9]: 10

In [10]: bp.ignore_count = 2

In [11]:

pwndbg> i b
Num     Type           Disp Enb Address            What
2       breakpoint     keep y   0x00007ffff7fe32b3 <_start+3>
	ignore next 2 hits
3       breakpoint     del  y   0x00007ffff7fe32c6 <_dl_start_user+14>
```

**Comment by disconnect3d** [comment]
Regarding the interface for such command, maybe we should overwrite the `ignore` command since we can reimplement it in Python without recursively executing it (via `gdb.execute("ignore ...")`?

And it could have an interface like:
```
ignore <count> - ignore last set bp count times
ignore <bp-num> <count> - ignore bp with bp-num count times
```

**Comment by gsingh93** [comment]
Nice, seems like this will be easy to implement. I think overwriting the ignore command makes sense. If we define a command in Python with the same name, will that just work? Or will it complain about a command of that name already being defined?
