### ISSUE TITLE
Add a stepuntilasm command

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#1264]
We have all the fancy `stepsyscall`, `nextret`, `nextsyscall` instructions: should we maybe have `stepuntilasm` that would step by step until an instruction with given assembly text is reached? We already do disasm instructions when doing the listed commands, so we can have another command to match asm.

In the future, we may want to merge all of the above into one `stepuntil` or just some `until` command that would have flags/args for different scenarios. But for now, lets add an additional command with this cool functionality.

**Comment by gsingh93** [comment]
If we do this, it would probably be good to tackle this at the same time: https://github.com/pwndbg/pwndbg/issues/1167
