### ISSUE TITLE
Fix the reload command

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#1305]
We have a `reload` command that is intended to reimport all of the Python modules, so that while working on new features we don't have to quit and restart GDB to test out our changes. However, it doesn't seem to work. We should investigate this, as it will make development much easier.

**Comment by disconnect3d** [comment]
Fixed in https://github.com/pwndbg/pwndbg/commit/a4233eb101c793aec7f2aeae0c078df4d566972f :)
