### ISSUE TITLE
Install a git pre-push lint hook as part of setup-test-tools.sh

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#1306]
When running `./setup-dev.sh`, we should prompt the user (if we detect a tty?) if they want to install a git pre-push hook (if we detect one doesn't already exist?) that automatically runs `./lint.sh -f` for them.

**Comment by ruijia-zhou** [comment]
Hi, @gsingh93 , I just used lint for my pull request. I think I can help with this. 
I have successfully implemented this locally. Can you please assign this issue to me (the assignment is a requirement from one of my university courses)? 
Thanks

**Comment by gsingh93** [comment]
Thanks @ruijia-zhou! Just FYI, if you run into any issues feel free to join our Discord server (link in README) and ask any questions you have.

Also, it would be good to give a more descriptive message in the hook that explains why there is a failure (people may not be familiar with hooks).

**Comment by ruijia-zhou** [comment]
@gsingh93 thanks, I will join now.
