### ISSUE TITLE
Run all tests in Docker containers

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#1328]
In https://github.com/pwndbg/pwndbg/issues/1327 we discovered that the version of GDB used in the CI is actually newer than what's provided in the apt repositories. This means we're going to miss bugs in older versions of GDB.

We should switch to running all of our tests inside Docker images, which will actually match a production environment. The Ubuntu 22.04 hosted worker contains cached Docker images for all of the Ubuntu versions we care about: https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#cached-docker-images

Since these machines also have cached images for Debian 11 and 10, we should also run tests on those images as well.

**Comment by disconnect3d** [comment]
We can probably force to install an older version of the GDB package just for Ubuntu 18.x.

**Comment by gsingh93** [comment]
I think we should go with this Docker approach anyway:
1. This is going to happen in the future with newer Ubuntu versions eventually
2. Who knows what other packages are actually different and could lead to problems
3. We want to do this anyway to support testing on Debian, so why not just do it for all of our tests

**Comment by KevinN318** [comment]
Hi, I would like to try to implement this.

**Comment by gsingh93** [comment]
@KevinN318 I've assigned it to you. If you need help, let us know here or in Discord (link is in the README).

**Comment by disconnect3d** [comment]
This was finally merged in https://github.com/pwndbg/pwndbg/pull/1370
