### ISSUE TITLE
When 'ni' or 'si' - clear screen

### ISSUE THREAD

**Issue by glen-mac** [pwndbg/pwndbg#133]
Gdb Peda clears the screen when I am entering through instructions and the screen layout doesn't change - because it clears the screen first and writes from the top of the terminal downwards.

I believe this is a worthwhile change to make.

**Comment by disconnect3d** [comment]
@glen-mac Can you show some example/screenshot what exactly do you mean? For me both peda and pwndbg `ni` stepping feels the same.

**Comment by anthraxx** [comment]
I guess he means a feature that clears the whole screen when stepping... seen that and i understand people may find it handy... so here is the pull request #134 :stuck_out_tongue_closed_eyes:
