### ISSUE TITLE
How to use pwngdb on gdb.exe for Windows XP

### ISSUE THREAD

**Issue by aleff-github** [pwndbg/pwndbg#1386]
I found this executable for Windows XP [1] but use gdb without pwngdb tool is really hard... exist a metodh for use pwngdb on Windows XP?

[1] http://www.equation.com/servlet/equation.cmd?fa=gdb

**Comment by disconnect3d** [comment]
Hi, I think you should not use a GDB binary downloaded from an unofficial/random site and instead compile GDB yourself.

This being said, we do not support PE/PE+ files at all if GDB is used on Windows for that matter. So I don't think Pwndbg will work. However, if anyone wants to work on adding support for it, then I would be happy to merge it.

**Comment by disconnect3d** [comment]
I am closing tihs issue for now as I doubt anyone is going to work on it.
