### ISSUE TITLE
 import pwndbg  # noqa: F401

### ISSUE THREAD

**Issue by hhlp** [pwndbg/pwndbg#1392]
### Description

every time I call gdb I've gotten this error... 

```
Traceback (most recent call last):
  File "/home/hhlp/.pwndbg/gdbinit.py", line 75, in <module>
    import pwndbg  # noqa: F401
    ^^^^^^^^^^^^^
  File "/home/hhlp/.pwndbg/pwndbg/__init__.py", line 11, in <module>
    load_commands()
  File "/home/hhlp/.pwndbg/pwndbg/commands/__init__.py", line 458, in load_commands
    import pwndbg.commands.aslr
  File "/home/hhlp/.pwndbg/pwndbg/commands/aslr.py", line 28, in <module>
    @pwndbg.commands.ArgparsedCommand(parser)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hhlp/.pwndbg/pwndbg/commands/__init__.py", line 400, in __call__
    return _ArgparsedCommand(self.parser, function, command_name=self._command_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hhlp/.pwndbg/pwndbg/commands/__init__.py", line 366, in __init__
    super(_ArgparsedCommand, self).__init__(function, command_name=command_name, *a, **kw)
  File "/home/hhlp/.pwndbg/pwndbg/commands/__init__.py", line 69, in __init__
    raise Exception('Cannot override non-whitelisted built-in command "%s"' % command_name)
Exception: Cannot override non-whitelisted built-in command "aslr"
gef➤  

```

### My setup

This can be displayed in pwndbg through `version` command.??????

If it is somehow unavailable, use:

* `show version` - for gdb

GNU gdb (GDB) Fedora Linux 12.1-6.fc37

* `import sys; print(sys.version)` - for python

3.11.0 (main, Oct 24 2022, 00:00:00) [GCC 12.2.1 20220819 (Red Hat 12.2.1-2)]

* Distro

Fedora 37
Kernel : 6.0.9-300.fc37.x86_64

* pwndbg version/git commit id

39ebd66

Regards.,

**Comment by disconnect3d** [comment]
Are you really using both gef and pwndbg? :) Those may not play well together, but you can always try ;).

Also, isn't the exception self-explanatory? There is an `aslr` command defined in your GDB session and Pwndbg detects it and crashes on that.

I guess we can change that crash into a warning print instead maybe, to make experience like this more pleasant...

**Comment by hhlp** [comment]
I'd resolved using the following method:

https://infosecwriteups.com/pwndbg-gef-peda-one-for-all-and-all-for-one-714d71bf36b8

Regards.,
