### ISSUE TITLE
Running setup.sh on installed Pwndbg should be more clear

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#1394]
We have this at the end of our setup.sh:
https://github.com/pwndbg/pwndbg/blob/f01f932755d7ce88da520ef62dccd5eecae8b0b2/setup.sh#L157-L160

This can be confusing for users when they try to install Pwndbg for the second time but they haven't cleared the ~/.gdbinit file.

I guess we should:
* Check for `source <gdbinit.py>` in `~/.gdbinit` as the very first thing in setup.sh
* If we find an entry, we should ask the user if they want to proceed and override the initializer line
* If the user don't want to proceed, we should stop the installation
* If the user wants to proceed, we should install all deps etc, and add the `source ...` line to `~/.gdbinit` at the end of setup.sh

**Comment by Cycatz** [comment]
@disconnect3d Could I take this?

**Comment by disconnect3d** [comment]
@Cycatz Hi, sure.

**Comment by Cycatz** [comment]
@disconnect3d I have an idea: we can mark the region of the configs added by the setup script, such as `### Begin of pwndbg configs ###` and `### End of pwndbg configs###`. 

Thus we can remove the config between the comments when user want to overwrite, and it also avoids some false positives when simply grepping "pwndbg" in `.gdbinit` (e.g., a comment `# pwndbg` falls out of the condition).

**Comment by disconnect3d** [comment]
@Cycatz We can do so, but will it actually improve anything? I mean, the user could still put anything in between that and may want to have those preserved on another pwndbg install :/

**Comment by Cycatz** [comment]
>  I mean, the user could still put anything in between that and may want to have those preserved on another pwndbg install :/

You're right, the user could still put anything in between the tags. 

My concern is that the condition `if ! grep pwndbg ~/.gdbinit &> /dev/null;` is not robust enough to handle the scenarios where a user has comments with the word "pwndbg"  or has renamed the cloned directory of pwndbg. In these cases, the grep command would not be able to accurately detect the presence of pwndbg in the user's `~/.gdbinit` file, which could lead to problems with the installation process.

Anyway, it's up to you to decide if the potential benefits are worth the effort of implementing this feature.

**Comment by disconnect3d** [comment]
Shall we then look for 'pwndbg/gdbinit.py' and then fallback to gdbinit.py?

**Comment by Cycatz** [comment]
> Shall we then look for 'pwndbg/gdbinit.py' and then fallback to gdbinit.py?

Yes, I think that's a good idea!

**Comment by Cycatz** [comment]
Here is my rough implementation:
```sh
# Check for the presence of the initializer line in the user's ~/.gdbinit file
if grep -q "pwndbg/gdbinit.py" ~/.gdbinit; then
    # Ask the user if they want to proceed and override the initializer line
    read -p "An initializer line was found in your ~/.gdbinit file. Do you want to proceed and override it? (y/n) " answer

    # If the user does not want to proceed, exit the script
    if [ "$answer" != "y" ]; then
        exit 0
    fi
fi

# Install all necessary dependencies

# Check for the presence of the initializer line in the user's ~/.gdbinit file again
if grep -q "pwndbg/gdbinit.py" ~/.gdbinit; then
    # If so, comment it out
    sed -i '/pwndbg\/gdbinit.py/ s/^/# /' ~/.gdbinit
fi
# Now we can append the line sourcing pwndbg's gdbinit script
echo "source $PWD/gdbinit.py" >> ~/.gdbinit

**Comment by disconnect3d** [comment]
@Cycatz Can you just send this as a pull request? :)

**Comment by Cycatz** [comment]
Sure! I will clean the file up and issue a PR in these two days.

**Comment by Cycatz** [comment]
Fixed in #1620

**Comment by gsingh93** [comment]
@disconnect3d anything left to be done here or can this be closed?

**Comment by disconnect3d** [comment]
I think we are good to close it. Thanks again!
