### ISSUE TITLE
`nextcall` is broken on ARM

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#1419]
`nextcall`/`stepcall` don't work on ARM. In `break_next_call` in `pwndbg/gdblib/next.py`, we check for calls like this:
```
        if capstone.CS_GRP_CALL not in ins.groups:
            continue
```
Unfortunately, the `bl` instruction is only classified as `branch_relative` and `jump`, but not `call`. We should probably report this upstream to Capstone, though I have a feeling this intentional.

In any case, we'll have to directly check the mnemonic matches 'bl' on ARM.

**Comment by gsingh93** [comment]
I think this should be fixed, but would be good if someone could confirm (@DarkRyu550?)

**Comment by gsingh93** [comment]
Also, maybe we should add a test for this before closing?

**Comment by disconnect3d** [comment]
Double checked that and it works.

However, there is some quirk/gotcha: if u try to execute `nextcall` right away after connecting to a target, without a `break main; continue` it will not work. Not sure why, but **this isn't a memoize/caching issue**.

**Comment by disconnect3d** [comment]
Closing this for now. We may implement a test in the future but idk if we will
