### ISSUE TITLE
Don't fail CI jobs if codecov fails

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#1427]
The codecov step of the GH testing workflow has been failing often recently. We should probably add [continue-on-error](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error) to that step to prevent the entire job from failing.

**Comment by mohitsaxenaknoldus** [comment]
Hey, I'll work on this, you can assign it to me.

**Comment by gsingh93** [comment]
Thanks! Feel free to ask questions here or on Discord. Just note, I've never used `continue-on-error` so not 100% sure it's the right solution, but it seems like it from the docs.

**Comment by mohitsaxenaknoldus** [comment]
> Thanks! Feel free to ask questions here or on Discord. Just note, I've never used `continue-on-error` so not 100% sure it's the right solution, but it seems like it from the docs.

PR: https://github.com/pwndbg/pwndbg/pull/1438
@gsingh93 `continue-on-error` will do the job but still mark the complete workflow as a failure so I've put up a better solution.

**Comment by gsingh93** [comment]
Interesting, I had got the idea from here that the full workflow should still succeed even if that one step fails: https://stackoverflow.com/questions/58858429/how-to-run-a-github-actions-step-even-if-the-previous-step-fails-while-still-f#comment123845055_70048004
