### ISSUE TITLE
Improve memoization code

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#1453]
There's various issues with the memoization code in `pwndbg/lib/memoize.py`. To name a few:

1. From reading the code, it seems like it doesn't handle keyword arguments properly (not verified)?
2. Instead of having one cache and clearing that cache on each event, we have multiple caches per event.
3. The implementation with a class member variable defined in the subclass, used in the parent class, and also used in a static method in the subclass is confusing. I feel like there's a simpler way to do this.
4. We should probably have some performance profiling of the memoization code as it's the most frequently executed code in the codebase, and even small optimizations there will have a large performance impact.

**Comment by gsingh93** [comment]
Suggestion from @disconnect3d: we can make the caches per-function instead of per-event by saving the cache in the function itself.

**Comment by disconnect3d** [comment]
Done in #1671.
