### ISSUE TITLE
Add a decorator to mark a command as userspace only

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#1459]
Some commands don't make sense for use with a kernel (i.e. `arena`). To avoid confusion, we should have a decorator we can apply to these commands to mark them as userspace only.

**Comment by Saumya-ranjan** [comment]
I'd like to take this up. I would really appreciate some clarification on the same.

**Comment by gsingh93** [comment]
We have a decorator called [`OnlyWhenQemuKernel`](https://github.com/pwndbg/pwndbg/blob/f9ff357ba0b873e0a18955944ae27b61f0778c5e/pwndbg/commands/__init__.py#L214) that we can use to only allow certain commands to be run if the user is debugging a kernel under QEMU, like this: https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/commands/kconfig.py#L13

But there are some commands that don't make sense to run when debugging a kernel with QEMU, and we should use a similar decorator to display a warning to the user in that case. So essentially you can copy the decorator, flip the check, and then apply it to any commands that don't make sense for the kernel (this doesn't need to be exhaustive in this PR, we can always add it to more commands later).

But before making this change, I want to check with @disconnect3d: do you think this makes sense? At first I was concerned there may be too many commands that don't make sense when debugging a kernel, but looking now it seems like there aren't as many as I thought. It would be all of the heap commands and a couple of libc and ELF related commands (i.e. `tls`, `auxv`, `environ`, etc.).

**Comment by disconnect3d** [comment]
I think it makes sense; we have to support all the things somehow and I guess that's the way.

**Comment by gsingh93** [comment]
@Saumya-ranjan do you still plan to work on this? If not, I'll go ahead and unassign you so someone else can pick this up.

**Comment by gsingh93** [comment]
Fixed in #1729.
