### ISSUE TITLE
Binary Ninja Integration

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#148]
Currently, Pwndbg supports integration with IDA via `ida_script.py` and `pwndbg/ida.py`.

Among the interesting currently- supported functionality:

- Extraction of comments
- Extraction of symbols
- Bidirectional breakpoint setting/clearing (kind of)
- Jump-to-PC / Cursor 

This functionality should also be supported with Binary Ninja (https://binary.ninja).  It should be relatively easy to hack in support.  Later, a clean re-design would be nice to have a standardized interface to e.g. add symbols, vs the symbol-query code specifically asking IDA / BN for symbols.

**Comment by junorouse** [comment]
When will the implementation be completed? I am very excited.
