### ISSUE TITLE
build error at unicorn setting.

### ISSUE THREAD

**Issue by junorouse** [pwndbg/pwndbg#149]
```
mkdir -p /usr/lib
install -m0755 libunicorn.so.1 /usr/lib
install: cannot stat 'libunicorn.so.1': No such file or directory
Makefile:253: recipe for target 'install' failed
make: *** [install] Error 1
```

# 1
I've already tested on both python2 and python3 environment.

# 2
And reinstall my ```root@ubuntu-linux:~/pwndbg# uname -a
Linux ubuntu-linux 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
root@ubuntu-linux:~/pwndbg# cat /etc/issue
Ubuntu 16.04.1 LTS \n \l

root@ubuntu-linux:~/pwndbg#```

# 3
I builded unicorn manually but occurred diffrent error.

```
Command "/usr/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-LQX9_C-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-IzpwA0-record/install-record.txt --single-version-externally-managed --compile --home=/tmp/tmpfNCOee" failed with error code 1 in /tmp/pip-LQX9_C-build/
```

please help.

**Comment by saidelike** [comment]
I get the same error with a Ubuntu 14.04.2 64-bit and the git repo cloned today:

```
$ uname -a
Linux user-ubuntu14 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ gdb --version
GNU gdb (GDB) 7.11

```

```
pwndbg$ ./setup.sh 
...
++ which python2
+ sudo UNICORN_QEMU_FLAGS=--python=/usr/bin/python2 ./make.sh install
mkdir -p /usr/lib
install -m0755 libunicorn.so.1 /usr/lib
install: cannot stat ‘libunicorn.so.1’: No such file or directory
make: *** [install] Error 1
```

**Comment by zachriggle** [comment]
This was caused by updating the version of Unicorn, which introduced build problems.

I fixed this by rolling back to the version we were using before (ea1b533).

I pushed this commit a few days ago to `dev`, but didn't merge it to `master`.

Everything should work now.
