### ISSUE TITLE
Add a `OnlyWithLibcLoaded` decorator

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#1496]
We have two commands at the moment that don't make sense to run if libc is not loaded: `errno` and `tls`. `errno` has some basic logic in there to handle this, but `tls` doesn't. It would be much better if we had a decorator (`OnlyWithLibcLoaded`) that checked `info sharedlibrary` (see `info.py` for a helper function) for the libc library before allowing the command to run.

Even better would be an `OnlyWithLibraryLoaded` decorator that took a library as an argument, and `OnlyWithLibcLoaded` would be one special case of that ([`OnlyWithArch`](https://github.com/pwndbg/pwndbg/blob/dbaba63a74415ee2a0991d936ea93bbe97512828/pwndbg/commands/__init__.py#L266) is an example of a similar decorator).

**Comment by dmur1** [comment]
is there another use case for this decorator? because the stated one seems to be well handled in my tests with https://github.com/pwndbg/pwndbg/blob/dev/tests/gdb-tests/tests/binaries/emulate_disasm.asm

![image](https://github.com/pwndbg/pwndbg/assets/93072266/cf984c62-39ba-499a-b549-d89c4f186d16)

![image](https://github.com/pwndbg/pwndbg/assets/93072266/c93bde31-98cf-4e0e-8370-5a2442b418bd)

```
pwndbg> version
Gdb:      12.1
Python:   3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
Pwndbg:   2023.03.19 build: 92ca6b9
Capstone: 4.0.1024
Unicorn:  2.0.1
```

**Comment by gsingh93** [comment]
These commands currently handle libc not being loaded but 1) at least for `errno` this wasn't always the case, meaning the command was first implemented in a way that threw an exception when libc wasn't loaded, 2) both of these commands have to implement the same error handling for the same issue, and 3) new commands we write in the future are going to have the same problems, and we'd ideally like to solve that problem by just adding a decorator onto the command instead of reimplementing the same logic.

**Comment by dmur1** [comment]
here you go https://github.com/pwndbg/pwndbg/pull/1722

take a look and let me know if you want a libc specific decorator implemented in terms of this too

**Comment by lebr0nli** [comment]
I agreed that we should have this decorator to handle some checks more elegant.

But regarding this:
> don't make sense to run if libc is not loaded: `errno` and `tls`.

If the binary is a statically linked executable, I guess `OnlyWithLibraryLoaded`/`OnlyWithLibcLoaded` will probably prevent the `errno` command be used even `errno` symbol is there?
(So does the `tls` command in some cases.)
Maybe we should have an `OnlyWithLibraryLoadedOrStaticallyLinked` or something instead if we want to apply to `errno` and `tls`?

Btw, `OnlyWithLibraryLoaded` might prevent the use of `LD_PRELOAD` with a name that can't match the expectations.
I mean if we do something like `LD_PRELOAD=./libc-2.37.so ./chall`, we might get false negatives if we only allow `r"libc\.so"` to use some commands.
Also, we might get false positives if some libraries have similar names.
(Similar issues also happened on handling the heap heuristics. Currently, I don't have a good idea to fix this, and not sure if it is really possible to handle all the cases XD)

**Comment by gsingh93** [comment]
Good point.

> OnlyWithLibraryLoadedOrStaticallyLinked

I think generically determining whether some arbitrary library is statically linked may be difficult. Are we doing something like this for heap heuristics for libc at least? How are we doing this?

> Btw, OnlyWithLibraryLoaded might prevent the use of LD_PRELOAD with a name that can't match the expectations.

Good catch. Whatever you're doing for heap heuristics, we can pull it out into a helper function and use the same function everywhere we want to do this. Then as we fix bug reports for one feature, the other will also get those fixes. Maybe we can even fallback to some slower heuristics if no libc is found, i.e. looking for a certain symbol or string in some of the loaded libraries.

**Comment by lebr0nli** [comment]
> I think generically determining whether some arbitrary library is statically linked may be difficult.

Yea, I also think it's quite hard to determine.

> Are we doing something like this for heap heuristics for libc at least? How are we doing this?

Currently, the check is still quite rough, for heap heuristics, we just check if the binary is fully statically linked or not by this:
https://github.com/pwndbg/pwndbg/blob/b5a1219e2f93235b6116be6dce1a4f91ea871b75/pwndbg/heap/ptmalloc.py#L1310-L1312

> Whatever you're doing for heap heuristics, we can pull it out into a helper function and use the same function everywhere we want to do this.

Yeah, I agreed. Here's the code that we used to parse the libc filename from `info sharedlibrary` btw: https://github.com/pwndbg/pwndbg/blob/b5a1219e2f93235b6116be6dce1a4f91ea871b75/pwndbg/glibc.py#L76-L109

**Comment by disconnect3d** [comment]
I think we can drop this issue for now. We handle `errno` and `tls` somewhat for now. This can be seen when stopping at the very first instruction of the loader (its entrypoint; note: requires a dynamically linked binary):

```
pwndbg> starti
...
pwndbg> errno
Could not determine error code automatically: the __errno_location@got.plt has no valid address yet (perhaps libc.so hasn't been loaded yet?)
pwndbg> tls
Couldn't find Thread Local Storage (TLS) base.
You can try to use -p/--pthread option to get the address of TLS by calling pthread_self().
(This might cause problems if the pthread_self() is not in libc or not initialized yet.)
```

vs - when dynamic loader loaded the binary and we stop at entrypoint of the binary:

```
pwndbg> entry
...
pwndbg> tls
Thread Local Storage (TLS) base: 0x7ffff7ee6800
TLS is located at:
    0x7ffff7ee6000     0x7ffff7ee9000 rw-p     3000      0 [anon_7ffff7ee6]
pwndbg> errno
Errno 2: ENOENT

**Comment by disconnect3d** [comment]
Closing this for now.
