### ISSUE TITLE
heap i386 errors

### ISSUE THREAD

**Issue by GrosQuildu** [pwndbg/pwndbg#151]
Hey
When running heap commands (heap, bins...) on 32bit binaries I got error from pwndbg/pwndbg/typeinfo.py#132:
```Command '/usr/bin/x86_64-redhat-linux-g++ -m32 -w -c -g /tmp/pwndbg/i386_struct-malloc_state.cc -o /tmp/pwndbg/i386_struct-malloc_state.o' returned non-zero exit status 1```

And first error from g++ (there is a lot): 
`In file included from /tmp/pwndbg/i386_struct-malloc_state.cc:40:0:
/usr/include/ffitarget-i386.h:34:2: error: #error "Please do not include ffitarget.h directly into your source.  Use ffi.h instead."`

Everything works fine with x64 binaries. OS is Fedora 23 (know you don't support it, but still).
g++ is x86_64-redhat-linux-g++ (GCC) 5.3.1 20160406 (Red Hat 5.3.1-6). glibc-headers/devel.i686 version 2.22
Any ideas what to do?

**Comment by zachriggle** [comment]
You likely need to install debug symbols for your copy of libc, so that it has access to the `malloc_state` struct.

On Ubuntu, the magic incantation is:

```
$ apt-get install libc6-dbg:i386 libc6-dbg
```

You can check whether you have the debug information via:

```
gdb$ info sharedlib
From                To                  Syms Read   Shared Object Library
0x00007ffff7dd8aa0  0x00007ffff7df6140  Yes         /lib64/ld-linux-x86-64.so.2
0x00007ffff7bbb6f0  0x00007ffff7bc76c8  Yes (*)     /lib/x86_64-linux-gnu/libtinfo.so.5
0x00007ffff79abd80  0x00007ffff79ac98e  Yes         /lib/x86_64-linux-gnu/libdl.so.2
0x00007ffff76039c0  0x00007ffff77540b3  Yes         /lib/x86_64-linux-gnu/libc.so.6
(*): Shared library is missing debugging information.
```

**Comment by GrosQuildu** [comment]
Ok, solved. Had to download debuginfo from rpmfind.net though.
Thanks.

**Comment by zachriggle** [comment]
It looks like you should be able to install via `yum` or `dnf`: https://ask.fedoraproject.org/en/question/76537/how-to-keep-installed-debuginfo-packages-up-to-date-with-dnf/

**Comment by ducphanduyagentp** [comment]
Today I've encountered the same problem when running the `heap` command but the error is different. I'm running Kali Linux 64-bit 2017.1 and tried to install libc6-dbg:i386 but that didn't help. This is my error output. Any solution?

``` In file included from /tmp/pwndbg/i386_struct-malloc_state.cc:62:0:
/usr/include/liblwgeom.h:35:22: fatal error: proj_api.h: No such file or directory
 #include "proj_api.h"
                      ^
compilation terminated.
Traceback (most recent call last):
  File "/root/pwndbg/pwndbg/commands/__init__.py", line 99, in __call__
    return self.function(*args, **kwargs)
  File "/root/pwndbg/pwndbg/commands/__init__.py", line 191, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/root/pwndbg/pwndbg/commands/heap.py", line 65, in heap
    main_arena  = main_heap.get_arena(addr)
  File "/root/pwndbg/pwndbg/heap/ptmalloc.py", line 157, in get_arena
    return self.main_arena
  File "/root/pwndbg/pwndbg/heap/ptmalloc.py", line 37, in main_arena
    self._main_arena = pwndbg.memory.poi(self.malloc_state, main_arena_addr)
  File "/root/pwndbg/pwndbg/memoize.py", line 48, in __call__
    value = self.func(*args, **kwargs)
  File "/root/pwndbg/pwndbg/heap/ptmalloc.py", line 75, in malloc_state
    return pwndbg.typeinfo.load('struct malloc_state')
  File "/root/pwndbg/pwndbg/typeinfo.py", line 141, in load
    compile(filename)
  File "/root/pwndbg/pwndbg/typeinfo.py", line 156, in compile
    subprocess.check_output(' '.join(gcc), shell=True)
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '/usr/bin/x86_64-linux-gnu-g++ -m32 -w -c -g /tmp/pwndbg/i386_struct-malloc_state.cc -o /tmp/pwndbg/i386_struct-malloc_state.o' returned non-zero exit status 1```

**Comment by zachriggle** [comment]
In any case, I have no idea what `proj_api.h` is or why it's being included, nor do I know why `liblwgeom.h` is being included.

Our auto-headers-to-symbols compilation just kind of grabs *all* of the include files that it can.  I guess some of yours aren't quite compatible.  #261 is related
