### ISSUE TITLE
The heuristic for `tcache` of the single-threaded target should be enhanced

### ISSUE THREAD

**Issue by lebr0nli** [pwndbg/pwndbg#1530]
Currently, if we can't find `tcache` with debug symbol or the config, the heuristic will try to analyze the assembly of `__libc_malloc` first.
But this method easily fails or gets a false positive result, especially for the thread-local variable like `tcache`.
In comparison, the accuracy of `mp_`'s heuristic is much better currently.
So if the target is single-threaded, we should try `mp_.sbrk_base + 0x10` first, like what we did when we have the debug symbols:
https://github.com/pwndbg/pwndbg/blob/d4562ea462b8013253c219ed5ddd292386be5c6c/pwndbg/heap/ptmalloc.py#L1139

**Comment by disconnect3d** [comment]
@lebr0nli Is this fixed with #1536?

**Comment by lebr0nli** [comment]
Yes, I think it's fixed now.

**Comment by lebr0nli** [comment]
Yes, I think it's fixed now.
