### ISSUE TITLE
Improve scroll functionality.

### ISSUE THREAD

**Issue by kmskrishna** [pwndbg/pwndbg#155]
Okay, I know that the name is too vague. But looking at the screenshot should give you a clear view of what I want to say. After you execute next command in **peda-gdb**, It automatically aligns the top part of the terminal to the registers part, So it is much easier to follow a register or stack. In **pwndbg**, It does not auto align making it confusing at times for me. I hope you understood my problem.

![screenshot from 2017-01-31 04-28-54](https://cloud.githubusercontent.com/assets/7846950/22445529/d7f7d1d0-e76d-11e6-8870-db097ce76527.png)

**Comment by zachriggle** [comment]
They are aligned to the bottom of the terminal ;-)

**Comment by kmskrishna** [comment]
Is there no way you guys can implement this functionality? I really like pwndbg and this is the only thing that is confusing me because I was used to peda-gdb. Come on guys I request you people to implement it. :smiley:

**Comment by disconnect3d** [comment]
Isn't it just a matter of clearing screen before sending all of the output/tui?

**Comment by kmskrishna** [comment]
@disconnect3d  I believe so.

**Comment by zachriggle** [comment]
Turns out there's actually an option for this already, thanks @anthraxx! (https://github.com/pwndbg/pwndbg/commit/6e2f8f7b)

```
pwndbg> config
Name                       Value (Def)       Documentation
----------------------------------------------------------
auto-save-search           False             automatically pass --save to "search" command
context-clear-screen       False             whether to clear the screen before printing the context
debug-events               False             display internal event debugging info
emulate                    True              Unicorn emulation of code near the current instruction
hexdump-bytes              64                number of bytes printed by hexdump command
hexdump-width              16                line width of hexdump command
ida-rpc-host               '127.0.0.1'       ida xmlrpc server address
ida-rpc-port               8888              ida xmlrpc server port
left-pad-disasm            True              whether to left-pad disassembly
show-flags                 False             whether to show flags registers
show-retaddr-reg           False             whether to show return address register
telescope-lines            8                 number of lines to printed by the telescope command
You can set config variable with `set <config-var> <value>`
You can generate configuration file using `configfile` - then put it in your .gdbinit after initializing pwndbg
```

```
pwndbg> set context-clear-screen on
```

**Comment by kmskrishna** [comment]
I have no words to express my gratitude. :smiley:
