### ISSUE TITLE
bugreport command: show more info

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#1555]
The bugreport command should display more information like:
* show osabi
* show architecture
* show endian

Depending on current arch -- note that those are only available if given arch is supported by current GDB, like `gdb-multiarch`:
* show arm
* show mips

Maybe also:
* show charset
* show width
* show height

**Comment by ggold7046** [comment]
Hi, how to get involved in pwndbg project as a newcomer ?

**Comment by disconnect3d** [comment]
Hi, just [send a pull request with a change that you want implemented](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

You can also use `rip grep`/`grep`/git grep` to find files ineository, which may or may not help. See also this: https://github.com/pwndbg/pwndbg/blob/dev/DEVELOPING.md

**Comment by gsingh93** [comment]
You can also join our Discord (link in the README) and we can help you with any questions.

**Comment by Unknown1934-del** [comment]
To display more information in the bugreport, we can add the following in the existing bugreport code:

    # 1. showing osabi
    osabi_info = platform.uname().version
    current_setup += "OS ABI: %s\n" % osabi_info

    # 2. showing architecture
    arch_info = platform.machine()
    current_setup += "Architecture: %s\n" % arch_info

    # 3. showing endian
    endian_info = sys.byteorder
    current_setup += "Endian: %s\n" % endian_info

    # 4. Depending on current arch -- note that those are only available if given arch is supported by current GDB, like gdb-multiarch
    if arch_info in ["armv7l", "aarch64"]:
        arm_info = gdb.execute("show arm", to_string=True)
        current_setup += "ARM: %s\n" % arm_info

    if arch_info in ["mips", "mips64"]:
        mips_info = gdb.execute("show mips", to_string=True)
        current_setup += "MIPS: %s\n" % mips_info

    # 7. showing charset
    charset_info = sys.getdefaultencoding()
    current_setup += "Charset: %s\n" % charset_info

    # 8. showing width
    width_info = os.get_terminal_size().columns
    current_setup += "Width: %s\n" % width_info

    # 9. showing height
    height_info = os.get_terminal_size().lines
    current_setup += "Height: %s\n" % height_info
