### ISSUE TITLE
gdbinit breaks with the latest kali installation

### ISSUE THREAD

**Issue by AlienX2001** [pwndbg/pwndbg#1560]
Hey,
So I just updated my kali box yesterday. Here are my specifications
![216100967-35a92e5f-c46f-4a15-aa22-d3a44e8be081](https://user-images.githubusercontent.com/64488123/216102591-34f19828-726f-4641-935b-666f7aef6d1c.png)

And as you can see I can easily import pwntools

![](https://user-images.githubusercontent.com/64488123/216101077-90085fc3-e4fc-4d65-9d1d-f04bd3189912.png)

But whenever I start gdb, it says it cant find the module "pwnlib"
![216101409-bfcd05f1-4ac8-48f2-af01-4a86c66c3538](https://user-images.githubusercontent.com/64488123/216102705-465588ec-6b01-413a-a945-cdadb45d903c.png)

**Comment by disconnect3d** [comment]
Hi, can you show `pi` -> `import sys; print(sys.version)` in GDB?

**Comment by AlienX2001** [comment]
![image](https://user-images.githubusercontent.com/64488123/216412712-b0a306bf-2496-49c7-8c46-1cddb33f4eac.png)

Here

**Comment by AlienX2001** [comment]
![image](https://user-images.githubusercontent.com/64488123/216413397-fba6d23a-d7ea-4231-84a4-2c6f077931f7.png)
 And this is my system wide python installation

**Comment by AlienX2001** [comment]
Right, with the help of this comment https://github.com/Gallopsled/pwntools/issues/2164#issuecomment-1413339907, I simply re executed the setup.sh and it fixed my gdb's python.
I wonder why they both have different python installations though.

Thanks
