### ISSUE TITLE
Support Rizin

### ISSUE THREAD

**Issue by egelja** [pwndbg/pwndbg#1566]
**Is your feature request related to a problem? Please describe.**
[Rizin](https://github.com/rizinorg) is a fork of Radare2, and comes with Ghidra built-in. It has nearly the same API, and there is also a [`rz-pipe`](https://github.com/rizinorg/rz-pipe/tree/master/python) for python. It would be great to have support for it.

**Describe the solution you'd like**
Add support for `rz-pipe`.

**Describe alternatives you've considered**
N/A

**Additional context**
The Ghidra disassembly command is `pdg`

**Comment by gsingh93** [comment]
@MrAwesomeRocks would you be willing to submit a PR for this? We have support for `radare2` and `r2pipe`, so the implementation may be similar (the same?): https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/commands/radare2.py#L57

**Comment by mariaWitch** [comment]
I have created pull request #1571  which should add rizin support.

**Comment by egelja** [comment]
Thank you @mariaWitch! I was planning to take a look at this when I had some free time, but it looks like you beat me to it.

**Comment by gsingh93** [comment]
Fixed in #1571, feel free to open new issues if any specific functionality is broken or missing.
