### ISSUE TITLE
Support Pagetables for i386/x86_32 Targets

### ISSUE THREAD

**Issue by mariaWitch** [pwndbg/pwndbg#1577]
**Is your feature request related to a problem? Please describe.**
When using pwndbg on a 32 bit QEMU target, vmmap fails to retrieve page tables, with the error that it is not implemented. And prevents context from being opened at all.

**Describe the solution you'd like**
Add pagetable support for i386/x86_32 targets,  or suppress the error if an architecture is not supported so that context can still be used.

**Describe alternatives you've considered**
At the very least, this error should be surpressed to allow normal application function.

**Additional context**
This specifically occurred for me when I am targeting a 32 bit QEMU target with limited file system access.
See the following stack trace.
![image](https://user-images.githubusercontent.com/77745122/218270048-46a21926-00d9-44f4-b30f-b7df2193e4b7.png)

**Comment by gsingh93** [comment]
Are you seeing this with `qemu-user` or `qemu-system-i386`?

**Comment by mariaWitch** [comment]
qemu-system-i386. It is integrated into a custom QEMU build for emulating the Original Xbox. (XEMU)

**Comment by gsingh93** [comment]
Thanks, I'll try to take a look this week. In the meantime, you can try `set kernel-vmmap none` to see if that will at least make pwndbg usable again, even if you don't have page table information.

**Comment by mariaWitch** [comment]
Looking for Update on this @gsingh93

**Comment by disconnect3d** [comment]
Does a `monitor info mem` command work on this target? If so, can you see if `set kernel-vmmap monitor` solves your issue?

**Comment by gsingh93** [comment]
Sorry for the delay here. #1739 will fix this issue, but I need a bit more time to clean it up before merging. I also needed this patch for gdb-pt-dump (https://github.com/martinradev/gdb-pt-dump/pull/23), but that should only be required for some versions of GDB. Once it's merged, I'll update our submodule to the latest version.
