### ISSUE TITLE
pwndbg with Exception occurred: context: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by DuckRui** [pwndbg/pwndbg#1587]
hi, I am using pwndbg to debug the program, but this error occurred.

Exception occurred: context: invalid literal for int() with base 10: '627\n662\n686\n783\n920' (<class 'ValueError'>)

![image](https://user-images.githubusercontent.com/41203418/220328643-3592f7a5-e484-4ee9-b83b-4b2d2ba733f9.png)

Can you help me to solve it? Thank you very much!

**Comment by disconnect3d** [comment]
Hey, can you do `set exception-verbose on` and show us the stacktrace?

Also any chance u can share ur setup/binary/etc so we can reproduce this?

**Comment by DuckRui** [comment]
> Hey, can you do `set exception-verbose on` and show us the stacktrace?
> 
> Also any chance u can share ur setup/binary/etc so we can reproduce this?

After set exception-verbose on
![image](https://user-images.githubusercontent.com/41203418/220339663-d4cddb07-4cdb-4462-aa21-e9c2ab6e1266.png)

this is my company's computer, so I can not share you binary, sorry

**Comment by DuckRui** [comment]
> Hey, can you do `set exception-verbose on` and show us the stacktrace?
> 
> Also any chance u can share ur setup/binary/etc so we can reproduce this?

I use a lower version pwndbg to fix this problem

**Comment by disconnect3d** [comment]
This error comes from gdb-pt-dump, a library we depend on.

They parse the output of `pgrep qemu-system` in https://github.com/martinradev/gdb-pt-dump/blob/ebdc24573a4bf075cf3ab6016add9db6baacf977/pt.py#L160-L162 which in your case, returns multiple process IDs which then cannot be parsed with `int(..., 10)`.

The easiest thing u can do to fix this is to... kill all other qemu-system processes on your machine and have only one of them.

Alternatively, u can patch the gdb-pt-dump to choose the first or last or other pid, based on whatever your need is.

We need to take this into gdb-pt-dump so they fix it _somehow_, but I am not sure if there is any "best" solution to that.

**Comment by gsingh93** [comment]
You can also run `set kernel-vmmap none` as a temporary workaround.

**Comment by disconnect3d** [comment]
Maybe we should just make it possible to specify the QEMU process pid?
