### ISSUE TITLE
Finalize Rizin Support

### ISSUE THREAD

**Issue by mariaWitch** [pwndbg/pwndbg#1596]
**Is your feature request related to a problem? Please describe.**
There is some differences between Radare2 and Rizin which can't be easily reconciled with just changing commands. Unfortunately, I was not able to resolve these before my Pull request was merged. There is specific logic needed in order to switch just which commands we are using to check that Ghidra is present.

**Describe the solution you'd like**
A specific config variable which will define if we are using Rizin or Radare2 would simplify and prevent a complex if chain in ghidra.py

**Describe alternatives you've considered**
I have tried adding specific solutions to Ghidra.py with little to no success, the only other solution I can think of is if we add a config variable that we can reference so that we will do one execution path or the other, since the command to identify if Ghidra is installed in Rizin is different from Radare2.

I should hopefully have a pull request draft up in the next few days.

**Comment by disconnect3d** [comment]
Ping :)

**Comment by disconnect3d** [comment]
Closing as this was never implemented. If anyone wants r2/rizin added anyhow, please send us a PR with that.
