### ISSUE TITLE
An error occurs during the ubuntu22 installation of setup.sh

### ISSUE THREAD

**Issue by djhtdjdywgjc** [pwndbg/pwndbg#1603]
```
The following packages have unmet dependencies:
 libglib2.0-dev : Depends: libglib2.0-0 (= 2.64.6-1~ubuntu20.04.4) but 2.72.4-0ubuntu1 is to be installed
                  Depends: libglib2.0-bin (= 2.64.6-1~ubuntu20.04.4)
                  Depends: libmount-dev (>= 2.28) but it is not going to be installed
                  Depends: libpcre3-dev (>= 1:8.31) but it is not going to be installed
                  Depends: libselinux1-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by disconnect3d** [comment]
It works on our CI with Ubuntu 22.04 and I never had this problem on Ubuntu 22.04. Can this be that you installed some Ubuntu PPAs that cause this trouble for you?

Any chance you can provide any more information about your environment?

**Comment by disconnect3d** [comment]
I am closing this since we have not enough information to act on this. However, I will look if we can improve this by having an option to install Pwndbg in a virtual environment in the future.
