### ISSUE TITLE
`pwndbg.gdblib.symbol.address` might return invalid address if vmmap is not working

### ISSUE THREAD

**Issue by lebr0nli** [pwndbg/pwndbg#1628]
https://github.com/pwndbg/pwndbg/blob/be306da2553596443d2bdaa378bf11cf59e3eab5/pwndbg/gdblib/symbol.py#L146-L147

Some weird results for thread-local variables might pass this check if our vmmap is not working.
For example, with qemu-user, the result of vmmap is a 0~0xfffff…ffff region, so `not pwndbg.gdblib.vmmap.find(address)` will always be `False`.

**Comment by disconnect3d** [comment]
Oh that's... obviously unintentional :), guess we need to handle the qemu 0-fffff case differently; perhaps we should check for this case somewhere and do sth based on that.

**Comment by gsingh93** [comment]
Would appreciate a PR for this @lebr0nli or @disconnect3d, otherwise will remove from the upcoming release milestone.
