### ISSUE TITLE
Long Strings Over Remote GDB

### ISSUE THREAD

**Issue by agkunkle** [pwndbg/pwndbg#163]
First off, I'd like to quickly say that pwndbg has truly been an indispensable tool - thank you for "making gdb great again"!

I recently started using pwndbg with gdb-multiarch 7.11 on Ubuntu 16.04 LTS to remote debug a process on Android with gdbserver.  I noticed that whenever one of the registers points to a very long string, running the "context" command (including automatically at a breakpoint) would take a **really** long time.  Digging into the source, I noticed that while `pwndbg.strings.get()` will use the conservative value set by default by `set print elements 15`, the `pwndbg.memory.string()` function it invokes does *not*, resulting in a byte-by-byte read of however long the string is in memory.  

It just so happened that $r1 was pointing to a ~30,000-char long string in my situation (don't ask), so it took quite a while to refresh.  During this time there isn't any prompt or other user feedback from gdb.

This could be fixed by updating the `string()` function to take a `maxlen` argument and then just pass that from `strings.get()`.  I didn't see any other callers of the function in the source.

**Comment by zachriggle** [comment]
> don't ask

I'll just bet it was `'A'*30000'` ;-)

**Comment by agkunkle** [comment]
Awesome, thanks!

**Comment by agkunkle** [comment]
Just curious, is there a slick way you know of to attach any type of debugger to a gdb process running pwndbg?  I would have done something like that to track down the "hang" a little quicker than just doing print-driven debugging.

**Comment by zachriggle** [comment]
Nope, not really.  Printing is your best bet.  You could use Python's built-in `pdb` module to step through things, but unless you invoke the function from the Python interpreter (`pi` in GDB), GDB will hook stdin so that you can't actually interact with it :(.
