### ISSUE TITLE
Officially support installation in a virtualenv

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#1634]
- [ ] Add a `--venv` flag to `setup.sh` that creates a new venv and installs pwndbg in it
- [ ] Remove any warnings about venvs, i.e. "Pwndbg/GDB run in virtualenv with which it may not work correctly"
- [ ] Add tests
- [ ] Add docs

**Comment by Cnly** [comment]
I think one bit isn't quite clear in the description: Do we want to create a venv dedicated to pwndbg, or will we reuse the user's currently active venv? If it's the former, maybe `~/.cache` would be an option for the location of our venv?

**Comment by disconnect3d** [comment]
@Cnly Whatever is best. I think we rather want to create a new virtual environment and we will just have to ask the user "where to put it", suggesting a location like `$pwndbg/.venv`, `~/.venv/pwndbg` or `~/.local/pwndbg-venv`. Alternatively, iirc we were thinking some time ago about some local cache, so maybe it could be sth like `~/.pwndbg/{venv,cache}`? I am not sure.
