### ISSUE TITLE
`rz-ghidra` may be not compatible with pwndbg, fixed by small tweaks with `ghidra.py`

### ISSUE THREAD

**Issue by sci-42ver** [pwndbg/pwndbg#1663]
### Description

I tried use Ghidra mentioned [here](https://github.com/pwndbg/pwndbg/blob/dev/FEATURES.md#ghidra), but the [`ghidra.py`](https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/ghidra.py) may be not compatible with `rizin` installed on my machine and I fixed that by small tweaks. 
Hope the following can help newbie like me (begin learning assembly and RE recently).

Best regards.

### Steps to reproduce

source code is same as this [issue](https://github.com/pwndbg/pwndbg/issues/1662#issue-1659751924).

original output without changing `ghidra.py`
```bash
$ gdb ./prog -ex 'start'
...
The target architecture is set to "i386:x86-64".
Voltron loaded.
pwndbg: loaded 139 pwndbg commands and 46 shell commands. Type pwndbg [--shell | --all] [filter] for a list.
pwndbg: created $rebase, $ida GDB functions (can be used with print/break)
Reading symbols from ./prog...
Temporary breakpoint 1 at 0x1149: file 010-main.c, line 6.

Temporary breakpoint 1, main () at 010-main.c:6
6       int main() {
------- tip of the day (disable with set show-tips off) -------
Disable Pwndbg context information display with set context-sections ''
WARNING: Neither hash nor gnu_hash exist. Falling back to heuristics for deducing the number of dynamic symbols...
WARNING: Neither hash nor gnu_hash exist. Falling back to heuristics for deducing the number of dynamic symbols...
WARNING: Neither hash nor gnu_hash exist. Falling back to heuristics for deducing the number of dynamic symbols...
ERROR: Command 'LD' does not exist.
ERROR: Displaying the help of command 'L'.

ERROR: Usage: L[?]   # List, unload, load rizin plugins
| L <plugin_file>    # Load a plugin from file
| L- <plugin_file>   # Unload a plugin from file
| Ll[j]              # List the lang plugins
| La[jq]             # List the asm/analysis plugins
| Lc[j]              # List the core plugins
| Ld[jq] [<handler>] # List debug plugins / Set debug backend (e dbg.backend)
| Lh[jq]             # List the hash plugins
| Li[jq]             # List the bin plugins
| Lo[jqt] [<path>]   # List IO plugins / Register IO plugin from <path>
| Lp[j]              # List the parser plugins
...
───────────────────────────────────────────────────────────[ GHIDRA DECOMPILE ]────────────────────────────────────────────────────────────
radare2/rizin plugin r2ghidra/rzghidra must be installed and available from r2/rz
```

### My setup

I build both rizin and pwndbg from github source, and env is same as this [issue](https://github.com/pwndbg/pwndbg/issues/1662#issue-1659751924).

.rizinrc
```bash
af
e scr.color=3
eco solarized
```

### my modification with source code
after the following modification, it shows I use `rizin` installed on my machine and `ghidra` decompile well.
```diff
$ diff ~/czg_tmp/ghidra_orig.py ~/czg_tmp/ghidra.py 
--- /home/czg/czg_tmp/ghidra_orig.py    2023-04-09 18:15:20.564533104 +0800
+++ /home/czg/czg_tmp/ghidra.py 2023-04-09 18:14:16.163050710 +0800
@@ -20,15 +20,18 @@
     """
     try:
         r2 = pwndbg.radare2.r2pipe()
+        print("use r2pipe")
     except ImportError:
         try:
             r2 = pwndbg.rizin.rzpipe()
+            print("use rzpipe")
         except ImportError:
             raise Exception("r2pipe or rzpipe not available, but required for r2/rz->ghidra bridge")
 
     # LD -> list supported decompilers (e cmd.pdc=?)
     # Outputs for example: pdc\npdg
-    if "pdg" not in r2.cmd("LD").split("\n"):
+
+    if "ghidra" not in r2.cmd("Laq").split("\n"):
         raise Exception(
             "radare2/rizin plugin r2ghidra/rzghidra must be installed and available from r2/rz"
         )
@@ -40,7 +43,7 @@
             else "main"
         )
 
-    src = r2.cmdj("pdgj @" + func)
+    src = r2.cmdj("pdgj @ " + func)
     if not src:
         raise Exception("Decompile command failed, check if '{}' is a valid target".format(func))
```
1. I found `L` command related doc is generated in file `cmd_descs.c`, and by `git log -p -- librz/core/cmd_descs/cmd_descs.c` I found this feature is added in `8811b8c`(commited at May 9 ) which is ancestor of current `dev` commit.
```bash
$ rg "List the core plugins" ~/rizin   
/home/czg/rizin/librz/core/cmd_descs/cmd_plugins.yaml
37:    summary: List the core plugins

/home/czg/rizin/librz/core/cmd_descs/cmd_descs.c
11438:  .summary = "List the core plugins",
$ git branch --contains 8811b8c
* dev
```

Then I check source code history, found rizin source code [changed](https://github.com/rizinorg/rizin/blob/9ab709bc34843f04ffde3b63322c809596123e77/librz/core/cmd_descs/cmd_descs.c#L20593) above APIs in `cmd_descs.c` after [newest](https://github.com/pwndbg/pwndbg/commit/84120d161b9342b4cd46f1a62eb2e2a92dc2c13a) of `ghidra.py`, which may result emiting errors on my machine.

I fixed by detecting `ghidra ... SLEIGH Disassembler from Ghidra` in `La` because `SLEIGH` is installed in `CMakeLists.txt` in `rz-ghidra` repo.

2. Also the `@` also need one [space](https://book.rizin.re/first_steps/command_format.html) after itself, tested on my machine.

**Comment by sci-42ver** [comment]
After using rizin for some time, I found it may have more internal [problems](https://github.com/rizinorg/rizin/issues/3456#issue-1660796761) than I can perceive ( maybe because rizin begins its independent development in 2020, still need time to become mature)

```bash
$ git merge-base origin/dev r2/master
af337b143909c9dfe1560b5005463ab44ba2548b
$ git log # /af337b143909c9dfe1560b5005463ab44ba2548b
...
commit af337b143909c9dfe1560b5005463ab44ba2548b
Author: Riccardo Schirone <ret2libc@users.noreply.github.com>
Date:   Wed Sep 30 10:40:23 2020 +0200
...
```

in r2, the above tweaks are redundant.

**Comment by disconnect3d** [comment]
Hi, please send a PR fixing this if possible. Otherwise, I am closing this issue for now.
