### ISSUE TITLE
Weird behavior when using `pwndbg.gdblib.symbol.address` on thread-local variables

### ISSUE THREAD

**Issue by lebr0nli** [pwndbg/pwndbg#1666]
This is yet another bug caused by the `info address` result of the thread-local variable.
This can be reproduced by:
```console
$ cat a.c
#include <stdlib.h>

int main(){
    free(malloc(0x20));
    return 0;
}
$ gcc -static-pie a.c
$ gdb -q ./a.out -ex 'set context-sections' -ex 'set exception-verbose' -ex start -ex 'print thread_arena' -ex 'info address thread_arena' -ex 'pi hex(pwndbg.gdblib.symbol.address("thread_arena"))'
...
Cannot find thread-local storage for process 2593, executable file /tmp/a.out:
Cannot find thread-local variables on this target
Symbol "thread_arena" is at 0x7fcfc93de038 in a file compiled without debugging.
'0x7fcfc93de038'
...
```

As you can see, GDB can't print `thread_arena` because it can't find thread-local storage.
But somehow, when we used `info address` to query the address of `thread_arena`, GDB still gave us a weird address (probably bug of GDB?):
```
Symbol "thread_arena" is at 0x7fcfc93de038 in a file compiled without debugging.
```
So `pwndbg.gdblib.symbol.address` returns `0x7fcfc93de038`, but this is not correct.

----

I'm on GDB 13.1 btw

**Comment by disconnect3d** [comment]
@lebr0nli After https://github.com/pwndbg/pwndbg/pull/1724 we get:
```
pwndbg> pi hex(pwndbg.gdblib.symbol.address("thread_arena"))
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: 'NoneType' object cannot be interpreted as an integer
Error while executing Python code.
```
Can you look at this?

**Comment by lebr0nli** [comment]
> Can you look at this?

Hmm, I guess this error is expected?
Since we didn't link with pthread, somehow gdb can't find the `thread_arena` without it, so `pwndbg.gdblib.symbol.address("thread_arena")` is `None`:
```
pwndbg> p thread_arena
Cannot find thread-local storage for process 93553, executable file /tmp/a.out:
Cannot find thread-local variables on this target
```
Before #1723 we will get an address instead of `None`, but the address we got is a weird and wrong result.

**Comment by disconnect3d** [comment]
Ah, you are right. The exception is thrown from `hex(...)` not from our code :P.

Closing this then :). Thanks!
