### ISSUE TITLE
`heap-dereference-limit` is not respected by heap commands

### ISSUE THREAD

**Issue by CptGibbon** [pwndbg/pwndbg#1677]
Reported by @yooo1999 via Discord

Shown below, the `unsortedbin` command ignoring the `heap-dereference-limit` config variable and only printing 5 chunks.

![unsortedbin limit wrong](https://user-images.githubusercontent.com/16000770/233204063-47e2e28b-69f7-4796-8689-af5a596f87b7.png)

The `heap-dereference-limit` config variable is indeed used to *fetch* an appropriate number of chunks for the heap commands via `GlibcMemoryAllocator.bin_at()`:
https://github.com/pwndbg/pwndbg/blob/e6037f547acf94b3badf0b2dea72cc72b22adf3e/pwndbg/heap/ptmalloc.py#L1184-L1192

But when this data is formatted by `pwndbg.commands.heap.format_bin()` no explicit limit is set, resulting in the default value from `pwndbg.chain` being used (the `dereference-limit` config variable).
https://github.com/pwndbg/pwndbg/blob/e6037f547acf94b3badf0b2dea72cc72b22adf3e/pwndbg/commands/heap.py#L81

One solution could be to pass `heap-dereference-limit` as an explicit argument to `pwndbg.chain.format()` in `pwndbg.commands.heap.format_bin()`.

**Comment by disconnect3d** [comment]
@CptGibbon Is this still a valid bug?

**Comment by CptGibbon** [comment]
> @CptGibbon Is this still a valid bug?

I shall check, if it's not fixed it could be an easy win for a GSoC contributor.

**Comment by CptGibbon** [comment]
This is indeed still a valid bug.

**Comment by disconnect3d** [comment]
This was implemented in https://github.com/pwndbg/pwndbg/pull/2077
