### ISSUE TITLE
Logger to file with colors

### ISSUE THREAD

**Issue by yooo1999** [pwndbg/pwndbg#1698]
To save logs to file I use

```
set logging file gdb_log.txt
set logging enabled on
```
The problem is that it doesn't save the colors, and colors help to analyze heap etc. 
`contextoutput` know only to save regs/code/stack etc.

Please consider to add logger with colors to file.

**Comment by disconnect3d** [comment]
I'm not sure why doesn't colors get added to logger; would be nice if someone investigated that. Adding 'help wanted' flag.

**Comment by Unknownsentinel193** [comment]
Hi, I would like to work on this, Can please assign this to me.

**Comment by jetchirag** [comment]
I might be wrong but I don't think gdb itself stores colors in log since they are just plaintext files and can't keep color info. It might be possible to use special character which can be used to set color in terminal but not normal log files.

**Comment by gsingh93** [comment]
Colors can be written to plaintext files through terminal escape/control codes (try `grep` or `rg` with `--color=always` and write to a file to see an example), but GDB doesn't support this so there's nothing we can do (unless someone wants to add this to GDB). Going to close this.
