### ISSUE TITLE
Better display for canary command

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#1704]
The canary command should:
* Display the thread id for a given stack
* For the current stack (to which RSP points to) it should mark the offset from RSP to the given address

We can discuss which format we want to display it in when a PR comes.

**Comment by Unknownsentinel193** [comment]
Hi, can I work on this?

**Comment by disconnect3d** [comment]
@Unknown1934-del Sure, you don't have to ask, just implement something and send a PR :)

**Comment by dmur1** [comment]
i'm going to take a look at this:

to clarify @disconnect3d 

you would like:

1) to add -a / --all flag to toggle between listing canary values on the current thread's stack vs all thread stacks
2) to clearly label each telescope line with the thread id

is that roughly correct?

**Comment by dmur1** [comment]
https://discord.com/channels/843809097920413717/871339601149706270/1213066349308280873 see additional comments here

**Comment by dmur1** [comment]
![image](https://github.com/pwndbg/pwndbg/assets/93072266/1d4a67a4-28a2-4650-82ef-66779076a39e)
@disconnect3d thoughts on this?

**Comment by disconnect3d** [comment]
@dmur1 Ideally:
* the first column is redundant and the thread id could be there?
* Thinking about it more, telescoping/enhancing the ptrs may not make sense since they all have canary value :P 
* We don't show rsp offsets (or: the sccreen doesnt show it)

**Comment by dmur1** [comment]
> @dmur1 Ideally:
> 
> * the first column is redundant and the thread id could be there?

agreed

> * Thinking about it more, telescoping/enhancing the ptrs may not make sense since they all have canary value :P

agreed - only difference is the CURRENT thread stack shows in yellow rather than purple

> * We don't show rsp offsets (or: the sccreen doesnt show it)

oh yeah missed this requirement, will look

**Comment by k4lizen** [comment]
I think this should be closed? The PR that implements this was merged

**Comment by disconnect3d** [comment]
Yes, thanks :)
