### ISSUE TITLE
Adjust pwndbg to uclibc

### ISSUE THREAD

**Issue by joko99999** [pwndbg/pwndbg#1715]
Please adjust pwndbg to uclibc so we can inspect the heap as we can do in GLIBC

Thank you

**Comment by joko99999** [comment]
@gsingh93 I start to look , and I couldn't do that...
Uclibc has only 1 arena

**Comment by disconnect3d** [comment]
Not planned for now. However, I would be happy to merge `uclibc` heap inspection if anyone is willing to work on that.
