### ISSUE TITLE
Drop support for Python 3.6 (Ubuntu 18.04) and Python 3.7

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#1744]
The release next month will be the last release supporting Python 3.6 and Python 3.7, which also means it's the last release supporting Ubuntu 18.04.

Python 3.6 has been EOL for a year and a half, and Python 3.7 is EOL next month. Python 3.6 is used for the GDB package on Ubuntu 18.04, so this will break `pwndbg` support on that distro by default (which became EOL itself last month). Python 3.7 is not used in the GDB package for any Ubuntu distro (Ubuntu 20.04 uses Python 3.8).

It's time to drop Python 3.6 so we can start using newer Python features and dealing with the headache of supporting old distros that aren't being used as much. Since no Ubuntu distro uses Python 3.7, we'll be dropping support for it at the same time.

If you need to use `pwndbg` on Ubuntu 18.04 distros, you can either: 1) install the last release supporting it or 2) build/install a newer version of GDB on your distro.

- [x] Tag next release as `ubuntu18.04-final` or something similar, so it's easy for people to find if they need it
- [x] Remove GH CI infrastructure still using 18.04 (including in Docker images)
- [x] Update `vermin` in `lint.sh` to check for Python 3.8 compatibility instead of Python 3.6
- [x] Upgrade dependency versions in `requirements.txt` and `dev-requirements.txt`, keeping only versions needed for Python 3.8
- [x] Remove string forward declarations and import `annotations` from `__future__` instead (see https://stackoverflow.com/a/55344418/803801)

**Comment by gsingh93** [comment]
@disconnect3d I think Debian 10 still uses Python 3.7. Should we only drop Python 3.6? Or only support the latest two Debian releases (11 and 12)? If anyone really needs to use Debian 10, they can still use the next release without any issues, they just won't get any feature updates.

**Comment by disconnect3d** [comment]
https://wiki.debian.org/LTS

<img width="931" alt="image" src="https://github.com/pwndbg/pwndbg/assets/10009354/03cefb65-21b6-49f0-bf13-0c9ce80f1379">

Good question; I bet we can probably drop support for 3.7 and Debian 10, but I wonder: what's the difference between 3.7 and 3.8?

**Comment by gsingh93** [comment]
The improvements I'm interested in are mainly typing related things:
- This annoyance is fixed in Python 3.8: https://stackoverflow.com/questions/55320236/does-python-evaluate-type-hinting-of-a-forward-reference/55344418#55344418
- `typing.TypedDict` is useful
- `typing.Literal` is useful
- [Protocols](https://docs.python.org/3/library/typing.html#typing.Protocol) are useful

I've also been using `from functools import singledispatchmethod` in other projects, not sure where exactly we would use it in pwndbg but it would be nice to have the option.

Looking at [this](https://docs.python.org/3/whatsnew/3.8.html), there are number of other small quality of life improvements that would be nice to have.

**Comment by disconnect3d** [comment]
The next release has shipped in https://github.com/pwndbg/pwndbg/releases/tag/2023.07.17

**Comment by disconnect3d** [comment]
Ubuntu 18.04 support removed in https://github.com/pwndbg/pwndbg/pull/1814
Debian 10 support removed in https://github.com/pwndbg/pwndbg/pull/1812

**Comment by disconnect3d** [comment]
Python <= 3.7 deps were removed from requirements files in https://github.com/pwndbg/pwndbg/pull/1816

**Comment by disconnect3d** [comment]
We can add annotations imports to all files with isort: https://adamj.eu/tech/2021/05/15/python-type-hints-future-annotations/#adding-to-all-files (thx to Łukasz from Pykonik for this ;))

**Comment by disconnect3d** [comment]
Finally finished in https://github.com/pwndbg/pwndbg/pull/1840
