### ISSUE TITLE
Parse heap start from address

### ISSUE THREAD

**Issue by joko99999** [pwndbg/pwndbg#1747]
In `vis` command I can put a start address to present.

Please add that feature to `heap` command .

**Comment by disconnect3d** [comment]
Hi, isn't this feature already there? The `heap` command does indeed take an `addr` argument which is "Address of the first chunk (malloc_chunk struct start, prev_size field).": https://github.com/pwndbg/pwndbg/blob/addf96f9bc7d530329d8c323dfc93e72c04368a9/pwndbg/commands/heap.py#L144-L163
