### ISSUE TITLE
Print real size in heap command

### ISSUE THREAD

**Issue by joko99999** [pwndbg/pwndbg#1748]
The command `heap` print the size for each chunk
That size is not the real size , that include 3 bits for flag.

I offer to  change the size for real size.

**Comment by disconnect3d** [comment]
Hi, I guess we can make such a change but aren't we printing the flags as their macro names?

Anyway, I am okay with changing this but I believe its nice to show both "chunk size" and "real size".

Maybe sth like I described in https://github.com/pwndbg/pwndbg/pull/1689#issuecomment-1532222865

Also, this is pretty easy to change, would you be fine with making a pull request with it?

The chunk printing is done in https://github.com/pwndbg/pwndbg/blob/addf96f9bc7d530329d8c323dfc93e72c04368a9/pwndbg/commands/heap.py#L375-L442

**Comment by joko99999** [comment]
@disconnect3d I don't know how to fix the test .
I don't this we need to print both size.

**Comment by disconnect3d** [comment]
Well, you will say that you like version X, we implement the change, and in a week someone else will say they like version Y.

We can of course make this configurable, but how many people will really configure this?

We need to balance user experience so things are crystal clear and understandable for new users as well...

**Comment by joko99999** [comment]
@disconnect3d OK. Print then both its easy, but I can't find the desire changes in unitest

**Comment by gsingh93** [comment]
Was this completed in #1781 ? If so, lets close this issue.

**Comment by disconnect3d** [comment]
Yup, #1781 closes this! :)
