### ISSUE TITLE
More docs about how other distribution install this

### ISSUE THREAD

**Issue by Escapingbug** [pwndbg/pwndbg#175]
I found it no doc about how other distribution should install pwndbg, and so I have to dive deeper to install this on my Arch.

**Comment by anthraxx** [comment]
how about https://aur.archlinux.org/packages/pwndbg-git/ or https://aur.archlinux.org/packages/pwndbg/

**Comment by Escapingbug** [comment]
Thanks for that. But I think if there can be a little more doc about this kind of problem in readme. And still, thanks.

**Comment by zachriggle** [comment]
I don't have time to maintain instructions for every distro.  If you'd like to contribute some instructions, I'd be glad to add them.  Currently, the `setup.sh` script seems pretty straightforward.  Any distro-specific changes are the responsibility of the user.  Or just use Ubuntu :D

**Comment by disconnect3d** [comment]
Added the info in PR #186.
