### ISSUE TITLE
Validate docker-compose version before run tests.sh

### ISSUE THREAD

**Issue by yooo1999** [pwndbg/pwndbg#1758]
I have tried to run `docker-compose run main ./tests.sh` and I got error:
```
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

The problem was I used docker-compose 1.25.0
```
docker-compose --version
docker-compose version 1.25.0, build unknown
```
and that was incompatible with the requirement .

Maybe   `tests.sh` should contains `docker-compose run main` command and validate minimum version of  docker-compose (if not it will be installed )

**Comment by disconnect3d** [comment]
Ideally yes, but what is the minimum docker-compose version here? I feel like this issue is easy to google or just ask about on discord...

I am not sure if its worth implementing.

**Comment by disconnect3d** [comment]
Ideally yes, but what is the minimum docker-compose version here? I feel like this issue is easy to google or just ask about on discord...

I am not sure if its worth implementing. @gsingh93 what do you think?

**Comment by disconnect3d** [comment]
If someone wants to add this, go ahead and send a PR. I don't think this is a major issue that needs to be prioritized or that needs a separate GH issue to be tracked. 

Because of that, I am closing this here :).
