### ISSUE TITLE
use find_addr_on_stack for retaddr

### ISSUE THREAD

**Issue by dmur1** [pwndbg/pwndbg#1762]
see discussion in pull request here: https://github.com/pwndbg/pwndbg/pull/1740/

**Comment by disconnect3d** [comment]
This issue itself does not do much on describing what we want to achieve here, but the point was to add `retaddr` display in context. I don't remember what was the reason we closed it, I think this may cause some perf troubles so this have to be measured, but generally speaking I am open to add/merge such feature in the future.

Closing this for now, as I believe it is somehow tracked by #1071
