### ISSUE TITLE
vmmap <address/page>

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#1766]
It would be nice if the `vmmap $rdx` command would also display few memory pages after the found one.

This is often helpful for any out-of-bounds read/write primitives when we can jump over pages.

**Comment by gsingh93** [comment]
Probably want before as well, not just after. Should this be the default or enabled with an optional flag?

**Comment by gsingh93** [comment]
We could make it like grep, with -A, -B, -C for after, before, both with a number of how many additional to print.

**Comment by disconnect3d** [comment]
I think this should be a default. -A/B/C flags would also be okay, or, a config option if the default is wanted or not ( ? ).

**Comment by disconnect3d** [comment]
Done in #1810. We finally added -B and -A options and we didn't add -C since we don't want to handle the mix of them.

**Comment by disconnect3d** [comment]
Hmm @feelfreelinux the #1810 broke a case where the filtered memory page displayed the offset from the address, e.g. in:

```
pwndbg> vmmap $rip
LEGEND: STACK | HEAP | CODE | DATA | RWX | RODATA
             Start                End Perm     Size Offset File
    0x555555554000     0x555555558000 r--p     4000      0 /usr/bin/ls
    0x555555558000     0x55555556c000 r-xp    14000   4000 /usr/bin/ls
    0x55555556c000     0x555555574000 r--p     8000  18000 /usr/bin/ls
```

We previously showed:
```
    0x555555558000     0x55555556c000 r-xp    14000   4000 /usr/bin/ls + <offset from the begining of the page>
```
