### ISSUE TITLE
Fix Arch Linux tests

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#1772]
The Arch Linux tests are failing due to new versions of pip needing to use the `--break-system-packages` flag to install packages globally. We should update the CI to use a virtualenv here.

**Comment by disconnect3d** [comment]
https://github.com/pwndbg/pwndbg/pull/1776 removed arch from CI for now. 

In the future, #1634 should allow for bringing back Arch on CI (or not bothering about it at all?).

Going to close this for now.

**Comment by gsingh93** [comment]
This was actually intended to be the tracking issue for re-enabling the test, so going to reopen :)

**Comment by disconnect3d** [comment]
Fixed in https://github.com/pwndbg/pwndbg/pull/1800 <3
