### ISSUE TITLE
find_fake_fast --glibc-fastbin-bug option is broken

### ISSUE THREAD

**Issue by SlidyBat** [pwndbg/pwndbg#1773]
### Description

Using the `find_fake_fast` option `--glibc-fastbin-bug` always results in an error, at least on 64-bit platforms.
This seems to be because the option causes [only 4 bytes](https://github.com/pwndbg/pwndbg/blob/8d0ccbc3eb94ee91b25c76a1b9e3201e7a70ad82/pwndbg/commands/heap.py#L686) to be read for the size, but then that gets [passed to `unpack()`](https://github.com/pwndbg/pwndbg/blob/8d0ccbc3eb94ee91b25c76a1b9e3201e7a70ad82/pwndbg/commands/heap.py#L761) which expects 8 bytes.

### Steps to reproduce

Run `find_fake_fast -b <address>` in a 64-bit environment and observe error.

### My setup

```
Gdb:      12.1
Python:   3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
Pwndbg:   2023.03.19 build: 79ade42
Capstone: 4.0.1024
Unicorn:  2.0.1
```

**Comment by CptGibbon** [comment]
Confirmed, thanks for reporting this.
That'll teach me not to test my new features 😵
