### ISSUE TITLE
Update Pwntools

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#1777]
**EDIT: This issue is blocked by Pwntools release, see https://github.com/pwndbg/pwndbg/issues/1777#issuecomment-1621546403 for more info**

A recent PR (https://github.com/pwndbg/pwndbg/pull/1770#discussion_r1251932873) added this branching for Pwntools version here:
https://github.com/pwndbg/pwndbg/blob/a6cc19aa5ce36147c80281923bf3603ee40743ea/pwndbg/gdblib/arch.py#L12-L39

We should:
1) Update Pwntools
2) Release new version of Pwndbg
3) Remove the branching code and set appropriate keys into the `pwnlib_archs_mapping` dict

We can do 1) and 3) at the same time, but people may not update dependencies when they update pwndbg and they may complain that the update broke some behavior. On the other hand, risc-v is not that common use case yet, so it is not so likely that this will happen.

Also, if we move to installation with virtualenv before the next release, we can probably do 1) and 3) at the same time.

**Comment by disconnect3d** [comment]
Small update: we can definetely do 1) and 3) together. A recent commit updated capstone and if someone doesn't update deps, they will get: 
```
Traceback (most recent call last):
  File "/root/pwndbg/gdbinit.py", line 101, in <module>
    import pwndbg  # noqa: F401
  File "/root/pwndbg/pwndbg/__init__.py", line 7, in <module>
    import pwndbg.commands
  File "/root/pwndbg/pwndbg/commands/__init__.py", line 15, in <module>
    from pwndbg.heap.ptmalloc import DebugSymsHeap
  File "/root/pwndbg/pwndbg/heap/ptmalloc.py", line 20, in <module>
    import pwndbg.disasm
  File "/root/pwndbg/pwndbg/disasm/__init__.py", line 38, in <module>
    "rv32": CS_ARCH_RISCV,
NameError: name 'CS_ARCH_RISCV' is not defined. Did you mean: 'CS_ARCH_MIPS'?
```

already ;)

**Comment by peace-maker** [comment]
We could catch that error as well on older capstone releases? virtualenv sounds good too though.

**Comment by disconnect3d** [comment]
We can:
1. Check dependency versions on startup 
2. Import everything explicitly (instead of `from x import *`) and then catch import errors and then check dependency versions
3. Ignore issues like this and tell users to re-install

**Comment by disconnect3d** [comment]
Fwiw Pwntools latest is 4.10.0 and 4.11 is only in beta: https://github.com/Gallopsled/pwntools/releases

**Comment by peace-maker** [comment]
4.11.0 is out now https://github.com/Gallopsled/pwntools/releases/tag/4.11.0

**Comment by disconnect3d** [comment]
Done in https://github.com/pwndbg/pwndbg/pull/1905/commits/97806ba1aa156da864824e6af562876565a700b7
