### ISSUE TITLE
Add spray memory command

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#1778]
I find myself doing `pi pwndbg.gdblib.memory.write(<address or pwndbg.gdblib.regs.rdi>, b'a' * some_length)` to spray memory or similar.

I think its time to have a command for this that would work in the following way:

```
spray <address> <length> [--value <value>] [-x | --only-funcptrs]
spray $rdi 0x1000          - writes cyclic(len=0x1000, n=ptrsize) to address pointed by $rdi
spray $rdi                        - writes cyclic starting at $rdi until the end of vmmap page pointed by $rdi
```

* By default, we should spray with cyclic
* If someone wants/needs, they can spray with a certain value: `--value 0x41` should spray with `bytes([0x41]) * length`, `--value 0x41414141` with `bytes([0x41, 0x41, 0x41, 0x41]) * (length / 4)` etc.
* If address is not valid, we should inform the user about it
* If length exceeds the vmmap the address points to, we should detect it early on and error out
* What if vmmap is a page guard or is read-only? Does this still work? I think yes for read-only and not for page-guard? To be checked
* The `-x | --only-funcptrs` flag should make it that we only spray values that are code/function pointers -- so we start at <address>, we check if it is a pointer to code, if yes, we spray it, if not, we do not; we then increment the address by ptrsize and do the same until we hit the expected length

---

Here are some materials that may help in implementing this (for whoever takes this task):
- different command implementations: https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/commands/ -- you can look at `xor.py`, `hexdump.py`, `vmmap.py` etc.
- memory utilities: https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/gdblib/memory.py -- `pwndbg.gdblib.memory.write` can be used to write to memory

Also note that the `ArgparsedCommand` abstraction we use may return you a `gdb.Value` if you take an `int` type argument. Thanks to this, the command that takes an `int` argument can also take an argument which is symbol name. So if you have a symbol in your debugged binary like `main` and you do `spray main 0x100` the `main` will be processed by GDB and returned as a `gdb.Value` object on which you can then do `int(obj)` to get its address.
* Actually, I think this is a bit more complex and you would have to do `spray &main 0x100` but oh well, check it out for yourself?

**Comment by disconnect3d** [comment]
The first part of this has been done in https://github.com/pwndbg/pwndbg/pull/1782 :)

**Comment by disconnect3d** [comment]
And a `--value` flag was added in https://github.com/pwndbg/pwndbg/commit/de4acb2f40da3b0c97353a8b680ffa6440346f7b

**Comment by disconnect3d** [comment]
@bog2n any chance u can add the `--only-funcptrs|-x` flag? And maybe some test[s] :P

**Comment by bog2n** [comment]
I'm working on it

**Comment by disconnect3d** [comment]
Finished in https://github.com/pwndbg/pwndbg/pull/1809 :)
