### ISSUE TITLE
Heap UAF Detection

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#178]
https://twitter.com/_hugsy_/status/840700401938718720

**Comment by disconnect3d** [comment]
@mbrla0 I think this was implemented as part of heap tracking feature?

**Comment by disconnect3d** [comment]
Yeah, this was implemented as part of `track-heap` feature.

```
pwndbg> track-heap
usage: track-heap [-h] {enable,disable,toggle-break} ...
track-heap: error: the following arguments are required: {enable,disable,toggle-break}
```

Tested with:
```c
int main() {
    int * x = malloc(123);
    free(x);
    *x = 123;
}
```
Compile with `gcc a.c` and then `gdb ./a.out`, `break main`, `run`, `track-heap enable`, `continue`:
<img width="665" alt="image" src="https://github.com/user-attachments/assets/b2f42ea2-e6e3-4263-ba51-0e866181a89b">
