### ISSUE TITLE
GH actions - save-state is deprecated

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#1787]
Our GH actions builds warn us about this:

> The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

This can be seen here: https://github.com/pwndbg/pwndbg/actions/runs/5470271945

**Comment by intrigus-lgtm** [comment]
Easiest way to fix this would be to switch from https://github.com/satackey/action-docker-layer-caching to https://github.com/jpribyl/action-docker-layer-caching in https://github.com/pwndbg/pwndbg/actions/runs/5470271945/workflow#L18
See: https://github.com/satackey/action-docker-layer-caching/issues/347

**Comment by disconnect3d** [comment]
@intrigus-lgtm iiuc this was closed in https://github.com/pwndbg/pwndbg/pull/1794

(Please let me know in case I am wrong :P). Thanks!
