### ISSUE TITLE
context, context-sections: display threads

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#1802]
We should add a new context section that will display threads.

We should probably also make this section being displayed by default if the program has more than 1 thread? I'm not sure...

**Comment by disconnect3d** [comment]
This has been added in https://github.com/pwndbg/pwndbg/pull/1829

**Comment by disconnect3d** [comment]
@gsingh93 do u think we should display threads in the context by default? That's kinda a big change, but how else would we inform users about that this exist? lol

**Comment by gsingh93** [comment]
> @gsingh93 do u think we should display threads in the context by default? That's kinda a big change, but how else would we inform users about that this exist? lol

What if we displayed it by default only when there's multiple threads? That would require some special case handling in `context` though.

**Comment by disconnect3d** [comment]
We can do that. Also a small nitpick is that this may bloat the view if there are LOTS of threads like in:
![image](https://github.com/pwndbg/pwndbg/assets/10009354/b1343d4d-8ef1-484c-8dcc-6e0a17578b59)

**Comment by disconnect3d** [comment]
> > @gsingh93 do u think we should display threads in the context by default? That's kinda a big change, but how else would we inform users about that this exist? lol
> 
> What if we displayed it by default only when there's multiple threads? That would require some special case handling in `context` though.

@bog2n can you implement this?

**Comment by bog2n** [comment]
Yeah, sure

**Comment by wallds** [comment]
![image](https://github.com/pwndbg/pwndbg/assets/12907032/58f38716-2808-476e-8396-7081e8e92959)

qemu kernel debug

**Comment by disconnect3d** [comment]
Thanks for reporting this. Seems like a thread may not have its name… :)

Going to fix this later today.

**Comment by disconnect3d** [comment]
Reopening due to bug reported by @wallds

**Comment by disconnect3d** [comment]
@wallds The #1850 should fix this issue; pls let us know if it is still there or not. Closing for now.
