### ISSUE TITLE
Add moar tips

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#1834]
We should add more tips to:
* https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/lib/tips.py

E.g.:
- [ ] `vmmap -A|-B` flags
- [ ] `killthreads` command
- [ ] `spray <addr>` command
- [ ] `patch` command -- e.g. "Need to NOP some instructions? Use `patch <addr> 'nop; nop; nop'`
- [ ] `heap_config`
- [ ] (maybe) thread context section?
- [ ] `break-if-taken`, `break-if-not-taken` commands
- [ ] `stepuntilasm` command
- [ ] `plist` command

**Comment by bog2n** [comment]
assign me pls ;)

**Comment by disconnect3d** [comment]
Done in #1852
