### ISSUE TITLE
Linux kernel: kallsyms command?

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#1836]
I am not sure if this is doable, but if someone debugs a kernel with KASLR it would be nice to be able to find and parse kallsyms from within Pwndbg and then either set symbols or at least be able to print/fetch them via some Pwndbg API.

Here is a project that shows how one could deal with this: https://github.com/pagabuc/kallsyms-extractor/ although I am not sure if this works with latest kernels.

**Comment by disconnect3d** [comment]
Btw if we do this by looking for some strings in memory, in order to be efficient, we may need to e.g. search only for read-only mappings or read-write or something like that -- depending on where the searched string is to be expected in.

**Comment by disconnect3d** [comment]
This may be useful here as well: https://github.com/marin-m/vmlinux-to-elf

**Comment by chrf01** [comment]
may be useful: https://sourceware.org/pipermail/gdb-patches/2023-January/195589.html

**Comment by disconnect3d** [comment]
Yes, we should use symbol addition API it when it lands in a GDB release
but even when it does, we will still want to support older GDB versions.
(Thx @mbrla0 for working on this API :))

**Comment by chrf01** [comment]
I'll take a look at this

**Comment by disconnect3d** [comment]
Related: https://github.com/pwndbg/pwndbg/pull/2142#issuecomment-2133864906

**Comment by disconnect3d** [comment]
@fidgetingbits Given the recent work being finished, is there anything else we would need to be done here, or can I close this? :D

**Comment by fidgetingbits** [comment]
I think it can be closed now ya. There was the one related discussion around using something like LIEF to generate the symbols inside a stripped template binary to be able to load them directly into gdb which would be nice, but should just be a separate issue I think.
