### ISSUE TITLE
Drop support for GDB < 9.2

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#1854]
We do have this in README:
> Pwndbg is supported on Ubuntu 20.04, and 22.04 with GDB 9.2 and later.

So we should remove all the old workaround code we used for old GDBs < 9.2. This issue is there to track those efforts: feel free to send a PR fixing just one thing, or a PR fixing many or all of those.

Those are:
* [x] `gdb77_get_register` and the relevant "if hasattr" code: https://github.com/pwndbg/pwndbg/blob/1c4307df9d6d7086fa476f551f16300b24179bf9/pwndbg/gdblib/regs.py#L22-L35
* [x] `_fs_gs_helper` - we don't need to use `ptrace` anymore iiuc: https://github.com/pwndbg/pwndbg/blob/1c4307df9d6d7086fa476f551f16300b24179bf9/pwndbg/gdblib/regs.py#L187-L190
* [x] We probably don't need to try/except this anymore: https://github.com/pwndbg/pwndbg/blob/1c4307df9d6d7086fa476f551f16300b24179bf9/pwndbg/gdblib/events.py#L120-L125
* [x] The description for `entry` command mentions GDB 8.1 - we can probably drop the parentheses here: https://github.com/pwndbg/pwndbg/blob/1c4307df9d6d7086fa476f551f16300b24179bf9/pwndbg/commands/start.py#L87-L89
* [x] There was some weird GDB 8.2 case in `check_repeated`, a functionality for "repeating commands execution" - the except can probably be removed, but I recommend investigating the linked issue there: https://github.com/pwndbg/pwndbg/blob/1c4307df9d6d7086fa476f551f16300b24179bf9/pwndbg/commands/__init__.py#L166-L171
* [x] Handling version:
```
commands/version.py
29:        return gdb.VERSION  # GDB >= 8.1 (or earlier?)
188:    # 8. showing width
```
* [x] Some heap cases:
```
heap/structs.py
40:    # alignof doesn't available in GDB < 8.2 (https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blob_plain;f=gdb/NEWS;hb=gdb-8.2-release)

heap/ptmalloc.py
974:            # alignof doesn't available in GDB < 8.2 (https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blob_plain;f=gdb/NEWS;hb=gdb-8.2-release)
977:            # TODO: We can remove this when we drop supports for GDB < 8.2
```

* [x] Handling symbols:
```
gdblib/symbol.py
167:            # GDB < 9.x does not have `gdb.lookup_static_symbol`
170:            # TODO/FIXME: Find a way to get the static linkage symbol's address in GDB < 9.x
```

**Comment by dmur1** [comment]
i'll take a look at this one

**Comment by dmur1** [comment]
> _fs_gs_helper - we don't need to use ptrace anymore iiuc:

in trying to remove this the tests break - specifically tls command test - doing ptrace when `pwndbg.gdblib.arch.current != "x86-64"` seems to fix the issue which suggests that ptrace may be required in some cases even if read register is supported @disconnect3d

**Comment by disconnect3d** [comment]
@dmur1 seems that GDB doesnt allow to read fs/gs on x86 (i386) via read register and that's why we need to use ptrace there.

**Comment by disconnect3d** [comment]
Also: would be nice to investigate this: https://github.com/pwndbg/pwndbg/blob/7a528bb3f7ba38e47f60539777e5d82881ea709a/pwndbg/gdblib/events.py#L71-L75

We may be able to remove that abstraction nowadays? I am not sure! :P

**Comment by disconnect3d** [comment]
I'm moving the remaining thing to issue #1887. I believe that we finally dropped support for <9.2.
