### ISSUE TITLE
Port checksec command to native command and add colors

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#1874]
This is annoying IMHO. I want colors and no pwntools update checks here!
![image](https://github.com/pwndbg/pwndbg/assets/10009354/9d1affbb-413c-43d7-872d-5b33e22cfad9)

**Comment by disconnect3d** [comment]
Fwiw:
![image](https://github.com/pwndbg/pwndbg/assets/10009354/cd32dc8a-460d-44a0-ae81-1e23143f6133)

e.g. partial RELRO should be yellow etc.

**Comment by CristhianMotoche** [comment]
Hello there! I think I could give a hand to this issue. Let me give it a try.

**Comment by disconnect3d** [comment]
The coloring was added in #1923.

I will still keep this open: we should use pwntools dependency to call checksec instead of a wrapper binary

**Comment by dmur1** [comment]
> The coloring was added in #1923.
> 
> I will still keep this open: we should use pwntools dependency to call checksec instead of a wrapper binary

what exactly does this mean?

that we should use ELF directly like pwn checksec does? 

https://github.com/Gallopsled/pwntools/blob/dev/pwnlib/commandline/checksec.py#L38

**Comment by disconnect3d** [comment]
@dmur1 tl;dr yeah, sorry I forgot to answer here. @diivi already started to work on this.
