### ISSUE TITLE
gdbserver 8.0.1, gdb 13.2: Unable to access 16000 bytes of target memory

### ISSUE THREAD

**Issue by fidgetingbits** [pwndbg/pwndbg#1892]
This is effectively the same as #1618, but I can confirm that it seems to be related to the gdb server version. I'm using client version 13.2, and when talking to a gdbserver 8.0.1 I ran into this issue.  

The error I get when doing a search:

```
gdbserver: Unable to access 16000 bytes of target memory at 0x97d98e87, halting search.
```

Interestingly `i.search_memory()` ends up actually returning a value other than `None`, and also doesn't throw an exception. The value it consistently returns for me is `0x7f74ad2bfd18`, but the target is 32-bit, so isn't a valid target address at least.

I confirmed that manually applying the suggested workaround `set remote search-memory-packet off` that was used for #808 fixes the problem. 

In this case the automatic check from #808 doesn't apply because it's only testing the client version afaict, so this bug report is mostly to suggest seeing if there is a way to also test the server version and if it's old also set that setting.

FWIW I did confirm that running a newer gdbserver 13.2 on the target makes the problem go away.

I'm able to easily reproduce the problem if there needs to be any testing done.

**Comment by disconnect3d** [comment]
Shall we create a reproducer and handle this somehow? Or shall we mark it as "wontfix" and just ask people to use latest gdbserver+gdb?

**Comment by disconnect3d** [comment]
Is there a way to ask gdbserver about its version? Anything like `maintenance packet version`? huh

**Comment by fidgetingbits** [comment]
I finally skimmed through the list of [gdb protocol](https://sourceware.org/gdb/onlinedocs/gdb/Remote-Protocol.html) docs didn't see any way of actually getting the version back, so I think there won't be a `maintenance`-based command or anything. 

There is `qSupported [:gdbfeature [;gdbfeature]… ]` packet for querying the stub for various features it supports, but I also don't see a feature listed that would correlate to the search memory packet, closest might be `qXfer:memory-map:read`, but doesn't seem the same.

In light of that "wontfix" and just telling people to use newer version makes sense.
