### ISSUE TITLE
Save history of previous context output

### ISSUE THREAD

**Issue by peace-maker** [pwndbg/pwndbg#1899]
You would save some scrolling if you could reprint the context of a previous stop. Caching the displayed data everytime context is used would allow to review old state (without actually rewinding the inferior of course).

My major motivation for this is the [splitmind layout](https://github.com/pwndbg/pwndbg/blob/dev/FEATURES.md#splitting--layouting-context) which organizes the output neatly, but loses the ability to review the output of a previous step. Looking for solutions there's [hyperpwn](https://github.com/bet4it/hyperpwn) which implements this based on a special terminal emulator. But having shortcuts like `ctrl+shift+pageup/down` to walk the history would be cool to have integrated in pwndbg without requiring a special terminal program.

@disconnect3d

**Comment by disconnect3d** [comment]
> But having shortcuts like ctrl+shift+pageup/down to walk the history would be cool to have integrated in pwndbg without requiring a special terminal program.

For that, we would need to add some additional API into GDB to support that, or, maybe use something like ncurses from Pwndbg? I am not sure.

**Comment by peace-maker** [comment]
There's an issue tracking adding key bindings from python https://sourceware.org/bugzilla/show_bug.cgi?id=31127
