### ISSUE TITLE
Enhance thread context

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#1904]
The thread context can be improved so that:
1. It shows the number of all threads in the top bar e..g `[ THREADS (20) ]`
2. It limits the number of displayed threads via some config variable
* When there are more threads then the limit, it should display current thread and other threads up to the limit and the following text: "... (use `ctx thread` or `set context-threads-limit <N>`)"

**Comment by disconnect3d** [comment]
Impl details:
* https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/commands/context.py#L853-L897
* https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/commands/context.py#L620C5-L627

**Comment by CptGibbon** [comment]
Any objections to using the tabulate library to display this information?

**Comment by disconnect3d** [comment]
Nope, it probably makes sense to use it
