### ISSUE TITLE
The `ctx threads` (or `threads`) should display all threads no matter of context threads limit

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#1917]
cc: @CptGibbon we should probably add this option for convenience :)

**Comment by CptGibbon** [comment]
Sure I'll look into it 👍

**Comment by CptGibbon** [comment]
@disconnect3d do you want `context threads` to behave differently to the other context subcommands?

**Comment by disconnect3d** [comment]
I'm not sure. Maybe we should have a `threads` command similarly to `stack` (alias for `telescope`) or `regs`?

Basically we need a way to display threads nicely, huh
