### ISSUE TITLE
threads context doesnt display current thread?

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#1918]
When I attached to an app with 39 threads, the threads context panel doesn't show me the thread I am currently stopped on.

Seems like some sorting issue. cc: @CptGibbon

**Comment by CptGibbon** [comment]
As far as I'm aware it never did this, the command simply prints the threads in reverse order. Though I appreciate this was a feature request in #1904 so I can certainly add it 👍
