### ISSUE TITLE
Cannot detect i386 arch when remote debugging

### ISSUE THREAD

**Issue by SuperKenVery** [pwndbg/pwndbg#1924]
### Description

```python3
Exception occurred: Error: Unknown arch. Message: The target architecture is set to "auto" (currently "i386").
 (<class 'Exception'>)
```

When I run `show architecture`, gdb can print:
```
The target architecture is set to "auto" (currently "i386")
```

Note the quotes around `i386`. 

In `pwndbg/gdb-pt-dump/pt.py`, there is:

```python3
        if "aarch64" in arch:
            self.backend = PT_Aarch64_Backend(self.phys_mem)
        elif "x86-64" in arch or "x64-64" in arch:
            self.backend = PT_x86_64_Backend(self.phys_mem)
        elif "x86-32" in arch or "x64-32" in arch or "(currently i386)" in arch:
            self.backend = PT_x86_32_Backend(self.phys_mem)
        elif "riscv:rv64" in arch:
            self.backend = PT_RiscV64_Backend(self.phys_mem)
        else:
            raise Exception(f"Unknown arch. Message: {arch}")
```

Which would raise an exception when the architecture is detected as i386. 

### Steps to reproduce

```sh
qemu-system-i386 -machine type=pc-i440fx-3.1 -kernel xxx.elf -s -S
pwndbg a_binary
pwndbg> target remote :1234
```

### My setup

```sh
pwndbg> version
Gdb:      13.2
Python:   3.10.12 (main, Jun  6 2023, 22:43:10) [GCC 12.3.0]
Pwndbg:   1.1.1
Capstone: 4.0.1024
Unicorn:  2.0.1
```

I'm using nix to setup the shell environment (not flake)

**Comment by disconnect3d** [comment]
Hi, so this is about debugging a 32-bit kernel? EDIT: Yeah, it is

**Comment by disconnect3d** [comment]
This seems an inherent limitation of gdb-pt-dump as described in its readme: https://github.com/martinradev/gdb-pt-dump

Can you see if `set kernel-vmmap monitor` helps in your case?

**Comment by disconnect3d** [comment]
Oh wait, I am blind.

It seems we need to change this part to also take into account the `"i386"` string lol:
```py
        elif "x86-32" in arch or "x64-32" in arch or "(currently i386)" in arch:
            self.backend = PT_x86_32_Backend(self.phys_mem)
```

**Comment by disconnect3d** [comment]
@SuperKenVery can you try to fix it and [send a PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)?

**Comment by SuperKenVery** [comment]
Yeah I probably can, after I get back to my computer 😂

By the way, is the i386 without quotes actually correct? I.E. does certain versions of gdb return i386 without quotes?

Should I preserve the original one and add one more "or", or should I change the original one to add the quotes?

**Comment by disconnect3d** [comment]
> By the way, is the i386 without quotes actually correct? I.E. does certain versions of gdb return i386 without quotes?

Yup, otherwise we (hopefully) wouldn't write such code. 

Seems that the change ocurred in GDB 10.1: https://github.com/bminor/binutils-gdb/commit/ccb9eba6a254f8d5e593972a73504c94a009c729

**Comment by disconnect3d** [comment]
@patryk4815 btw did the latest change to gdb-pt-dump updated it to use the latest? If so, we should have https://github.com/martinradev/gdb-pt-dump/pull/23 in and this should be fixed.

@SuperKenVery pls try to reinstall latest pwndbg dev branch and see if this works now. Closing this for now since it should work
