### ISSUE TITLE
Enabling reverse stack growth

### ISSUE THREAD

**Issue by davidemaiorca** [pwndbg/pwndbg#1939]
**Is your feature request related to a problem? Please describe.**
In GEF it is possible to visualize the stack growth in reverse (i.e., upper addresses go to higher positions). This is possible by setting up the context.grow_stack_down parameter.

**Describe the solution you'd like**
It would be very nice to have the equivalent functionality in Pwndbg (or if there is already, make it more accessible).

**Comment by disconnect3d** [comment]
Hey, this should be pretty easy to implement. I'm happy to merge such feature if someone would send it as a PR.

**Comment by disconnect3d** [comment]
Hey, this was added in #1978. One can now pass `-i` or `--inverse` to the `stack` and `telescope` commands.

**Comment by disconnect3d** [comment]
Let us know if this is sufficient or if you think we should make it a configurable parameter instead.

**Comment by disconnect3d** [comment]
cc: @suhassuhas it may make more sense to move it to a parameter 🤔
