### ISSUE TITLE
Pwndbg Hangs with gdbserver on High Thread Count Programs

### ISSUE THREAD

**Issue by shsirk** [pwndbg/pwndbg#1947]
### Description

Pwndbg gets stuck when used with gdbserver when debugging a program with 40+ threads, an example of which is Chromium running on Android.

### Steps to reproduce

debug chromium apk on android

### My setup
pwndbg commit hash:
13f467b0246367548a7fd9fd952391978ec1d47c

Gdb:      13.2
Python:   3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Pwndbg:   2023.07.17 build: 13f467b
Capstone: 5.0.1280
Unicorn:  2.0.1

We have verified that this is not the issue with GDB.

The issue seems to be located in the `update()` function in the `pwndbg/gdblib/stack.py` file. This function takes a significantly long time to process when there is a high number of threads as it tries to find the stack boundary for each one.

When enabling the debug feature, we can see that Pwndbg gets hung up on the "stop" event for thread processing as shown here:

```
...
'obj' pwndbg.gdblib.hooks.reset_config (<gdb.NewObjFileEvent object at 0x7fde7a41bb10>,)
'obj' pwndbg.lib.cache.clear (<gdb.NewObjFileEvent object at 0x7fde7a41bb10>,)
0x0000007984eeab68 in __epoll_pwait () from /home/dev/android-solibs/system/lib64/libc.so
'stop' pwndbg.gdblib.events._start_stop (<gdb.StopEvent object at 0x7fde7a3fa2f0>,)
'stop' pwndbg.gdblib.regs.update_last (<gdb.StopEvent object at 0x7fde7a3fa2f0>,)
'stop' pwndbg.gdblib.stack.update (<gdb.StopEvent object at 0x7fde7a3fa2f0>,)
```

It appears that the current method of enumerating all thread information for context is inefficient for the case of debugging applications with a high number of threads. This should be more on-demand or limited to only showing information about the current thread.

Relevant Code:

```python
@pwndbg.gdblib.events.stop
@pwndbg.lib.cache.cache_until("stop")
def update() -> None:
    """
    For each running thread, updates the known address range
    for its stack.
    """
    curr_thread = gdb.selected_thread()
    try:
    ...
```

Proposed Solution:

A potential solution to reduce processing time could be to only display thread information on-demand or solely display information about the current thread.

**Comment by hacksysteam** [comment]
The same function exists in the commit 5943c5e16e51bb351b712c5e1d16ad2509991c4b and this is much faster than the latest dev branch. So the issue seems to be in cache?

**Comment by hacksysteam** [comment]
I have the update, the bisect shows that the bug was introduced with this commit: e77c6f5c2e0d23b5073eb035076e280ec5ef84c3

Commenting `pwndbg.gdblib.regs.__getattr__.cache.clear()` makes it faster as it was

**Comment by disconnect3d** [comment]
Hey, thanks for debugging this. I guess we need to double check why do we need all thread stack information being resolved on each stop and then we can decide what to do with it further.


I believe the fix made in e77c6f5 is needed, though, we could alternatively fix it by invoking the clear before calling `canary` - otoh - then the canary command would be slow... heh :)

**Comment by hacksysteam** [comment]
So it turns out that the actual issue is not with register cache clearing but the cache using `UserDict`, a faster data type should be good to solve this issue

**Comment by disconnect3d** [comment]
> So it turns out that the actual issue is not with register cache clearing but the cache using `UserDict`, a faster data type should be good to solve this issue

Hmm are you sure? The UserDict should only be used if cache debugging is enabled in the code itself: https://github.com/pwndbg/pwndbg/blob/13f467b0246367548a7fd9fd952391978ec1d47c/pwndbg/lib/cache.py#L124

**Comment by hacksysteam** [comment]
Ah! Right! I profiled a bit and the issue is calling the `find_upper_stack_boundary` function because the cache was cleared.

**Comment by disconnect3d** [comment]
Hm why do we even call it, I mean, we should know the vmmaps already and we
should be able to get stack bounds from those mappings..

**Comment by hacksysteam** [comment]
By patching these two functions and using binary search instead of linear search, improves the speed drastically.

file: `memory.py`

```py
@pwndbg.lib.cache.cache_until("stop")
def find_upper_boundary(addr: int, max_pages: int = 1024) -> int:
    """find_upper_boundary(addr, max_pages=1024) -> int

    Use binary search to find the upper boundary of a memory mapping,
    by reading the first byte of each page, until an unmapped
    page is found.
    """
    addr = pwndbg.lib.memory.page_align(int(addr))
    low = 0
    high = max_pages

    while low < high:
        mid = (low + high) // 2
        test_addr = addr + mid * PAGE_SIZE

        if test_addr > pwndbg.gdblib.arch.ptrmask:
            high = mid
            continue

        try:
            pwndbg.gdblib.memory.read(test_addr, 1)
            low = mid + 1
        except gdb.MemoryError:
            high = mid

    return addr + low * PAGE_SIZE


@pwndbg.lib.cache.cache_until("stop")
def find_lower_boundary(addr, max_pages=1024):
    """find_lower_boundary(addr, max_pages=1024) -> int

    Use binary search to find the lower boundary of a memory mapping,
    by reading the first byte of each page, until an unmapped
    page is found.
    """
    addr = pwndbg.lib.memory.page_align(int(addr))
    low = -max_pages
    high = 0

    while low < high:
        mid = (low + high) // 2
        test_addr = addr + mid * PAGE_SIZE

        if test_addr < 0:
            low = mid + 1
            continue

        try:
            pwndbg.gdblib.memory.read(test_addr, 1)
            high = mid
        except gdb.MemoryError:
            low = mid + 1

    # If the high is still 0, it means the original address is the lower boundary
    if high == 0:
        return addr

    return addr + high * PAGE_SIZE
```

If you think this is acceptable change, I can send a pull request

**Comment by hacksysteam** [comment]
Some trace

```
find_upper_boundary took 1439.25 milliseconds
find_upper_boundary2 took 26.46 milliseconds
find_upper_boundary took 1317.58 milliseconds
find_upper_boundary2 took 10.91 milliseconds
find_upper_boundary took 1279.20 milliseconds
find_upper_boundary2 took 8.99 milliseconds
find_upper_boundary took 1498.95 milliseconds
find_upper_boundary2 took 11.88 milliseconds
find_upper_boundary took 1367.71 milliseconds
find_upper_boundary2 took 14.06 milliseconds
find_upper_boundary took 1357.41 milliseconds
find_upper_boundary2 took 14.01 milliseconds
...
```

**Comment by shsirk** [comment]
@hacksysteam I tested above patch but it is still slow for 40+ threads.

**Comment by disconnect3d** [comment]
My main quesiton still stands: we need to find out why we do this at all since we should have stack memory page information from vmmap already

**Comment by disconnect3d** [comment]
@shsirk can you try with this patch?

```patch
diff --git a/pwndbg/gdblib/stack.py b/pwndbg/gdblib/stack.py
index 000e8b8..cdaccf9 100644
--- a/pwndbg/gdblib/stack.py
+++ b/pwndbg/gdblib/stack.py
@@ -17,8 +17,8 @@ import pwndbg.gdblib.memory
 import pwndbg.lib.cache

 # Dictionary of stack ranges.
-# Key is the gdb thread ptid
-# Value is a pwndbg.lib.memory.Page object
+# Key is the gdb thread num
+# Value is a pwndbg.lib.memory.Page object - DO NOT MODIFY IT!
 stacks: dict[tuple[int, int, int], pwndbg.lib.memory.Page] = {}

 # Whether the stack is protected by NX.
@@ -54,51 +54,37 @@ def find_upper_stack_boundary(stack_ptr: int, max_pages: int = 1024) -> int:
 @pwndbg.lib.cache.cache_until("stop")
 def update() -> None:
     """
-    For each running thread, updates the known address range
-    for its stack.
+    For each running thread, updates the known address range for its stack.
     """
     curr_thread = gdb.selected_thread()
-    try:
-        for thread in gdb.selected_inferior().threads():
-            thread.switch()
-            pwndbg.gdblib.regs.__getattr__.cache.clear()
-            sp = pwndbg.gdblib.regs.sp
-
-            # Skip if sp is None or 0
-            # (it might be 0 if we debug a qemu kernel)
-            if not sp:
-                continue
-
-            sp_low = sp & ~(0xFFF)
-            sp_low -= 0x1000
-
-            # If we don't already know about this thread, create
-            # a new Page mapping for it.
-            page = stacks.get(thread.ptid, None)
-            if page is None:
-                start = sp_low
-                stop = find_upper_stack_boundary(sp)
-                page = pwndbg.lib.memory.Page(
-                    start, stop - start, 6 if not is_executable() else 7, 0, "[stack]"
-                )
-                stacks[thread.ptid] = page
-                continue
-            elif page.objfile is None:
-                pid, tid, _ = thread.ptid
-                if pid == tid:
-                    page.objfile = "[stack]"
-                else:
-                    page.objfile = "[stack:%i]" % tid
-
-            # If we *DO* already know about this thread, just
-            # update the lower boundary if it got any lower.
-            low = min(page.vaddr, sp_low)
-            if low != page.vaddr:
-                page.memsz += page.vaddr - low
-                page.vaddr = low
-    finally:
-        if curr_thread:
-            curr_thread.switch()
+    pages = pwndbg.gdblib.vmmap.get()
+
+    for thread in gdb.selected_inferior().threads():
+        thread.switch()
+
+        # Need to clear regs values cache after switching thread
+        # So we get proper value of the SP register
+        pwndbg.gdblib.regs.__getattr__.cache.clear()
+
+        sp = pwndbg.gdblib.regs.sp
+
+        # Skip if sp is 0 (it might be 0 if we debug a qemu kernel)
+        if not sp:
+            continue
+
+        page = None
+
+        # Find the given SP in pages
+        for p in pages:
+            if sp in p:
+                page = p
+                break
+
+        if page:
+            stacks[thread.num] = page
+            continue
+
+    curr_thread.switch()


 @pwndbg.lib.cache.cache_until("stop")
```

**Comment by disconnect3d** [comment]
Hey, I've included https://github.com/pwndbg/pwndbg/pull/1959 in the dev branch which should resolve this issue. Please let us know if it doesn't.

**Comment by shsirk** [comment]
Hi, I have tried latest commit and tested again. it works great now for high thread count  program. Thanks for the work! :). much appreciated.

**Comment by hacksysteam** [comment]
Hi @disconnect3d would you like to integrate the `find_upper_boundary` and `find_lower_boundary` functions? from the output we can see that it performs much better than the current implementation. I can send a pull request if you are interested.

**Comment by disconnect3d** [comment]
> Hi @disconnect3d would you like to integrate the `find_upper_boundary` and `find_lower_boundary` functions? from the output we can see that it performs much better than the current implementation. I can send a pull request if you are interested.

I am not sure. Can't we end up with incorrect memory mapping, if we accidentally jump over some pages?

In the end, I would like to remove any of the exploration we may do "by default" to be "opt in" and configurable with things like "how much bytes to jump over" etc. to give the best possible UX/UI to the users and actually support different use cases instead of causing hangs like we did here :(.
