### ISSUE TITLE
IDA Pro Integration - decompile() segfault

### ISSUE THREAD

**Issue by cloudburst** [pwndbg/pwndbg#196]
Calling `idaapi.decompile()` causes my IDA `6.9.151221 (December 21, 2015)` to segfault (often corrupting the database) when Hex-Rays is not installed.

There needs to be some sanity checking in the [context](https://github.com/pwndbg/pwndbg/blob/master/pwndbg/commands/context.py#L209) command before calling `pwndbg.ida.decompile()`

I'm not sure if this is fixed in the latest IDA `6.95.160808 (August 08, 2016)`

**Comment by cloudburst** [comment]
Just for documentation, I confirmed that this bug is still present in the latest IDA `6.95.160808 (August 08, 2016)`

**Comment by zachriggle** [comment]
Can you find any docs about how to determine whether the decompiler is
available?

Also, could you report this to support@hexrays?

**Comment by disconnect3d** [comment]
@zachriggle @cloudburst 
There is [`bool	
init_hexrays_plugin(flags=0)`](https://www.hex-rays.com/products/ida/support/idapython_docs/ida_hexrays-module.html#init_hexrays_plugin) which seems to be the thing we are looking for.

[Here](https://www.hex-rays.com/products/decompiler/sdk.shtml) is something that might be confirmation that it actually returns whether the decompiler is there:
```c
// Initialize the plugin.
int idaapi init(void)
{
  if ( !init_hexrays_plugin() )
    return PLUGIN_SKIP; // no decompiler
```

Also found the documentation for this function in C or C++: https://www.hex-rays.com/products/decompiler/manual/sdk/group__type.shtml#ga1d89ee3fd8c60f34a85ae78f5c8ff400

**Comment by cloudburst** [comment]
I've reported the `idaapi.decompile()` issue to hexrays.

If i call `ida_hexrays.get_hexrays_version()` it also segfaults IDA.  However `ida_hexrays.init_hexrays_plugin()` returns `False` so that seems to work for an API to use potentially.

**Comment by cloudburst** [comment]
Hex-Rays said this will be patched in the next release.
