### ISSUE TITLE
IDA Pro Integration - Support Comments

### ISSUE THREAD

**Issue by cloudburst** [pwndbg/pwndbg#198]
Currently the IDA Pro RPC only syncs [Anterior](https://github.com/pwndbg/pwndbg/blob/master/pwndbg/commands/nearpc.py#L112) comments for marking up the dissassembly in gdb.

It would be nice to support pulling comments as well via something like:

```diff
         line   = ' '.join((prefix, address_str, s, asm))

+        # Add any comment from ida to the end of the assembly
+        comment = pwndbg.ida.Comment(i.address)
+        if comment:
+            line += " ; {}".format(comment)
 ```

However, this probably needs testing on the idc.GetCommentEx() api to see whether it handles pulling decompiler output from Hex-Rays or not.  I don't have a setup to try this.

The current ida.Comment() does:

```python
  @withIDA
  @takes_address
  def Comment(addr):
     return _ida.GetCommentEx(addr, 0) or _ida.GetCommentEx(addr)
```

**Comment by zachriggle** [comment]
`GetCommentEx` gets a regular comment.

From the docs:

```
GetCommentEx(ea, repeatable) 
Get regular indented comment
Parameters:
ea - linear address
repeatable - 1 to get the repeatable comment, 0 to get the normal comment
Returns:string or None if it fails
```
