### ISSUE TITLE
Heap structures display irrelevant fields

### ISSUE THREAD

**Issue by 0xTac** [pwndbg/pwndbg#199]
As you can see in the Code below ,0x60300 and 0x603020 is Fastbins,it should not have the fd,bk,fd_nextsize,bk_nextsize,If I am not mistaken....I know in this place user data is begin from fd pointer,But I think it can be imporved to distinguish different chunk,make it more Humanize
```
pwndbg> heap
Top Chunk: 0x603050
Last Remainder: 0

0x603000 FASTBIN {
  prev_size = 0, 
  size = 33, 
  fd = 0x603030, 
  bk = 0x0, 
  fd_nextsize = 0x0, 
  bk_nextsize = 0x31
}
0x603020 FASTBIN {
  prev_size = 0, 
  size = 49, 
  fd = 0x676e6978676e6978, 
  bk = 0x0, 
  fd_nextsize = 0x0, 
  bk_nextsize = 0x0
}
0x603050 PREV_INUSE {
  prev_size = 0, 
  size = 135089, 
  fd = 0x0, 
  bk = 0x0, 
  fd_nextsize = 0x0, 
  bk_nextsize = 0x0
}
pwndbg> x/gx 0x603020
0x603020:	0x0000000000000000
pwndbg> x/10gx 0x603020
0x603020:	0x0000000000000000	0x0000000000000031
0x603030:	0x676e6978676e6978	0x0000000000000000
0x603040:	0x0000000000000000	0x0000000000000000
0x603050:	0x0000000000000000	0x0000000000020fb1
0x603060:	0x0000000000000000	0x0000000000000000
pwndbg> 

```

**Comment by zachriggle** [comment]
Those fields are present in the structure regardless of the state of the actual heap chunk.

I believe that the only way to change this display is to write a "Pretty-Printer" for the given type.

More information is available here: https://sourceware.org/gdb/onlinedocs/gdb/Writing-a-Pretty_002dPrinter.html#Writing-a-Pretty_002dPrinter

**Comment by zachriggle** [comment]
It looks like @cloudburst already has some code for displaying lots of the structures:

https://github.com/cloudburst/libheap/blob/c4a4f4ca340c1459fbe9face69e7cb496e99b378/libheap/frontend/frontend_gdb_pretty_printers.py#L187

**Comment by gsingh93** [comment]
Not applicable to the latest version of the command, closing.
