### ISSUE TITLE
Feature request: RVA-based breakpoints

### ISSUE THREAD

**Issue by chivay** [pwndbg/pwndbg#2004]
**Is your feature request related to a problem? Please describe.**
I am missing a command that would allow creating a breakpoint relative to some image - either main program or a library - for example at offset 0x1337 from libc base.

**Describe the solution you'd like**
A new command that would enable this, for example

````
bp libc.so+0x1337
````

**Describe alternatives you've considered**
The alternative is to manually find the image bases which is tedious.

**Comment by disconnect3d** [comment]
Hey,

1) We have such feature but only for the base binary address. You can do `break *$rebase(0x1234)`
2) It should be super easy to add this, check out https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/gdblib/functions.py#L51-L55

You would have to implement it as:
```py
@GdbFunction(only_when_running=True)
def base(objfile: str) -> int:
    base = next(p for p in pwndbg.gdblib.vmmap.get() if objfile in p.objfile)
    return base
```

Probably also wrapping it in `try: ... except: ...` in case when vmmap is not available or there is no such mapping? And displaying the issue to the user? Or maybe an exception is desirable. To be checked.

**Comment by disconnect3d** [comment]
Also, the adventage of doing it as a GDB function is that it would work with any other command within GDB/Pwndbg.

**Comment by disconnect3d** [comment]
@nikoshell Btw I think u made some wrapper over Pwndbg where u handle stdin in a script.

I wonder if we could provide an extra UX this way by detecting `<something>.so` in the input line typed by the user and replacing it with `$base(<something>.so)`? But do things like tab completion works then?

**Comment by disconnect3d** [comment]
@chivay any chance you can send a PR with the `base` function above and also test it by yourself? (ideally, add a testcase to Pwndbg tests, but skip it if u don't have time/don't want to deal with it)
