### ISSUE TITLE
pattern_create & run features

### ISSUE THREAD

**Issue by nthdeg** [pwndbg/pwndbg#2007]
It is annoying to have to have multiple versions of gdb to complete some of my work. I don't understand why this feature hasn't been brought over yet like gdb-peda has implemented. Reversing takes long enough, this would make our lives a little bit easier.

I would like to add the pattern_create feature into pwndbg. As well as run, so that I can quickly create our cyclic values and then run our output (run < payload-100.txt) so we can check the registers in under 10 seconds without restarting the program.

**Comment by disconnect3d** [comment]
@nthdeg can u remind us what `pattern_create` do in peda?

I believe we have that as a `cyclic` command?

**Comment by nthdeg** [comment]
Ah thank you, I didn't see that function. `pattern_create 50 payload-50.txt` does the same thing but it saves the string in a txt file within the working dir. then you can run the binary `run < payload-50.txt` feeding it the cyclic pattern.

We then can use `pattern_offset 0xaddress` to return the exact offset in bytes. all while not leaving the program. I am not sure if the same workflow exists with other functions?

**Comment by disconnect3d** [comment]
@nthdeg Added the `[filename]` argument to `cyclic` command in #2009.

So you can now do:
```
cyclic 100 input
run < input
cyclic -l 0xdeadbeef
```
(replace `0xdeadbeef` with some cyclic pattern value)

We still need some kind of `cyclic -d|--detect` to auto detect the cyclic pattern values in registers and/or stack though.

**Comment by nthdeg** [comment]
I just answered my own question reading up some more, as it turns out cyclic_find() is what i was looking for. I will close this request, I appreciate

**Comment by nthdeg** [comment]
Wow you are awesome. Hopefully its okay with you I open a new issue for this additional feature <3
