### ISSUE TITLE
Append ":line number" to the source file path

### ISSUE THREAD

**Issue by knowanegg** [pwndbg/pwndbg#2021]
I hope to append ":line number" to the source file path, so that by holding Ctrl and clicking in IDEs like VSCode, it can jump directly to the specific code line.

![image](https://github.com/pwndbg/pwndbg/assets/108446106/ba5bb4f5-42b0-40c9-8da1-e3f059bad988)

**Comment by disconnect3d** [comment]
Hey, this is trivial to add. You would have to
1) Determine how to get the line number
2) Modify the `["In file: %s" % filename]` banner line in:
https://github.com/pwndbg/pwndbg/blob/66df243bd6457c55ec3f540d0dad457f04c25a02/pwndbg/commands/context.py#L745-L753

**Comment by disconnect3d** [comment]
Also, shall it show `:305` in your example or `:300`? Since the displayed disassembly starts at `:300`

**Comment by disconnect3d** [comment]
Ping @knowanegg any chance you can contribute to Pwndbg with this improvement? :)

**Comment by knowanegg** [comment]
Hi, :305 is correct, you can see by making the font bold; I forked pwdbg, and then modified the code as follows:
![image](https://github.com/pwndbg/pwndbg/assets/108446106/402f87a6-43fa-4026-af9d-3172f6b62ef9)

**Comment by disconnect3d** [comment]
@knowanegg Please send a PR with that change then :)

**Comment by knowanegg** [comment]
I am pleased to be able to contribute to pwndbg, I haven't made a PR (Pull Request) before, let me give it a try  :)

**Comment by disconnect3d** [comment]
You may find the following articles helpful:
-
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork
-
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
-
https://docs.github.com/en/get-started/learning-about-github/github-glossary#pull-request

**Comment by disconnect3d** [comment]
This has been implemented in #2072
