### ISSUE TITLE
Show lint errors as inline annotations in Github PRs

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#2053]
There are Github Actions that can run linters and report any violations inline on the PR itself (similar to the codecov comments we see now). This would be especially useful when we have new contributors who don't know to run the lint script, or struggle with fixing an issue. They would see the issue on the PR itself, and we could comment any suggestions there to help them.

I don't know exactly how to set this up, it would require some investigation.

**Comment by gsingh93** [comment]
Ruff can automatically do this if we run with `--output-format github`. For `mypy`, we have to use another action: https://github.com/tsuyoshicho/action-mypy

**Comment by gsingh93** [comment]
Ruff support was implemented in #2070. Would appreciate it if someone could look into setting this up for `mypy`.

**Comment by diivi** [comment]
`mypy` support added in #2075

**Comment by disconnect3d** [comment]
@gsingh93 do we need to do anything else here?

**Comment by gsingh93** [comment]
Nope, this is complete.
