### ISSUE TITLE
search --asm: set breakpoint on found instructions

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#2084]
We now have `search --asm "<instructions>"` command and it would be nice if it can set breakpoint on found addresses.

Shall this be another option/flag like `-b|--break` or `-b|--set-breakpoint`? Or maybe a `--asmbp` option?

Or a separate command? Probably not. To be discussed.

Fwiw while this makes sense for instructions, such feature may also make sense for normal findings, where we could set watchpoints on the found addresses. Though, if there are lots and lots of results it probably doesn't make that much sense...

So I'd be up for doing this now just for asm and thinking if we really need it for normal findings later on.

**Comment by diivi** [comment]
I'll take a look at this!

**Comment by TheLazron** [comment]
I'd like to try this

**Comment by TheLazron** [comment]
Can I get a review on this pr please, thanks

**Comment by disconnect3d** [comment]
This has been implemented in #2103 as `--asmbp` flag. Thanks!
