### ISSUE TITLE
Next flag for malloc_chunk

### ISSUE THREAD

**Issue by jetchirag** [pwndbg/pwndbg#2086]
Opening this FR related to #1059. I don't think this was later implemented so I want to pick this up to get more familiar with codebase.

> Why stop at the next chunk? The chunk after that can be just as important, as can the previous chunk. Maybe a flag that lets you print a user-defined number of next/previous/surrounding chunks would be useful.

I was however wondering on the way to go about flags. Should we keep 3 seperate flags similar to grep (A, B for next, prev and C for surrounding) or just the next X chunks e.g. `--next 3`?

**Comment by CptGibbon** [comment]
I'd vote to keep it simple and use your latter suggestion of `--next 3`
