### ISSUE TITLE
Implement strings command

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#2105]
It would be nice to have `strings [<page[s]...>]` command that would act similarly as `strings <binary>` in CLI, but would search strings in the debugged process memory.

**Comment by B1N4RY-P4R45173** [comment]
Hello @disconnect3d 

I am thinking of getting the page size with get_memory_page_size() and then for each page 
```
address = int(page, 16)
data = pwndbg.memory.read(address, page_size)
print(f"\nStrings found in memory at {hex(address)} (min_length={min_length}):")
extract_strings(data, min_length)
```

**Comment by disconnect3d** [comment]
You can get virtual memory maps via `pwndbg.aglib.vmmap.get()`, then iterate over the returned tuple of pages and do `pwndbg.aglib.memory.read(page.start, page.size)` and process the returned data to return strings.

Now the command interface could be as follows:
```
strings      # dump all strings with at least N bytes long (N = default = 4?)
strings [pagename filter] [--save-as=<file>]
```

The `[pagename filter]` can be similar as in `search` command.

**Comment by disconnect3d** [comment]
Done in #2505! Thanks to @kapiw04  :)
