### ISSUE TITLE
remove reliance on debug symbols for kconfig

### ISSUE THREAD

**Issue by chrf01** [pwndbg/pwndbg#2106]
To locate the kernel configuration without debug symbols, we should search for `IKCFG_ST` and `IKCFG_ED` markers in the kernel memory. Focus the search on the kernel mappings where the kernel config is likely to be found; probably the first read-only mapping after the kernel base

https://elixir.bootlin.com/linux/latest/source/kernel/configs.c#L25

**Comment by chrf01** [comment]
I've already implemented this; I'll drop a PR as soon as #2097  is merged

**Comment by disconnect3d** [comment]
Done in #2208
