### ISSUE TITLE
retaddr command is broken

### ISSUE THREAD

**Issue by chrf01** [pwndbg/pwndbg#2107]
### Description

the `retaddr` command is broken it prints the entire stack when debugging a kernel

### Steps to reproduce

1. debug kernel: qemu-tests 6.6.18
2. run `retaddr` command

### My setup
```
pwndbg> version
Gdb:      12.1
Python:   3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Pwndbg:   2024.02.14 build: e7548c7
Capstone: 5.0.1280
Unicorn:  2.0.1
pwndbg> retaddr
0xffffffff83203e98 —▸ 0xffffffff8204b66a ◂— call 0xffffffff8204ab60
0xffffffff83203ea0 —▸ 0xffffffff810f0dc2 ◂— jmp 0xffffffff810f0ea3
0xffffffff83203ea8 ◂— 0x202
0xffffffff83203eb0 ◂— 0xa35fb6fbd66e7200
0xffffffff83203eb8 ◂— 0xed
0xffffffff83203ec0 ◂— 0x0
0xffffffff83203ec8 ◂— 0x0
0xffffffff83203ed0 ◂— 0x0
0xffffffff83203ee0 ◂— 0x0
0xffffffff83203f00 ◂— 0x0
0xffffffff83203f30 ◂— 0x0
```

**Comment by disconnect3d** [comment]
@chrf01 Shall we just make the command not work on qemu kernel or shall we implement it somehow for it?

**Comment by disconnect3d** [comment]
The current impl is as follows:

```py
@pwndbg.commands.ArgparsedCommand(
    "Print out the stack addresses that contain return addresses.", category=CommandCategory.STACK
)
@pwndbg.commands.OnlyWhenRunning
def retaddr() -> None:
    sp = pwndbg.gdblib.regs.sp
    stack = pwndbg.gdblib.vmmap.find(sp)

    # Enumerate all return addresses
    frame = gdb.newest_frame()
    addresses = []
    while frame:
        addresses.append(int(frame.pc()))
        frame = frame.older()

    # Find all of them on the stack
    start = stack.vaddr
    stop = start + stack.memsz
    while addresses and start < sp < stop:
        value = pwndbg.gdblib.memory.u(sp)

        if value in addresses:
            index = addresses.index(value)
            del addresses[:index]
            print(pwndbg.chain.format(sp))

        sp += pwndbg.gdblib.arch.ptrsize
```

**Comment by gsingh93** [comment]
The last frame reported by GDB is at address 0x0:
```
pwndbg> ipi

In [1]:     sp = pwndbg.gdblib.regs.sp
   ...:     stack = pwndbg.gdblib.vmmap.find(sp)
   ...:
   ...:     # Enumerate all return addresses
   ...:     frame = gdb.newest_frame()
   ...:     addresses = []
   ...:     while frame:
   ...:         addresses.append(int(frame.pc()))
   ...:         frame = frame.older()
   ...:

In [2]: addresses
Out[2]:
[18446743799118392792,
 18446743799118392764,
 18446743799118392824,
 18446743799118446620,
 18446743799101139984,
 18446743799101139984,
 18446743799101140444,
 18446743799100277488,
 0]
```

1) We should manually remove 0x0 from the `addresses` array if it exists
2) I'm confused why `del addresses[:index]` didn't remove it from the list. Printing it at all is wrong, but even then it should have only been printed one time.

**Comment by gsingh93** [comment]
> I'm confused why del addresses[:index] didn't remove it from the list. Printing it at all is wrong, but even then it should have only been printed one time.

Oh, `del addresses[:index]` deletes everything before `index`, not including `index`. I'm not sure if this is intentional or not.

**Comment by chrf01** [comment]
> @chrf01 Shall we just make the command not work on qemu kernel or shall we implement it somehow for it?

I don't know; it would be nice to have this feature, but implementing it across all supported kernel archs might not be straightforward. For instance, on aarch64, we need to account for PAC-signed return addresses on the stack. Additionally, we should attempt to read the first byte to verify if it's a valid address and check whether the mapping is marked as executable.
