### ISSUE TITLE
`regs <reg_group>` is broken

### ISSUE THREAD

**Issue by chrf01** [pwndbg/pwndbg#2108]
### Steps to reproduce

1. execute `regs all` command

### My setup

![grafik](https://github.com/pwndbg/pwndbg/assets/72693057/637a97de-821e-4694-a215-952c88effc3f)

**Comment by disconnect3d** [comment]
Fwiw one should just use `regs` to display all registers, though it doesn't display flags and perhaps it should?

I think that `regs stack|common|retaddr` should probably also not work?

```
pwndbg> regs
*RAX  0x7ffff7e1bf10 (initial+16) ◂— 1
 RBX  0x7ffff7e1a838 (__exit_funcs) —▸ 0x7ffff7e1bf00 (initial) ◂— 0
 RCX  0
 RDX  1
 RDI  0x7ffff7e1bf00 (initial) ◂— 0
 RSI  0x7ffff7e1bf00 (initial) ◂— 0
 R8   0x7ffff7e1bf10 (initial+16) ◂— 1
 R9   0x7ffff7fc9040 (_dl_fini) ◂— endbr64 
 R10  0x77
 R11  0x246
 R12  0x7fffffffddf8 —▸ 0x7fffffffe1b2 ◂— '/usr/bin/ls'
 R13  0x555555558d10 ◂— endbr64 
 R14  0
 R15  0
 RBP  0x7ffff7e1bf00 (initial) ◂— 0
 RSP  0x7fffffffdd40 ◂— 0
*RIP  0x7ffff7c4576c (__new_exitfn+156) ◂— add qword ptr [rip + 0x1d676c], 1
pwndbg> 
```

**Comment by gsingh93** [comment]
When was the last version of `pwndbg` where this worked? I honestly didn't know this was a feature and don't see it documented anywhere. Even if it used to be supported, should we still support it?

**Comment by gsingh93** [comment]
Ok, from Discord we found out OP may have thought this was a feature because of the methods in `gdblib/regs.py`, but currently these are just used in the Python code and not intended to be used in commands. This may change in the future if there's a compelling use case for this, but for now we'll close this.
