### ISSUE TITLE
Can't find GLIBC version required for this command to work, maybe is because GLIBC is not loaded yet.

### ISSUE THREAD

**Issue by kamathhrishi** [pwndbg/pwndbg#2122]
I get the stated error when I run vis command:

```
Can't find GLIBC version required for this command to work, maybe is because GLIBC is not loaded yet.
If you believe the GLIBC is loaded or this is a statically linked binary. Please set the GLIBC version you think the target binary was compiled (using `set glibc <version>` command; e.g. 2.32) and re-run this command
```

I try running the command 
```
set glibc 2.37 
```
and end up with the message 

```
Set GLIBC version for heap heuristics resolution (e.g. 2.31) to (2, 37).
```

But. when I run vis I gain I end up with the same error. Any inputs on how I can get this resolved? Can I manually link glibc its using?

When I run the command ```ldd --version```

I get this:

```
ldd (Debian GLIBC 2.37-15) 2.37
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

So I do have GLIBC

**Comment by lebr0nli** [comment]
Hi, thanks for reporting the bug!
Could you kindly offer more context regarding the binary you debugged?
It would be immensely helpful if you could provide details such as the binary itself, the breakpoint address, the result of `info sharedlibrary`, and information about the `libc.so.6` and `ld-linux-x86-64.so.2` libraries used by the binary.
Your additional insights will greatly aid us in resolving this issue effectively.

**Comment by disconnect3d** [comment]
Ping @kamathhrishi

**Comment by kamathhrishi** [comment]
Hello, I made a mistake of exiting the program rather than pressing Control+C so vis was not getting the context. It was a simple error from my part.

Closing the issue.
