### ISSUE TITLE
[bug]: Python Exception: Recursion Error

### ISSUE THREAD

**Issue by k4lizen** [pwndbg/pwndbg#2132]
### Description
pwndbg hitting recursion limit while gdb works fine.

 CTF challenge zip: [the_wilderness.zip](https://github.com/pwndbg/pwndbg/files/15133514/the_wilderness.zip)
Im using an older version of the sde than the challenge intended: https://www.intel.com/content/www/us/en/download/684897/784319/intel-software-development-emulator.html

### Steps to reproduce

`./sde-external-<version>-lin/sde64 -debug -no-follow-child -cet -cet_output_file /dev/null -- ./build/the_wilderness`
The program will give the command to run in gdb in a new window, it will look like: `target remote :40395`. Works as intended in gdb, while pwndbg goes crazy:
![image](https://github.com/pwndbg/pwndbg/assets/124312252/c8eac522-631b-41c1-921f-6ffe5dd56e74)

### My setup

Gdb:      13.2
Python:   3.11.8 (main, Feb  7 2024, 21:52:08) [GCC 13.2.0]
Pwndbg:   2024.02.14 build: da817b23
Capstone: 5.0.1280
Unicorn:  2.0.1

### related
My be related to https://github.com/pwndbg/pwndbg/issues/2110 though the behaviour seems a bit different, and `set follow-fork-mode parent` does not seem to have any effect.

**Comment by disconnect3d** [comment]
Fixed in https://github.com/pwndbg/pwndbg/pull/2311
