### ISSUE TITLE
Typesetting seems to be wrong

### ISSUE THREAD

**Issue by Bluekezhou** [pwndbg/pwndbg#215]
![image](https://cloud.githubusercontent.com/assets/7897423/24843862/42e004bc-1dd9-11e7-8447-b8cf87ed6fe1.png)

**Comment by zachriggle** [comment]
Can't reproduce, I expect your terminal is broken.

Try opening a new terminal window.  Does this still happen?

Try removing the `source pwndbg/gdbinit.py` line from your `~/.gdbinit`.  Does this still happen?

**Comment by disconnect3d** [comment]
@zachriggle Happens for me only if pwndbg is initialized in both gnome-terminal and terminator.

**Comment by cloudburst** [comment]
FWIW this also happens to me with gnome-terminal (including opening a new terminal).  Goes away if you don't source pwndbg in your .gdbinit

**Comment by zachriggle** [comment]
Hmmmmmmmmmm

**Comment by zachriggle** [comment]
Does this only occur when attempting to tab-complete?  Does it only occur for tab-completing command names?

**Comment by disconnect3d** [comment]
@zachriggle I think so: https://asciinema.org/a/652yj24od38z01aot65zehi8k

**Comment by disconnect3d** [comment]
This is caused because of `set width 0` in https://github.com/pwndbg/pwndbg/blob/master/pwndbg/__init__.py#L128

Here is a recording:
https://asciinema.org/a/8dvzsu6keibmua694y2scqpk8

**Comment by anthraxx** [comment]
I can confirm this also happens for me and removing `set width 0` seems to fix it.

**Comment by zachriggle** [comment]
Hmm, that kind of makes sense that the tab-completion doesn't "wrap" into rows when the width is `0` or `unlimited`.

It might be better for us to do something that grabs the width via `tcgetattr` or similar.

**Comment by anthraxx** [comment]
just as a reminder, if we do something like that then we will need a hook for resizing row width of the terminal

**Comment by zachriggle** [comment]
Yep! It's not too hard to set up a signal handler for `SIGWINCH`.

**Comment by Bluekezhou** [comment]
everything seems to be right after I grab the latest version

**Comment by anthraxx** [comment]
please re-open this is still an issue and happening

**Comment by anthraxx** [comment]
I could work on a patch with SIGWINCH and proper `set with` so feel free to assign me this issue.

**Comment by disconnect3d** [comment]
@Bluekezhou Can you check if https://github.com/pwndbg/pwndbg/pull/291 works for you?
