### ISSUE TITLE
Top-level Exception Handlers

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#217]
It seems that we could do well to register a top-level exception handler (sys.excepthook) and check for common `gdb` exceptions.

From the exception handler, we can walk the Python call stack and see which `Command` object was invoked (if any) and the lowest `pwndbg` call-frame to extract the offending internal function's name.

This would allow us to *generally* not have to worry about having pretty messages for the user doing something silly.

A specific example is the `hexdump` command here: https://github.com/pwndbg/pwndbg/blob/433bf23177c60590bacfc37bbed3d244e7872cde/pwndbg/commands/hexdump.py#L44

```py
    try:
        data = pwndbg.memory.read(address, count, partial=True)
    except gdb.error as e:
        print(e)
        return
```

**Comment by zachriggle** [comment]
The top-level exception handler might save us in cases where we also don't expect exceptions (yet).  A convenient thing we could do is to log the full stack-trace to a file, and point the user to the Issue tracker here on Github.

For functions where we *expect* the exception may be raised (and know that we only want to display an error message), we might be able to use a decorator or a context manager.  For example:

```py
@PrintGdbError
@Command
def foo(...):
    ...
```

```py
def bar(...):
    with GdbErrorMessageHandler:
        gdb.DoSomeStuff(...)
```

Where `GdbErrorMessageHandler` (terrible name) will raise some other `Exception`-derived object which the top-level `sys.excepthook` will silently discard.

**Comment by disconnect3d** [comment]
Possible extensions of above idea:
* have a setting for developers like `set debug-postmortem` which make the excetion handler calling `import pdb; pdb.post_mortem(exception_obj)` when something fails
* ask user for automatic error report generation and upload (not sure if that's possible on github) - that would contain: stacktrace, user's gdb, python, pwndbg version, ~/.gdbinit content, analysed binary and commands history.

**Comment by disconnect3d** [comment]
Closing as this is more or less covered by https://github.com/pwndbg/pwndbg/pull/300 or to be more specific:
https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/exception.py#L42-L68
