### ISSUE TITLE
An exception occurred in QemuGdbMachine

### ISSUE THREAD

**Issue by peiwithhao** [pwndbg/pwndbg#2171]
### Description

When I open pwndbg to debug the qemu booted kernel(sysret bug practice), an exception will be reported:
```
Exception ignored in: <function QemuGdbMachine.__del__ at 0x77792a10aa20>
Traceback (most recent call last):
  File "/home/peiwithhao/tools/pwndbg/.venv/lib/python3.12/site-packages/pt_gdb/pt_gdb.py", line 19, in __del__
    if self.file:
       ^^^^^^^^^
AttributeError: 'QemuGdbMachine' object has no attribute 'file'
```

And there is an error report about gdb on it

```
Permission error when attempting to parse page tables with gdb-pt-dump.
Either change the kernel-vmmap setting, re-run GDB as root, or disable `ptrace_scope` (`echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope`)
```
This has bothered me all morning until now :(

version
```
Gdb:      14.2
Python:   3.12.3 (main, Apr 23 2024, 09:16:07) [GCC 13.2.1 20240417]
Pwndbg:   2024.02.14 build: 00adfbbb
Capstone: 5.0.1280
Unicorn:  2.0.1
```

**Comment by gsingh93** [comment]
This error is coming from gdb-pt-dump, not pwndbg.

> Either change the kernel-vmmap setting, re-run GDB as root, or disable `ptrace_scope` (`echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope`)

Did you try any of these suggestions? Is ptrace_scope disabled?

**Comment by gsingh93** [comment]
@peiwithhao ping

**Comment by peiwithhao** [comment]
@gsingh93 I got it!Thanks For your help :)
