### ISSUE TITLE
Remove pwndbg.constants

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#2175]
Most of [pwndbg.constants](https://github.com/pwndbg/pwndbg/tree/dev/pwndbg/constants) is copied from [pwnlib.constants](https://github.com/Gallopsled/pwntools/tree/e92a30bbf7a838e739b8428d9b1d446fd671cf48/pwnlib/constants) in pwntools. We should just use the pwntools constants to avoid duplication of code.

I believe the only place this code was used was in this `syscall` function: https://github.com/pwndbg/pwndbg/blob/e812ef0fffc2826bd22d274de55de1a691778538/pwndbg/constants/__init__.py#L26

So after making the change, we need to verify that still works (if there is not already a test for this, we should add one).

The only file here that should be kept is [pwndbg/constants/ptmalloc.py](https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/constants/ptmalloc.py). Personally, I don't think we should keep the entire constants directory for this one small file, and we should move this into the ptmalloc code.

**Comment by disconnect3d** [comment]
Pwntools was updated to the latest & recent release in https://github.com/pwndbg/pwndbg/pull/2355
