### ISSUE TITLE
Install all dependencies with poetry

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#2219]
We've almost entirely switched to poetry, except for the fact that we still do `pip install` in `setup.sh`. `pip install` will *not* use the poetry.lock file, and so currently everyone is running on different versions of the dependencies. We should:

1. Install poetry in setup.sh
2. Don't install pip
3. Convert the `pip install` to a `poetry install`
4. Remove the redundant installation of the poetry binary in `setup-dev.sh`, we shouldn't need to redo anything already done in `setup.sh`

**Comment by Fe1777** [comment]
Below is a more detailed step-by-step guide formatted specifically for GitHub community engagement.

---

### Issue #2219: Install All Dependencies with Poetry

**Opened by:** @gsingh93  
**Status:** Open, last updated 23 hours ago  
**Labels:** `enhancement`, `help wanted`, `good first issue`

### Description

We need to transition to using Poetry for dependency management across our project to ensure version consistency and simplify the setup process. The current `setup.sh` script still uses `pip install`, which doesn't leverage the `poetry.lock` file. This leads to potential inconsistencies in dependency versions across different environments.

### Objectives

1. **Install Poetry**: Ensure Poetry is installed as part of the setup process.
2. **Remove `pip install`**: Eliminate `pip install` dependency installations from `setup.sh`.
3. **Use Poetry for Dependency Installation**: Switch from `pip install` to `poetry install` in `setup.sh`.
4. **Avoid Redundant Setup**: Remove any redundant installations of the Poetry binary in `setup-dev.sh`.

### Details

#### Step 1: Install Poetry in `setup.sh`
We need to check if Poetry is installed. If not, install it.

**Instructions:**
1. **Open the `setup.sh` file**.
2. **Insert the following code at the beginning of the file** to check for existing Poetry installation:

    ```sh
    # Install Poetry
    if ! command -v poetry &> /dev/null
    then
        echo "Poetry not found. Installing Poetry..."
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.local/bin:$PATH"
    else
        echo "Poetry is already installed."
    fi
    ```

#### Step 2: Replace `pip install` with `poetry install`
Remove all instances of `pip install` and replace them with `poetry install`.

**Instructions:**
1. **Find all `pip install` commands** within the `setup.sh` file.
2. **Replace each instance with**:

    ```sh
    # Install dependencies using Poetry
    poetry install
    ```

3. **Ensure the `poetry.lock` file is included in the repository** (if not already).

#### Step 3: Modify `setup-dev.sh`
Remove any redundant installations of Poetry. The installation should now be handled by `setup.sh`.

**Instructions:**
1. **Open the `setup-dev.sh` file**.
2. **Find and remove any blocks of code related to installing Poetry**:

    ```sh
    # Remove this block if found
    # Install Poetry
    # curl -sSL https://install.python-poetry.org | python3 -
    ```

### Benefits

- **Consistency**: Ensures all contributors are using the same versions of dependencies.
- **Simplification**: Simplifies the setup process by consolidating dependency management under Poetry.
- **Efficiency**: Reduces duplications in setup scripts, making maintenance easier.

### Getting Started

1. **Discussion**: Engage in discussions by commenting on this issue.
2. **Pull Requests**: Follow the guidelines below to submit a PR addressing the mentioned tasks.

### References

- [Poetry Documentation](https://python-poetry.org/docs/)
- [Existing `setup.sh` Script](https://github.com/pwndbg/pwndbg/blob/master/setup.sh)
- [Poetry Installation Guide](https://python-poetry.org/docs/#installation)

### How to Contribute

#### Step-by-Step Contribution Guide

1. **Fork the Repository**:
    - Go to the [repository page](https://github.com/pwndbg/pwndbg).
    - Click on the "Fork" button.

2. **Clone Your Fork**:
    - Open a terminal and execute:
        ```sh
        git clone https://github.com/<your-username>/pwndbg.git
        cd pwndbg
        ```
3. **Create a New Branch**:
    - It's good practice to create a new branch for your work:
        ```sh
        git checkout -b enhance-poetry-setup
        ```

4. **Make Your Changes**:
    - Follow the instructions in the Details section to update `setup.sh` and `setup-dev.sh`.

5. **Stage and Commit Your Changes**:
    - After making changes, in the terminal:
        ```sh
        git add setup.sh setup-dev.sh
        git commit -m "Switch to Poetry for dependency management in setup"
        ```

6. **Push Your Changes to Your Fork**:
    - Push your branch to your forked repository:
        ```sh
        git push origin enhance-poetry-setup
        ```

7. **Create a Pull Request**:
    - Go to your fork on GitHub.
    - You should see a prompt to create a pull request for your newly pushed branch.
    - Follow the prompts, ensure your PR is descriptive and references this issue.

8. **Address Feedback**:
    - Be proactive in addressing any feedback from maintainers or other contributors.

Thank you for contributing to the "pwndbg" project! If you have questions, feel free to ask in the comments of this issue.

---

**Comment by egorus1** [comment]
Hi! I am new here, will try to solve this issue!

**Comment by walstper** [comment]
Hello, I've prepared [PR](https://github.com/pwndbg/pwndbg/pull/2220). Please take a look at it.

**Comment by B1N4RY-P4R45173** [comment]
I think (not sure) we might have to update the Docker files as well.
