### ISSUE TITLE
support artix in install script

### ISSUE THREAD

**Issue by k4lizen** [pwndbg/pwndbg#2224]
Currently running
`bash setup.sh --update` on artix says its not supported
probably just changing
`136:       "arch" | "archarm" | "endeavouros" | "manjaro" | "garuda" | "cachyos" | "archcraft")`
to
`136:       "arch" | "archarm" | "endeavouros" | "manjaro" | "garuda" | "cachyos" | "archcraft" | "artix")`
would fix the issue.

**Comment by disconnect3d** [comment]
Hi, please send a pull request with the listed change or let us know and I can send a PR with such a change.

In case you need help with sending PRs see:
* https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests
* https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
