### ISSUE TITLE
run setup.sh without affecting .gdbinit 

### ISSUE THREAD

**Issue by k4lizen** [pwndbg/pwndbg#2225]
This is what I dislike currently:
1. I manage my dotfiles so I can have the `source pwndbg/gdbinit.py` line set in my .gdbinit without having installed pwndbg yet. When I run setup.sh it detects this, asks if I want it to edit my .gdbinit, I say no, it exits. I would rather that it just continue on with the script in this case, and it isn't really clear that my choice led to the script not doing anything without peeking at the code.
2. So I run `bash setup.sh --update` since it says
>   --update: Install/update dependencies without checking ~/.gdbinit

But then the debuginfod line gets added to my .gdbinit without any warning whatsoever. (and I don't want the line there since debuginfod can be slow and restarts on ctf challenge files with no results etc.)

# Feature
A possible solution to the problem I face is:
1. Don't exit the script when I decline to have .gdbinit edited (isn't it just going to skip installing everything if its already installed, whats the harm in letting the script finish?)
2. Add a message about debuginfod like there is for `source pwndbg/gdbinit.py`:
> echo "[*] Added 'source $PWD/gdbinit.py' to ~/.gdbinit so that Pwndbg will be loaded on every launch of GDB."

3. Don't add the debuginfod line to .gdbinit when --update is passed.

**Comment by disconnect3d** [comment]
The way we manage `.gdbinit` is really suboptimal. If you agree on adding the line, I think it removes/comments out previous line like this and adds the line at the end. And ur gdbinit may already have some `set <param> <value>` where params come from Pwndbg and ... things break.

This should be changed/fixed anyway.

**Comment by gsingh93** [comment]
The current behavior is really weird, I checked where it came from and it seems like it was https://github.com/pwndbg/pwndbg/pull/1620, which was intended to fix #1394.

@disconnect3d I'm not understanding the motivation for the solution you proposed in #1394. Why not just not skip adding the .gdbinit line if it exists and do everything else the exact same way, why prompt the user at all?

BTW, this comment proposed having some comment to indicate the start/end of the pwndbg configuration: https://github.com/pwndbg/pwndbg/issues/1394#issuecomment-1335452939

This is actually common practice these days whenever some tools automatically modifies an rc file, we should consider doing it.

**Comment by disconnect3d** [comment]
> @disconnect3d I'm not understanding the motivation for the solution you proposed in https://github.com/pwndbg/pwndbg/issues/1394. Why not just not skip adding the .gdbinit line if it exists and do everything else the exact same way, why prompt the user at all?

Honestly I don't remember why I suggested that. I think we can drop prompting the user at all.

If we add an indicator for start/end of pwndbg config, we should probably also do:
- change `configfile` command to show the indicators :)
- extend `configfile` to have a `--save` flag to actually save the `~/.gdbinit`, optionally having a `-c <configpath>` flag for it

**Comment by patryk4815** [comment]
@disconnect3d 
>  And ur gdbinit may already have some set <param> <value> where params come from Pwndbg and ... things break.

I think we need introduce `.pwndbginit` and it will executed always after pwndbg initialisation it should solve a lot of problems, and introduces new 'UX' problems 😅
Maybe it will help for lldb/gdb agnostic config? 🤔

**Comment by disconnect3d** [comment]
The main thing from this issue was resolved in #2529.

As per what @patryk4815 suggests, maybe this is the time to actually add .pwndbginit now that we have both GDB and LLDB being supported? I'm not sure. :p 

cc: @mbrla0 Do we support pre-configuring lldb anyhow currently?

**Comment by mbrla0** [comment]
> cc: @mbrla0 Do we support pre-configuring lldb anyhow currently?

Not currently, but it's not hard to support that. We fully control initialization in LLDB, so we can have the configuration be as wacky and as powerful as we want. From running custom LLDB+Pwndbg CLI commands from a text file to just running a Python script that has access to the whole of Pwndbg.

**Comment by patryk4815** [comment]
@disconnect3d I think it is better(?) somehow drop directly modifying .gdbinit. And support something `gdb -q --init-command=gdbinit.py`

**Comment by k4lizen** [comment]
fwiw I think having a .pwndbginit is a good idea. I sometimes swap between gef and pwndbg and that would make it easier. I currently have something like this in gdbinit
```bash
#!/bin/sh
# pwndbg config
define pwndbg_run
	source ~/pwndbg/gdbinit.py
	set max-visualize-chunk-size 0x50
	set exception-verbose on
	# set exception-debugger on
end

# == Run the appropriate gdb script ==
# source ~/opt/gef/gef.py
pwndbg_run

# == Various ==
# ... gdb settings
```
