### ISSUE TITLE
Setup should detect apt and pacman instead of distros

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#2227]
As described in https://github.com/pwndbg/pwndbg/pull/2226#pullrequestreview-2111784359 instead of "supported distro" we can probably go with just detecting `apt` and `pacman` (and others?) in setup.sh and use them right away.

https://github.com/pwndbg/pwndbg/blob/dev/setup.sh#L121-L164

**Comment by raffifu** [comment]
Hii @disconnect3d can i work on this issue?

**Comment by disconnect3d** [comment]
@raffifu Sure, just send a PR with this change. You don't have to be assigned to the issue, but I will do it here.
