### ISSUE TITLE
Runtime Error with Poetry

### ISSUE THREAD

**Issue by itsabugnotafeature** [pwndbg/pwndbg#2234]
### Description

Pwndbg installs successfully but fails to run in gdb, producing the following error 

```
Traceback (most recent call last):
  File "/opt/pwndbg/gdbinit.py", line 83, in <module>
    update_deps(__file__)
  File "/opt/pwndbg/gdbinit.py", line 60, in update_deps
    stdout, stderr, returncode = run_poetry_install(dev=dev_mode)
  File "/opt/pwndbg/gdbinit.py", line 40, in run_poetry_install
    result = subprocess.run(command, capture_output=True, text=True)
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'poetry'
```

It appears to stem from code in commit 180102bf176596e99c4dd79a40918e1a911114a8.

The problem can be fixed by running `pip install poetry`. 

### Steps to reproduce

A minimal dockerfile

```# syntax=docker/dockerfile:1
FROM ubuntu:latest

# Necessary for pwndbg
ENV LANG en_US.UTF-8
ENV LC_CTYPE C.UTF-8

RUN apt-get update

# Install dev requirements
RUN apt-get install -y tmux git
RUN echo "set auto-load safe-path /" >> /root/.gdbinit

# Install pwndbg
RUN apt-get install -y python3 python3-pip
WORKDIR /opt
RUN git clone https://github.com/pwndbg/pwndbg
WORKDIR /opt/pwndbg
RUN ./setup.sh

ENTRYPOINT [ "/bin/bash" ]
```

Running `gdb` from the command line will trigger the error.

### My setup

```
(gdb) show version
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "aarch64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
```

```
root@bdb668b3229b:/# python3 -c "import sys; print(sys.version)"
3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
```

```
root@bdb668b3229b:/opt/pwndbg# git log -1 --pretty=oneline
180102bf176596e99c4dd79a40918e1a911114a8 (HEAD -> dev, origin/dev, origin/HEAD) Auto-update dependencies after a git pull (#2203)
```

**Comment by itsabugnotafeature** [comment]
Running `if ! command -v poetry &> /dev/null; then echo "Poetry not installed"; else echo "Poetry is already installed"; fi;` prints "Poetry not installed". This check is used to determine if poetry has already been installed in `setup.sh`, although it seems to be harmless, because the poetry installer will check on its own.

This seems to stem from the fact that the path to `poetry` is not added to the calling shell's $PATH variable (export only exposes it to the children of the process running `setup.sh`), so even after running `setup.sh` the calling shell can't find the poetry binary.

**Comment by gsingh93** [comment]
Thanks for the report! I guess [here](https://github.com/pwndbg/pwndbg/blob/dev/gdbinit.py#L37) we should just use the full path to poetry instead of assuming it's on the path? I didn't notice it locally because for me `$HOME/.local/bin` is already on my path. I'm guessing the CI jobs on the PR didn't catch this because 1) it's probably already on the path for GH CI, and 2) for the Docker tests I just checked and turns out they were failing (https://github.com/pwndbg/pwndbg/actions/runs/9535190528/job/26280632135), but they showed up as passing due to #2218.

After fixing that, I'm also wondering if `gdbinit.py` should check if poetry is installed first, and if it doesn't exist tell the user they need to run `./setup.sh` and then continue without running poetry. On one hand it seems like extra work for us to do when everyone should always re-run `setup.sh` after a pull, but on the other hand I know people don't do that and will be confused when they don't have poetry installed.

@B1N4RY-P4R45173 would you be able to take a look at the first part of this issue, with using the full path to poetry when executing it?

**Comment by itsabugnotafeature** [comment]
Running `export PATH="$HOME/.local/bin:$PATH"` in the calling shell of `setup.sh` fixes this issue. 

It seems that the issue is caused specifically by https://github.com/pwndbg/pwndbg/blob/180102bf176596e99c4dd79a40918e1a911114a8/gdbinit.py#L40, which will fail because as mentioned earlier, the $PATH in the calling shell is not updated due to https://github.com/pwndbg/pwndbg/blob/180102bf176596e99c4dd79a40918e1a911114a8/setup.sh#L188, so subprocess returns a file not found error.

**Comment by itsabugnotafeature** [comment]
> Thanks for the report! I guess [here](https://github.com/pwndbg/pwndbg/blob/dev/gdbinit.py#L37) we should just use the full path to poetry instead of assuming it's on the path? I didn't notice it locally because for me `$HOME/.local/bin` is already on my path. I'm guessing the CI jobs on the PR didn't catch this because 1) it's probably already on the path for GH CI, and 2) for the Docker tests I just checked and turns out they were failing (https://github.com/pwndbg/pwndbg/actions/runs/9535190528/job/26280632135), but they showed up as passing due to #2218.
> 
> After fixing that, I'm also wondering if `gdbinit.py` should check if poetry is installed first, and if it doesn't exist tell the user they need to run `./setup.sh` and then continue without running poetry. On one hand it seems like extra work for us to do when everyone should always re-run `setup.sh` after a pull, but on the other hand I know people don't do that and will be confused when they don't have poetry installed.
> 
> @B1N4RY-P4R45173 would you be able to take a look at the first part of this issue, with using the full path to poetry when executing it?

Re: tests passing, sounds right. I'm running a stock ubuntu container so my environment is pretty spare. 

Re: checking for poetry in `gdbinit.py`, I did not know that you were supposed to rerun `setup.sh`, so a reminder doesn't sound like a bad idea.

I'm happy to submit my own PR for this as well, if @B1N4RY-P4R45173  is busy. I was thinking it would make the most sense to check if `poetry` is installed in the normal location, then check if there is a `$POETRY_HOME` env variable (sort of described [here](https://python-poetry.org/docs/#installing-with-the-official-installer)), then if all else fails, announce it wasn't found to the user and quit. I'm not familiar with gdb scripting and the pwndbg virtualenv so I'm not sure the best way to handle the no-poetry-found case gracefully.

**Comment by gsingh93** [comment]
> I'm happy to submit my own PR for this as well, if @B1N4RY-P4R45173 is busy

Sure!

The checks for poetry you mentioned make sense to add. But if poetry isn't installed, we can just skip running it. It's only used to update python dependencies (so that you no longer need to rerun setup.sh after a pull), but if we can't find it we should just continue without updating anything as often it'll just work fine. But we should warn users to get poetry on the path in case a dependency changes in the future and they need to run it (or setup.sh) for things to work correctly.

**Comment by B1N4RY-P4R45173** [comment]
> I'm happy to submit my own PR for this as well, if @B1N4RY-P4R45173 is busy. I was thinking it would make the most sense to check if `poetry` is installed in the normal location, then check if there is a `$POETRY_HOME` env variable (sort of described [here](https://python-poetry.org/docs/#installing-with-the-official-installer)), then if all else fails, announce it wasn't found to the user and quit. I'm not familiar with gdb scripting and the pwndbg virtualenv so I'm not sure the best way to handle the no-poetry-found case gracefully.



Thanks for the report! At the present I have some exams going on. So I am busy with them. I would be happy if you can submit a PR. Once again thanks for brining this under our notice

**Comment by B1N4RY-P4R45173** [comment]
> The checks for poetry you mentioned make sense to add. But if poetry isn't installed, we can just skip running it. It's only used to update python dependencies (so that you no longer need to rerun setup.sh after a pull), but if we can't find it we should just continue without updating anything as often it'll just work fine. But we should warn users to get poetry on the path in case a dependency changes in the future and they need to run it (or setup.sh) for things to work correctly.

Honestly I am confused about error handling if I should just break out of `update_deps` function to skip updating/installing the dependencies, or should I ask the user to run `./setup.sh` ? or should I just automate the python script to run `./setup.sh` if it doesn't find poetry?

**Comment by gsingh93** [comment]
> should just break out of update_deps function to skip updating/installing the dependencies, or should I ask the user to run ./setup.sh?

Both, I'll comment on the PR.

**Comment by gsingh93** [comment]
@B1N4RY-P4R45173 Thanks for the quick fix, especially when you were busy!

@itsabugnotafeature please retest this, if it's still an issue free to reopen.

**Comment by B1N4RY-P4R45173** [comment]
> @B1N4RY-P4R45173 Thanks for the quick fix, especially when you were busy!

That's my pleasure! I couldn't have done it without your guidance. Thank you!

**Comment by B1N4RY-P4R45173** [comment]
Also, @itsabugnotafeature, thanks for suggesting the idea of using `$POETRY_HOME`. I hadn't considered that the user might have already installed Poetry but customized its path.

**Comment by itsabugnotafeature** [comment]
Can confirm that it works with the docker file I provided above. Thanks for the quick fix!
