### ISSUE TITLE
Add a configuration option to disable auto dependency updates

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#2235]
We recently added a feature where Python dependencies are automatically updated when launching GDB. In the majority of cases this is best to leave on by default, but we should add a configuration option in case anyone wants to disable this functionality in some specific cases.

The thing is that pwndbg's normal configuration infra isn't loaded yet, so we can't use it in `gdbinit.py`. Maybe we just use an environment variable?

**Comment by disconnect3d** [comment]
This has been implemented in #2380 :). I have also added info log when the update is happening as detailed in #2490, which was annoying when update occurred for a long time and nothing was printed on when GDB was started.
