### ISSUE TITLE
Incorrect caching on `start` command

### ISSUE THREAD

**Issue by Aplet123** [pwndbg/pwndbg#2237]
### Description

`start` caches the entry breakpoint for too long (I think this is an issue with the caching on `pwndbg.gdblib.elf.entry()` specifically), so if you enable ASLR then `start` twice, the second time won't reset the breakpoint.

### Steps to reproduce

Pick a PIE executable, then run `set disable-randomization off`, then `start`, then `start` again. If you run `memoize` to disable caching, the issue no longer persists.

### My setup

```
Gdb:      14.2
Python:   3.12.4 (main, Jun  7 2024, 06:33:07) [GCC 14.1.1 20240522]
Pwndbg:   2024.02.14 build: 180102b
Capstone: 5.0.1280
Unicorn:  2.0.1
```

**Comment by disconnect3d** [comment]
The `start` command does not cache anything, but it creates a temporary breakpoint on one of the symbols:
https://github.com/pwndbg/pwndbg/blob/6cb96632a4e492a6c943a2a85ea0503b15d35ee4/pwndbg/commands/start.py#L59-L78

It takes the symbol addresses from `pwndbg.gdblib.symbo.address`:
https://github.com/pwndbg/pwndbg/blob/6cb96632a4e492a6c943a2a85ea0503b15d35ee4/pwndbg/gdblib/symbol.py#L139-L164

And this one is cached until a new `objfile` is loaded. I bet this is the thing that is cached and doesn't work properly here.

**Comment by disconnect3d** [comment]
@Aplet123 Can you check if this works properly when you disable cache for `pwndbg.gdblib.symbol.address` (just comment out its `cache_until("objfile")`?

If so, we should probably do a: `cache_until("start", "objfile")` instead? Does that fix the issue?

We should probably also add a comment like `# We need to cache until "start" as ASLR may change the symbol address` in there.

If so, please send a PR with the fix :). 

(It would also be nice to add a test case for it)

**Comment by disconnect3d** [comment]
Btw I have looked for other potential bugs like this, and this could be a candidate:
https://github.com/pwndbg/pwndbg/blob/6cb96632a4e492a6c943a2a85ea0503b15d35ee4/pwndbg/gdblib/elf.py#L152-L153

But it isn't a bug because the `vaddr` which is the base address to rebase to is an argument and our cache caches the results for given arguments, so this should work fine, huh :).

**Comment by Aplet123** [comment]
The binary I was testing on was stripped, so it went to the fallback case of breaking on entrypoint due to not finding any of the symbols:
https://github.com/pwndbg/pwndbg/blob/6cb96632a4e492a6c943a2a85ea0503b15d35ee4/pwndbg/commands/start.py#L23-L29

Commenting out the cache on `pwndbg.gdblib.elf.entry()` fixed the bug in that case. When testing on a binary that has symbols, it actually works for me as-is, because the breakpoint is set on the symbol, not on the cached address.

~~I think there's a bigger issue at hand though, as I sometimes don't get a start event when running the program using the `start` command. I need to do some more testing to see why this happens.~~ I may have just been hallucinating? I can't reproduce it anymore.

**Comment by Aplet123** [comment]
I think there's a bit of an event ordering issue, where the cache is cleared after everything else for the event is run, which means that event handlers can receive a stale cache when running.
