### ISSUE TITLE
Tests always pass on Ubuntu 24.04

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#2247]
Our tests rely on `sys.exit` in Python exiting the GDB process with the specified return code. This behavior worked in GDB 12.1, but is different in GDB 15 which is used on Ubuntu 24.04. On GDB 15, the process will not exit. This means the tests status on CI will always pass, even if tests are actually failing, as the return code is always zero.

I asked about this on the GDB mailing list here: https://sourceware.org/pipermail/gdb/2024-June/051417.html

Some other details can be found in #2218.

**Comment by gsingh93** [comment]
From the email thread, we can try `os._exit(1)`. And on discord it was suggested to use `gdb.execute(f"quit {return_code}")`

**Comment by disconnect3d** [comment]
To be clear, those are the lines we will have to change for GDB 15:

https://github.com/pwndbg/pwndbg/blob/dc9c87254aae436147a577290007b0a0b3a8210a/gdbinit.py#L176-L178

We should contact GDB devs if they can persist the old behavior and if not, we should change the above lines accordingly.

**Comment by gsingh93** [comment]
Actually this is the primary line that will need to be changed: https://github.com/pwndbg/pwndbg/blob/dev/tests%2Fgdb-tests%2Fpytests_launcher.py#L32

But we should change the location you mentioned as well.

According to the mailing list thread, this was not intended and we should file a bug. But getting this fixed will take time, so we should make this change anyway.

**Comment by gsingh93** [comment]
I filed a GDB bug here: https://sourceware.org/bugzilla/show_bug.cgi?id=31946

In any case, let's go with the `os._exit(1)` solution for now. And if the bug ever gets fixed we can go back to the original `sys.exit`.
