### ISSUE TITLE
When I type canary on the command line in pwndbg, I get an error

### ISSUE THREAD

**Issue by edgarfy** [pwndbg/pwndbg#2257]
### error like this!!!
![image](https://github.com/pwndbg/pwndbg/assets/132528494/4ac224bd-6227-4161-bf74-e49d94e42323)

**Comment by edgarfy** [comment]
Python Exception <class 'gdb.error'> Argument required (expression to compute).: 
Python Exception <class 'gdb.error'> Error occurred in Python: Argument required (expression to compute).: 
Error occurred in Python: Error occurred in Python: Argument required (expression to compute).

**Comment by gsingh93** [comment]
I can't reproduce this. Are you using the latest version of pwndbg? What OS are you on? Can you share a binary and how you can reproduce this with that binary?

**Comment by gsingh93** [comment]
@edgarfy please reopen if you can provide more information.
