### ISSUE TITLE
stepuntilasm not running when initially attaching to qemu

### ISSUE THREAD

**Issue by OBarronCS** [pwndbg/pwndbg#2269]
The handy `stepuntilasm` command sometimes fails to run due to the `stopped_with_signal` check:
https://github.com/pwndbg/pwndbg/blob/95dd553ab7ee28866d97f919c822b2778d7c9b97/pwndbg/gdblib/next.py#L184-L187

Internally, it runs `info program` which indicates if the program was stopped with a signal.

However, when initially attaching GDB to a qemu instance, the program will indicate that it was stopped by a "breakpoint" signal. This means that after attaching, if you attempt to run `stepuntilasm`, it will not pass the above check.  You first need to `step` the program once.

Info program output immediately after attaching to qemu:
![image](https://github.com/pwndbg/pwndbg/assets/55004530/3447a68d-4c38-4b6b-803a-9a8186736b9d)

A potential fix is to narrow down the specific signal that we care about in this check.

**Comment by disconnect3d** [comment]
Hmm, the `stopped_with_signal` is doing its purpose: it tells us the reason we stopped was a signal...

I was thinking that the same bug should apply if we do a breakpoint on e.g. `ret` instruction and then try `stepret` or `nextret` but it turns out GDB shows this information differently:

```
pwndbg> info program
Last stopped for thread 1 (Thread 0x7ffff7ee9800 (LWP 864409)).
	Using the running image of child process 864409.
Program stopped at 0x55555555ab94.
It stopped at breakpoint 2.
Type "info stack" or "info registers" for more information.
```

**Comment by disconnect3d** [comment]
This could also be fixed by moving the signal check at the end of the loop instead of at its beginning.
