### ISSUE TITLE
[bug] setup-dev.sh doesn't work on Artix (and probably on Arch as well?)

### ISSUE THREAD

**Issue by k4lizen** [pwndbg/pwndbg#2284]
The setup script seems to look for the `glibc-debug` package, but I don't think that exists?
https://archlinux.org/packages/?sort=&q=glibc-debug&maintainer=&flagged=
https://aur.archlinux.org/packages?O=0&K=glibc-debug

Also it appends three repositories to `/etc/pacman.conf` which happens quite willy-nilly, I believe it should be clearer on what it's doing. On artix the `/etc/pacman.d/mirrorlist` is the artix mirrorlist, and most people have a separate mirrorlist for arch repos. So when `sudo pacman -Syu` is run it can't find those repos (so it stalls? weird).

Next, even when I switch the repos to point to the arch mirrorlist (I even put `Server = https://geo.mirror.pkgbuild.com/$repo/os/$arch` at the top), it errors out with the following message:
```bash
doas pacman -Syyu
error: GPGME error: No data
error: GPGME error: No data
error: GPGME error: No data
:: Synchronizing package databases...
 system                254.0 KiB   406 KiB/s 00:01 [----------------------] 100%
 world                   4.8 MiB  2020 KiB/s 00:02 [----------------------] 100%
 galaxy                636.0 KiB   712 KiB/s 00:01 [----------------------] 100%
 extra                   7.9 MiB  11.3 MiB/s 00:01 [----------------------] 100%
 multilib              138.8 KiB   588 KiB/s 00:00 [----------------------] 100%
 core-debug             69.4 KiB   342 KiB/s 00:00 [----------------------] 100%
 extra-debug             3.4 MiB  8.11 MiB/s 00:00 [----------------------] 100%
 multilib-debug         78.5 KiB   422 KiB/s 00:00 [----------------------] 100%
error: GPGME error: No data
error: GPGME error: No data
error: GPGME error: No data
error: failed to synchronize all databases (invalid or corrupted database (PGP signature))
```
Do these repositories even exist? They aren't here: https://wiki.archlinux.org/title/official_repositories.

**Comment by gsingh93** [comment]
cc: @anthraxx 

FWIW, tests are still passing with the ArchLinux Dockerfile: https://github.com/pwndbg/pwndbg/blob/dev/Dockerfile.arch

**Comment by Aplet123** [comment]
I think the current setup-debug is pretty fragile (altering pacman.conf is pretty bad and also requires `geo.mirror.pkgbuild.com` to be the first mirror, which isn't configured by the script), so maybe we should just take the directions from [the wiki](https://wiki.archlinux.org/title/Debugging/Getting_traces#Installing_debug_packages) and do a direct install (although we'd need some way to fetch the newest version, so it's still not ideal)

> Do these repositories even exist?

From the wiki page linked above: "A few mirrors currently distribute debug packages in accessible repositories.", which leads me to believe that this is a mirror-specific repo and not standardized.

**Comment by disconnect3d** [comment]
Can you send a PR that would fix it?

**Comment by k4lizen** [comment]
Well the fact that ArchLinux tests are passing is confusing me, i'm not well versed in this topic so I'd rather someone else take a look at it, but I can take a look at it in a week or two

**Comment by disconnect3d** [comment]
If the tests are passing there then it means it either installed there properly OR there is some caching and we are getting some old docker image or packages etc. (which is a CI bug then)

**Comment by disconnect3d** [comment]
Going to close this for now. Please reopen if this is still a valid issue for you or please send a PR to fix that.

Generally, I'd recommend using the latest stable release instead of using setup.sh, or, building from nix.

**Comment by k4lizen** [comment]
Running the command now gives me:
```
~> bash setup-dev.sh
# --------------------------------------
# Install testing tools.
# Only works with Ubuntu / APT or Arch / Pacman.
# --------------------------------------
Install a git hook to automatically lint files before pushing? (y/N)
n
"artix" is not supported distro. Will search for 'apt' or 'pacman' package managers.
setup-dev.sh: line 239: hash: apt: not found
ZIGPATH set to ~/pwndbg/.zig
[sudo] password for user: 
:: Synchronizing package databases...
 system is up to date
 world is up to date
 galaxy is up to date
 extra                                        7.5 MiB  5.41 MiB/s 00:01 [----------------------------------------] 100%
 multilib                                   133.2 KiB   126 KiB/s 00:01 [----------------------------------------] 100%
:: Starting full system upgrade...
 there is nothing to do
warning: nasm-2.16.03-1 is up to date -- skipping
warning: gcc-14.2.1+r134+gab884fffe3fc-1 is up to date -- skipping
error: target not found: glibc-debug
warning: curl-8.11.0-3 is up to date -- skipping
warning: base-devel-1-2 is up to date -- skipping
warning: gdb-15.2-3 is up to date -- skipping
~>
```
It runs successfully (well, it exits early because of `set -e`) so it's likely there was an issue with my setup. I would note the `setup-dev.sh: line 239: hash: apt: not found` line is a bit weird though.

Regarding `error: target not found: glibc-debug` Looking at the output of building `Dockerfile.arch` shows the package clearly being installed:
`core-debug/glibc-debug  2.40+r16+gaa533d58ff-2        91.22 MiB      15.28 MiB`
so this is actually just a difference between arch and artix. It seems on artix glibc-debug comes with glibc so it isn't a seperate package (https://forum.artixlinux.org/index.php/topic,6481.0.html).
