### ISSUE TITLE
[bug] pwndbg error when heap-dereference-limit is negative

### ISSUE THREAD

**Issue by k4lizen** [pwndbg/pwndbg#2290]
Bug is not too important and quite an edge case but it would be nice if the user got some clearer error message rather than an exception.

### Reproduce
```c
#include <stdio.h>
#include <stdlib.h>
int main(){
    void* a = malloc(0x500);
    malloc(0x10);
    free(a);
}
```
In pwndbg do:
`set heap-dereference-limit -1`
Then after the chunk is freed:
```
pwndbg> bins
tcachebins
empty
fastbins
empty
unsortedbin: An unknown error occurred when running this command.
You can try `set resolve-heap-via-heuristic force` and re-run this command.

For more info invoke `set exception-verbose on` and rerun the command
or debug it by yourself with `set exception-debugger on`
[...]
```

**Comment by disconnect3d** [comment]
<img width="1297" alt="image" src="https://github.com/user-attachments/assets/41cc7210-daa0-4891-a160-49d018a1b70e">
This can be fixed by enforcing this is an ZUINTEGER :)

**Comment by k4lizen** [comment]
I was expecting you to merge the fix since you discovered it yourself, should I submit a PR?

**Comment by disconnect3d** [comment]
@k4lizen oh yeah, I eventually forgot to send this in, sure, go ahead and send a PR :)
