### ISSUE TITLE
Install of Pwndbg 

### ISSUE THREAD

**Issue by tmz-pwn** [pwndbg/pwndbg#2291]
### Description

Install using git clone and ./setup.sh script results in error saying issues with updating PIP..

Updating pip (23.0.1 -> 24.0): Failed

DBusException

  org.freedesktop.DBus.Error.ServiceUnknown: The name :1.99 was not provided by any .service files

  at /usr/lib/python3/dist-packages/dbus/connection.py:634 in call_blocking
      630│                           args, signature, e.__class__, e)
      631│             raise
      632│ 
      633│         # make a blocking call
    → 634│         reply_message = self.send_message_with_reply_and_block(
      635│             message, timeout)
      636│         args_list = reply_message.get_args_list(**get_args_opts)
      637│         if len(args_list) == 0:
      638│             return None

InitError

  Failed to open keyring: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.99 was not provided by any .service files.

  at /usr/lib/python3/dist-packages/keyring/backends/kwallet.py:100 in connected
       96│             remote_obj = bus.get_object(self.bus_name, self.object_path)
       97│             self.iface = dbus.Interface(remote_obj, 'org.kde.KWallet')
       98│             self.handle = self.iface.open(self.iface.networkWallet(), wId, self.appid)
       99│         except dbus.DBusException as e:
    → 100│             raise InitError('Failed to open keyring: %s.' % e)
      101│ 
      102│         if self.handle < 0:
      103│             return False
      104│         self._migrate(service)

### Steps to reproduce

git clone repo
cd pwndbg
./setup.sh

### My setup

I am on Parrot OS Hack the Box edition.

GDB 13.1

**Comment by gsingh93** [comment]
Did you pull recently? We don't use pip anymore, so it seems like you're using an older version of pwndbg. Is that correct?

**Comment by tmz-pwn** [comment]
Can you explain how to install for me then? I usually do git clone ?

**Comment by tmz-pwn** [comment]
i downloaded the latest 2024. amd 64.deb package and installed through package manager. 

after install on command line i type : pwndbg
and it says:
Cannot convert between character sets `UTF-32' and `UTF-8'

it goes right to GEF.

**Comment by disconnect3d** [comment]
> it goes right to GEF.

If it does, then it means you have a `source ...` line for that other plugin in your `~/.gdbinit`.

**Comment by disconnect3d** [comment]
> i downloaded the latest 2024. amd 64.deb package and installed through package manager.
> 
> after install on command line i type : pwndbg and it says: Cannot convert between character sets `UTF-32' and `UTF-8'

Hmm.. the release packages are a bit old, but we probably need to make another release now. I believe this bug should not be present on the dev branch. You can install via `git clone <repo> && cd pwndbg && ./setup.sh` for now.

**Comment by fr33k3v1n0** [comment]
i have the same problem:
after follow those steps
git clone https://github.com/pwndbg/pwndbg
cd pwndbg
./setup.sh
    

```
reating virtualenv in path: ./.venv                                                                     
Installing dependencies from lock file                                                                                         
                                                                                                                               
Package operations: 49 installs, 2 updates, 0 removals                                                                         
                                                                                                                                                                                              
  • Updating pip (23.0.1 -> 24.2): Failed                                                                                      
                                                                                                                                                              
  DBusException                                                                                                                                               
                                                                                                                                                              
  org.freedesktop.DBus.Error.ServiceUnknown: The name :1.128 was not provided by any .service files                                                                                           
                                                                                                                                                              
  at /usr/lib/python3/dist-packages/dbus/connection.py:634 in call_blocking                                                                                                                   
      630│                           args, signature, e.__class__, e)                                                                                                                         
      631│             raise                                                                                                                                                                  
      632│                                                                                                                                                                                    
      633│         # make a blocking call                                                      
    → 634│         reply_message = self.send_message_with_reply_and_block(                                                                                                                    
      635│             message, timeout)                            
      636│         args_list = reply_message.get_args_list(**get_args_opts)     
      637│         if len(args_list) == 0:                                                               
      638│             return None                                                                       
                                                                                                         
The following error occurred when trying to handle this error:                                                                          
                                                                                                         
                                                                                               
  InitError                                                                                    
                                                    
  Failed to open keyring: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.128 was not provided by any .service files.            

  at /usr/lib/python3/dist-packages/keyring/backends/kwallet.py:100 in connected                                                        
       96│             remote_obj = bus.get_object(self.bus_name, self.object_path)                                                     
       97│             self.iface = dbus.Interface(remote_obj, 'org.kde.KWallet')                                                       
       98│             self.handle = self.iface.open(self.iface.networkWallet(), wId, self.appid)                                       
       99│         except dbus.DBusException as e:  
    → 100│             raise InitError('Failed to open keyring: %s.' % e)                                                               
      101│                                                          
      102│         if self.handle < 0:                              
      103│             return False                                 
      104│         self._migrate(service)                           

┌─[✗]─[top0n3@parrot]─[~/pwndbg]                                    
└──╼ $peotry                                                        
-bash: peotry: command not found               
```

**Comment by disconnect3d** [comment]
I wonder: why do people use Parrot OS, if its just "nicely looking" Debian? Are there more packages? Or newer versions? Or what? Why not Debian or Ubuntu which are much more battle tested and *just works*? (The "nice default look" of Parrot OS doesn't seem like an appealing argument because you should be able to achieve the same thing on any other  distro).

Anyway, @fr33k3v1n0 can you use a release build? If you want to live on edge and use the latest dev branch, you can build a release using the Nix package manager. But if you don't care and want to have something working for CTFs, your best bet is the portable package release we have here: https://github.com/pwndbg/pwndbg/releases/download/2024.08.29/pwndbg_2024.08.29_amd64-portable.tar.gz (from https://github.com/pwndbg/pwndbg/releases/tag/2024.08.29 release).

**Comment by tmz-pwn** [comment]
I guess you can thank HackThEBox for that one lol and I guess it does look kinda cool,
