### ISSUE TITLE
Command Name Blacklist

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#230]
We should implement a blacklist against GDB-defined default commands and keywords, so that we don't accidentally implement a command that overwrites an existing command.

A specific example of one that we overwrite is `start` (though we maintain similar behavior).

**Comment by ZetaTwo** [comment]
With my PR merged this now means that an attempt to override an existing GDB command will throw an exception. There is a whitelist for commands which are allowed to override existing commands which currently contains: "up", "down", "pwd", "search", "start".

**Comment by disconnect3d** [comment]
Done in #543, thanks again @ZetaTwo o/ :beers:
