### ISSUE TITLE
attachp: attach to process based on partial process name

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#2301]
It would be nice if the `attachp` command worked with not full process names.

It should first go over and see if there is a matching process name and only then look for processes based on partial match.

```
pwndbg> attachp qemu-system
Process qemu-system not found

pwndbg> !ps auxf | grep qemu
root        3608  0.0  0.0  12504  3584 pts/3    S+   22:22   0:00  |       |               \_ bash -c ps auxf | grep qemu
root        3610  0.0  0.0  11744  2688 pts/3    S+   22:22   0:00  |       |                   \_ grep qemu
1001        3588 40.4  1.6 3575592 258200 pts/0  Sl+  22:22   0:08      \_ /home/user/qemu-system-x86_64 -L /home/user/bios -kernel /hom

pwndbg> attachp qemu-system-x86_64
Attaching to 3588
[New LWP 3589]
```

**Comment by disconnect3d** [comment]
Implemented in https://github.com/pwndbg/pwndbg/pull/2331

**Comment by disconnect3d** [comment]
@wwwXOX hmm it turns out that the current implementation is a bit broken: doing `attachp whatever qemu` will make us attach to a `qemu-system-x86_64`. Not sure if that was the intention but I think this is counter-intuitive for users -- as it was for me ;).

**Comment by wwwXOX** [comment]
Hi, @disconnect3d ,thank you for pointing out this issue. I understand that the current behavior might be counter-intuitive. Just to clarify, the intention behind this change was to support searching for multiple commands at once, as discussed in this [comment](https://github.com/pwndbg/pwndbg/pull/2331#issuecomment-2263286101).  

For example:

> Now supports searching for multiple commands at once, e.g., ['bash', 'example-sys'].
```
#### Multi-command search example:
pwndbg> attachp "bash example-sys"
Multiple processes found. Current resolution method is "ask". Run the command `config attachp-resolution-method` to see more informations.
      pid  user    elapsed    command
--  -----  ------  ---------  -----------------------
 1      1  root    17:22      /bin/bash
 2     23  root    16:58      bash
 3     46  root    16:51      bash
 4    389  root    16:08      ./example-system-x86_64
which process to attach?(1-4)
```

In the the command `attachp whatever qemu`, could you please share what you would expect it to match? For example, would the following cases align with your expectations?

- whatever-sys-qemu-x64 (O)
- whatever-qemu-x64 (O)
- ever-qemu-x64 (X)
- whatever-qem-x64 (X)

Your input would greatly help me in refining this feature, thank you!
