### ISSUE TITLE
attachp: flag for attaching in a loop until a process is found

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#2302]
It would be nice if the `attachp` command would have a flag to try to attach in a loop until a process is found.

Something like: `attachp --retry qemu-system-x86_64` which would retry up until a process is found.

I am not sure what is the best name for the flag.

**Comment by harsha-mangena** [comment]
Hey @disconnect3d, Can I pick this issue?

**Comment by disconnect3d** [comment]
@harsha-mangena Of course? I mean, just send a PR for it. You do not need to be assigned but I will assign you.

**Comment by harsha-mangena** [comment]
@disconnect3d, I am thinking about considering the following flag(s). 
- `--retry`
- `--wait`
- `--poll`
- `--loop`
- `--until-found`

```bash
attachp --retry qemu-system-x86_64
attachp --retry --timeout 60 qemu-system-x86_64[Optional Flag]
attachp --wait --max-attempts 30 qemu-system-x86_64[Optional Flag]
```

**Comment by cfreal** [comment]
Would you be willing to consider a `--user <username/uid>` flag to tackle processes that `fork()`+`setuid()` ?

**Comment by disconnect3d** [comment]
@cfreal so u want additional filtering by user/uid? sure, why not

**Comment by disconnect3d** [comment]
@cfreal Your ask was implemented in https://github.com/pwndbg/pwndbg/pull/2371 ;)

You can now do `attachp --user <uid|username> <procname or partial procname or 'some procname or arguments'>`

**Comment by disconnect3d** [comment]
And a `--retry` was added in https://github.com/pwndbg/pwndbg/pull/2372 so this is now completed.

**Comment by cfreal** [comment]
@disconnect3d Thanks. Will surely use this in the future :)
