### ISSUE TITLE
Search command bugs and deficiencies

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#232]
There are some weird cases about `search` command [all checked just on gdb with Python 3]:

1) "How can I use that?"
```
pwndbg> help search

Search memory for byte sequences, strings, pointers, and integer values

pwndbg> pwndbg search
ropper               ROP gadget search with ropper.
search               Search memory for byte sequences, strings, pointers, and integer values
pwndbg> search
usage: search [-h] [-t {byte,short,word,dword,qword,pointer,string,bytes}]
              [-1] [-2] [-4] [-8] [-p] [-x] [-s] [-e] [-w] [--save]
              [--no-save] [-n]
              value [mapping]
search: error: the following arguments are required: value
```
Probably `help search` and/or `pwndbg search` should show the usage as well?

2) The `-t <type>` is optional but I can't really specify `-t string`:
```
pwndbg> search -t string "aaa"
must be str, not bytes
'search': Search memory for byte sequences, strings, pointers, and integer values
```
It doesn't even work with `u'...'` or `unicode('...')`.

3) This probably should have better output:
```
pwndbg> search -t byte "a"
int() argument must be a string, a bytes-like object or a number, not 'NoneType'
'search': Search memory for byte sequences, strings, pointers, and integer values
```

4) I can do a bytes search which works with `u'...'` strings, not sure if that is intended:
```
pwndbg> search -t bytes u"/bin/ls"
warning: Unable to access 16000 bytes of target memory at 0x7ffff7a13507, halting search.
warning: Unable to access 16007 bytes of target memory at 0x7ffff7bda000, halting search.
pwndbg> search -t bytes "/bin/ls"
warning: Unable to access 16000 bytes of target memory at 0x7ffff7a13506, halting search.
warning: Unable to access 16006 bytes of target memory at 0x7ffff7bda000, halting search.
[stack]         0x7fffffffdc2f 0x736c2f6e69622f /* '/bin/ls' */
[stack]         0x7fffffffeff0 0x736c2f6e69622f /* '/bin/ls' */
```

5) The ugly `warning: Unable to access 16000 bytes of target memory at 0x7ffff7a13507, halting search.` - however this is actually a problem with gdb's `find` command and there is no good solution to disable this warning for now.
I will probably make a feature request to gdb to add a parameter/setting to disable warnings (e.g. `set warnings off`).

**Comment by zachriggle** [comment]
To address them in order:

1. Maybe.  That'd be nice :)
2. Added a pull request (#242)
3. Cannot reproduce, this works fine for me.
4. The `u"..."` format is not understood by GDB's parser, and I don't intend to require users to have valid Python-quoted strings (i.e. unquoted strings should work).  GDB's parser will strip the quotes, so we can't just do Python quote parsing via `eval` either.
5. I suppose that could work, to temporarily disable warnings.  The only real way to do this is to do weird hacks with `set logging off` and various command-line-driven logging hacks.

**Comment by disconnect3d** [comment]
Another two issues:

6. `-x` or `--hex` should be accepted only with `-s` or `--string`
The description for `-x`/`--hex` states it is for "bytes/strings", so someone might get suggested that if he/she wants to search for 1-byte integer he/she has to write it like `search -1 -x ff` and this doesn't work - `search -1 255` or `search -1 0xff` does. 

7. Search can boom in some circumstances:
```
[dc@dc:~]$ gdb /bin/ls
Defined pretty print function (pp) and libc (CDLL)
sLoaded 107 commands. Type pwndbg [filter] for a list.
Reading symbols from /bin/ls...(no debugging symbols found)...done.
pwndbg> set context-sections ''
Set which context sections are displayed by default (also controls order) to ''
pwndbg> entry
Temporary breakpoint 1 at 0x404030

Temporary breakpoint 1, 0x0000000000404030 in ?? ()
Breakpoint *0x404030
pwndbg> search -s -x ff
# TONS OF OUTPUT
<class 'gdb.MemoryError'> Cannot access memory at address 0xffffffffc40961e1
```

8. It might be good to either have a command `examples <command>` or just have an examples section in each command's help.

**Comment by disconnect3d** [comment]
Closing in favor of https://github.com/pwndbg/pwndbg/issues/232
