### ISSUE TITLE
.deb install: "Cannot convert between character sets `UTF-32` and `UTF-8`"

### ISSUE THREAD

**Issue by zupd** [pwndbg/pwndbg#2323]
After installing the newest deb package from 2024-02 I get this message when starting pwndbg: "Cannot convert between character sets `UTF-32` and `UTF-8`". 
It seems like it is only a warning, and I can still use pwndbg as usual.

**Comment by zupd** [comment]
I think I tagged it wrong, because I first wanted to ask if a new .deb release could be released soon. But This issue should be tagged with bug

**Comment by disconnect3d** [comment]
Yes, thanks, it is a bug. We need to create a new release that would fix this utf-* issue on Ubuntu 24.04.

**Comment by disconnect3d** [comment]
Additionally, we need to start testing the release build on CI.

**Comment by disconnect3d** [comment]
Fixed in https://github.com/pwndbg/pwndbg/pull/2355 , release soon (max few days)
