### ISSUE TITLE
Do not eat stack traces

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#235]
We should not eat all exceptions anywhere.

Any time a generic exception is raised, the full backtrace should be printed.

This may impact usability, but greatly increases the ability to fix bugs.

We should **additionally** print a user-friendly error message, but all `except Exception`-style handlers should always end with `raise`.

**Comment by disconnect3d** [comment]
This issue is connected to https://github.com/pwndbg/pwndbg/issues/217

**Comment by disconnect3d** [comment]
Closing as this is more or less covered by https://github.com/pwndbg/pwndbg/pull/300 or to be more specific:
https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/exception.py#L42-L68
