### ISSUE TITLE
IDA connect failed

### ISSUE THREAD

**Issue by Bluekezhou** [pwndbg/pwndbg#236]
I tried to set a rpc server with host address 0.0.0.0
![image](https://cloud.githubusercontent.com/assets/7897423/25281721/c92ea5ae-26e0-11e7-8915-b5eb2a98f499.png)
but something went wrong when it set breakpoints 
![image](https://cloud.githubusercontent.com/assets/7897423/25281794/061e48b6-26e1-11e7-9906-b49a2ff817fd.png)

**Comment by disconnect3d** [comment]
Can't reproduce.

Can you provide some more information about your setup and prepare a small code or binary that causes the issue?

**Comment by Bluekezhou** [comment]
ok, below is the binary file, and there is not any other config.
[test.txt](https://github.com/pwndbg/pwndbg/files/947605/test.txt)
I am not allowed to upload the binary file directly, so I changed its appendix to txt

**Comment by disconnect3d** [comment]
I still cannot reproduce - setting multiple breakpoints for that binary works for me (with and without rebased program in IDA, however probably not the same as you had, because I can't get the exact same addresses).

Maybe you are not using the latest pwndbg version?
If you would like to check this issue together e.g. through teamviewer, catch me at freenode irc.

**Comment by Bluekezhou** [comment]
I'm using GNU gdb (Debian 7.12-6) 7.12.0.20161007-git, IDA 6.8 and Kali2.0.
I try to listen on a specific address (vmware virtual gateway ip for kali2.0), it works fine.
But when I try using 0.0.0.0, it breaks down.
And I didn't run any other script or set any breakpoint.

**Comment by Bluekezhou** [comment]
and I didn't run any other script or add any breakpoint

**Comment by zachriggle** [comment]
Correct, you can't use 0.0.0.0, since one cannot connect to 0.0.0.0.


*Zach Riggle*

**Comment by zachriggle** [comment]
Correct, you can't use `0.0.0.0`, since one cannot connect to `0.0.0.0`.  I think you misunderstand how IP addresses work, and the use of `0.0.0.0`.
