### ISSUE TITLE
 xinfo fails on remote qemu

### ISSUE THREAD

**Issue by OBarronCS** [pwndbg/pwndbg#2365]
Using the `xinfo` command while debugging a qemu process causes a crash. While determining information on the page in memory, it attempts to read a file which does not exist on the local machine.

![image](https://github.com/user-attachments/assets/b7b3aa56-d4d4-44af-8447-02f8380e1819)

To reproduce, connect to qemu and use `xinfo` on any address.

**Comment by disconnect3d** [comment]
(Can this be somehow related to the removed assert in get_file?)

**Comment by disconnect3d** [comment]
Fixed by https://github.com/pwndbg/pwndbg/pull/2386 thx to @OBarronCS
