### ISSUE TITLE
VMMAP problems on remote

### ISSUE THREAD

**Issue by OBarronCS** [pwndbg/pwndbg#2385]
This issue details some issues and potential fixes to problems with detection of memory mappings when debugging a remote QEMU process.

QEMU 8.1 added support for `info proc mappings`, returning a list of memory regions, which Pwndbg uses:

https://github.com/pwndbg/pwndbg/blob/d59ae31360bec1de672008178be310a61438b60e/pwndbg/gdblib/vmmap.py#L112-L114

However, memory permissions on `vmmap` don't line up with those sent by the `info proc mappings` command. 

![image](https://github.com/user-attachments/assets/dfe677b6-cef4-4d61-941a-98f94dd945a7)

This is because our call to `info_proc_maps` has `parse_flags=False` as a default parameter. avoiding a codepath that reads the page permissions.  Additionally, the code that parses the string output of info proc mappings assumes that everything in the `objfile` column has text, which is not True for qemu, and needs to be updated.

https://github.com/pwndbg/pwndbg/blob/d59ae31360bec1de672008178be310a61438b60e/pwndbg/gdblib/vmmap.py#L437

On local processes, we use another, more accurate method https://github.com/pwndbg/pwndbg/blob/d59ae31360bec1de672008178be310a61438b60e/pwndbg/gdblib/vmmap.py#L466

Another consideration is that I've found that `info proc mappings` misses some mappings when debugging remote processes. The current code will assume that the mappings are complete, and return immediately.

https://github.com/pwndbg/pwndbg/blob/d59ae31360bec1de672008178be310a61438b60e/pwndbg/gdblib/vmmap.py#L123-L130

This means that manually "explored" pages never get returned on a call to vmmap.get. Whenever a pointer is telescoped in various parts of the codebase, it will call `explore()` with the address, adding it to a global list of explored pages:

https://github.com/pwndbg/pwndbg/blob/d59ae31360bec1de672008178be310a61438b60e/pwndbg/gdblib/vmmap.py#L266-L272

These pages are never combined with the `info_proc_mappings`, however. This causes us to not return them in vmmap, and also to continously re-explore them, since we don't remember that we've seen them before.

These lines (at the bottom of get()) could be combined with the output of the proc mappings, to properly get both our explored pages and the ones provided by `info proc mappings`.

https://github.com/pwndbg/pwndbg/blob/d59ae31360bec1de672008178be310a61438b60e/pwndbg/gdblib/vmmap.py#L183-L186

Finally, whenever we explore a new page we need to clear the cache of vmmap.get so it includes pages that have been explored in the current step.
https://github.com/pwndbg/pwndbg/blob/d59ae31360bec1de672008178be310a61438b60e/pwndbg/gdblib/vmmap.py#L122-L123

**Comment by OBarronCS** [comment]
The note above about `info proc mappings` not showing all the pages might be incorrect. While fixing this bug, I found that our parser for `info proc mappings` would sometimes fail to parse a line in the output, resulting in the page not showing up in our vmmap.

**Comment by disconnect3d** [comment]
Fixed by https://github.com/pwndbg/pwndbg/pull/2386 thx to @OBarronCS
