### ISSUE TITLE
Remove or document MemoryAllocator.breakpoint

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#2404]
https://github.com/pwndbg/pwndbg/blob/26ba400dbdeafa09fce1f77fb93d9940d7db00ba/pwndbg/gdblib/heap/heap.py#L11-L20

As in https://github.com/pwndbg/pwndbg/pull/2382#discussion_r1733653835 : is it sth we need? Seems like sth to be removed.

cc: @CptGibbon

**Comment by CptGibbon** [comment]
Not sure about the origin of this, I assume someone wanted an easy way to breakpoint common memory allocator operations 🤷‍♂️

**Comment by disconnect3d** [comment]
Let's just remove this. PRs welcome if someone wants to help :)

**Comment by disconnect3d** [comment]
Done in https://github.com/pwndbg/pwndbg/pull/2433 ; the class can be further refactored in the future
