### ISSUE TITLE
Heap tcache command doesn't produce proper display

### ISSUE THREAD

**Issue by itaysnir** [pwndbg/pwndbg#2406]
### Description

Upon running the `tcache` command, an invalid representation of `pwndbg.dbg.gdb.GDBValue` is being displayed:

```bash
pwndbg> tcache
tcache is pointing to: 0x129f010 for thread 1
{
  counts = <pwndbg.dbg.gdb.GDBValue object at 0x7f893c3db210>,
  entries = <pwndbg.dbg.gdb.GDBValue object at 0x7f893c3db250>,
}
```

### Steps to reproduce

1. Run a binary
2. Issue `tcache`

### My setup

```bash
pwndbg> version
Gdb:      14.2
Python:   3.11.9 (main, Apr  2 2024, 08:25:04) [GCC 13.2.0]
Pwndbg:   2024.08.29 build: c2bf902
Capstone: 5.0.1280
Unicorn:  2.0.1
```

P.S.
I'm deeply sorry in case there's no actual bug here. I did some pwndbg code auditing, and it seems like `GDBValue` doesn't implements `__str__` nor `__repr__` (and so is its parent class), which may be the issue.

Debugging journal:
1. By debugging `CStruct2GDB.__str__()`, defined within `pwndbg/aglib/heap/structs.py` , it does seems like the problem is missing `__str__` and `__repr__` methods.

2. By reading `GDBValue.string()`, defined within `pwndbg/dbg/gdb.py`, I thought it would serve as a candidate to replace the above stated methods. However, it doesn't seem to return a valid string.

Solution to the bug (will open PR soon, in case this really is a bug):
I've added the following method for `GDBValue`, which fixed the issue (would probably need to implement the parent class's "pure virtual" method of raising an exception + adding `@override` decorator here):

```python
def __repr__(self):
    return self.inner.__repr__()

def __str__(self):
    return self.inner.__str__()
```

Indeed, now the output is displayed properly:
```bash
pwndbg> tcache
tcache is pointing to: 0x1227010 for thread 1
{
  counts = {0, 0, 0, 0, 0, 1, 0 <repeats 58 times>},
  entries = {0x0, 0x0, 0x0, 0x0, 0x0, 0x12272a0, 0x0 <repeats 58 times>},
}
```

**Comment by CptGibbon** [comment]
Probably worth speaking to @lebr0nli about this

**Comment by disconnect3d** [comment]
Fixed in @2408. Needs further refactoring, but yeah, its fixed already
