### ISSUE TITLE
./setup.sh:行 211:/usr/bin/python3.12:没有那个文件或目录

### ISSUE THREAD

**Issue by xiaofeng789** [pwndbg/pwndbg#2435]
![Uploading image.png…]()
![Uploading 屏幕截图 2024-09-16 220717.png…]()

**Comment by xiaofeng789** [comment]
![Uploading 屏幕截图 2024-09-16 215604.png…]()

**Comment by disconnect3d** [comment]
Hi, please fix your post since the images did not upload.
