### ISSUE TITLE
Use ArgparsedCommand for everything

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#244]
Using ArgparsedCommand means that we can generate documentation trivially, and that we also can have a standardized mechanism for parsing which is consistent with Python's own things.

It also gives us a nice place to hook looking up symbols and values, by using the `ArgumentParser.add_argument` keyword `type=`, which takes an arbitrary callable, and delivers the string argument, and blindly uses the return value.

We can add a `type=gdb_int` which takes plain integers *or* evaluates a GDB expression. Same for `type=address` or similar.  This avoids a lot of ad-hoc parsing and calls to `int()` on things.

**Comment by disconnect3d** [comment]
By the way, moving to `ArgparsedCommand` makes docstrings useless, e.g.:

```python
@pwndbg.commands.ArgparsedCommand(argparse.ArgumentParser(description='ASDASDASD'))
@pwndbg.commands.OnlyWithFile
def checksec(file=None):
    '''
    Prints out the binary security settings. Attempts to call the binjitsu
    checksec first, and then falls back to checksec.sh.
    '''
```

Pwndbg session:
```
pwndbg> help checksec
ASDASDASD
pwndbg> pwndbg checksec
checksec             ASDASDASD
pwndbg> 
```

**Comment by disconnect3d** [comment]
FWIW we have only two commands that DO NOT use ArgparsedCommand right now:
```
user@user:~/pwndbg$ rg commands.Command
pwndbg/commands/defcon.py
104:@pwndbg.commands.Command

pwndbg/commands/shell.py
84:    pwndbg.commands.Command(handler, False)
```

The first one in defcon.py will be removed in https://github.com/pwndbg/pwndbg/pull/1203

The second should be refactoreg to ArgparsedCommand.

Then, we can remove `commands/__init__.py:Command` class and merge whatever it does with `_ArpgarsedCommand` or `ArgparsedCommand`.

**Comment by gsingh93** [comment]
Assigned to @disconnect3d to close this and make a new issue for any remaining work.

**Comment by gsingh93** [comment]
ping 🙂

**Comment by disconnect3d** [comment]
Closing this issue as its really _stale_ at this point.

I have created https://github.com/pwndbg/pwndbg/issues/1822 and  https://github.com/pwndbg/pwndbg/issues/1820

(fyi @gsingh93)
