### ISSUE TITLE
Abolish print() in favor of stdlib logging

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#245]
Currently, we use `print()` in lots of places.  This makes it difficult to filter things by verbosity, and results in us disabling various print statements or hiding them behind ad-hoc `if debug` statements.  This will also allow us to get rid of some quantity of `print(M.red("Error message"))` statements in favor of e.g. `log.error`.

Using real logging is more flexible, and also allows us to be more verbose in our debug statements, which in turn means we can get better bug reports from users.

I suggest something similar to what `pwntools` currently does, by implementing an e.g. `pwndbg.log` module, with a `log = getLogger(__name__)` method call in each module, so that each module has its own `log` object.

**Comment by disconnect3d** [comment]
PR containing those changes should also add information to use stdlib logging instead of prints in [.github/CONTRIBUTING.md](.github/CONTRIBUTING.md)

**Comment by disconnect3d** [comment]
We do have ` pwndbg.log` as of now which we use here and there and we have `message.{error,info,warn}` for color purposes.

**Comment by disconnect3d** [comment]
Closing this for now. May re-introduce this issue or even just fix it in the future if we start to feel that we should completely remove `print()`.
