### ISSUE TITLE
Disasm window only shows few lines

### ISSUE THREAD

**Issue by LittleYe233** [pwndbg/pwndbg#2452]
Maybe it is a stupid question here, but I am really confused about how to adjust the number of shown lines of disasm window, without much information about the approach in the README and the Internet. I found that disasm filled the whole panel in many examples of this repo, but I failed to reproduce it even if using the same configuration.

Here is the screenshot of my pwndbg instance:
![image](https://github.com/user-attachments/assets/9401593f-e735-4758-93a1-bdb7f308516f)

And this is my configuration of gdb:
```
source /usr/share/pwndbg/gdbinit.py
source /home/littleye233/.local/opt/splitmind/gdbinit.py

contextoutput backtrace /dev/null true

set disassembly-flavor att

# Personal configuration of splitmind
python
import splitmind
(splitmind.Mind()
  .tell_splitter(show_titles=True)
  .tell_splitter(set_title='Main')
  .left(display="disasm", size="60%", banner="none")
  .show("code", on="disasm", banner="none")
  .above(of="disasm", display="regs", size="40%", banner="none")
  .right(of="regs", display="stack", banner="none")
  .show("legend", on="disasm")
).build()
end
```

- OS: Arch Linux with a full system update
- Version of pwndbg: From AUR (using the latest commit of this repo)
- Version of GDB: 15.1

Any reply will be highly appreciated.

**Comment by OBarronCS** [comment]
The configuration that changes this is `context-disasm-lines`, with 10 being the default.

For example:
```
set context-disasm-lines 30
```

We could add a note about this to the disassembly section of the FEATURES.md file https://github.com/pwndbg/pwndbg/blob/dev/FEATURES.md#disassembly

I often use tab-complete to get the config setting that I want to find - I guess that the setting is related to the context display, then I type `set context TAB TAB TAB` and see if any of the available options seem right.

**Comment by LittleYe233** [comment]
@OBarronCS Thank you very much. This command works for me! I just forgot to use TAB completion to `set context` so that I couldn't figure out. I think it is also good to note the users to find useful variables via a completion to `set` command.

**Comment by disconnect3d** [comment]
Hi, you can also search for stuff using:
* GDB's builtin search - the `apropos [<text>]` command
* Pwndbg configuration paremeters via: `config [<text>]`, `theme [<text>]` or `heap_config` commands
* Pwndbg's `pwndbg [<text>]` command to filter/search for available commands

If you have any suggestions or ideas how we can improve the UX or make it more clear how context is configurable, please let us know. This is also why we display some config values in registers and disasm banners:
```
[ REGISTERS / show-flags off / show-compact-regs off ]
[ DISASM / x86-64 / set emulate off ]
```

But this may still be not so obvious for newcommers that those are GDB parameters that can be configured via `set <param> <value>` or seen via `show <param> <value>` GDB commands.

When I think about it more, maybe we should display some `(see also: help context)` in the legend that is displayed just before the context?
```
LEGEND: STACK | HEAP | CODE | DATA | WX | RODATA (see `help context`)
```

And then describe context configuration in `help context`? Would it be more clear? Would people use that?
