### ISSUE TITLE
release issue: Mistakenly have .gz in place of .xz extension 

### ISSUE THREAD

**Issue by tesuji** [pwndbg/pwndbg#2457]
Download https://github.com/pwndbg/pwndbg/releases/download/2024.08.29/pwndbg_2024.08.29_amd64-portable.tar.gz
on the release tags, I try to use gunzip but it errors that it isn't a gzip file.

**Comment by disconnect3d** [comment]
cc: @patryk4815 hmm... seems like maybe nix build issue?:)

**Comment by patryk4815** [comment]
🅰️

**Comment by patryk4815** [comment]
https://github.com/pwndbg/pwndbg/blob/dev/nix/bundle/pkg.nix#L68 
https://github.com/pwndbg/pwndbg/blob/dev/nix/bundle/pkg.nix#L63
^ yep it is mistake in filename

**Comment by disconnect3d** [comment]
@patryk4815 pls send a PR fixing this :)

**Comment by disconnect3d** [comment]
Fixed in #2471
