### ISSUE TITLE
wrong annotation of instructions with segment registers

### ISSUE THREAD

**Issue by k4lizen** [pwndbg/pwndbg#2463]
### Description
![image](https://github.com/user-attachments/assets/f0fd2cd5-58bd-40af-9995-c7567f1f202d)
```bash
pwndbg> p/x $fs_base
$6 = 0x7ffff7ff5700
pwndbg> x/gx 0x7ffff7ff5700
0x7ffff7ff5700:	0x00007ffff7ff5700
pwndbg> p/x $rbp
$7 = 0xffffffffffffffc0
pwndbg> p/x $fs_base + $rbp
$8 = 0x7ffff7ff56c0
pwndbg> x/gx 0x7ffff7ff56c0
0x7ffff7ff56c0:	0x0000000000000000
pwndbg> 
```
The `mov    rbx, qword ptr fs:[rbp]` instruction puts the value at address `0x7ffff7ff56c0` into rbx, which is also obvious from the annotation of the test instruction (rbx is zero). However the annotation of the mov instruction itself implies that the `mov` puts the value of address `0x7ffff7ff5700` into rbx which is not what is happening, that is just the value of fs.

### Steps to reproduce

Should be simple to reproduce, possibly with stack canaries as well, I'll provide a more detailed guide later if it proves troublesome.

### My setup
Gdb:      15.1
Python:   3.12.6
Pwndbg:   2024.08.29 build: d6a39fc9
Capstone: 5.0.1280
Unicorn:  2.0.1

**Comment by OBarronCS** [comment]
Thanks for catching this - looked into it, and this error occurs when a memory address contains a segment register AND the offset address is a register.

Current code assumes both cannot be present in a memory operand:
https://github.com/pwndbg/pwndbg/blob/686e93e0d0a26efc5a9f6a295fadba83d08b3875/pwndbg/aglib/disasm/x86.py#L270-L283

I made a PR to fix this
