### ISSUE TITLE
Search by bytes doesn't work.

### ISSUE THREAD

**Issue by kerszl** [pwndbg/pwndbg#2475]
### Description

Some time ago, You fixed a bug where string-based search wasn't working. That was resolved, but now byte-based search isn't working...

### Steps to reproduce

doesn't work
```
pwndbg> search  -x 010233
Exception occurred: search: 'bytes' object has no attribute 'encode' (<class 'AttributeError'>)
For more info invoke `set exception-verbose on` and rerun the command
or debug it by yourself with `set exception-debugger on`
```

So... 
search by string works in version:
Pwndbg:   2024.08.29 build: d9681515

search by bytes works in version
Pwndbg:   2024.08.29 build: c2bf902e

### My setup

Gdb:      12.1
Python:   3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
Pwndbg:   2024.08.29 build: d9681515
Capstone: 5.0.1280
Unicorn:  2.1.0

**Comment by disconnect3d** [comment]
Ech. @mbrla0 any chance u can fix it and add tests for this? :x

**Comment by mbrla0** [comment]
On it

**Comment by disconnect3d** [comment]
@mbrla0 Thanks! <3

**Comment by kerszl** [comment]
Search stings and bytes works. Thanx!
