### ISSUE TITLE
Add a symbol lookup helper function to aglib

### ISSUE THREAD

**Issue by fidgetingbits** [pwndbg/pwndbg#2521]
As discussed in this [PR](https://github.com/pwndbg/pwndbg/pull/2515#issuecomment-2470625879) the current symbol lookup could be improved so we don't have to write: `pwndbg.dbg.selected_inferior().symbol_address_from_name("je_arena_emap_global")`

Similar to other helper functions in aglib for fetching pointer values and such, it should probably expose it's own `symbol_address_from_name()` that calls `pwndbg.dbg.selected_inferior()`.

@mbrla0 @disconnect3d

**Comment by disconnect3d** [comment]
For some reason GH doesn't allow me to assign @mbrla0 to this issue. I don't get it.

@mbrla0 Can u work on this? I think we should cache the selected inferior, so that we don't recall it bazillion of times. Also I don't think we will ever use a different or multiple inferiors to be honest... Maybe we should drop support for that, though, it doesn't hurt to have that...

**Comment by mbrla0** [comment]
> @mbrla0 Can u work on this?
 
 Yeah, I can.
 
 > I think we should cache the selected inferior, so that we don't recall it bazillion of times.
 
That's probably a good idea, though it's important to note that caching `selected_inferior` will not yield much in the way of performance gains. And depending on the speed of object creation vs. the extra function calls and dict lookup involved in caching, it might even yield a slight performance loss. Either way, though, performance probably won't change much between caching and not caching the current selected inferior.
 
> Also I don't think we will ever use a different or multiple inferiors to be honest... Maybe we should drop support for that, though, it doesn't hurt to have that...

Maybe having it as part of the public API isn't all that useful, but the LLDB implementation of the `dbg` interfaces does benefit from that distinction, at least internally.

**Comment by mbrla0** [comment]
Hm.. Maybe we can just mirror the `gdblib` API for `symbol`, too? Originally I decided against it because that'd be an extra level of indirection for really no benefit at all, so I took it out before #2382. But, if you think it's better, we can very easily reintroduce `pwndbg.aglib.symbol.get`.

**Comment by fidgetingbits** [comment]
If mirroring the functions in aglib is redundant then probably not worth (sorry not super familiar with the code still, so this will all be a bit hand wavy). I mostly think not having to call selected_inferior() each time and ideally not even having to know to grab an inferior and then doing inf.foo() everywhere would be more ergonomic. 

If feasible, that part could be abstracted away at least for the common case where selected_inferior() is assumed. Unless you know what you are doing and actually need to change the inferior, you shouldn't have to think about it. If someone is hacking on some heap code in aglib, just calling pwndbg.dbg.symbol_address_from_name("je_arena_emap_global") could expand under the hood to pwndbg.dbg.selected_inferior().symbol_address_from_name("je_arena_emap_global") or whatever.

**Comment by disconnect3d** [comment]
> Unless you know what you are doing and actually need to change the inferior, you shouldn't have to think about it.

+1 exactly this.

Fwiw the GDB inferior abstraction is likely not used at all by any other Python scripts out there because they had a bug for years when they didn't account for the selected inferior at all in memory reading and maybe other places?: https://sourceware.org/bugzilla/show_bug.cgi?id=30615

**Comment by patryk4815** [comment]
implemented new symbol api in https://github.com/pwndbg/pwndbg/pull/2605
