### ISSUE TITLE
Enable `pset` Command Before Binary Execution

### ISSUE THREAD

**Issue by patryk4815** [pwndbg/pwndbg#2523]
### Description: 
Currently, the `pset exception-debugger on` command only works after starting the binary. This limits flexibility, especially when setting configurations ahead of time is necessary, for instance, in automated debugging workflows or when specific debugging settings are needed right from the start.

### Proposed Solution
Enable the `pset` command to apply configurations, like exception-debugger on, before starting the binary. 
This would allow users to configure debugging parameters in advance, ensuring the setup is in place as soon as the binary begins executing.

![image](https://github.com/user-attachments/assets/87ee7e8c-00fa-4d86-86ff-a66a85647bcc)

**Comment by mbrla0** [comment]
We need to get rid of `pset`, actually. Implementing it in `pwndbg/dbg/lldb/repl/__init__.py` as a command override (like `process start` and such) instead is a lot better, because we can both have it work before the process is alive, and we can also just have it be called just `set`, like in GDB.

**Comment by disconnect3d** [comment]
Fwiw (thx @patryk4815 for image):
![image](https://github.com/user-attachments/assets/fc945e0c-fe39-4e76-88e6-87fbcc047d8a)

**Comment by mbrla0** [comment]
Yeah, `set` being an alias for `settings` is why we can't easily just override it using regular LLDB commands. We'll probably have to document that `set` in Pwndbg isn't the same as `set` in regular LLDB, and that one must spell out `settings` to use it. Maybe we can do that in the same way that we already do with `script`.

What could work is printing out `If you meant to use the LLDB command, type 'settings' instead` as a warning if the regular Pwndbg command fails.
