### ISSUE TITLE
Issues with terminfo in GitHub-Actions and portable pwndbg 

### ISSUE THREAD

**Issue by patryk4815** [pwndbg/pwndbg#2531]
The issue related to changes introduced in the PR [#2459](https://github.com/pwndbg/pwndbg/pull/2459) (related https://github.com/pwndbg/pwndbg/pull/2157). 
After running portable-pwndbg, the following warning appears:

```console
$ ./pwndbg/bin/pwndbg
Warning: _curses.error: setupterm: could not find terminfo database

Terminal features will not be available.  Consider setting TERM variable to your current terminal name (or xterm).
```
This error occurs because the terminfo database is missing.

Additionally, the `PWNLIB_NOTERM=1` environment variable is being used with lldbinit.py - https://github.com/pwndbg/pwndbg/blob/cd918e435a1107626c644f4842447ae7ba13ae96/lldbinit.py#L145

LLDB message:
```console
$ ./pwndbg/bin/pwndbg-lldb
Cannot read termcap database;
using dumb terminal settings.
pwndbg: loaded 95 pwndbg commands and 0 shell commands.
------- tip of the day (some of these don't work in LLDB yet!) (disable with set show-tips off) -------
Use the killall command to kill all specified threads (via their ids)
```

Repro:
```
>>> import curses
>>> curses.setupterm()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
_curses.error: setupterm: could not find terminfo database
```

**Comment by patryk4815** [comment]
Also found out that our Github Actions has this message:
<img width="1011" alt="image" src="https://github.com/user-attachments/assets/87c3f644-41cb-4344-8dda-34d65ab14635">

**Comment by patryk4815** [comment]
@peace-maker have you encountered similar problem on github-actions? maybe some env is missing?

**Comment by patryk4815** [comment]
<img width="677" alt="image" src="https://github.com/user-attachments/assets/720696d2-94a7-460c-822a-0621ae611700">

Looks like setting TERM=xyz fixed this warning

**Comment by peace-maker** [comment]
We do `TERM=linux` in CI, yes. There are no nix packages for pwntools though, so not sure about the terminfo missing.
https://github.com/Gallopsled/pwntools/blob/6f0793eebcf78eab4ac86bb8fcbb1ffee3e59fa6/.github/workflows/ci.yml#L176
