### ISSUE TITLE
Differences in aglib.regs vs gdblib.regs

### ISSUE THREAD

**Issue by patryk4815** [pwndbg/pwndbg#2538]
Introduced in PR https://github.com/pwndbg/pwndbg/pull/2478#issuecomment-2480839629

![image](https://github.com/user-attachments/assets/8d21de65-3ef7-44b0-8e7f-62de10fdcb6b)

**Comment by disconnect3d** [comment]
Considering that we now have `regs.by_name` which may return `None` when register do not exist, we can just check for it I believe.

<img width="588" alt="image" src="https://github.com/user-attachments/assets/1ebbe2cc-fba9-4305-b033-19c3a4ed4ad6">

**Comment by disconnect3d** [comment]
And the `get_register` returns the `regs.by_name`. Meaning: this should just work in aglib as-is so no porting is needed afaiu.

**Comment by disconnect3d** [comment]
Also:

![image](https://github.com/user-attachments/assets/a7ea9088-434a-49a7-b38f-5ca0b5c22994)

```py
In [16]: type(pwndbg.dbg.selected_frame().regs().by_name('x1'))
Out[16]: NoneType
```

(Thx @patryk4815 for checking it)
