### ISSUE TITLE
LLDB invalid return from symbol_address_from_name `__libc_start_main`

### ISSUE THREAD

**Issue by patryk4815** [pwndbg/pwndbg#2540]
Some symbols returns wrong value(?) in lldb:
```console
pwndbg-lldb> lldb
You are now entering LLDB mode. In this mode, certain commands may cause Pwndbg to break. Proceed with caution.
(lldb) script
Python Interactive Interpreter. To exit, type 'quit()', 'exit()' or Ctrl-D.
>>> import pwndbg.dbg
>>> pwndbg.dbg.selected_inferior().symbol_address_from_name("__libc_start_main")
18446744073709551615
>>> hex(pwndbg.dbg.selected_inferior().symbol_address_from_name("__libc_start_main"))
'0xffffffffffffffff'
>>> hex(pwndbg.dbg.selected_inferior().symbol_address_from_name("main"))
'0x401a00'
>>>
```

In gdb:
```console
pwndbg> pi
>>> pwndbg.dbg.selected_inferior().symbol_address_from_name("__libc_start_main")
4200144
>>> quit
```

**Comment by mbrla0** [comment]
Does LLDB even know what the address of `__libc_start_main` is?

![image](https://github.com/user-attachments/assets/bc610ff3-992f-4807-bafb-82aaf0b72edb)

**Comment by mbrla0** [comment]
Anyhow, we should add an extra check for `GetStartAddress` not having a value and return `None` in that case, too.

**Comment by patryk4815** [comment]
<img width="1037" alt="image" src="https://github.com/user-attachments/assets/5ceced79-fba1-4155-947b-f124a05d3da8">

<img width="438" alt="image" src="https://github.com/user-attachments/assets/d88b4c43-ff59-441e-9c49-3c12a04217c5">

<img width="626" alt="image" src="https://github.com/user-attachments/assets/f55fdbeb-c902-41e1-8b60-38b010a9f21b">

**Comment by patryk4815** [comment]
fixed in https://github.com/pwndbg/pwndbg/pull/2605
