### ISSUE TITLE
Improve pwndbg.config

### ISSUE THREAD

**Issue by patryk4815** [pwndbg/pwndbg#2549]
In few places/tests we have eg.:
```
pwndbg.config.hexdump_group_width = -1
```
Documentation mention directly setting value:
https://github.com/pwndbg/pwndbg/blob/0caf175699a1d2f627512d3dbe46674611cc181e/DEVELOPING.md?plain=1#L92

But it is invalid usage, it should be probably `pwndbg.config.hexdump_group_width.value = -1`
It is a bit confusing because then we compare this value `pwndbg.config.hexdump_group_width == 1337`  (without `.value` attribute)

Can we somehow prevent usage like `pwndbg.config.hexdump_group_width = -1` and raise error?

**Comment by disconnect3d** [comment]
I believe this is a bug. We can override `__setattr__` to fix this?

**Comment by disconnect3d** [comment]
Just to be clear. We can implement `pwndbg.lib.Config.__setattr__` to either block the `config.<attr> = <value>` or to dispatch it to `self.params[attr] = value`. 

However, it is worth to mention that we can probably do nothing at runtime against bugs like this:

```py
param = config.param
param = 123
```

 Though we could probably check this via some SAST like Semgrep or CodeQL?
