### ISSUE TITLE
dt is broken

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#255]
:(

EDIT: see last post in this issue

**Comment by semihalf-oleksy-michalina** [comment]
Hello,
Can you provide some example where it doesn't work and all the examples and options you wish to implement in this command? I'm not sure if I assume it's purpose correctly.
It would be nice if you could provide more info than it is in help as I don't have windbg.

I've changed a little three places and now when I have a structure like this:

```C
typedef struct str_type {
	int num;
	char letter;
	int* ptr;
}str_type;

```

`dt str_type` prints:

```
pwndbg> dt str_type 
str_type
    +0x0000 num                  : int
    +0x0004 letter               : char
    +0x0008 ptr                  : int *
```

But I assume that it's not everything you'd like to achieve?

**Comment by disconnect3d** [comment]
@semihalf-oleksy-michalina Can you post a PR with your changes so we can try it out?
Also could you change the command to use `ArgparsedCommand` decorator like some of the other commands? Eventually we want all of the command to use it and remove `Command` or `ParsedCommand` decorators at all (and to provide better UX thanks to one, consistent interface, later on - see https://github.com/pwndbg/pwndbg/issues/244).

**Comment by disconnect3d** [comment]
@zachriggle Is the purpose of `dt` just describe particular type layout?
If so, we will have to show the padding to the user as well.

Also it might be good to check pahole and pahole-gdb projects/outputs - e.g. https://github.com/PhilArmstrong/pahole-gdb
However I feel like we should display padding by just saying `X bytes of padding`.

It might also be cool to describe what padding is in the `ArgparsedCommand` description and also have a `short_description` (if there is such a thing for ArgparsedCommands).

**Comment by zachriggle** [comment]
`dt` is intended to emulate [Windbg's command of the same name](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/dt--display-type-) -- currently only the very basic functionality of "display type" and "display type at address" are supported.

The current implementation, and the implementation used by Windbg, does not explicitly call out gaps / holes / padding.

If we'd like to add additional functionality, I'm all for it, but it should have a different command name if the functionality isn't present in Windbg.

**Comment by disconnect3d** [comment]
Btw https://sourceware.org/ml/gdb-patches/2017-11/msg00435.html
Still our approach is probably better as we support older gdb versions.

**Comment by disconnect3d** [comment]
One can use GDB's native command: `ptype /o <cmd>` now. Shall we make `dt` an alias to it?

Also, `dt` works now but it will crash not-nicely when one provides an argument to it which is not a type that exists in any header. Perhaps we could improve that particular flow?
