### ISSUE TITLE
module 'capstone' has no attribute 'arm64_const'. Did you mean: 'arm_const

### ISSUE THREAD

**Issue by Yuchuwa** [pwndbg/pwndbg#2572]
I have success install the .deb file for linux kali, but when i use the pwndbg get an error:
module 'capstone' has no attribute 'arm64_const'. Did you mean: 'arm_const
this is the screenshot

<img width="768" alt="无标题" src="https://github.com/user-attachments/assets/66de2047-1403-47b7-81a0-d2e8827f0d0f">

who can explain why?

**Comment by Yuchuwa** [comment]
i sloved this bug by intstall capstone==5.0.3 myself.

**Comment by patryk4815** [comment]
@Yuchuwa  Can you show result of:
```
$ pwndbg
pwndbg> pi
>>> import capstone
>>> print(capstone.__file__)
// result
>>> import sys
>>> print(sys.path)
// result
```

**Comment by patryk4815** [comment]
Please check if, solve issue: (it was fixed in https://github.com/pwndbg/pwndbg/pull/2532 )
```
export PYTHONNOUSERSITE=1
pwndbg
```

**Comment by disconnect3d** [comment]
Yeah, this bug was already fixed, but the fix is applied only on the dev branch. I think it didn't get a release yet.

**Comment by disconnect3d** [comment]
I'm going to close this for now since it has been fixed. I wanted to wait with a new release until the LLDB port gets mature enough, but given some bugs we fixed on the GDB side of things maybe we should make a gdb-only release shortly? Or release both saying that LLDB is still under dev? idk.

**Comment by patryk4815** [comment]
We could backport some fixes to old release
