### ISSUE TITLE
an err in aarcg64

### ISSUE THREAD

**Issue by jelasin** [pwndbg/pwndbg#2574]
### Description
![图片](https://github.com/user-attachments/assets/c00bea18-76db-4bcd-9c28-c80460c40547)

**Comment by patryk4815** [comment]
probably same as here; https://github.com/pwndbg/pwndbg/issues/2548
workaround, disable emulation:
`set emulate off`

**Comment by jelasin** [comment]
got it, thanks












今日店休.
***@***.***






---Original---
From: ***@***.***&gt;
Date: Tue, Nov 26, 2024 18:09 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [pwndbg/pwndbg] an err in aarcg64 (Issue #2574)




 
probably same as here; #2548
 workaround, disable emulation:
 set emulate off

**Comment by disconnect3d** [comment]
Closing this in favor of #2548. Thanks @patryk4815 for mentioning the workaround!
