### ISSUE TITLE
Writing to stdout means that other commands can't access the output of pwndbg commands

### ISSUE THREAD

**Issue by theblazehen** [pwndbg/pwndbg#258]
For example, I'd like to have a view of `context` available with https://github.com/snare/voltron, but using `voltron view command "context"` just ends up displaying it in the main gdb window, and voltron not showing anything

**Comment by zachriggle** [comment]
I'm not sure how you'd suggest to fix this.  If they'd like the output, the functions can be invoked directly.

**Comment by zachriggle** [comment]
Ping! If you could provide more information on the way that `voltron` captures output, we may be able to resolve this.

**Comment by zachriggle** [comment]
Do you have any more info @theblazehen?

**Comment by theblazehen** [comment]
Hi, sorry about the delay. I'll need to look into that

**Comment by gsingh93** [comment]
Closing, needs more info.
