### ISSUE TITLE
gdbpwn feature parity

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#259]
- [ ] libc : Print the base address of libc
- [ ] ld : Print the base address of ld
- [ ] codebase : Print the base of code segment
- [ ] heap : Print the base of heap
- [x] got : Print the Global Offset Table infomation
- [ ] dyn : Print the Dynamic section infomation
- [ ] findcall : Find some function call
- [ ] bcall : Set the breakpoint at some function call
- [ ] tls : Print the thread local storage address
- [ ] at : Attach by process name
- [ ] findsyscall : Find the syscall
- [ ] fmtarg : Calculate the index of format string
  - You need to stop on printf which has vulnerability.
- [ ] force : Calculate the nb in the house of force.
- [ ] heapinfo : Print some infomation of heap
- [ ] chunkinfo: Print the infomation of chunk (Address of victim)
- [ ] chunkptr : Print the infomation of chunk (Address of user ptr)
- [ ] mergeinfo : Print the infomation of merge (Address of victim)
- [ ] printfastbin : Print some infomation of fastbin
- [ ] tracemalloc on : Trace the malloc and free and detect some error .
  - You need to run the process first than tracemalloc on, it will record all of the malloc and free.
  - You can set the DEBUG in pwngdb.py , than it will print all of the malloc and free infomation such as the screeshot.
- [ ] parseheap : Parse heap layout

**Comment by disconnect3d** [comment]
Just leaving link here: https://github.com/scwuaptx/Pwngdb

**Comment by 0xddaa** [comment]
I have refactored some [features](https://github.com/0xddaa/Pwngdb/tree/master/pwndbg) in **Pwngdb** with pwndbg feature, but I have some questions:
1. Will you keep the module name as **pwndbg** or rename to **gdbpwn**(as title of this issue)?
2. The `heap` feature will conflict with the original `heap` command. Maybe we can rename all features about printing base to regular names.

**Comment by zachriggle** [comment]
There's no need for them to be in a named sub module like that. Just
integrate them as normal commands ❤️

**Comment by zachriggle** [comment]
Nevermind, you did `pwndbg.commands.gdbpwn`, I thought it was under `pwndbg.gdbpwn.commands`

**Comment by zachriggle** [comment]
Or if you really want, have it be pwndbg.commands.gdbpwn


*Zach Riggle*

**Comment by degrigis** [comment]
`got` implemented :+1:

**Comment by P4N74** [comment]
https://github.com/scwuaptx/Pwngdb/pull/20
Something similar in `pwndbg` would also be great. I tried to give a quick look at the code but I couldn't figure out where I should add those commands, hence mentioning it here in the issue.

**Comment by lonnywong** [comment]
I want the layout of parseheap

**Comment by disconnect3d** [comment]
Closing as this is obsolete. Some of these has been implemented one way or another (e.g. `$rebase` or `$base` functions, glibc heap commands or tracking heap).

If anyone finds any feature they want to be implemented, please open a GitHub issue describing a feature request, or, send a pull request implementing the feature.
