### ISSUE TITLE
Release pwndbg_2024.08.29_arm64-portable.tar.gz is actually XZ compressed

### ISSUE THREAD

**Issue by koalajoe23** [pwndbg/pwndbg#2597]
### Description

I am about to setup standalone pwndbg. Downloading the release from GitHub and `tar xvzf 
pwndbg_2024.08.29_arm64-portable.tar.gz ` fails with

```
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

Using `file` I saw it is actually `XZ compressed data`.

Thus the file extension should be .tar.xz

### Steps to reproduce

see above

### My setup

N/A

**Comment by patryk4815** [comment]
Yes file extension will be fixed in next release. Don't know if we can change filename in release page :/
https://github.com/pwndbg/pwndbg/issues/2457

**Comment by koalajoe23** [comment]
looks like it was already changed. Thanks!

Didn't see the already present issue, sorry.
