### ISSUE TITLE
Windbg Aliases / Feature Parity

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#26]
Needs more Windbg.
- Dot-prefixed aliases are not possible.
  - [x] .attach (`attach is builtin)
  - [x] .detach (`detach` is builtin)
  - [x] .restart (`restart` is builtin)
  - [x] .echo (`echo` is builtin)
  - [ ] .holdmem
  - [x] .frame (`frame` is builtin)
- Bang-prefixed aliases are not possible.
  - [x] !peb (implemented as `peb`)
  - [ ] !avrf
  - [x] !address (implemented as `address`)
  - [x] !vprot (implemented as `vprot`)
- Tilde prefix is not possible
  - [x] ~
- [x] ln
- [x] lm
- [ ] ta
- [ ] tt
- [x] pc
- [x] tc (would trample `tcatch` command)
- [x] r (would trample `run` command)
- [x] c (would trample `continue` command)
- [ ] m
- [x] f (would trample `frame` command)

**Comment by gsingh93** [comment]
I'm inclined to close this issue, if anyone wants any more aliases we can just add them when they're requested. Unless there is something on this list that we know we want right now.

**Comment by disconnect3d** [comment]
* `tt` and `ta` are used for time travel debugging to execute instruction or all instructions until a certain address is hit
* m is just memmove
* holdmem compares memory ranges:
```
0: kd> .holdmem -a 0xfffff802`37200000 0xfffff802`37200100
Holding fffff802`37200000 - fffff802`37200100
0: kd> .holdmem -c 0xfffff802`37200000 0xfffff802`37200100
Comparing fffff802`37200000 - fffff802`37200100
    memory ranges match.
0: kd> .holdmem -c 0xfffff802`37200100 0xfffff802`37200200
Comparing fffff802`37200100 - fffff802`37200200
                                                         ^ Memory access error in '.holdmem -c 0xfffff802`37200100 0xfffff802`37200200'
```

I think we can close this for now. We may want to have some memory diffing, but I guess we can do it with `hexdump` or other command.
