### ISSUE TITLE
Cleanup our `LLDBValue` custom logic and replace it with `lldb.value`

### ISSUE THREAD

**Issue by patryk4815** [pwndbg/pwndbg#2603]
Todo:
- Cleanup our `LLDBValue` custom logic and replace it with `lldb.value`
- Probably we can replace `create_value` logic with just `lldb SetValueFromCString`?

Our class:
https://github.com/pwndbg/pwndbg/blob/029b36eb9ba2bf86ba61ee60f66c18ec646631bf/pwndbg/dbg/lldb/__init__.py#L402-L566

Replace some logic with this wrapper:
https://github.com/llvm/llvm-project/blob/14086ed75d165b827b20de0101324bd8467d93c4/lldb/scripts/Python/python-extensions.swig#L856-L941

**Comment by AdwaithaV** [comment]
Hi i would like t o work on this issiue could you assign

**Comment by Heisenberg-Vader** [comment]
Hey, I plan on fixing this issue. Can you assign it?

**Comment by disconnect3d** [comment]
No. We are not a company with tasks, OKRs or assignments. Just send a PR :)
