### ISSUE TITLE
vis_heap_chunk should show last line hexdump

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#2609]
TL;DR:
```
pwndbg> vis
(...)
0x5fd86347bfc0	0x00005fd86347bf60	0x0000000000000021	`.Gc._..!.......
0x5fd86347bfd0	0x4f676f6c00000004	0x7878244c46524556	....logOVERFL$xx
0x5fd86347bfe0	0x0000006224282824
You can try `set max-visualize-chunk-size 0x500` and re-run this command.
```

It should really show me the 8 bytes from the last line, or even full 16 ones?

**Comment by CptGibbon** [comment]
> It should really show me the 8 bytes from the last line, or even full 16 ones?

vis-heap-chunks` shows data chunk by chunk, so it won't show you the 8 bytes at the end there because they are part of a different chunk.

I agree that it's clearly missing the byte interpretation of those last 8 bytes it displays though.

**Comment by disconnect3d** [comment]
Fixed in https://github.com/pwndbg/pwndbg/pull/2620
