### ISSUE TITLE
auto update

### ISSUE THREAD

**Issue by guard-wait** [pwndbg/pwndbg#2633]
When I use it,I found that "Detected outdated Pwndbg dependencies (poetry.lock). Updating."Is this doing automatic updates?if it's,how can I disable it?Because sometimes offline work is required, it can be very bad if this pops up

**Comment by patryk4815** [comment]
update is only triggered when you do `git pull` or `git checkout`. And when you start pwndbg, then update will trigger.
For `git pull` you need internet

**Comment by patryk4815** [comment]
It can be disabled by using env: `PWNDBG_NO_AUTOUPDATE=1`
