### ISSUE TITLE
After a while all pwndbg commands stop working and every invocation fails with "not enough values to unpack"

### ISSUE THREAD

**Issue by pixlark** [pwndbg/pwndbg#2638]
### Description

I'm using pwndbg for a reverse-engineering course and after a while, seemingly with no consistent trigger, all pwndbg commands will stop working, and will always produce the error:

```
Python Exception <class 'ValueError'>: not enough values to unpack (expected 2, got 1)
Error occurred in Python: not enough values to unpack (expected 2, got 1)
```

normal GDB commands seem to work fine, but anything pwndbg-related fails with that error.

<details>
<summary>examples</summary>

![image](https://github.com/user-attachments/assets/238d8278-dbb6-4c77-9e45-c4e1023508ed)

![image](https://github.com/user-attachments/assets/8afc348e-d9a4-47c9-8001-2ad4ffc2994f)

</details>

### Steps to reproduce

I really am not sure. If someone wants I can provide the crackme binary I'm working on. Otherwise I have zero clue what could be triggering it, it seems to happen at random after having pwndbg running for long enough. I've seen it four or five times today over the span of a few hours, and each time the only solution has been to restart the entire debugging session.

### My setup

I'm on Arch, so everything is the latest version installed via pacman:

```
Gdb:      15.2
Python:   3.12.7 (main, Oct  1 2024, 11:15:50) [GCC 14.2.1 20240910]
Pwndbg:   2024.08.29
Capstone: 5.0.1280
Unicorn:  2.0.1
```

The comment on this issue template says "we are currently supporting only Ubuntu installations," but that seems to be contradicted by the README, so maybe that's out-of-date? Even if so, this does not seem like an OS-specific problem, it seems like there's some scripting error in the python somewhere. But if yall need to close the ticket because I'm not on ubuntu, I understand.

Anyways, let me know if there's other information I can give.

**Comment by patryk4815** [comment]
@pixlark Please set `set exception-verbose on`  it should show place where exception happen

**Comment by patryk4815** [comment]
> latest version installed via pacman

It seems that you have installed Pwndbg via pacman. Unfortunately, we do not support downstream distribution packages, as they often introduce bugs — such as installing incorrect dependency versions, which has been a recurring issue.

We highly recommend using one of the officially supported installation methods:
- `git clone https://github.com/pwndbg/pwndbg` followed by `./setup.sh`
-  Downloading the portable tarball, .deb, or **Archlinux** package from the [Releases page](https://github.com/pwndbg/pwndbg/releases)
- or `nix shell github:pwndbg/pwndbg#pwndbg`
For the best experience and reliability, please follow one of the methods above.

**Comment by pixlark** [comment]
that's a shame, but alright. I'll install it unpackaged and set that debugging variable, and if it happens again I'll update with exception details. Thanks!

**Comment by disconnect3d** [comment]
As @patryk4815 said, we don't maintain the Arch/aur package ourselves, so its best to use our own packages or the setup.sh script. Closing this for now, please reopen or open another issue if such installation produces any issues.
