### ISSUE TITLE
cannot use ctrl-L to clear screen in 2024.08.29 amd64 portable release

### ISSUE THREAD

**Issue by tesuji** [pwndbg/pwndbg#2651]
### Description

With system-installed gdb (from apt-get), I can use ctrl-L to clear the screen.
However, using `bin/pwndbg` from [pwndbg_2024.08.29_amd64-portable.tar.xz][1] I couldn't do that.

### Steps to reproduce

Download and install [1].
Load it by typing `bin/pwndbg /bin/cat`.
Generate some output: `disass main`
Try to clear the screen with ctrl-L.

### My setup

Gdb:      15.1
Python:   3.12.4 (main, Jun  6 2024, 18:26:44) [GCC 13.3.0]
Pwndbg:   2024.08.29
Capstone: 5.0.1280
Unicorn:  2.0.1

There is also `.inputrc` and `.gdbinit` but I don't think those files causing this problem
because with vanilla gdb, ctrl-L works.

[1]: https://github.com/pwndbg/pwndbg/releases/download/2024.08.29/pwndbg_2024.08.29_amd64-portable.tar.xz

**Comment by patryk4815** [comment]
```
$ /pwndbg/bin/pwndbg -tui
Cannot enable the TUI: error opening terminal [TERM=xterm-256color]
```
this is the problem

**Comment by patryk4815** [comment]
Issue was fixed in https://github.com/pwndbg/pwndbg/issues/2531 https://github.com/pwndbg/pwndbg/pull/2532
But not released yet.

For workaround you can execute:
```
export TERMINFO_DIRS=/etc/terminfo:/lib/terminfo:/usr/share/terminfo:/run/current-system/sw/share/terminfo
```

**Comment by disconnect3d** [comment]
I am going to close this issue for the time being as we have a workaround above. This being said, we should make a release shortly so that this is fixed in the released version (along with many many other fixes, improvements and new features).
