### ISSUE TITLE
rip relative addressing

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#269]
This is how we show instructions that use rip relative addressing in pwndbg:
```
 ► 0x400f58    mov    dword ptr [rip + 0x2033c2], 0x27
   0x400f62    mov    qword ptr [rip + 0x2033bb], 0x402ac8
```

And this is how it looks in IDA Pro:
```
.text:0000000000400F58                 mov     cs:dword_604324, 27h
.text:0000000000400F62                 mov     cs:qword_604328, offset unk_402AC8
```

The proper address is calculated as:
```
addr = rip + offset + instruction_size
```

So here it is:
```
0x604324 = 0x400f58 + 0x2033c2 + (0x400f62 - 0x400f58)
```

It would be nice to have a setting (or even default) to display absolute/calculated address.

**Comment by zachriggle** [comment]
I agree. The current view is just what Capstone gives us.

**Comment by disconnect3d** [comment]
A bit related: https://github.com/aquynh/capstone/issues/443

**Comment by disconnect3d** [comment]
I have added an issue to capstone: https://github.com/aquynh/capstone/issues/920

**Comment by disconnect3d** [comment]
This has been implemented in recent disasm emulation enhancement features by @OBarronCS . Thanks again for this!

Here it can be seen in action:
<img width="866" alt="image" src="https://github.com/pwndbg/pwndbg/assets/10009354/468c6b42-8a24-4179-939b-cc065a98a76e">

ran on version:
```
pwndbg> version
Gdb:      12.1
Python:   3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Pwndbg:   2024.02.14 build: e144da77
Capstone: 5.0.1280
Unicorn:  2.0.1
```
