### ISSUE TITLE
"set python print-stack"

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#271]
I'm not sure when this became a thing.  We should probably enable this when our debug setting is enabled.

> By default, GDB will print only the message component of a Python exception when an error occurs in a Python script. This can be controlled using set python print-stack: if full, then full Python stack printing is enabled; if none, then Python stack and message printing is disabled; if message, the default, only the message component of the error is printed.

**Comment by zachriggle** [comment]
Added this to #251

**Comment by disconnect3d** [comment]
Can be closed (?)
