### ISSUE TITLE
OnlyWhenRunning not working well with ArgparsedCommand

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#273]
```
[dc@dc:pwndbg|repeat-commands $]$ gdb /bin/ls -q
Loaded 106 commands. Type pwndbg [filter] for a list.
Reading symbols from /bin/ls...(no debugging symbols found)...done.
pwndbg> hexdump
usage: hexdump [-h] [address] [count]
hexdump: error: argument address: invalid fix_int value: '$sp'
```

The order of decorators doesn't fix it (even makes it worse).

**Comment by disconnect3d** [comment]
As we are going to use `ArgparsedCommand` for everything (see https://github.com/pwndbg/pwndbg/issues/244), maybe it is good to just add keyword arguments like `when_running`, `with_file`?

**Comment by zachriggle** [comment]
Hmm.  I think the issue here is the use of the `default` with a register value.  The current `hexdump` command is broken when being invoked from the interactive shell, anyway.

I suggest this workaround:

```patch
diff --git a/pwndbg/commands/hexdump.py b/pwndbg/commands/hexdump.py
index ed315f8..2ee8d52 100644
--- a/pwndbg/commands/hexdump.py
+++ b/pwndbg/commands/hexdump.py
@@ -25,3 +25,3 @@ pwndbg.config.Parameter('hexdump-bytes',
 parser = argparse.ArgumentParser(description='Hexdumps data at the specified address (or at $sp)')
-parser.add_argument('address', nargs='?', default='$sp',
+parser.add_argument('address', nargs='?', default=None,
                     help='Address to dump')
@@ -33,2 +33,4 @@ parser.add_argument('count', nargs='?', default=pwndbg.config.hexdump_bytes,
 def hexdump(address=None, count=pwndbg.config.hexdump_bytes):
+    if address is None:
+        address = pwndbg.regs.sp
```

**Comment by zachriggle** [comment]
Alternately we need some other way to specify `OnlyWhileRunning` for `ArgparsedCommand` objects, since `fix_int("$sp")` will blow up if the target isn't running -- but we can't block `fix_int` with `@OnlyWhileRunning` since that'd prevent other things (e.g. inspecting the file itself before runtime).

**Comment by disconnect3d** [comment]
Closing, this will be tracked in #1462
