### ISSUE TITLE
Checksec delay

### ISSUE THREAD

**Issue by degrigis** [pwndbg/pwndbg#281]
I've noticed a weird behavior related to the use of checksec: sometimes the check for the Fortified and Fortifiable takes a while ( I've not investigated yet the reasons ), this causes a lag in all the commands that use the checksec wrapper ( as f.i. the `got` command ).

Should we consider to embed the techniques used by the script inside pwndbg or starting to maintain our own version of the script in order to call what we need when we need it? ( f.i. if I need to check RELRO status it's not worth to execute all the checks and eventually extract the string we need )

**Comment by disconnect3d** [comment]
As I wrote in PR referenced above, I guess we should just cache the output.

A one-time lag is acceptable for me. However, this might be annoying for multiple pwndbg sessions over the same binary (not necessarily done in the same time).
For that, a persistent cache might help - we will have it soon in pwndbg - see https://github.com/pwndbg/pwndbg/pull/279. I'd go for a volatile one (this would use /tmp).
