### ISSUE TITLE
search instructions in memory (Feature request) 

### ISSUE THREAD

**Issue by techvoltage** [pwndbg/pwndbg#289]
Ollydbg allows searching for instructions(e.g. a syscall). Can a similar thing be done for pwndbg? I know there already is an searching by opcode feature but one can't be expected to manually assemble the instruction to an opcode and then search it in memory

**Comment by zachriggle** [comment]
This is a role much better fulfilled by [pwntools](http://pwntools.com) + pwndbg.  Pwndbg exposes the command-line API for pwntools, which has an assembly tool.  It's a two-step process (assemble, then copy) but I think having them separate gives the maximum flexibility.

```
$ gdb
Loaded 106 commands. Type pwndbg [filter] for a list.
pwndbg> asm nop
90
pwndbg> asm -c aarch64 nop
1f2003d5
pwndbg> asm syscall
0f05
pwndbg> asm sysenter
0f34
```

**Comment by techvoltage** [comment]
Yep that should do it. Thanks!
