### ISSUE TITLE
rr integration

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#294]
> rr aspires to be your primary debugging tool, replacing — well, enhancing — gdb. You record a failure once, then debug the recording, deterministically, as many times as you want. The same execution is replayed every time.

> rr also provides efficient reverse execution under gdb. Set breakpoints and data watchpoints and quickly reverse-execute to where they were hit.

> rr works on real applications such as Firefox, with low overhead. It is being used by many developers inside and outside Mozilla to fix real bugs.

http://rr-project.org/

**Comment by n30m1nd** [comment]
I use both, and they seem to work flawlessly except for the `heap` command. Funny enough the other commands such as `bins`, `fastbins` and the like work well.

**Comment by disconnect3d** [comment]
@n30m1nd Does it mean we can close this issue?
Mind showing us an https://asciinema.org/ screencast of running rr with pwndbg?

Is there anything we can do to improve rr experience?

**Comment by zachriggle** [comment]
Cool! I'd also love an Asciinema snippet.  If you wouldn't mind filing a separate bug for the `rr` issues with the `heap` command, it'd be much appreciated <3

Since `rr` seems to mostly work, closing this for now.

**Comment by n30m1nd** [comment]
Here's the asciinema:
[![asciicast](https://asciinema.org/a/TxTOMZnFGHD4uuKsXgiYixZ2U.png)](https://asciinema.org/a/TxTOMZnFGHD4uuKsXgiYixZ2U)
