### ISSUE TITLE
Telescoping confuses .rodata with .text

### ISSUE THREAD

**Issue by pyllyukko** [pwndbg/pwndbg#298]
### Description

When debugging a program, the telescoping feature incorrectly displays ```.rodata``` section as ```.text``` and tries to disassemble it.

Example:

![pwndbg-sections-1-2](https://user-images.githubusercontent.com/1058704/27254927-ba5af7a2-539b-11e7-9a4c-7691a7bc1785.png)

Data at address ```0x8048548``` is within ```.rodata``` section, as can be checked with the ```elfheaders``` command:

```
0x8048154 - 0x8048167  .interp
0x8048168 - 0x8048188  .note.ABI-tag
0x8048188 - 0x80481b4  .hash
0x80481b4 - 0x80481d4  .gnu.hash
0x80481d4 - 0x8048234  .dynsym
0x8048234 - 0x8048286  .dynstr
0x8048286 - 0x8048292  .gnu.version
0x8048294 - 0x80482b4  .gnu.version_r
0x80482b4 - 0x80482bc  .rel.dyn
0x80482bc - 0x80482d4  .rel.plt
0x80482d4 - 0x80482eb  .init
0x80482ec - 0x804832c  .plt
0x8048330 - 0x8048524  .text
0x8048524 - 0x804853e  .fini
0x8048540 - 0x8048592  .rodata
0x8048594 - 0x8048598  .eh_frame
0x8049f0c - 0x8049f14  .ctors
0x8049f14 - 0x8049f1c  .dtors
0x8049f1c - 0x8049f20  .jcr
0x8049f20 - 0x8049ff0  .dynamic
0x8049ff0 - 0x8049ff4  .got
0x8049ff4 - 0x804a00c  .got.plt
0x804a00c - 0x804a018  .data
0x804a018 - 0x804a01c  .bss
```
Yet pwndbg displays the address with red color (```CODE```) and disassembles it to ```dec ecx```, even though that address contains a string.

### Steps to reproduce

1. Start to debug e.g. [crackme0x02](https://github.com/radare/radare2book/blob/master/crackmes/ioli/IOLI-crackme.tar.gz)
2. Break somewhere in main
3. Wait until ```.rodata``` sections are references in ```printf```s etc.
4. Observe pwndbg telescoping into ```.rodata``` section and disassembling it

### My setup

| software | version |
| -------- | ------- |
| gdb      | 7.11.1  |
| Python   | 2.7.13  |
| pwndbg   | dae257c |

**Comment by zachriggle** [comment]
Will take a look at this soon, just wanted to say thanks very much for
using the template ❤️❤️❤️

**Comment by zachriggle** [comment]
That address is both readable and executable, Pwndbg is doing the correct thing

**Comment by pyllyukko** [comment]
> That address is both readable and executable, Pwndbg is doing the correct thing

It doesn't seem executable:

```
 [14]     0x8048540->0x8048592 at 0x00000540: .rodata ALLOC LOAD READONLY DATA HAS_CONTENTS
```

Same section info from radare:

```
idx=15 vaddr=0x08048540 paddr=0x00000540 sz=82 vsz=82 perm=--r-- name=.rodata
```

**Comment by zachriggle** [comment]
The page is marked executable, I promise.  Check `/proc/<pid>/maps`.

**Comment by disconnect3d** [comment]
Yup it is. See https://asciinema.org/a/9MixgFtQUfAm1QzgMhPTPtGGi

**Comment by pyllyukko** [comment]
Ok. My mistake. Thanks for the clarification.
