### ISSUE TITLE
External commands existence 

### ISSUE THREAD

**Issue by degrigis** [pwndbg/pwndbg#312]
As pointed out by @disconnect3d in the discussion of PR #280: we should probably register command name in some global set and check for its existence in the system after pwndbg is initialized. 
If it is not there warn the user and disable particular command.

**Comment by disconnect3d** [comment]
Thx for creating issue for that! Probably this could be handled in `ArgparsedCommand` itself - https://github.com/pwndbg/pwndbg/issues/244

**Comment by gsingh93** [comment]
I think we can close this, since we're moving all existing shell commands into built-in commands, and other shell commands can be run with the `!` syntax.
