### ISSUE TITLE
Restore default layout after any command

### ISSUE THREAD

**Issue by CaledoniaProject** [pwndbg/pwndbg#314]
I've successfully installed pwndbg, the default layout is awesome.

However, when I type any command, e.g `x/x $esp`, the default layout is gone.

How can I restore it? I've tried commands like `layout asm`, but it's not what I wanted ..

**Comment by disconnect3d** [comment]
@CaledoniaProject What do you mean that the layout is gone?

We call our UI a `context` and so there is a command called `context` which brings it up.

It should also be displayed each time a next instruction/code line is hit - basically whenever the debugger stops somewhere.

**Comment by CaledoniaProject** [comment]
Looks good, thanks
