### ISSUE TITLE
Disassemble whole function (without branch emulation)

### ISSUE THREAD

**Issue by bennofs** [pwndbg/pwndbg#315]
It would be nice if there was a way to just pretty-print assembly, without doing branch emulation. For example, right now I cannot use `nearpc` to show disas of main because it jumps immediately to `exit` since it thinks that some branch is not satisfied (this is because it does not emulate `call`s)

**Comment by disconnect3d** [comment]
Thanks for the issue!

Theoretically `set emulate off` should do the job.
However I feel like we probably should override `disass` to disassemble code without emulation...

@zachriggle What do you think about it?

Btw we have currently two commands that does the deassembly:
- `u`
- `nearpc`

It seems they does the same (I haven't look at the code) and the `nearpc-lines` parameter affects only `nearpc`. I believe `u` should be an alias for `nearpc`...

@bennofs Do you mind adding such a feature and potentially fix the mess with `u` and `nearpc` having different implementation?

**Comment by zachriggle** [comment]
@bennofs Can you provide a repro case?  Your issue sounds like an actual emulation failure.

**Comment by bennofs** [comment]
@zachriggle example:
```c
#include <stdio.h>
#include <stdlib.h>
int foo() {
  printf("hello world\n");
  return 3;
}

int main() {
  char* a;
  a = malloc(136);
  if(a == NULL) {
    printf("malloc failed\n");
    return 1;
  }
  foo();  
  return 0;
}
```

`emulate` gives:

```
pwndbg> emulate
 ► 0x5555555546ce <main+4>     sub    rsp, 0x10
   0x5555555546d2 <main+8>     mov    edi, 0x88
   0x5555555546d7 <main+13>    call   malloc@plt                    <0x5555555545a0>
 
   0x5555555546dc <main+18>    mov    qword ptr [rbp - 8], rax
   0x5555555546e0 <main+22>    cmp    qword ptr [rbp - 8], 0
   0x5555555546e5 <main+27>    jne    main+48                       <0x5555555546fa>
 
   0x5555555546e7 <main+29>    lea    rdi, [rip + 0xa6]
   0x5555555546ee <main+36>    call   puts@plt                      <0x555555554590>
 
   0x5555555546f3 <main+41>    mov    eax, 1
   0x5555555546f8 <main+46>    jmp    main+65                       <0x55555555470b>
    ↓
   0x55555555470b <main+65>    leave  
```

Note how it assumes that the call to malloc will fail and thus follows the "short path" (the call to foo is not at all visible in the disas)

**Comment by zachriggle** [comment]
Kind of.  It doesn't emulate call, *nor* does it emulate the conditional after it.

Disassembly is 100% linear until `main+46`, which is *guaranteed* to go to the `leave`.

This is slightly misleading, but very different from "assumes the call will fail" -- it doesn't, it just keeps disassembling linearly.  The case *happens to be* that linear disassembly follows the failure path.

In any case, you should be able to disable emulation via `set emulate off`.

**Comment by disconnect3d** [comment]
@zachriggle https://asciinema.org/a/CEl8tS982fP0w5YRhhwO2xw7U
Seems that `set emulate off` doesn't help. Guess that's a bug?

**Comment by zachriggle** [comment]
In your `asciinema` run, the disassembly output (specifically, the "next instruction" for each instruction) is cached.

Do `set emulate off` beforehand and it should work.  We should probably invalidate the cache when `emulate` is disabled.

**Comment by disconnect3d** [comment]
Just to clarify, invalidation of cache can be done by adding a trigger for emulate parameter.

This would look like:
```python
@pwndbg.config.Trigger([emulate])
def invalidate_instruction_cache():
    
```

Above should be done anyway. 

@zachriggle @anthraxx What do you guys think about adding a keyword argument like `dont_use_cache=True` which would be retrieved by `memoize` if passed into `__call__` and if it `True` then we can evaluate function instead of using cache?

This would let us either override gdb command like `disass` and so provide a `nearpc` without emulation or add a flag to `nearpc` which would not emulate (if the `emulate` parameter is `on`).

**Comment by zachriggle** [comment]
I think we can just use the `invalidate_instruction_cache` `Trigger` for now, if that solves the problem

**Comment by gsingh93** [comment]
This probably got fixed a while ago, `nearpc` now doesn't use emulation by default and the `emulate` command does.
