### ISSUE TITLE
wrong result with command checksec

### ISSUE THREAD

**Issue by Bluekezhou** [pwndbg/pwndbg#332]
This is result in pwndbg
```
pwndbg> checksec 
[!] Couldn't find relocations against PLT to get symbols
[*] '/root/\xe6\xa1\x8c\xe9\x9d\xa2/sentosa/sentosa'
    Arch:     amd64-64-little
    RELRO:    Full RELRO
    Stack:    No canary found
    NX:       NX enabled
    PIE:      PIE enabled
```
This is from IDA
![image](https://user-images.githubusercontent.com/7897423/29699510-de5a6a3c-898f-11e7-82d4-e5d5881d276f.png)

here is bin

[sentosa.zip](https://github.com/pwndbg/pwndbg/files/1250830/sentosa.zip)

**Comment by Bluekezhou** [comment]
pwndbg> version
Gdb: GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Python: 3.5.3 (default, Jan 19 2017, 14:11:04)  [GCC 6.3.0 20170118]
Pwndbg: 1.0.0 build: 124e997

**Comment by zachriggle** [comment]
The canary check relies on __stk_chk_fail (or something similar) being in
the symbols. Separately, checksec is not a Pwndbg implementation. It’s just
a wrapper around the command-line tool.

**Comment by zachriggle** [comment]
Original binary is here: https://github.com/briansp8210/CTF-writeup/blob/master/HITB-GSEC-CTF-2017/SENTOSA/sentosa

It looks like you have an old version of Pwntools or something, it looks fine to me.

```
$ pwn update
[*] You have the latest version of Pwntools (3.8.0)
$ pwn checksec /Users/riggle/Downloads/sentosa
[*] '/Users/riggle/Downloads/sentosa'
    Arch:     amd64-64-little
    RELRO:    Full RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      PIE enabled
    FORTIFY:  Enabled
```

**Comment by Bluekezhou** [comment]
Ok, I'll update it. Thank you.
