### ISSUE TITLE
Arch Support - Roadmap

### ISSUE THREAD

**Issue by klockeph** [pwndbg/pwndbg#340]
Hi,

pwndbg currently only supports Ubuntu and as stated in some other issues, help would be appreciated to make it compatible with other distros.

As I'm an arch user and pwndbg lover myself, I would like to contribute something to this - if I am able to.

The problem is, that I (and probably also other possible collaborators) don't know where to start. So I'm creating this issue to ask for a basic roadmap on what is needed for arch support (especially the heap stuff).

Could you provide a basic roadmap what issues exist?

**Comment by anthraxx** [comment]
Basic arch support itself is there, you can take a look at the pwndbg and pwndbg-git packages in the AUR.
The problem with Heap is the way how it is implemented right now. It loops through /usr/include and compiles everything. We have a separate issue somewhere, you could start over there?

**Comment by disconnect3d** [comment]
Someone pointed out somewhere (might have been @bennofs on IRC?) that it is possible to use heap when one has libc compiled with debug symbols.

@anthraxx I've reformatted your msg a bit; guess u write from the phone? ;p

**Comment by bennofs** [comment]
I am using pwndbg on arch without much problems. For `heap` support, you need a glibc with debug symbols which you can get by following the steps in https://wiki.archlinux.org/index.php/Arch_Build_System to build `glibc` yourself after enabling debug in `/etc/makepkg.conf`. The main issue that doesn't work well is the type detection that just tries to parse include files, but I am not sure how many features rely on that one?

**Comment by disconnect3d** [comment]
Maybe we should add a glibc-debug AUR package and add it as pwndbg and pwndbg-git dependency?

What do you guys think? I don't have any experience in AUR packaging.

**Comment by klockeph** [comment]
A follow-up question: I've manually set up pwndbg (with git clone, make etc.), can I somehow uninstall it and reinstall it from the AUR then if this improves arch support? I didn't want to install it from AUR because the last update was from 2016. 
(But maybe I misunderstood the last-update thing, and it's using the latest version, I'm not experienced with the AUR)

**Comment by klockeph** [comment]
@bennofs could you elaborate on your answer a little bit more? I think I understand how to enable debugging in `/etc/makepkg.conf` but not how to rebuild glibc myself.

**Comment by bennofs** [comment]
@KillPinguin 

Assuming you have enabled `DEBUG` in `/etc/makepkg.conf`, do the following steps:

###### for 64 bit glibc debug symbols:

```
$ svn checkout --depth=empty svn://svn.archlinux.org/core arch-core
$ cd arch-core
$ svn update glibc
$ cd glibc/repos/core-x86_64/
$ makepkg
# pacman -Q glibc-*.pkg.tar.xz
```

###### for 32 bit glibc debug symbols:
```
$ svn checkout --depth=empty svn://svn.archlinux.org/community arch-community
$ cd arch-community
$ svn update lib32-glibc
$ cd lib32-glibc/repos/multilib-x86_64/
$ makepkg
# pacman -Q lib32-glibc-*.pkg.tar.xz
```

You will need to rebuilt these when the glibc version in the official repository changes.

**Comment by zachriggle** [comment]
There are two official Arch packages:

https://aur.archlinux.org/packages/pwndbg/
https://aur.archlinux.org/packages/pwndbg-git/

My recommendation is to use the second package.

**Comment by klockeph** [comment]
@zachriggle thank you for your comment. But don't I have to remove the current installation before installing it from AUR?

**Comment by disconnect3d** [comment]
@KillPinguin `pwndbg` vs `pwndbg-git` packages? Probably AUR will tell you that they conflict and ask whether you want to remove `pwndbg` if you install `pwndbg-git`.

If you ask git clone+install vs AUR package then I think it doesn't really matter.
You just need proper path to the pwndbg you want to launch in `source ...` in `~/.gdbinit`.

**Comment by Aloxaf** [comment]
A simple way to make pwndbg work on Arch Linux based on @bennofs 's solution
```bash
svn checkout --depth=empty svn://svn.archlinux.org/packages
cd packages
svn update glibc

# Build glibc (Fix #340)
cd glibc/repos/core-x86_64
echo en_US.UTF-8 UTF-8 >>locale.gen.txt
## For Chinese users
## echo zh_CN.UTF-8 UTF-8 >>locale.gen.txt
## sed -i 's#sourceware.org/git/glibc.git#gitee.com/Aloxaf/glibc.git#' PKGBUILD
# generate detached debugging symbols
sed -i 's#!strip#debug#' PKGBUILD
makepkg --skipchecksums
sudo pacman -U *.pkg.tar.xz


# Build gdb (Fix #535)
# --DELETED, NOT GDB'S PROBLEM--
```

**Comment by disconnect3d** [comment]
@Aloxaf you mean to make pwndbg work with glibc/heap?

@anthraxx you might consider adding this to the distro packages.

**Comment by anthraxx** [comment]
i don't see what recompiling GDB in Arch would achieve, it already links to pthread. And for glibc we need to wait for debug symbol support (which is being worked on)

**Comment by Aloxaf** [comment]
@disconnect3d Yes. But it's not something new, I just renewed the way to get debug symbols.
@anthraxx You are right, I haven't noticed that  before and thought it was a problem with GDB. 
It's great to hear that debug symbol support is being worked on, rebuild glibc everytime it updates is really troublesome.

**Comment by Y7n05h** [comment]
Hi,
 I rebuild glibc and lib32-glibc with debug info in ArchLinux , but the heap command still has some bugs.
When I use heap command,I get the message:
```
In file included from /tmp/pwndbg/x86-64_struct-malloc_state.cc:54:
/usr/include/nc_tparm.h:39:10: fatal error: ncurses_cfg.h: No such file or directory
39 | #include <ncurses_cfg.h>
|          ^~~~~~~~~~~~~~~
compilation terminated.
Exception occurred: heap: No struct type named malloc_state. (<class 'gdb.error'>)
For more info invoke `set exception-verbose on` and rerun the command
or debug it by yourself with `set exception-debugger on`
```
Maybe rebuild glibc with debug info is not enough.

**Comment by Y7n05h** [comment]
Based On https://github.com/pwndbg/pwndbg/issues/340#issuecomment-431254792

ArchLinux User can rebuild glibc with debug Info in this way:
1. install asp and devtools `pacman -S asp devtools`
2. use asp checkout glibc `asp checkout glibc`
3. `cd glibc/repos/core-x86_64`
4. edit the `PKGBUILD` add `--enable-debug=yes` in `_configure_flags` and run `sed -i 's#!strip#debug#' PKGBUILD`
5. run `extra-x86_64-build` 
6. Now you success rebuild glibc and lib32-glibc with debug info. use  `pacman -U  *.pkg.tar.zst` install them.

**Comment by synap5e** [comment]
I was able to get this working by adding eschwartz's repository (unofficial repo, but arch trusted user)
`/etc/pacman.conf +a`
```
[eschwartz]
Server = https://pkgbuild.com/~eschwartz/repo/$arch
```

then just 
```
sudo pacman -Sy glibc-git-debug glibc-git
```

**Comment by gsingh93** [comment]
If there are any Arch Linux specific issues that come up in the future, we can make a new issue for it.
