### ISSUE TITLE
NCC Group Heap Inspection

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#342]
Cool stuff!  BSD 3-clause so compatible but not exactly MIT.

https://github.com/nccgroup/libdlmalloc

https://github.com/nccgroup/libptmalloc

https://github.com/nccgroup/libmempool (mempool = Cisco)

**Comment by disconnect3d** [comment]
We have our own ptmalloc2 (glibc) and jemalloc inspection features.
