### ISSUE TITLE
time for a new release tag?

### ISSUE THREAD

**Issue by anthraxx** [pwndbg/pwndbg#343]
@zachriggle @disconnect3d 

what do you think, maybe we should tag a new release? The last one is half a year old and we made a lot of fixes and some cool features :smile_cat:

**Comment by zachriggle** [comment]
@disconnect3d Could you take care of this?  Just check out `tag_release.sh` for what I used to do.  Not sure if it works anymore, now that we switched to `dev` / `beta` / `stable` branches.  Also I'm not sure if there are any open Pull Requests against `stable` that you'd like to land before tagging.

This might be something that we set up a repeating job for on each `stable` Travis CI job, with an `after_success` rule.  Pwntools has something similar with [`travis/update_demo.sh`](https://github.com/Gallopsled/pwntools/blob/dev/travis/update_demo.sh) which uses a secret environment variable with an SSH key loaded into it.

**Comment by disconnect3d** [comment]
@zachriggle Yeah I can do that.

**Comment by disconnect3d** [comment]
Huh, this was easier then I thought :P. Had to just modify the branch in `tag_release.sh` - will put that into PR to stable, but I have already made the tag:
 https://github.com/pwndbg/pwndbg/tree/2017.09.26

**Comment by zachriggle** [comment]
The script also needs to be modified to:

1. Check out `beta`
2. Merge `stable`
3. Check out `dev`
4. Merge `beta`
5. Push the branches
