### ISSUE TITLE
Freebins list gets truncated at the end

### ISSUE THREAD

**Issue by dipanjan** [pwndbg/pwndbg#352]
If the free bins list is too long, it is truncated at the end.

![issue](https://preview.ibb.co/c3qnBG/image.png)

**Comment by disconnect3d** [comment]
Can you provide C code that can be used to reproduce this issue?

Also does `fastbins` command truncate it too? Maybe `bins` returns just a general look over all the bins not to bloat the display (?).

**Comment by zachriggle** [comment]
It's not truncated, that's just how the telescope code works.  If there
were somehow a loop, or just a really long chain, it'd take up too much
screen space.


*Zach Riggle*

**Comment by dipanjan** [comment]
Can a new command be added that'll allow me to traverse the chain for `n` block starting from `i`-th block? I'd say such long chains are not uncommon in real world applications (this is an instrumented version of GNU diffutils)

**Comment by zachriggle** [comment]
Been busy for a while, sorry to leave this sit for a bit.  When the above pull request lands, you should be able to `set heap-dereference-limit 0x100` to get what you want.

**Comment by dipanjan** [comment]
Thanks @zachriggle
