### ISSUE TITLE
Android: Currently Broken

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#354]
Attempting to debug an Android 8.0 phone with GDB 8.0 (on macOS) causes GDB to abort.

**Comment by zachriggle** [comment]
It looks like at least part of this is due to `pwndbg.android.is_android()` not being cached, and eventually we will invoke `pwndbg.android.sysroot` to set the sysroot, which causes `is_android()` to return `False`.

**Comment by zachriggle** [comment]
Apparently the issue is `follow-fork-mode child`.

When a fork occurs, the following is printed to `stdout`:

```
Detaching from process <pid>
Aborted
```

**Comment by zachriggle** [comment]
May be related to https://sourceware.org/bugzilla/show_bug.cgi?id=13584

**Comment by gsingh93** [comment]
According to https://source.android.com/docs/core/tests/debug/gdb, GDB support is deprecated and will be removed soon (in favor of lldb), so maybe we should just close this.

**Comment by gsingh93** [comment]
Closing this, if anyone wants to debug Android they should use LLDB, which unfortunately we currently don't support.
