### ISSUE TITLE
Improve function docs

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#38]
At the very least, we could use `inspect` to print out things like the argument names when you run `help` on a command.

**Comment by zachriggle** [comment]
Another way to do this is to make each tool declare a full CLI via ArgParse.  This could help with some of the casting needs and help with docs.  A bit painful to backfill all the commands, though.  We get nice usage and a known-usable interface, too.

**Comment by gsingh93** [comment]
I'm fine with that. It's a lot of work, but we can do it bit by bit.

**Comment by zachriggle** [comment]
I've added support for this in 27b4a9a3140a0b6054bef6b25cec878b82feaf33.

Please confirm that the implementation works for what you want :)

**Comment by zachriggle** [comment]
Assuming this works for you, closing :)
