### ISSUE TITLE
update in glibc 2.26 which is called tcache not handled in arena, heap, bins commands

### ISSUE THREAD

**Issue by motazreda** [pwndbg/pwndbg#387]
Related:
* https://www.phoronix.com/scan.php?page=news_item&px=glibc-malloc-thread-cache

**Comment by mdebski** [comment]
Hi,

may I ask why did you close it? I believe this is a valid feature request. In fact I just started exploring on how this could be implemented.

**Comment by disconnect3d** [comment]
@mdebski idk, reopening!

**Comment by mdebski** [comment]
Added initial support in #420. It only works if program is compiled with -lpthread, as otherwise gdb cannot access thread-local variables. I don't know yet how tls works without pthread (tcache is still enabled), will look into this.

**Comment by motazreda** [comment]
@mdebski sorry for closing it, my bad maybe by mistake :), and really thanks for the implementation

but a small question, are you sure that it works if the code compiled with lpthread ?
to be honest, I am not sure but I think it works by default without adding -lpthread option.

**Comment by disconnect3d** [comment]
The tcache support has been added by @mdebski so I am closing it. Thanks!
