### ISSUE TITLE
Small refactoring: remove pwndbg.compat in favor of six.PY2/six.PY3

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#391]
There is no point of having `pwndbg.compat.python2`/`python3` when there is `six.PY2` and `six.PY3`.

So this task is just about refactoring, feel free to pick it if you want to contribute :).

**Comment by zachriggle** [comment]
If you can also include removing pwndbg.compat.basestring in the refactor
and kill compat.py entirely, this PR would be perfect <3


*Zach Riggle*
