### ISSUE TITLE
Heap features from gdb-heap

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#4]
Whatever they're doing: https://github.com/rogerhu/gdb-heap

**Comment by disconnect3d** [comment]
I believe we are not going to implement this and we have most of the features from there already implemented. Or even more.

Closing.

cc: @CptGibbon @lebr0nli  FYI / for visibility.

**Comment by CptGibbon** [comment]
@disconnect3d I think the only gdb-heap feature that's still unimplemented in pwndbg is the heap diff.
I suppose if anyone wants something like that in the future they could always open a feature request issue.
