### ISSUE TITLE
Context isn't showing the X29 register ( frame pointer ) while debugging aarch64 binary

### ISSUE THREAD

**Issue by bruce30262** [pwndbg/pwndbg#406]
As title, pwndbg isn't showing the x29 register while debugging the aarch64 binary:

<img width="360" alt="default" src="https://user-images.githubusercontent.com/4478350/35185097-9e96202a-fe39-11e7-8809-c54ee6ccd973.PNG">

if we use the `i r` command:
```
........
x27            0x0      0
x28            0x0      0
--- missing ---
x29            0x4141414141414141       4702111234474983745
--- missing ---
x30            0x4008c4 4196548
sp             0x7f326e57dce0   0x7f326e57dce0
pc             0x4008c4 0x4008c4
cpsr           0x60000000       1610612736
fpsr           0x0      0
fpcr           0x0      0
```

**Comment by disconnect3d** [comment]
@br0ns Hey, thx for reporting the issue and sry for so long reply.

All the regs are specified here:
https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/regs.py#L109-L110

So... for x29 and x30 we have to change `range(29)` to `range(31)`, for the rest, just add them?

Would you mind sending a PR that would fix that?

**Comment by zachriggle** [comment]
@bruce30262 see the above comment <-- @disconnect3d mentioned @br0ns by accident

I would prefer that the $FP register is hidden behind a setting similar to $EFLAGS and $LR register:

https://github.com/pwndbg/pwndbg/blob/869e8320e123f4fe2d039a31c12ee8c7be7a54d3/pwndbg/commands/context.py#L107-L108

**Comment by bruce30262** [comment]
@disconnect3d  in Aarch64 x30 = LR, which is already shown in the context, so we only have to show x29.  
However I'm not sure if I use 
```python
gpr     = tuple('x%i' % i for i in range(30)),
```
or use
```python
frame   = 'x29',                                                                                                                                                                
gpr     = tuple('x%i' % i for i in range(29)),
```
to show x29. I've tested both code and the result looks the same. I prefer the latter though.

@zachriggle According to line [114~117 in context.py](https://github.com/pwndbg/pwndbg/blob/869e8320e123f4fe2d039a31c12ee8c7be7a54d3/pwndbg/commands/context.py#L114) :

```python
if not regs and pwndbg.config.show_retaddr_reg:
    regs = pwndbg.regs.gpr + (pwndbg.regs.frame, pwndbg.regs.current.stack) + pwndbg.regs.retaddr + (pwndbg.regs.current.pc,)
elif not regs:
    regs = pwndbg.regs.gpr + (pwndbg.regs.frame, pwndbg.regs.current.stack, pwndbg.regs.current.pc)
```
The frame pointer register is always displayed in the context, so I think it's OK to always show the frame pointer register ?

BTW how do you display the code like this in markdown?
![ccc](https://user-images.githubusercontent.com/4478350/35715001-e55cd956-080a-11e8-9ce5-1aa82ff9ee76.PNG)

**Comment by disconnect3d** [comment]
I am not into aarch64 but:
>  I prefer the latter though.

seems more verbose to me so I am fine with that.

> BTW how do you display the code like this in markdown?

Its a new github feature, if you paste a link to proper file with some code lines as a parameter, it will render it as a code. E.g. @zachriggle's post contains this link:
```
https://github.com/pwndbg/pwndbg/blob/869e8320e123f4fe2d039a31c12ee8c7be7a54d3/pwndbg/commands/context.py#L107-L108

**Comment by bruce30262** [comment]
@disconnect3d  @zachriggle  I've created a [PR](https://github.com/pwndbg/pwndbg/pull/418), please take a look.

**Comment by disconnect3d** [comment]
Fixed in #418 by @bruce30262 , thx :heart:

**Comment by zachriggle** [comment]
> Aarch64 x30 = LR, which is already shown in the context, so we only have to show x29.

This should be gated by a configuration point, `show-retaddr-reg`

**Comment by bruce30262** [comment]
@zachriggle yes, I forgot to mention I've enable the config to always show the LR register :P
