### ISSUE TITLE
heap function issue

### ISSUE THREAD

**Issue by deadeert** [pwndbg/pwndbg#407]
Hello, 

I use glibc 2.26. 
I installed pwndbg from the Arch repository. 
My system is up to date. 

`pwndbg> version `
`Gdb: GNU gdb (GDB) 8.0.1`
`Python: 3.6.4 (default, Dec 23 2017, 19:07:07)  [GCC 7.2.1 20171128]`
`Pwndbg: 1.0.0`

I'm experimenting the following issue when invoking the heap functionnality 

> In file included from /usr/include/dis-asm.h:35:0,
>                 from /tmp/pwndbg/x86-64_struct-malloc_state.cc:31:
> /usr/include/bfd.h:35:2: error: #error config.h must be included before this header
> #error config.h must be included before this header
>  ^~~~~
> In file included from /usr/include/cursesw.h:40:0,
>                 from /usr/include/cursslk.h:39,
>                 from /tmp/pwndbg/x86-64_struct-malloc_state.cc:43:
> /usr/include/etip.h:346:44: error: la macro    THROW    requiert 2 arguments, mais seulement 1 ont   t   pass  s
> inline void THROW(const NCursesException *e) {
>                                            ^
> In file included from /tmp/pwndbg/x86-64_struct-malloc_state.cc:43:0:
> /usr/include/cursslk.h:121:37: error: la macro    THROW    requiert 2 arguments, mais seulement 1 ont   t
>pass  s
>     THROW(new NCursesException (msg));
>                                     ^
> In file included from /tmp/pwndbg/x86-64_struct-malloc_state.cc:78:0:
> /usr/include/pcre2.h:828:2: error: #error PCRE2_CODE_UNIT_WIDTH must be defined before including pcre2.h.
> #error PCRE2_CODE_UNIT_WIDTH must be defined before including pcre2.h.
>  ^~~~~
> /usr/include/pcre2.h:829:2: error: #error Use 8, 16, or 32; or 0 for a multi-width application.
> #error Use 8, 16, or 32; or 0 for a multi-width application.
>  ^~~~~
> In file included from /tmp/pwndbg/x86-64_struct-malloc_state.cc:145:0:
> /usr/include/nc_tparm.h:38:10: erreur fatale: ncurses_cfg.h : Aucun fichier ou dossier de ce type
>  #include <ncurses_cfg.h>
>          ^~~~~~~~~~~~~~~
> compilation termin  e.
> Traceback (most recent call last):
>  File "/usr/share/pwndbg/pwndbg/commands/__init__.py", line 56, in __call__
>    return self.function(*args, **kwargs)
>
>
>  File "/usr/share/pwndbg/pwndbg/commands/__init__.py", line 130, in _OnlyWhenRunning
>    return function(*a, **kw)
>  File "/usr/share/pwndbg/pwndbg/commands/heap.py", line 64, in heap
>    main_arena  = main_heap.get_arena(addr)
>  File "/usr/share/pwndbg/pwndbg/heap/ptmalloc.py", line 142, in get_arena
>    return self.main_arena
>  File "/usr/share/pwndbg/pwndbg/heap/ptmalloc.py", line 31, in main_arena
>    self._main_arena = pwndbg.memory.poi(self.malloc_state, main_arena_addr)
>  File "/usr/share/pwndbg/pwndbg/memoize.py", line 47, in __call__
>    value = self.func(*args, **kwargs)
>  File "/usr/share/pwndbg/pwndbg/heap/ptmalloc.py", line 63, in malloc_state
>    return pwndbg.typeinfo.load('struct malloc_state')
>  File "/usr/share/pwndbg/pwndbg/typeinfo.py", line 141, in load
>    compile(filename)
>  File "/usr/share/pwndbg/pwndbg/typeinfo.py", line 156, in compile
>    subprocess.check_output(' '.join(gcc), shell=True)
>  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
>    **kwargs).stdout
>  File "/usr/lib/python3.6/subprocess.py", line 418, in run
>    output=stdout, stderr=stderr)
>subprocess.CalledProcessError: Command '/usr/bin/g++ -m64 -w -c -g /tmp/pwndbg/x86-64_struct-malloc_state.cc -o
>/tmp/pwndbg/x86-64_struct-malloc_state.o' returned non-zero exit status 1.

Have you any idea of what could be the problem ? 

Thanks.

**Comment by disconnect3d** [comment]
The heap functionality requires some headers to be present and they are not
there by default on arch. I will probably work on that soon.
It should work on Ubuntu.

23.01.2018 12:50 AM "deadeert" <notifications@github.com> napisał(a):

**Comment by deadeert** [comment]
I clearly understand that point, but is there a workaround, such installing the right headers files and give the right pass to pwndbg ? 
Do you have any idea about the missing headers (glibc ?). 

Thanks for the support.

**Comment by disconnect3d** [comment]
@deadeert try this https://github.com/pwndbg/pwndbg/issues/340#issuecomment-328915318

**Comment by deadeert** [comment]
Will try this today. Thanks

**Comment by disconnect3d** [comment]
Closing as this should be the solution.
