### ISSUE TITLE
Support heap implementations other than ptmalloc2

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#41]
https://github.com/pwndbg/pwndbg/pull/36 adds support for basic heap commands, but only for ptmalloc2 (which is what glibc uses).

**Comment by zachriggle** [comment]
Is it `ptmalloc`-specific, or is it also compatible with `jemalloc`?  The only real difference is the number of arenas.

**Comment by gsingh93** [comment]
I haven't tested with dlmalloc, so I can't say anything about that. We should at least test it before claiming we support it.

**Comment by disconnect3d** [comment]
We added jemalloc recently. Closing this for now. Please open an issue if a specific heap implementation is wanted, and, if possible, please work on it and send a PR.
