### ISSUE TITLE
GDB 8.1 Improvements

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#411]
It looks like there are some goodies, particularly “starti” and “ptype” offsets.

https://sourceware.org/ml/gdb/2018-01/msg00026.html

**Comment by disconnect3d** [comment]
Is this issue about using `starti` for `entry` (`start`) commands?
What about `ptype`? Use `dt` as an alias for `ptype`?

I mean, for GDB>=8.1 ofc

**Comment by zachriggle** [comment]
More or less, yes.  If the GDB version is high enough, we should use `starti` instead of the current `start` logic which attempts to find the "real" entry point.

For `dt` specifically, I'm not sure.  The current format mimics the actual `dt` format used by Windbg.  I haven't seen the `8.1` output with offsets, so I don't know what it looks like.

**Comment by disconnect3d** [comment]
This is how `ptype` with offsets looks like compared to `dt`:

```
pwndbg> help ptype
Print definition of type TYPE.
Usage: ptype[/FLAGS] TYPE | EXPRESSION
Argument may be any type (for example a type name defined by typedef,
or "struct STRUCT-TAG" or "class CLASS-NAME" or "union UNION-TAG"
or "enum ENUM-TAG") or an expression.
The selected stack frame's lexical context is used to look up the name.
Contrary to "whatis", "ptype" always unrolls any typedefs.

Available FLAGS are:
  /r    print in "raw" form; do not substitute typedefs
  /m    do not print methods defined in a class
  /M    print methods defined in a class
  /t    do not print typedefs defined in a class
  /T    print typedefs defined in a class
  /o    print offsets and sizes of fields in a struct (like pahole)
```
In action (compiled with `-ggdb`):

```
#include <stdio.h>

struct X {
    int a, b, c;
    char x;
    int z;
};
int main(int argc, char* argv[]) {
    struct X x;
    printf("x=%d\n", x.z);
}

pwndbg> ptype /o struct X
/* offset    |  size */  type = struct X {
/*    0      |     4 */    int a;
/*    4      |     4 */    int b;
/*    8      |     4 */    int c;
/*   12      |     1 */    char x;
/* XXX  3-byte hole  */
/*   16      |     4 */    int z;

                           /* total size (bytes):   20 */
                         }
```


vs `dt`:
```
pwndbg> dt "struct X"
struct X
    +0x0000 a                    : int
    +0x0004 b                    : int
    +0x0008 c                    : int
    +0x000c x                    : char
    +0x0010 z                    : int
```

@zachriggle What do you think?

**Comment by disconnect3d** [comment]
Given that our `start` and `entry` does sth else than `starti` I am leaving `start` and `entry` as they are and will just improve their description to match certain standards :P.

Regarding `dt`, I think we should just alias it to `ptype`.
