### ISSUE TITLE
Pwndbg Bugreport

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#414]
It would be useful if Pwndbg could generate a bugreport on its own.  This would give users something nice to copy-paste into the bug-report.  
Included information might include:

- Pwndbg commit or release
  - Since installation requires `git`, we should be able to `git -C log -1 --oneline`
  - Find install directory via `os.path.dirname(pwndbg.__file__)`
- GDB version
  - Get path via `os.readlink('/proc/self/exe')`
  - Invoke with `-version` to get the full build info
  - Output of `show configuration`
- System info via `platform` module
  - `platform.system()`
  - `platform.platform()`
  - `platform.python_version()`
  - `platform.python_compiler()`
- ZIP file containing the file under test (optional for the user to upload)
  - `open('/proc/self/cmdline').read().split('\x00')`
  - `info file`
  - `info sharedlib`
- GDB command history
  - This would require saving the contents of the history file, and diffing from the session start
- Exception / backtrace information
  - `sys.last_value` / `sys.last_exception`
  - However, they're pretty unreliable if e.g. there's lots of exceptions

We could even try to be really nice and open the browser to the **New Issue** page (`xdg-open`, `open` for Linux / OSX) -- but the user would still need to copy-paste the template.

We could even use `ISSUE_TEMPLATE.md` to generate the copy-paste-able information.

**Comment by disconnect3d** [comment]
@GrosQuildu can you extend the `bugreport` command with the debugged file? I think this should also be optional with e.g. `--attach-debugged-file` flag.

**Comment by gsingh93** [comment]
Is there any way to get the output of the last command before uploading? Or would we have to save the output of the last command ourselves if we wanted to do this?

**Comment by gsingh93** [comment]
I think we can close this, the command has pretty much everything we need now except `--attach-debugged-file`, but I'm not sure if there's an easy way to do that. If there is some way, we can create a new issue for it.
