### ISSUE TITLE
ANSI Colors, Strings, String Lengths

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#415]
It looks like we've done some work where we are concerned about the display-width of a string that is colored with escape codes.

I suggest that rather than dealing with this via `colored_ljust` or similar, that we should just declare a subclass which is returned by all of the colorizing tools.

This would also add some flexibility for future stuff.  Consider something like the snippet below (using color names instead of ANSI codes for clarity).

```py
import types

class ColoredString(types.StringType):
    fg = ''
    bg = ''

    def __format__(self, *a, **kw):
        # do format stuff if we need this? __str__() should be enough
        return super(ColoredString, self).__format__(*a, **kw)

    def __str__(self, *a, **kw):
        # actually apply self.fg and self.bg
        # for demo purposes:
        return self.fg.lower() + self.bg.upper() + super(ColoredString, self).__str__() + 'NORMAL'
```

They can then be manipulated pretty easily:

```py
c = ColoredString('asdf')
c.fg = 'red'
c.bg = 'blue'
print 'printed:', c
print 'length is', len(c)
print 'type is str?', isinstance(c, str)
print 'c is {c}'.format(c=c)
# printed: redBLUEasdfNORMAL
# length is 4
# type is str? True
# c is redBLUEasdfNORMAL
```

We could also probably handle nested colors with some hacks, but I don't think that's an issue we need to solve right now.

**Comment by anthraxx** [comment]
sure we can do a base class, but ljust does more then just formatting, it padds an arbitrary lenghed string to a very max of a given length (f.e. very useful for banner length adjustment or orher things).
Also in my humble opinion we have several cases where we have nested colors and i don't see why we should break that just because of the sake of doing it differently.

**Comment by zachriggle** [comment]
>  it padds an arbitrary lenghed string to a very max of a given length

This describes `str.ljust` pretty well.  Why aren't we just using `str.ljust`?

```
>>> 'x'.ljust(3)
'x  '
>>> 'x'.ljust(3, 'y')
'xyy'
```

It looks like the only case that matters is using more than one character, which we don't actually need anywhere (e.g. `'x'.ljust(30, 'yz')`)

Perhaps I misunderstood the purpose, and also now I can't find the issues / PR that had the ANSI length considerations.

**Comment by disconnect3d** [comment]
@zachriggle the problem is there with colored/escaped things e.g.:
```
In : print('x'+red('x').ljust(3)+'y')
xxy
In : print('x'+'x'.ljust(3)+'y')
xx  y
```

**Comment by zachriggle** [comment]
Yep, thus the suggestion to implement a class that does this ~= transparently.

We'll have to override / wrap a few methods which strip type information, e.g. `ljust`.

```py
>>> class foo(str):
...     pass
...
>>> type(foo('asdf'))
__main__.foo
>>> type(foo('asdf').ljust(6))
str
```

**Comment by anthraxx** [comment]
Again: it doesn't work with arbitrary lengthed optional padding strings. Like if you want to pad a possible 3 character padding to a max of 8 you will get a string with length of 6. This doesn't work to keep a fixed length required for correct line length and. Columns alignment it just works for single characters

**Comment by zachriggle** [comment]
Also TIL about https://github.com/jonathaneunice/colors/ (`pip install ansicolors`)

**Comment by anthraxx** [comment]
There is also colorama https://pypi.python.org/pypi/colorama
Anyway, we need a wrapper around configs of ours, we shall never reference colors explicitly ever, but reference configuration keys that pull in the colors, either named features like nearpc or output types like warn. So we should never directly use those in the code anyway.

**Comment by anthraxx** [comment]
I feel like i'm the theme/color guy :joy_cat: ... so gonna hack together a PR that we can use as a base for such cases aware of better formatting string stuff, proper multi char ljust, colored len aware and nesting like we already support and consums configs instead of hard enforced colors.
You can assign me this issue if you like

**Comment by disconnect3d** [comment]
@anthraxx bump :P

**Comment by disconnect3d** [comment]
Given that we now have `pwndbg.log.*` and `message.{error,warn,info}` + probably some other coloring stuff and that we didn't do anything with this issue for 6+ years I think this can be closed.
