### ISSUE TITLE
Make the `bins` command print out all bins instead of just the fastbins

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#42]
https://github.com/pwndbg/pwndbg/pull/36 added the `bins` command, which currently only prints out the fastbins. We should print the rest of the bins as well, as long as they're not empty.

**Comment by zachriggle** [comment]
@gsingh93 Can you check that this is fixed?  Right now the function looks like:

```py
@pwndbg.commands.ParsedCommand
@pwndbg.commands.OnlyWhenRunning
def bins(addr=None):
    """
    Prints out the contents of the fastbins, unsortedbin, smallbins, and largebins from the
    main_arena or the specified address.
    """
    fastbins(addr)
    unsortedbin(addr)
    smallbins(addr)
    largebins(addr)
```

I'm assuming this prints out everything you want it to.  If not, please re-open this issue.
