### ISSUE TITLE
ida.py inside pwndbg crashes spectacularly when you are using Fiddler proxy (127.0.0.1:888)

### ISSUE THREAD

**Issue by J-Phi1123** [pwndbg/pwndbg#426]
### Description

While running Fiddler and pwndbg simultaneously, ida.py makes a call to an RPC within ida and tries to connect at 127.0.0.1:8888. Fiddler accepts the connection and returns a Fiddler error which causes pwndbg to crash.  

### Steps to reproduce

Start Fiddler and run gdb.  
Watch Fiddler call out to 127.0.0.1:8888 /RPC2
*** Crash **** 

The crash is happening within ida.py, line 57 _ida.here().  It is throwing an unhandled exception.

My fix is such:

```
--- ida.py	2018-03-15 11:14:31.860729082 -0400
+++ ida.py_fix	2018-03-15 11:31:17.065235731 -0400
@@ -17,6 +17,7 @@
 import traceback
 
 import gdb
+import xml
 
 import pwndbg.arch
 import pwndbg.compat
@@ -73,6 +74,9 @@
     except xmlrpclib.ProtocolError:
         exception = sys.exc_info()
         _ida = None
+    except xml.parsers.expat.ExpatError:
+        exception = sys.exc_info()
+        _ida = None
 
     if exception:
         if not isinstance(_ida_last_exception, exception[0]) or _ida_last_exception.args != exception[1].args:
```

**Comment by disconnect3d** [comment]
@J-Phi1123 There are some `config` options to modify IDA RPC host/port address:
```
set ida-rpc-host 127.0.0.1
set ida-rpc-port 1234
```

which should let you work with both the tools.
