### ISSUE TITLE
pwndbg cannot show source when debugging Linux kernel

### ISSUE THREAD

**Issue by deadly-platypus** [pwndbg/pwndbg#438]
### Description

When debugging the kernel through QEMU's remote gdbserver, `pwndbg` cannot show the source, but only the disassembly.  However, vanilla gdb has no problem displaying the source while debugging.  In fact, if I start a remote debugging session, and then hit <Ctrl+2>, I can see the source.

### Steps to reproduce

1. Start QEMU as a gdbserver: 
```
qemu-system-x86_64 -S -s -kernel arch/x86_64/boot/bzImage -drive \
format=raw,file=wheezy.img -m 2046 -nographic -append "root=/dev/sda \
console=ttyS0 rw single nokaslr"
```

2. Start gdb with the `vmlinux` symbol file, connect to the remote server, set a breakpoint, and start the boot process (NB: this assumes that the kernel was built with debug symbols):
```
gdb vmlinux
pwndbg> target remote :1234
pwndbg> b fat_fill_super
pwndbg> continue
```

When the breakpoint is hit, only the disassembly is shown.  There is an error report: 
`ERROR: Could not find ELF base!`

### My setup
```
pwndbg> version
Gdb:      GNU gdb (Ubuntu 8.0.1-0ubuntu1) 8.0.1
Python:   3.6.3 (default, Oct  3 2017, 21:45:48)  [GCC 7.2.0]
Pwndbg:   1.0.0 build: e225ba9
Capstone: 4.0.1024
Unicorn:  1.0.1
```
QEMU 2.10.1

**Comment by disconnect3d** [comment]
Hey, thanks for the bug report!

@deadly-platypus could you please provide all the necessary files to launch it and have the sources?

**Comment by deadly-platypus** [comment]
Is there an email address I can send stuff to?

**Comment by disconnect3d** [comment]
Can u share it publicly through some Google drive or another site like this?

**Comment by deadly-platypus** [comment]
I guess listing the steps here will work.  Warning, this process will take up a lot (>4 GB, I think) of storage space.

1. Install QEMU, either from [source](https://github.com/qemu/qemu) or from your favorite package manager.

2. Build the Linux kernel with debug symbols
  a. `git clone https://github.com/torvalds/linux`
  b. `cd linux && make defconfig && make menuconfig`
  c. Ensure that `kernel hacking --> Compile-time checks and compiler options --> Compile the kernel with debug symbols` is checked.
  d. `make`

3. Run this bash script to generate a correct filesystem.
[create-image.txt](https://github.com/pwndbg/pwndbg/files/1895245/create-image.txt)

4. Run the QEMU command in the initial bug report, the the `kernel` path being where you built the kernel, and `drive` file option be the location of the wheezy.img that was created in step 3.

5. Start up GDB and follow the steps in the bug report.

I think thats what you need to do...if I missed something you can't figure out, let me know.

**Comment by disconnect3d** [comment]
Thanks I will check it out tomorrow :)

**Comment by disconnect3d** [comment]
Eh, will come back to it in some days. If osmeone else is willing to contribute, feel free to do so (if you need help, ping me on irc; [this](https://github.com/pwndbg/pwndbg/blob/dev/DEVELOPING.md) might be helpful too).

**Comment by disconnect3d** [comment]
Hey, I finally got it launched. The thing is... it might require some work to make it work properly, but lets see what are the problems:

1) `ERROR: Could not find ELF base!` - this comes from `get_ehdr` which tries to find ELF magic.

2) Just on the first break, the `stack` memory page is wrong:
```
pwndbg> vmmap
LEGEND: STACK | HEAP | CODE | DATA | RWX | RODATA
           -0x1000           0x400000 rwxp   401000 0      [stack]
```
At start the SP register is 0 and [we read it and decrease it by 0x1000 here](https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/stack.py#L72-L81) and boom, "it starts at -0x1000".
Its ending address is set as `0x1000*1024 = 0x400000` because we check maximum of 1024 memory pages when finding ELF magic (in `find_elf_magic`; this is also the problem of 1.).

3) There are no other memory pages than the stack. We can do `vmmap_clear` and `vmmap_load` so that the pages are loaded from the ELF file but it is probably not correct?

---

I may try to look some more over this, but I will probably not work on making this work properly. Pwndbg was not designed for kernel debugging.

Anyway, it would be awesome to make it happen, so if you or anyone else would like to help with that, I may answer any questions out there or help with some stuff.

**Comment by disconnect3d** [comment]
Also, things described here might be helpful: https://github.com/pwndbg/pwndbg/issues/168

**Comment by 0x43434343** [comment]
still have the same issue

**Comment by 0x43434343** [comment]
did you guys fixed that ?

**Comment by disconnect3d** [comment]
If you have the issue then I guess not. This seems to boil down as a "we cant get memory mappings properly" issue.

There was an improvement in getting memory pages information for linux kernel via qemu monitor, though, we still try to find memory mappings by exploring e.g. registers and this is likely wrong.

It's hard to have a 'best' solution here bcoz:
- qemu monitor command for getting memory mappings is very slow for x64 so we shouldn't do it every step (I think we do for now)
- qemu monitor command doesn't work on all archs (only x86, x86-64 and risc-v, huh)
- it does not give us information whether a memory page is executable

Anyway I think we should:
- drop exploring registers for getting memory mappings by default, or, at least don't do that on kernels from which we can use qemu monitor for getting vmmap info
- make qemu monitor vmmap fetching more lazy: i.e. do it once every X steps, on user demand or when we encounter situation that we hit memory page that was unmapped or is not in our vmmap list

**Comment by disconnect3d** [comment]
Also, this should be possible but probably not that easy to work around this issue by removing few things... mainly:
- memory exploration - so, commenting out/removing this code: https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/vmmap.py#L120-L124
- finding stack boundaries, which is done [here](https://github.com/pwndbg/pwndbg/blob/2f3626046448fbffcfa21822779c769c7be6606a/pwndbg/memory.py#L326-L363) 
- removing some bits around getting AUXV - https://github.com/pwndbg/pwndbg/search?utf8=%E2%9C%93&q=pwndbg.auxv&type=

**Comment by disconnect3d** [comment]
I would be happy to review and merge patches that make pwndbg more robust against debugging kernels with sources etc.

**Comment by amlamarra** [comment]
Just chiming in that this is still an issue and it would be awesome to get it fixed.

**Comment by jonaskaempf** [comment]
I also have had this issue for a while.

Generally, as @disconnect3d says, there's very poor support for kernel debugging, and the problems are spread out across the code base as there's numerous assumptions that only work for user-land. For example, a lot of stuff in pwndbg/elf.py does plainly not work for vmlinux debugging.

In my opinion, it will be a major undertaking adding "first-class" support for kernel debugging (whether it be QEMU or hardware), for all the reasons @disconnect3d have mentioned here, and in related issues like #736.  

I have some local patches here: https://github.com/jonaskaempf/pwndbg/tree/vmlinux-dev, that hacks a few places to get rid of the most annoying errors and exceptions to actually get a somewhat durable UX, at least for the simplest case: QEMU+vmlinux with symbols. It's not intended as a merge request, more a hack on top of several other hacks. Especially the very hackish user-land-only functions in pwndbg/elf.py could use a major refactor.

Also there's the issue of memory maps, stack finding etc. that break all over the place when debugging kernel. But it seems most of these errors are not fatal in the sense that you can get a usable experience without "fixing" them.

Finally, there's lots of cool kernel debugging features that could be added when the basis mentioned above is in place; e.g. getting info on current userland process, if breaking inside userland mode etc.

**Comment by gsingh93** [comment]
The kernel debugging experience isn't great, but it's gotten a bit better over the past few years and will be a bigger focus next year. I've been debugging x86 and aarch64 linux kernels recently and haven't had any problems with seeing the source, so I think we should close this.
