### ISSUE TITLE
After update to glibc 2.27 the allocing of heap is strange

### ISSUE THREAD

**Issue by SoWhereAreYou** [pwndbg/pwndbg#445]
I download the kali 2018.1 and directly install pwndbg
I want to test a pwn of ctf topic
It is the writeup of it
http://tacxingxing.com/2018/02/20/pwnabletw-secretgarden/
And Here is the topic named secretgarden
https://pwnable.tw/challenge/
I found i can't  use the unsorted bin to leak the address of libc
And I test the exp in my friend’s ubuntu with glibc 2.23
Everything is true
I saw the heap ，found the chunk didn‘t have pointer to the main_arena
So I want to know if the memory mangement in glibc has been changed？
Could I use the lower glibc in pwndbg？

------------------------------------------------------------------------------------------------------------------Update，I get it！https://stackoverflow.com/questions/50084250/after-use-glibc-2-27-many-uaf-bug-can-t-to-use
He said the heap layout had been changed.Could it be improve?

**Comment by disconnect3d** [comment]
Hey, thanks for reporting the issue.
What version of pwndbg did you try? Can you try it on last pwndbg dev branch?

**Comment by disconnect3d** [comment]
> He said the heap layout had been changed.Could it be improve?


We have added glibc's allocator tcache support recently. If there is something else to be done please open a new issue. Thanks.
