### ISSUE TITLE
The reverse- commands of rr stop working after a SIGSEGV when used with pwndbg

### ISSUE THREAD

**Issue by andigena** [pwndbg/pwndbg#476]
### Description

When running rr with pwndbg and encountering a SIGSEGV in the debugged application, the reverse- commands of rr stop working. After executing them, the same context is printed as before, rip and the other registers/memory remains in the same state, etc. (see the attached session below).

If I disable pwndbg, they work fine in the same situation. They also work with pwndbg when there's no SIGSEGV encountered. Another thing I noticed is that I can step back from SIGABRTs, so it might be specific to segmentation faults?

I also think I've seen this issue in the not-so-recent past (last year maybe), so it's likely not something new.

### Steps to reproduce

```
tukan@farm:~/t$ cat sigsegv.c
int main() {
    *(int *)0x414141 = 0x41;
    return 0;
}
tukan@farm:~/t$ gcc -O0 -o sigsegv sigsegv.c 
tukan@farm:~/t$ rr record ./sigsegv
rr: Saving execution to trace directory `/home/tukan/.local/share/rr/sigsegv-1'.
Segmentation fault
tukan@farm:~/t$ rr replay
```
rr session attached: [rr-session.txt](https://github.com/pwndbg/pwndbg/files/2053502/rr-session.txt)

### My setup

* Ubuntu 16.04 amd64
* Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
* GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
* rr latest (f3bde22)
* pwndbg latest (f56f271)

**Comment by disconnect3d** [comment]
Hey, thanks for reporting this. I will take a look on that tomorrow.

**Comment by disconnect3d** [comment]
We've both investigated it today and talked on irc, the problem is caused by `gdb.parse_and_eval` invoked here:
https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/commands/context.py#L371-L375

We use this code to display to the user that something has happend with debugging program (it exited, segaulted etc) AFTER we display context. GDB does it by default but it does it before the context and so most of the time the user doesn't see that.

If we remove them, everything works fine.

**Comment by disconnect3d** [comment]
I have also asked about how to detect rr here: https://mail.mozilla.org/pipermail/rr-dev/2018-May/000626.html

**Comment by disconnect3d** [comment]
@andigena Could you review the PR above? I have also applied a fix for a recently introduced bug that made context registers RIP display wrong in some cases ( https://github.com/pwndbg/pwndbg/pull/477 ).

**Comment by andigena** [comment]
I just did, thanks for quickly fixing this!
