### ISSUE TITLE
[feature request]Ida: display pseudocode around $rip, not whole function

### ISSUE THREAD

**Issue by sven337** [pwndbg/pwndbg#491]
### Description

pwndbg will talk to Ida to get the full pseudocode dump of the function being run. When that function is long, this is not good. It would be better to only display 10 or 20 lines around the current value of $rip. I do not know how to implement that myself but I believe it should be possible since Ida itself is able to do that when using tab in disassembly view.

**Comment by disconnect3d** [comment]
I am not sure if I understand what is the problem here. Is it too long code display or is it that we transfer too much stuff between IDA and Pwndbg?

I believe the first thing should be configurable by one of those config parameters:
```
pwndbg> config code
Name                            Value (Def) Documentation
---------------------------------------------------------
context-code-lines              10         number of additional lines to print in the code context
context-source-code-lines       10         number of source code lines to print by the context command
```

**Comment by sven337** [comment]
It's more complicated than this - the problem is that the decompile call to Ida doesn't take a PC as argument, so it will decompile the whole function. You'd want to display only 10 lines around PC, but since you can't know which line corresponds to PC, it's the whole decompiled function that gets displayed.
This has to be fixable since the Ida interface is able to jump from one line of assembly to the corresponding line of pseudocode, but I don't know how to do that with the API.
Relevant code lives here:
https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/commands/context.py#L272

**Comment by disconnect3d** [comment]
I have spent some time on this and I couldn't find anyything in idaapi for that purpuse :/.

However another approach could be dumping IDA information into dwarf debugging symbols and loading them in GDB.

Probably this could be used: https://github.com/ALSchwalm/dwarfexport

@sven337 would you check this out and if it works fine, add it to pwndbg?

**Comment by sven337** [comment]
I have used this years ago and found it not reliable, but I cannot remember why.
... or maybe it was another project, this one seems recent.

**Comment by disconnect3d** [comment]
Comming back to this topic, if someone is willing to add this, please send a PR.

The thing can be done in IDA>=7.1 using more or less this code:
```
cfunc = idaapi.decompile(func_addr)
item = cfunc.body.find_closest_addr(insn_addr)
x_holder = idaapi.int_pointer()
y_holder = idaapi.int_pointer()
cfunc.find_item_coords(item, x_holder, y_holder)
x, y = x_holder.value(), y_holder.value()
```

However, I can't work on that as I don't have IDA atm.

**Comment by NyaMisty** [comment]
I've tested your code on IDA 7.2. Basically it worked very well. It requires the user to open the pseudocode widget, or the `find_item_coords` will return False and fail.
Currently I placed this snipped into the ida_script.py, because this code snippet does a bunch of API request, and are called every time the context shows. Would you agree with me?

**Comment by disconnect3d** [comment]
@NyaMisty yeah, please send a PR. If you could also provide some demo to show it works it would be awesome too but we can skip that :P

**Comment by NyaMisty** [comment]
![image](https://user-images.githubusercontent.com/5344431/57147371-fec33100-6df9-11e9-946c-78d59eede7c2.png)
Small demo here~ You can see that the the comment corresponds with the pseudocode part :)

**Comment by NyaMisty** [comment]
PR already submitted~ My pleasure to contribute code for pwndbg 👍

**Comment by stnevans** [comment]
Closing this because it seems #630 fixes this.
