### ISSUE TITLE
Colors not friendly for light terminal

### ISSUE THREAD

**Issue by offlinemark** [pwndbg/pwndbg#503]
hi!

### Description

The colorscheme hides brackets in x64 asm when viewed on a light color scheme

### My setup

macos, iterm2, solarized light colors (i happen to be ssh'd into a vm in these pictures)

i tried looking in `theme` for a config for this, but couldn't quickly find one, any tips?

![image](https://user-images.githubusercontent.com/2467355/42838741-94c5c36c-89cf-11e8-8881-078f11329b90.png)

![image](https://user-images.githubusercontent.com/2467355/42838749-9b8733ac-89cf-11e8-9751-c22cc6decf8f.png)

**Comment by zachriggle** [comment]
You should be able to change the colors of pretty much anything, Pwndbg has extensive theming support.  Check the `theme` command to see what you can change.

It looks like the code syntax highlighting specifically relies on `pygments`, and its built-in styles.  The default is `monokai`.

https://github.com/pwndbg/pwndbg/blob/0f5b028e2eb55e69beb276384f1e277c99ac2538/pwndbg/color/syntax_highlight.py#L23-L24

You should be able to do something like `set syntax-highlight off` to disable it entirely, or `set syntax-highlight-style XXX` where `XXX` is one of the built-in styles.  Presumably, you can define your own as well!

```
>>> from pygments.styles import STYLE_MAP
>>> print sorted(STYLE_MAP.keys())
['abap', 'algol', 'algol_nu', 'arduino', 'autumn', 'borland', 'bw', 'colorful', 'default', 'emacs', 
'friendly', 'fruity', 'igor', 'lovelace', 'manni', 'monokai', 'murphy', 'native', 'paraiso-dark', 
'paraiso-light', 'pastie', 'perldoc', 'rainbow_dash', 'rrt', 'tango', 'trac', 'vim', 'vs', 'xcode']
```

**Comment by offlinemark** [comment]
i see, thanks so much for the quick response. for anyone looking later, `default` looks great with solarized light!

`set syntax-highlight-style default`
