### ISSUE TITLE
TUI - ugly & raw console escape and control sequences

### ISSUE THREAD

**Issue by osiixy** [pwndbg/pwndbg#504]
When I switch to tui mode (eg. tui enable)
the tui not resize itself and the prompt
is full of control sequences:
 ^A^[[31m^[[1m^Bpwndbg> ^A^[[0m^[[31m^[[0m^B

**Comment by disconnect3d** [comment]
It seems that tui mode doesn't care about control sequences... :/
You can do `set disable-colors on` to prevent them from appearing but this will also don't show any colors etc.

**Comment by osiixy** [comment]
Ok, that fixes the prompt.
However the resize issue remains.

**Comment by osiixy** [comment]
That's sad that is needed to disable colors,
if it cannot be achieved to use colors with TUI
it could be turned on & off automatically between
switching back and forth TUI mode at least.

**Comment by disconnect3d** [comment]
> it could be turned on & off automatically between
switching back and forth TUI mode at least.

I believe there is no GDB's event for that so we cannot hook in here (see https://sourceware.org/gdb/current/onlinedocs/gdb/Events-In-Python.html).

That being said, I am afraid we cannot do anything in here, so I am closing the issue.

Feel free to add comments here or work on that - I would be happy to accept a PR that handles this properly (this might require changes in GDB itself though...).
