### ISSUE TITLE
When I use  gdb.attach(p) by pwntools , I run heap command, I get this error!

### ISSUE THREAD

**Issue by wonderkun** [pwndbg/pwndbg#509]
```
pwndbg> heap
'heap': Prints out chunks starting from the address specified by `addr`.
Exception occured: heap: Could not convert Python object: None. (<class 'TypeError'>)
For more info invoke `set exception-verbose on` and rerun the command
or debug it by yourself with `set exception-debugger on`
pwndbg> set exception-verbose on
Set whether to print a full stacktracefor exceptions raised in Pwndbg commands to True
pwndbg> heap
'heap': Prints out chunks starting from the address specified by `addr`.
Traceback (most recent call last):
  File "/home/wonderkun/github/pwndbg/pwndbg/commands/__init__.py", line 109, in __call__
    return self.function(*args, **kwargs)
  File "/home/wonderkun/github/pwndbg/pwndbg/commands/__init__.py", line 200, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/home/wonderkun/github/pwndbg/pwndbg/commands/__init__.py", line 208, in _OnlyWhenHeapIsInitialized
    if pwndbg.heap.current.is_initialized():
  File "/home/wonderkun/github/pwndbg/pwndbg/heap/ptmalloc.py", line 526, in is_initialized
    return self.global_max_fast != 0
  File "/home/wonderkun/github/pwndbg/pwndbg/heap/ptmalloc.py", line 177, in global_max_fast
    return pwndbg.memory.u(addr)
  File "/home/wonderkun/github/pwndbg/pwndbg/memory.py", line 245, in u
    }[size](addr)
  File "/home/wonderkun/github/pwndbg/pwndbg/memory.py", line 228, in u64
    return readtype(pwndbg.typeinfo.uint64, addr)
  File "/home/wonderkun/github/pwndbg/pwndbg/memory.py", line 87, in readtype
    return int(gdb.Value(addr).cast(gdb_type.pointer()).dereference())
TypeError: Could not convert Python object: None.

If that is an issue, you can report it on https://github.com/pwndbg/pwndbg/issues
(Please don't forget to search if it hasn't been reported before)
PS: Pull requests are welcome
```
my linux kernal version:
```
➜  pwn3-2 uname -r 
4.15.0-32-generic
➜  pwn3-2 cat /etc/issue    
Ubuntu 16.04.5 LTS \n \l
```

**Comment by disconnect3d** [comment]
Can you share your pwndbg version and pwntools code that presents this issue?

**Comment by wonderkun** [comment]
```
pwndbg> version 
Gdb:      7.11.1
Python:   3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
Pwndbg:   1.1.0 build: c188ed3
Capstone: 4.0.1024
Unicorn:  1.0.1
```
I download pwndbg yesterday.  

```python
# ./pwndbg/memory.py:87
def readtype(gdb_type, addr):
    """readtype(gdb_type, addr) -> int

    Reads an integer-type (e.g. ``uint64``) and returns a Python
    native integer representation of the same.

    Arguments:
        gdb_type(gdb.Type): GDB type to read
        addr(int): Address at which the value to be read resides

    Returns:
        :class:`int`
    """
    return int(gdb.Value(addr).cast(gdb_type.pointer()).dereference())
```

error info 
```
pwndbg> heap
'heap': Prints out chunks starting from the address specified by `addr`.
Traceback (most recent call last):
  File "/home/wonderkun/github/pwndbg/pwndbg/commands/__init__.py", line 109, in __call__
    return self.function(*args, **kwargs)
  File "/home/wonderkun/github/pwndbg/pwndbg/commands/__init__.py", line 200, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/home/wonderkun/github/pwndbg/pwndbg/commands/__init__.py", line 208, in _OnlyWhenHeapIsInitialized
    if pwndbg.heap.current.is_initialized():
  File "/home/wonderkun/github/pwndbg/pwndbg/heap/ptmalloc.py", line 526, in is_initialized
    return self.global_max_fast != 0
  File "/home/wonderkun/github/pwndbg/pwndbg/heap/ptmalloc.py", line 177, in global_max_fast
    return pwndbg.memory.u(addr)
  File "/home/wonderkun/github/pwndbg/pwndbg/memory.py", line 245, in u
    }[size](addr)
  File "/home/wonderkun/github/pwndbg/pwndbg/memory.py", line 228, in u64
    return readtype(pwndbg.typeinfo.uint64, addr)
  File "/home/wonderkun/github/pwndbg/pwndbg/memory.py", line 87, in readtype
    return int(gdb.Value(addr).cast(gdb_type.pointer()).dereference())
TypeError: Could not convert Python object: None.
```

**Comment by wonderkun** [comment]
```
    @property
    def global_max_fast(self):
        addr = pwndbg.symbol.address('global_max_fast')
        return pwndbg.memory.u(addr)
```
why addr = pwndbg.symbol.address('global_max_fast') is None , which lead this error ! 

This error only happen when I use  gdb.attach(p) by pwntools, when I use `gdb ./programe`  without this error!

**Comment by wonderkun** [comment]
I know what happened .....
1. I start a process when I give a LD_PRELOAD  env. This error occurs. 
```
env = {"LD_PRELOAD":os.path.join(os.getcwd(), "./libc-2.23.so")}
r = process("./UNote",env=env)
```
without LD_PRELOAD env, without this error!

**Comment by zachriggle** [comment]
As a side-note, you want to use `LD_LIBRARY_PATH` in this case, not `LD_PRELOAD`.

That said, it shouldn't mess up `pwndbg` unless you actually end up with two copies of libc loaded into your process.

**Comment by disconnect3d** [comment]
Hmm.. so is there any issue or can we close it?

**Comment by JX-Zhang98** [comment]
> As a side-note, you want to use `LD_LIBRARY_PATH` in this case, not `LD_PRELOAD`.
> 
> That said, it shouldn't mess up `pwndbg` unless you actually end up with two copies of libc loaded into your process.

Emmm...sorry,  I meet the same problem that if I use a designated libc , error occurs when checking the heap.
>  Could not convert Python object: None.

But I didn't what you mean to solve this error ,actually
No matter what I do like this , error exists.

- env = {"LD_PRELOAD":os.path.join(os.getcwd(), "./libc_64.so.6")}
  io = process('./secretgarden', env=env)
- io = process('./secretgarden', env={'LD_PRELOAD': './libc_64.so.6'})

But when I use 'LD_LIBRARY_PATH' instead, the process doesn't use the designed libc at all

In addition, I use pwngdb in a docker, but I don't think it matters.
kernel version 

> root@CTF:/ctf/work# uname -r
> 4.15.0-29deepin-generic
> root@CTF:/ctf/work# cat /etc/issue
> Ubuntu 16.04.3 LTS \n \l
> pwndbg> version
> Gdb:      7.11.1
> Python:   3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
> Pwndbg:   1.1.0 build: 054f209
> Capstone: 4.0.1024
> Unicorn:  1.0.1

 Thank you!


----------------
*update 12/21*
it may be the matter of the libc, because I changed the soft link of libc.so.6 to my designed libc but the error still happens .
If you have any idea, thank you for informing me.

**Comment by shellmage** [comment]
same problem here
OS : Linux pc 5.12.1-arch1-1
Gdb:      10.1
Python:   3.9.4 (default, Apr 20 2021, 15:51:38)  [GCC 10.2.0]
Pwndbg:   1.1.0
Capstone: 4.0.1024
Unicorn:  1.0.2

the debugging symbols and the heap commands work fine when i execute pwndbg directly 
but this issue (No debugging symbols found in <libc path>) always happens when attaching to pwndbg from pwntools
no matter if using the system libc or designated libc with LD_PRELOAD or patchelf to patch the libc path
