### ISSUE TITLE
Python Error 

### ISSUE THREAD

**Issue by FilipDjurkoviccc** [pwndbg/pwndbg#510]
When I run program I got this 

![screenshot from 2018-08-19 23-44-46](https://user-images.githubusercontent.com/37014351/44313520-869f1180-a40a-11e8-8260-a98a1e91a77e.png)

**Comment by FilipDjurkoviccc** [comment]
help?

**Comment by disconnect3d** [comment]
Have you used `setup.sh` to install pwndbg?

**Comment by FilipDjurkoviccc** [comment]
yes

**Comment by FilipDjurkoviccc** [comment]
I fixed it
I uninstall ubuntu and install Kali Linux and it works :)
