### ISSUE TITLE
repeating last command fails when pressing enter in pwndbg

### ISSUE THREAD

**Issue by bash-c** [pwndbg/pwndbg#511]
### Description
We have just solved the problem of [tab completion fails in pwndbg](https://github.com/pwndbg/pwndbg/issues/494) and this time a new problem occured.

We know that if we press enter in gdb, the last command will repeat. But it fails in my gdb with pwndbg(without .gdbinit from pwndbg it works normally). When I press enter, it's just an enter to a new  line with no command repeating. 

Besides some commands work normally like `apropos` but some not like `ni`.
I record a [video](https://asciinema.org/a/ohAksbfgeCULxbHaNWNVUGAsz)

### My setup

Here is my config:
```
pwndbg> show configuration 
This GDB was configured as follows:
   configure --host=x86_64-pc-linux-gnu --target=x86_64-pc-linux-gnu
             --with-auto-load-dir=$debugdir:$datadir/auto-load
             --with-auto-load-safe-path=$debugdir:$datadir/auto-load
             --with-expat
             --with-gdb-datadir=/usr/local/share/gdb (relocatable)
             --with-jit-reader-dir=/usr/local/lib/gdb (relocatable)
             --without-libunwind-ia64
             --without-lzma
             --without-babeltrace
             --without-intel-pt
             --disable-libmcheck
             --with-mpfr
             --with-python=/usr
             --without-guile
             --with-separate-debug-dir=/usr/local/lib/debug (relocatable)

("Relocatable" means the directory can be moved with the GDB installation
tree, and GDB will still find it.)
pwndbg> show version
GNU gdb (GDB) 8.2.50.20180818-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
pwndbg> version 
Gdb:      8.2.50.20180818-git
Python:   2.7.13+ (default, Jul 19 2017, 18:15:03)  [GCC 6.4.0 20170704]
Pwndbg:   1.0.0
Capstone: 3.0.768
Unicorn:  1.0.1
pwndbg> 
```

```bash
pwnable_alloca [master●●] lsb_release -a
No LSB modules are available.
Distributor ID:	Deepin
Description:	Deepin 15.6
Release:	15.6
Codename:	unstable
```

**Comment by disconnect3d** [comment]
@0x01f Just installed pwndbg on a fresh Ubuntu 18.04 and enter works fine :|.

```
pwndbg> show configuration 
This GDB was configured as follows:
   configure --host=x86_64-linux-gnu --target=x86_64-linux-gnu
             --with-auto-load-dir=$debugdir:$datadir/auto-load
             --with-auto-load-safe-path=$debugdir:$datadir/auto-load
             --with-expat
             --with-gdb-datadir=/usr/share/gdb (relocatable)
             --with-jit-reader-dir=/usr/lib/gdb (relocatable)
             --without-libunwind-ia64
             --with-lzma
             --with-python=/usr (relocatable)
             --without-guile
             --with-separate-debug-dir=/usr/lib/debug (relocatable)
             --with-system-gdbinit=/etc/gdb/gdbinit
             --with-babeltrace

("Relocatable" means the directory can be moved with the GDB installation
tree, and GDB will still find it.)
pwndbg> version
Gdb:      8.1.0.20180409-git
Python:   3.6.5 (default, Apr  1 2018, 05:46:30)  [GCC 7.3.0]
Pwndbg:   1.1.0 build: c188ed3
Capstone: 4.0.1024
Unicorn:  1.0.1
```

I am afraid this issue might be related to Deepin or its fancy console?
Can you check how does it behave e.g. in `terminator` console?

PS: I will check this out on recent GDB version - maybe they changed something between 8.1 and 8.2.

**Comment by bash-c** [comment]
Yep I agree with it.
I copied my config to another machine(ubuntu 17.10 with gnome-terminal) and it works well. 
Now I'm considering other distributions. Thank you.

**Comment by itszn** [comment]
I just pulled the latest on ubuntu16, previously had been working fine on the same box. Now hitting enter after nexti or stepi does not repeat the command. This is over ssh as well.

**Comment by dipanjan** [comment]
I am facing the same issue on `Ubuntu 18.04.2 x86_64`, `pwndbg` commit `0f4e31e72a10320670f04616041ab800fc9cadf1`

```
pwndbg> version
Gdb:      8.2
Python:   3.6.7 (default, Oct 22 2018, 11:32:17)  [GCC 8.2.0]
Pwndbg:   1.1.0 build: 068bcff
Capstone: 4.0.1024
Unicorn:  1.0.1
```

**Comment by pullp** [comment]
I am facing the same issue on ubuntu 18.10 x86_64

when I hit ENTER gdb will repeat the last instruction(I have test n ni s si) if I don't use pwndbg otherwise it just show a new line. 


environment infomation:
➜    uname -a
Linux pwn 4.18.0-16-generic #17-Ubuntu SMP Fri Feb 8 00:06:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

pwndbg> show version
GNU gdb (Ubuntu 8.2-0ubuntu1) 8.2
....
This GDB was configured as "x86_64-linux-gnu".
...
pwndbg> version
Gdb:      8.2
Python:   3.6.7 (default, Oct 22 2018, 11:32:17)  [GCC 8.2.0]
Pwndbg:   1.1.0
Capstone: 5.0.1280
Unicorn:  1.0.1

**Comment by disconnect3d** [comment]
Can you guys try on the latest release of GDB? The 8.2.0 had some bugs which we talked about in https://github.com/pwndbg/pwndbg/issues/523. I believe it might be it...

You can build particular GDB version as in:
```
wget https://ftp.gnu.org/gnu/gdb/gdb-8.1.tar.gz
tar -xvf gdb-8.1.tar.gz
cd gdb-8.1
mkdir build
cd build
../configure --prefix=/usr --disable-nls --disable-werror --with-system-readline --with-python=/usr/bin/python3.6 --with-system-gdbinit=/etc/gdb/gdbinit --enable-targets=all
make -j7
sudo make install
```
Please note that you need to specify proper python path and this might require some additional libs e.g. `libreadline` (install from apt). It also installs the GDB to `/usr` as specified with `--prefix`.

**Comment by pullp** [comment]
> Can you guys try on the latest release of GDB? The 8.2.0 had some bugs which we talked about in #523. I believe it might be it...
> 
> You can build particular GDB version as in:
> 
> ```
> wget https://ftp.gnu.org/gnu/gdb/gdb-8.1.tar.gz
> tar -xvf gdb-8.1.tar.gz
> cd gdb-8.1
> mkdir build
> cd build
> ../configure --prefix=/usr --disable-nls --disable-werror --with-system-readline --with-python=/usr/bin/python3.6 --with-system-gdbinit=/etc/gdb/gdbinit --enable-targets=all
> make -j7
> sudo make install
> ```
> Please note that you need to specify proper python path and this might require some additional libs e.g. `libreadline` (install from apt). It also installs the GDB to `/usr` as specified with `--prefix`.

Thanks a lot. GDB 8.1  don't have such problem.
besides, I also need to install `texinfo` from apt to make gdb.

Maybe this is really a gdb's bug as I refered to gdb's commit history and saw this:
[Fix gdb/TUI behavior in response to [Enter] keypress](https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=commit;h=b17c4cd078e2d1d8951951016815e474fb133780)
