### ISSUE TITLE
Better radare2 support

### ISSUE THREAD

**Issue by matrix1001** [pwndbg/pwndbg#514]
# Problem
r2 works well on pwndbg. !!BUT!! when it comes to PIE enabled binarys, r2 cannot find the right address.
# My fix
```python
@pwndbg.commands.ArgparsedCommand(parser)
@pwndbg.commands.OnlyWithFile
def r2(arguments, no_seek=False):
    filename = pwndbg.file.get_file(pwndbg.proc.exe)

    # Build up the command line to run
    cmd = ['radare2', filename]
    addr = pwndbg.regs.pc
    if pwndbg.wrappers.checksec.pie_status() == "PIE enabled":
        addr -= pwndbg.elf.exe().address
    if not no_seek and pwndbg.proc.alive:
        cmd.extend(['-s', hex(addr)])
    cmd += arguments

    try:
        subprocess.call(cmd)
    except Exception:
        print("Could not run radare2.  Please ensure it's installed and in $PATH.")

```
I add in PIE check, and recalculate the address.
# Result
```
──────────[ DISASM ]────────────────────
 ► 0x55555555dff1    test   eax, eax
   0x55555555dff3    mov    ebx, eax
   0x55555555dff5    js     0x55555555dfc8

   0x55555555dff7    test   eax, eax
   0x55555555dff9    jne    0x55555555def1
    ↓
   0x55555555def1    movsxd r12, ebx
   0x55555555def4    mov    rbp, qword ptr [rip + 0x212aed]
   0x55555555defb    sub    r12, 1
   0x55555555deff    jmp    0x55555555df19
    ↓
   0x55555555df19    movsx  eax, byte ptr [rbp]
   0x55555555df1d    sub    ebx, 1
─────────────[ STACK ]───────────────────
00:0000│ rsp  0x7fffffffdfe0 —▸ 0x7fffffffe040 —▸ 0x555555772aa0 ◂— 0x0
01:0008│      0x7fffffffdfe8 ◂— 0x0
... ↓
03:0018│      0x7fffffffdff8 —▸ 0x5555555627f5 ◂— mov    ebx, eax
04:0020│      0x7fffffffe000 —▸ 0x7fffffffe040 —▸ 0x555555772aa0 ◂— 0x0
05:0028│      0x7fffffffe008 —▸ 0x555555562a62 ◂— mov    ebx, eax
06:0030│      0x7fffffffe010 —▸ 0x7fffffffe040 —▸ 0x555555772aa0 ◂— 0x0
07:0038│      0x7fffffffe018 —▸ 0x555555772d10 ◂— 0x0
─────────────[ BACKTRACE ]───────────────
 ► f 0     55555555dff1
   f 1     5555555627f5
   f 2     555555562a62
   f 3     555555564737
   f 4     55555556042f
   f 5     55555555772f
   f 6     7f35fc443a87 __libc_start_main+231
pwndbg> r2
[0x00009ff1]> pd 4
        :   ;-- rip:
        :   0x00009ff1      85c0           test eax, eax
        :   0x00009ff3      89c3           mov ebx, eax
        `=< 0x00009ff5      78d1           js 0x9fc8
            0x00009ff7      85c0           test eax, eax
[0x00009ff1]>

```
As you can see, r2 works properly with PIE.
# Suggestion
r2 is really useful when using pwndbg, although few people use it at present. I got an idea about transport all data including memory and register into r2 for better analysing.

**Comment by disconnect3d** [comment]
Hey,

Thanks for reporting this issue!

Can you send a Pull Request with your changes so we will be able to test this out on your branch?

[Here is some info on how to do that](https://help.github.com/articles/creating-a-pull-request/) :)

**Comment by disconnect3d** [comment]
@matrix1001 bump, are you going to work on that?

**Comment by XVilka** [comment]
@matrix1001 don't hesitate to open an issue in radare2 repo if something is missing/required/not working properly.

**Comment by ladreamist** [comment]
Is it intended behavior that the loading of the binary and the program counter doesn't reflect the state of the debugee? I've for the moment made a quick personal fix like so
https://github.com/n00bSec/pwndbg/commit/400502bc2787f4bf7004a542156ca9c6cc28db67
to make it more consistent with the already debugged binary.

The program counter thus also reflects the current PC of the debugee.

At the moment, pwndbg.regs not being populated (when not debugging) has meant I can only launch r2 while the program is running anyway.

**Comment by matrix1001** [comment]
@n00bSec Well, I forgot to close this issue after PR. Original problem is that `r2` command does not support PIE. I checked your fix. It's also an option.
