### ISSUE TITLE
typo in the pwndbg help list

### ISSUE THREAD

**Issue by properchopsticks** [pwndbg/pwndbg#515]
### Description
hi, there appears to be a typo in the help menu of pwndbg. whenever you access the 'pwndbg' command to see the help list some of the commands that should have the word 'breakpoint' have 'breapoint' instead.

[...]
bc                   Clear the breapoint with the specified index.
bd                   Disable the breapoint with the specified index.
be                   Enable the breapoint with the specified index.
[...]

### Steps to reproduce
starting in terminal:
$: gdb name-of-file
pwndbg> pwndbg

### My setup
Gdb:      8.1.0.20180409-git
Python:   3.6.5 (default, Apr  1 2018, 05:46:30)  [GCC 7.3.0]
Pwndbg:   1.1.0 build: c188ed3
Capstone: 4.0.1024
Unicorn:  1.0.1

**Comment by disconnect3d** [comment]
Thanks for reporting this. Fixed on dev :).
