### ISSUE TITLE
probeleak error

### ISSUE THREAD

**Issue by GrosQuildu** [pwndbg/pwndbg#518]
```
pwndbg> probeleak  0x7ffc75b30008 100
Exception occured: probeleak: 'module' object has no attribute 'warning' (<type 'exceptions.AttributeError'>)
For more info invoke `set exception-verbose on` and rerun the command
or debug it by yourself with `set exception-debugger on`
```
and crash when the args are swaped

**Comment by disconnect3d** [comment]
Gonna fix it in a few days

**Comment by disconnect3d** [comment]
@GrosQuildu do u think of any upper limit for the size of items one would like to display?
Or maybe we could detect the address by checking if the value lies in one of the vmmap...

Neither of the solutions is best as one can create its own vmmap like [0, 1000] (start, end address).

**Comment by GrosQuildu** [comment]
Everything that lies on valid page should be shown by default imho. Maybe optional arg like [max offset from the address]?

**Comment by disconnect3d** [comment]
For reference: https://github.com/pwndbg/pwndbg/pull/525

**Comment by disconnect3d** [comment]
Done in https://github.com/pwndbg/pwndbg/pull/525!
