### ISSUE TITLE
Add _chk functions

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#519]
This should show a bit different arg names:

```
 ► 0x400855    call   __printf_chk@plt <0x400708>
        format: 0x1
        vararg: 0x400abc ◂— outsb  dx, byte ptr [rsi] /* 'Input offset: ' */
```

Functions to support:
* [x] `__printf_chk` (https://github.com/pwndbg/pwndbg/pull/528)
* [ ] `ts_chk`
* [x] `poll_chk`
* [x] `read_chk` (#536)
* [x] `recv_chk`
* [x] `fdelt_chk`
* [x] `fgets_chk` 
* [x] `fread_chk` (#536)
* [ ] `twd_chk`
* [x] `ppoll_chk`
* [x] `pread_chk` (#536)
* [x] `fgetws_chk`
* [ ] `tcwd_chk`
* [x] `memcpy_chk`
* [x] `memset_chk`
* [ ] `printf_chk`
* [x] `stpcpy_chk`
* [x] `strcat_chk`
* [x] `strcpy_chk`
* [x] `wcpcpy_chk`
* [x] `wcscat_chk`
* [x] `wcscpy_chk`
* [x] `wctomb_chk`
* [x] `confstr_chk`
* [ ] `printf_chk`
* [x] `fprintf_chk`
* [ ] `longjmp_chk`
* [x] `memmove_chk`
* [x] `mempcpy_chk`
* [x] `pread64_chk`
* [x] `sprintf_chk`
* [x] `stpncpy_chk`
* [x] `strncat_chk`
* [x] `strncpy_chk`
* [x] `vprintf_chk`
* [x] `wcpncpy_chk`
* [x] `wcrtomb_chk`
* [x] `wcsncat_chk`
* [x] `wcsncpy_chk`
* [x] `wmemcpy_chk`
* [x] `wmemset_chk`
* [x] `wprintf_chk`
* [x] `sysdeps/i386/memcpy_chk.S`
* [x] `sysdeps/i386/memset_chk.S`
* [x] `sysdeps/m68k/wcpcpy_chk`
* [x] `asprintf_chk`
* [x] `fwprintf_chk`
* [x] `mbstowcs_chk`
* [ ] `obprintf_chk`
* [x] `readlink_chk`
* [x] `realpath_chk`

**Comment by disconnect3d** [comment]
Some of them can be inspected e.g. here https://github.com/lattera/glibc/find/master (click `t` and search for `_chk`).

**Comment by disconnect3d** [comment]
Good to read here:

https://github.com/pwndbg/pwndbg/pull/528#issuecomment-422644418

https://github.com/pwndbg/pwndbg/pull/536#issuecomment-426627327

**Comment by disconnect3d** [comment]
I didn't have time to push this further.
I merged https://github.com/pwndbg/pwndbg/pull/536 which was a starting point for this issue.

If anyone is willing to help with this, just say! :)

**Comment by gsingh93** [comment]
@disconnect3d does #998 address this issue? can we close it?

**Comment by disconnect3d** [comment]
I have marked all the functions that directly appear in #998.

Some does not seem to appear but:
* I think their `_chk` functions may have alternative names apart from underscore - e.g. `ts_chk` maybe appears as `__getts_chk`?
* `printf_chk` - perhaps its already there?

Lets close this. Someone can add more if it bothers them. I haven't had problems with those recently :P.
