### ISSUE TITLE
Display source code filename

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#521]
Sometimes we can deduct source code filename, so we should display it in the banner:
```
─────────[ SOURCE (CODE) ]─────────
```

e.g.
```
pwndbg> info line
Line 174 of "../sysdeps/posix/system.c" starts at address 0x7fe22356d153 <do_system+675> and ends at 0x7fe2235
6d157 <do_system+679>.
```

**Comment by anthraxx** [comment]
Taking into account how long these are or could be it could be a better idea to just display a line containing path/filename before listing the source code?
IMO it may look odd, taking into account that the banner label can be left, center or right aligned.

**Comment by disconnect3d** [comment]
> the banner label can be left, center or right aligned

Totally forgot about this.

Yeah, we should probably display the filename (or path) above/below OR maybe instead of `SOURCE (CODE)`?
