### ISSUE TITLE
Exception occured search Invalid mode (CS_ERR_MODE) (<class 'capstone.CsError'

### ISSUE THREAD

**Issue by F1r** [pwndbg/pwndbg#524]
### Description
When I try to use pygdbmi to interact with pwndbg and init gdb by the command as follows:
        init_cmds = ["set exception-verbose on",
                     "source ~/.gdbinit",
                     "set print element 0",
                     "attach {}".format(str(self._pid)),
                     "set charset ASCII"]
, the error as follows occured when i use search command provided by pwndbg
['\\e[31mException', 'occured:', 'search:', 'Invalid', 'mode', '(CS_ERR_MODE)', '(<class', "'capstone.CsError'>)\\e[0m"]

### My setup
Gdb:      7.11.1
Python:   3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
Pwndbg:   1.1.0 build: 84345dc
Capstone: 4.0.1024
Unicorn:  1.0.1

**Comment by F1r** [comment]
It works well in Debian, but this error occured when I use ubuntu16.04.
I install pwntools in the way provided by official and install pwndbg by ./setup.sh.

**Comment by disconnect3d** [comment]
The capstone version should be fine. What's the target binary/arch? That would be weird but maybe capstone doesn't support it? Did you use the same pygdbmi/target binary on Debian and Ubuntu?

Offtopic: It's probably good to update GDB to 8.1 (8.2 seems to be not working yet).

**Comment by F1r** [comment]
Thanks! I upgrade my gdb by building it from source and it indeed solves this problem.
Actually, this problem is caused by gdb version.
Thanks again!
