### ISSUE TITLE
brva doesn't work if the target is a symlink.

### ISSUE THREAD

**Issue by rcx** [pwndbg/pwndbg#538]
```
$ ln -s /bin/cat target
$ gdb ./target
pwndbg> r
^C
0xf779a000 0xf779b000 r-xp     1000 0      /tmp/target
0xf779b000 0xf779c000 r--p     1000 0      /tmp/target
0xf779c000 0xf779d000 rw-p     1000 1000  /tmp/target
pwndbg> brva 0x7B0
There are no memory pages in `vmmap` for specified address=0x7b0 and module=/bin/cat
```

**Comment by disconnect3d** [comment]
Hey, thanks for reporting this!

Can you check out if https://github.com/pwndbg/pwndbg/pull/539 works for you and review this PR?

I hope the added comments are helpful and make things more clear, so if someone plays with this or any more bugs happens here it is easier to play with the code and understand what's going on.

**Comment by rcx** [comment]
Awesome work on the fast response to this. Just reviewed the PR and it LGTM. See my comment there for more details.
