### ISSUE TITLE
can't print the fastbin

### ISSUE THREAD

**Issue by chensem** [pwndbg/pwndbg#550]
i use the fastbin command , it doesn't work

![image](https://user-images.githubusercontent.com/27469499/47131526-ab601a00-d2d1-11e8-95f3-c2c62727849e.png)
![image](https://user-images.githubusercontent.com/27469499/47131532-b9ae3600-d2d1-11e8-9999-8214c252222b.png)

**Comment by disconnect3d** [comment]
@chensem why closing this?
