### ISSUE TITLE
setup.sh for unknown distros is (partially) broken

### ISSUE THREAD

**Issue by chemmi** [pwndbg/pwndbg#551]
The setup.sh for unknown distros (like kali) is partially broken.
This is due to the fact that it exits too early.
The relevant part is:
https://github.com/pwndbg/pwndbg/blob/ab46a7943fd1362c66bff4d085cdd0f5ee42e5ea/setup.sh#L62-L70
This can be fixed by moving =exit= into the else-branch.
One may use =exit 1= instead.

**Comment by disconnect3d** [comment]
@chemmi oh, thanks for catching this. Gonna fix it now o/
