### ISSUE TITLE
The unicorn aarch64 emulator hangs when start from the address 0x0

### ISSUE THREAD

**Issue by equation314** [pwndbg/pwndbg#556]
### Description

This is a bug of unicorn. The second parameter `until` of `uc.emu_start()` is always `0`, it cause hanging when the first parameter `begin` is also `0`, according to [https://github.com/unicorn-engine/unicorn/issues/1038](https://github.com/unicorn-engine/unicorn/issues/1038).

Here is the [https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/emu/emulator.py](https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/emu/emulator.py), line 322~325:

```py
try:
    self.emu_start(self.pc, 0, count=count)
finally:
    self.hook_del(ident)
```

### My setup

```
Gdb:      8.0.1
Python:   2.7.10 (default, Aug 17 2018, 17:41:52)  [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]
Pwndbg:   1.1.0 build: 4a34137
Capstone: 4.0.1024
Unicorn:  1.0.1
```

**Comment by disconnect3d** [comment]
Nice catch. Not sure if we can do anything with it except of waiting for an upstream fix?

**Comment by equation314** [comment]
Sorry, the latest unicorn (unreleased) fixed this.
