### ISSUE TITLE
pwndbg displays not well in docker tmux 

### ISSUE THREAD

**Issue by thinkycx** [pwndbg/pwndbg#565]
### Description

Hello , I use the latest verison of pwndbg.
When I use it in docker , I use tmux and run the gdb.
It displays not well like the picture bellow.
Could you fix it ?

![image](https://user-images.githubusercontent.com/13138128/47779435-0e22ce00-dd34-11e8-87d0-ec34db235103.png)

**Comment by disconnect3d** [comment]
Hmm I have used pwndbg with tmux before and it worked fine.

Can you share your tmux configuration?

**Comment by thinkycx** [comment]
> Hmm I have used pwndbg with tmux before and it worked fine.
> 
> Can you share your tmux configuration?

I use the default tmux and only add mouse settings in it
```
$ cat ~/.tmux.conf
set -g mouse on

#Enable oh my zsh in tmux
set -g default-command /bin/zsh

# Mouse based copy
bind-key -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
bind-key -T copy-mode MouseDragEnd1Pane send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
```

**Comment by thinkycx** [comment]
> Hmm I have used pwndbg with tmux before and it worked fine.
> 
> Can you share your tmux configuration?
```
# root @ d7af3bda10e2
$ cat ~/.tmux.conf
set-option -g mouse on
#setw -g mouse

# root @ d7af3bda10e2
$ tmux -V
tmux 2.1
```
After I clear tmux's configuration, it still displays not well.
I think that it might be pwndbg's output problem with tmux.
Is this a bug？

After I change to peda, it works well. 
Wish pwndbg will work well with tmux in future.

**Comment by disconnect3d** [comment]
I will check it out today on my setup. I still feel it worked before... :S

**Comment by disconnect3d** [comment]
Can u show ur gdbinit file?

**Comment by disconnect3d** [comment]
![image](https://user-images.githubusercontent.com/10009354/47886848-bde36300-de3c-11e8-86ad-deaa31a295e0.png)
it still works for me. I used tmux on a remote machine, not sure if that matters?

Also, my tmux version is 2.6 - maybe it is the problem?

**Comment by thinkycx** [comment]
> ![image](https://user-images.githubusercontent.com/10009354/47886848-bde36300-de3c-11e8-86ad-deaa31a295e0.png)
> it still works for me. I used tmux on a remote machine, not sure if that matters?
> 
> Also, my tmux version is 2.6 - maybe it is the problem?

**Thanks for your reply.**
At last, I figure out the problem is tmux.
**Tmux version 2.1 does't work well with pwndbg.**
And I change my tmux to the lastest version next-2.9 and 2.6 is both ok as can be seen in your picture.

My bash script for compiling the lastest tmux is here:
https://gist.github.com/thinkycx/8323b10474c2c9d35cc16c6355a56259
