### ISSUE TITLE
bug in heap command

### ISSUE THREAD

**Issue by matrix1001** [pwndbg/pwndbg#568]
### Description

Bug of command heap

### Steps to reproduce

This bug is due to a strange alignment strategy in newer version of 32 bit glibc.

In a nutshell, the first 16 bytes of heap is 0 in glibc-2.26 (32bit), glibc-2.27 (32bit).

As a result, while parsing heap, the first chunk has size 0 and trigger stop.

### My setup

No need for setup, just check those two glibc.

![image](https://user-images.githubusercontent.com/32097922/48119835-52b9e680-e2ab-11e8-8b90-b0919e308778.png)

### My fix

fix is really easy, just ignore the first chunk if size is 0.

**Comment by disconnect3d** [comment]
I believe the reason of this is thread cache and that a lot of bytes in there belong to `tcache_perthread_struct`, see https://github.com/pwndbg/pwndbg/pull/552#issuecomment-431706323

The `tcache_perthread_struct` structure layout can be seen here -  https://github.com/bminor/glibc/blob/master/malloc/malloc.c#L2898-L2902 , it starts with `char[64]` and then has `tcache_entry*[64]`.

**Comment by matrix1001** [comment]
I doubt that.

Check this (32bit libc-2.26).

![image](https://user-images.githubusercontent.com/32097922/48207747-49647300-e3ac-11e8-9b5a-adf2bb89fe98.png)

So I believe the reason is `_int_malloc`. 

And a bug view.
```
pwndbg> heap
0x5655a000 {
  mchunk_prev_size = 0,
  mchunk_size = 0,
  fd = 0x0,
  bk = 0x151,
  fd_nextsize = 0x0,
  bk_nextsize = 0x0
}
pwndbg>

```

**Comment by disconnect3d** [comment]
I believe it was fixed with https://github.com/pwndbg/pwndbg/pull/571
