### ISSUE TITLE
Add xuntil command from peda

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#574]
```
xuntil -- Continue execution until an address or function
```

e.g. `xuntil <expr>` where expr is an address/symbol; as a result we want an one time breakpoint + continue with given arguments.

I think we can also extend it with running the program if it is not started yet.

**Comment by ysf** [comment]
Is this needed with break_on_next(address) and break_next_call ? Or is this required for PEDA compatibility?

**Comment by disconnect3d** [comment]
I was asked to add this. Not sure what do you ask by:
> Is this needed with break_on_next(address) and break_next_call

I guess this functionality might use one of those functions

**Comment by alissonbezerra** [comment]
I'd like to take care of it as a first contribution.

**Comment by disconnect3d** [comment]
@alissonbezerra That's great! If you need any help feel free to write here or e.g. on freenode irc #pwndbg (or PM me there - disconnect3d).

**Comment by stnevans** [comment]
Looks like this can be closed. If anyone thinks this should be reopened, feel free.
