### ISSUE TITLE
pwndbg will not display source code when source code has chinese characters

### ISSUE THREAD

**Issue by thinkycx** [pwndbg/pwndbg#578]
When use directory glibc source in gdb(directory /root/Pwn/glibc/glibc-2.23/malloc),  it will display the source code in pwndbg like this:
![image](https://user-images.githubusercontent.com/13138128/49008442-cb280f00-f1a8-11e8-9bd9-7bae523ecbfa.png)

However, **when I add Chinese characters in souce code like this**, pwndbg will not display it . Is this a bug? Will you fix it?
![image](https://user-images.githubusercontent.com/13138128/49008565-180be580-f1a9-11e8-8d09-3992ae6c6ceb.png)

**Comment by disconnect3d** [comment]
Yes it is a bug. Can you show an example of those chars here on GitHub?

**Comment by thinkycx** [comment]
OK. You can paste the Chinese code below in any code.
```
// comment 注释：中华人民共和国万岁！
```
@disconnect3d

**Comment by disconnect3d** [comment]
@thinkycx Please try with latest dev, should be fixed now :)

**Comment by thinkycx** [comment]
It works! Thank you man!  Your **bug fixing** speed is very fast!
![image](https://user-images.githubusercontent.com/13138128/49072100-751ba000-f26a-11e8-89fb-711ea98c295b.png)
@disconnect3d
