### ISSUE TITLE
Integration of Pwntools

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#595]
Now that Pwntools has a dual Python2/3-compatible branch [dev3](https://github.com/Gallopsled/pwntools/tree/dev3), we should investigate integrating it into Pwndbg.

I duplicated lots of functionality when writing Pwndbg, or just outright copy-pasted from pwntools.  Integration is currently very loose, and just shells out to e.g. `pwn shellcraft` command-line tools.

Pwndbg will remain wholly separate, but it should be able to depend on parts of `pwnlib` as a library, rather than an external binary, if it's convenient.

**Comment by anthraxx** [comment]
I see where you are coming from. but if we replace core parts of pwndbg with calls to pwnlib, it becomes a hard dependency which makes is currently npita to properly maintain on a distro level as pwnlib has lot more dependencies and force `sortedcontainers<2.0` etc, which is very bad for Arch packaging f.e.

EDIT: in general I like the idea and we could add proper debruijn pattern support like other gdb integrations do, but we should revisig pwntools to bump the dependencies to latest versions without pinning. It looks like the issues got resolved and new releases published.

**Comment by zachriggle** [comment]
@anthraxx definitely a good point on introducing dependencies.  I have no problem blocking integration on that.
