### ISSUE TITLE
setup.py: provide a platform independent setup.py

### ISSUE THREAD

**Issue by blshkv** [pwndbg/pwndbg#598]
I'm not sure if I need to explain, but there is a universal way to handle the installation and uninstallation of a python package using setup.py. It can co-exist with the current setup.sh. In fact setup.sh could call setup.py at some point (after all deps are installed, etc)

This mechanism (using setup.py) is used by all linux distributions so it would allow to push latest releases of pwndbg almost instantly.

Here is nice example of how it can be done:
https://github.com/derv82/wifite2/issues/102

Thanks in advance

**Comment by disconnect3d** [comment]
We already had some discussion regarding setup script  (https://github.com/pwndbg/pwndbg/issues/296#issuecomment-430149413) and I think that's good idea to create setup.py. It's also probably not that hard to do so.

Would you mind sending a PR adding this and modifying the setup.sh so it would use it instead? The setup.sh is probably still needed for things "not covered" by Python part: e.g. libc debug symbols.

**Comment by blshkv** [comment]
Sorry, I don't have time for the initial change. But I will definitely test and help to fix any bugs later

**Comment by piotrzarycki** [comment]
I will take care of it

**Comment by SilvaMatteus** [comment]
Is a PR still interesting? I see that this issue is marked as a good first issue.
I have been using pwndbg and I want to start contributing. Maybe this could be my first step.

**Comment by stnevans** [comment]
I would tend to say yes, the installation process could be improved to work on more distros.
I'm not really sure how setup.py works, or how easy it would be to convert [setup.sh](https://github.com/pwndbg/pwndbg/blob/dev/setup.sh) to use it. 
pwndbg depends on a couple packages (some are not necessarily 100% required for it to run, but help with some things. e.g. libc-dbg for heap).

**Comment by zachriggle** [comment]
Unfortunately there's not a 100%-agnostic way to do `pip install pwndbg` or `python setup.py` which ensures an optimal experience.  A good example of this is installation of `libc` debug symbols (i.e. `apt-get install libc6-dbg`).

In particular, the biggest issue is that Pwndbg **must** be installed with the same Python package directory as the one linked to with GDB, which may not be the default Python, or even the system Python.  This is mostly captured in the `${INSTALLFLAGS}` which are passed into `pip install`.  One particularly weird case is when e.g. `gdb` is linked against `libpython2.7` but there is no `python27` interpreter on the machine at all, only `python3`.

Since the Python used by GDB may not have `setuptools` or `pip` available to it, there's a lot of hoops we have to jump through to make sure things work -- since we may be borrowing setuptools from a different python.

I definitely agree that it would be GREAT to have a single, unified, platform-agnostic installation experience -- and would encourage contributions toward that.  I just wanted to outline some of the reasons we haven't already done that, and some of the challenges that you might face.

Generally, the experience *can* be just `pip install -U --editable .` to get `pwndbg` up and running, and then `source`'ing it in your `gdbinit`.  You'll just miss out on lots of things, or some things may be broken, if some things are missing.  We may want to have a different failure case for "not supported" and just try our best after having the user acknowledge the limitation, e.g. something like:

```bash
echo "Your distribution is not supported, and things may be broken."
echo "Would you like to try to install Pwndbg anyway?"
read -p "(y/n): " yn
case $yn in
    [Yy]*) ;;
    *) exit 1
esac
```

**Comment by blshkv** [comment]
I think setup.py is designed specifically to solve such problems. First of all, if you have gdb linked against python2 but python2 is not installed - this is a broken setup. User's should use a system package manager to keep the env in sane state.

Secondly, ```pip{2,3}``` and python{2,3} can be used with setup.py to build against a specific version, so it should not be an issue.

**Comment by zachriggle** [comment]
I don’t disagree, but the fact of the matter is these setups exist and are not uncommon.  This was particularly the case for some Ubuntu distrust which shipped a py2 installed but linked GDB against py3 (or vice versa, I forget).

You can probably find more info by searching past issues.

**Comment by blshkv** [comment]
That's why i dont use Ubuntu :-). At Gentoo, it will be recompiled automatically

**Comment by zachriggle** [comment]
I think in the immediate term it might be easier to contribute a Gentoo-compatible set of commands to `setup.sh`.

A great many of our users are on Ubuntu, and this is what you get on 16.04:

```
$ apt-get update
...
$ apt-get install python-pip
...
$ apt-get install gdb
...
The following NEW packages will be installed:
  gdb gdbserver libbabeltrace-ctf1 libbabeltrace1 libc6-dbg libglib2.0-0 libglib2.0-data libicu55 libmpdec2 libpython3.5
  libpython3.5-minimal libpython3.5-stdlib libxml2 sgml-base shared-mime-info xdg-user-dirs xml-core
```

As you can see, Ubuntu 16.04 (and possibly 18.04) include a GDB linked against `python3.5`, and do include `libpython3.5`, but do not actually include a `python3.5` interpreter.  This is not something that can easily be worked around in `setup.py` without shelling out to `apt-get install`, which somewhat defeats the purpose.

```
root@51d61a10a0ee:/# gdb -batch -q --nx -ex 'pi import platform; print(".".join(platform.python_version_tuple()[:2]))'
3.5
root@51d61a10a0ee:/# python3.5 -c 'import platform; print(".".join(platform.python_version_tuple()[:2]))'
bash: python3.5: command not found
```

**Comment by blshkv** [comment]
@zachriggle you are looking at the problem from a wrong angle or don't understand the issue. Your setup.sh is basically a hack for a user while I'm talking about packaging the tool for a distro properly so that it would be possible to install it using a standard command ```apt install pwndbg```. In order to make our life easier, we (package maintainers of each distro) need the setup.py. Once created, we would create a script which would do something like this:
```
#!/bin/distro_setup
dependencies="python,gdb"
install="setup.py"
```
and it is a really few lines because ```/bin/distro_setup``` provides all required variables and functions so you don't need to do anything.

Without that, we need to inspect every new version of your setup.sh script for new changes and install all files manually which creates a huge load on us.

**Comment by blshkv** [comment]
Please also see: https://github.com/laramies/theHarvester/issues/52 where we managed to get rid of their ```install.sh``` hack too.
The end results is there: https://github.com/pentoo/pentoo-overlay/blob/master/net-analyzer/theHarvester/theHarvester-3.0.6_p20190415.ebuild and shorten version looks like this:
```
inherit distutils-r1
RDEPEND="dev-python/beautifulsoup[${PYTHON_USEDEP}] net-analyzer/wfuzz[${PYTHON_USEDEP}]```
```
The distutils script runs setup.py automatically so we don't need to do anything at all. PYTHON_USEDEP is a system variable and it forces ***ALL*** installed packages to be compiled with the correct (can be multiple) version of python.

**Comment by SilvaMatteus** [comment]
The issue seems to be more complicated than I thought. I am studying for a test (the last test before I get my graduation degree \o/) right now, but I'll think about that soon.

**Comment by SilvaMatteus** [comment]
@blshkv, I think I understood your point. I'll start in this direction.
Do you think this is still a good first issue? Could I count on your help if I get stuck? :)

**Comment by gsingh93** [comment]
@disconnect3d can we close this?

**Comment by blshkv** [comment]
Yes, ```pyproject.toml``` file is a newer alternative, thanks guys!
FYI, the package has been accepted to the main Gentoo tree after that.
