### ISSUE TITLE
'dt' feature compiler issues

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#6]
The current feature is not clean, and doesn't work well for anything but the OS-native architecture.  This is because the current approach globs all of the header files form the OS-native architecture directory, and passes them to alternate-architecture compilers.  

This has two issues:
- Arch-specific headers may not get pulled in or use the wrong ones
- Not all headers may exist for the alternate architecture (e.g. Python.h won't appear for ARM)

We should rework how this all works, perhaps with a whitelist of header files instead of a blacklist, and allowing the user to specify additional header files.

**Comment by disconnect3d** [comment]
FWIW current behavior of dt - we recently removed the logic that it tried to find types in system headers:
<img width="671" alt="image" src="https://user-images.githubusercontent.com/10009354/193487957-d931e156-94af-4e2b-90c4-9405a4872902.png">

**Comment by disconnect3d** [comment]
Also, if the type implements nested types, `dt` doesn't show it that great as e.g. `ptype`:
<img width="687" alt="image" src="https://user-images.githubusercontent.com/10009354/193488260-2df8e9c5-988d-4a0c-9ad0-0f8b5d2d6345.png">

Though `ptype` output is still bloated.

Also `dt` does not currently support arguments which are variable names and doesn't work with spaces (have to be quoted).

**Comment by disconnect3d** [comment]
This issue has been fixed or made irrelevant at some point and so is invalid anymore. Closing.

```
pwndbg> dt 'struct malloc_par' $rsp
struct malloc_par
    +0x0000 trim_threshold       : long unsigned int
    +0x0008 top_pad              : size_t
    +0x0010 mmap_threshold       : size_t
    +0x0018 arena_test           : size_t
    +0x0020 arena_max            : size_t
    +0x0028 thp_pagesize         : size_t
    +0x0030 hp_pagesize          : size_t
    +0x0038 hp_flags             : int
    +0x003c n_mmaps              : int
    +0x0040 n_mmaps_max          : int
    +0x0044 max_n_mmaps          : int
    +0x0048 no_dyn_threshold     : int
    +0x0050 mmapped_mem          : size_t
    +0x0058 max_mmapped_mem      : size_t
    +0x0060 sbrk_base            : char *
    +0x0068 tcache_bins          : size_t
    +0x0070 tcache_max_bytes     : size_t
    +0x0078 tcache_count         : size_t
    +0x0080 tcache_unsorted_limit : size_t
pwndbg> 
```
