### ISSUE TITLE
Incorrect symbol resolution in remote targets

### ISSUE THREAD

**Issue by duckythescientist** [pwndbg/pwndbg#600]
### Description

Symbol address resolution seems to be incorrect (inconsistently?) for remote targets. This is an issue with both `gdbserver` and `qemu-user` methods of executing the binary.

With a native gdbserver, `main` resolves correctly, but another symbol (`my_symbol`) in main resolves incorrectly. Gdb has the correct offset from `main` for `my_symbol`, though. After I execute `file native.elf` in gdb, `main` no longer resolves correctly, but `main+offset` is now the original (incorrect) address for `my_symbol`. The differences are equal to the offset of `.text`.

It's worse with native `qemu-user`. `main` never resolves properly.

With `qemu-arm`, it's differently wrong. If I don't specify the file before the target, neither symbol is resolved correctly. Once I load the file, `main` is still wrong, but `my_symbol is correct`. If I specify the file in the gdb command, `main` is correct, but `my_symbol` is wrong. If I then load in the file, it fixes `my_symbol` but makes `main` incorrect. After that, if I single step, both symbols end up with the wrong address. The offsets are wrong by the lower half word of the `.text` offset.

I've been working on figuring out why this is happening, but I'm struggling because of how inconsistent the behavior is. I may be missing some observation that ties all of this together. I'll keep working on it, but I'm hoping that someone else can quickly find the root cause.

Let me know if I need to add more details, but I think I'm approaching overkill already.

This is possibly related to #177 but I'm unsure.

### Steps to reproduce
```C
#include <stdio.h>

int main() {
    puts("Hello, world");
    asm("my_symbol: nop;");
    return 0;
}
```

#### Native x64 gdbserver
`gcc test.c -o native.elf`
Using `objdump`, `main` is at 0x63a  in `.text`, and `my_symbol` is at 0x64a in `.text`. `.text` is at 0x530.

`gdbserver localhost:3333 ./native.elf`

```
$ gdb -ex 'target remote localhost:3333'
pwndbg> p main
$1 = {<text variable, no debug info>} 0x55555555463a <main>
pwndbg> p my_symbol
$2 = {<text variable, no debug info>} 0x55555555411a <main+16>
pwndbg> p main+16
$3 = (<text variable, no debug info> *) 0x55555555464a <main+16>
pwndbg> file ./native.elf
Reading symbols from ./native.elf...(no debugging symbols found)...done.
pwndbg> p main
$4 = {<text variable, no debug info>} 0x55555555410a <main>
pwndbg> p my_symbol
Cannot access memory at address 0x64a
pwndbg> p main+16
$5 = (<text variable, no debug info> *) 0x55555555411a <main+16>
```

`gdbserver localhost:3333 ./native.elf`

```
$ gdb -ex 'file ./native.elf' -ex 'target remote localhost:3333'
... exactly the same as without the 'file ./native.elf' ...
```

`qemu-x86_64 -L /usr/arm-linux-gnueabi -g 3333 ./native.elf`

```
$ gdb -ex 'target remote localhost:3333'
pwndbg> p main
$1 = {<text variable, no debug info>} 0x400000010a <main>
pwndbg> p my_symbol
$2 = {<text variable, no debug info>} 0x400000011a <main+16>
pwndbg> p main+16
$3 = (<text variable, no debug info> *) 0x400000011a <main+16>
pwndbg> file ./native.elf
Reading symbols from ./native.elf...(no debugging symbols found)...done.
pwndbg> p main
$4 = {<text variable, no debug info>} 0x400000010a <main>
pwndbg> p my_symbol
Cannot access memory at address 0x64a
pwndbg> p main+16
$5 = (<text variable, no debug info> *) 0x400000011a <main+16>
```

`qemu-x86_64 -L /usr/arm-linux-gnueabi -g 3333 ./native.elf`

```
$ gdb -ex 'file ./native.elf' -ex 'target remote localhost:3333'
pwndbg> p main
Cannot access memory at address 0x63a
pwndbg> p my_symbol
$1 = {<text variable, no debug info>} 0x400000011a <main+16>
pwndbg> p main+16
$2 = (<text variable, no debug info> *) 0x64a <main+16>
pwndbg> file ./native.elf
Reading symbols from ./native.elf...(no debugging symbols found)...done.
pwndbg> p main
$3 = {<text variable, no debug info>} 0x400000010a <main>
pwndbg> p my_symbol
Cannot access memory at address 0x64a
pwndbg> p main+16
$4 = (<text variable, no debug info> *) 0x400000011a <main+16>
```

#### Qemu-user arm
`arm-linux-gnueabi-gcc test.c -o arm.elf`
Using `objdump`, `main` is at 0x103fc  in `.text`, and `my_symbol` is at 0x1040c in `.text`. `.text` is at 0x1030c.

`qemu-arm -L /usr/arm-linux-gnueabi -g 3333 ./arm.elf`

```
$ gdb-multiarch -ex 'target remote localhost:3333'
pwndbg> p main
$1 = {<text variable, no debug info>} 0x100f0 <main>
pwndbg> p my_symbol
$2 = {<text variable, no debug info>} 0x10100 <main+16>
pwndbg> p main+16
$3 = (<text variable, no debug info> *) 0x10100 <main+16>
pwndbg> file ./arm.elf
Reading symbols from ./arm.elf...(no debugging symbols found)...done.
pwndbg> p main
$4 = {<text variable, no debug info>} 0x100f0 <main>
pwndbg> p my_symbol
$5 = {<text variable, no debug info>} 0x1040c <main+16>
pwndbg> p main+16
$6 = (<text variable, no debug info> *) 0x10100 <main+16>
```

`qemu-arm -L /usr/arm-linux-gnueabi -g 3333 ./arm.elf`

```
$ gdb-multiarch -ex 'file ./arm.elf' -ex 'target remote localhost:3333'
pwndbg> p main
$1 = {<text variable, no debug info>} 0x103fc <main>
pwndbg> p my_symbol
$2 = {<text variable, no debug info>} 0x10100 <main+16>
pwndbg> p main+16
$3 = (<text variable, no debug info> *) 0x1040c <main+16>
pwndbg> file ./arm.elf
Reading symbols from ./arm.elf...(no debugging symbols found)...done.
pwndbg> p main
$4 = {<text variable, no debug info>} 0x100f0 <main>
pwndbg> p my_symbol
$5 = {<text variable, no debug info>} 0x1040c <main+16>
pwndbg> p main+16
$6 = (<text variable, no debug info> *) 0x10100 <main+16>

pwndbg> si

pwndbg> p main
$7 = {<text variable, no debug info>} 0x100f0 <main>
pwndbg> p my_symbol
$8 = {<text variable, no debug info>} 0x10100 <main+16>

```

### My setup

Ubuntu 18.04.2 LTS

gdb:
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git

python:
3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]

pwndbg:
commit 0f4e31e72a10320670f04616041ab800fc9cadf1 (HEAD -> dev, origin/dev, origin/HEAD)
Thu Feb 28 01:09:15 2019 +0800

**Comment by disconnect3d** [comment]
Hey,

thx for reporting this. I don't really have time to dive into it right now; I will try to look at this again next week.

This being said, I found the `file` command in gdb buggy sometimes - e.g. using it many times and attaching/running different binaries shown weird results. Can you see if this behaviour persists if you use `gdb ./binary` instead of `gdb -ex ./binary`? Also, if this is related to pwndbg at all? (I assume so as you mentioned pwndbg symbol adding).

**Comment by disconnect3d** [comment]
Btw this: `qemu-x86_64 -L /usr/arm-linux-gnueabi` feels wrong - i.e. you mismatch the  qemu target architecture with `-L` target architecture (x86-64 vs arm-gnueabi).

**Comment by disconnect3d** [comment]
Also the symbol stuff is related to the fact there is PIE + qemu/gdb not handling this properly.

I am not sure if we can do sth about that in pwndbg...

---

Below an example.

```
$ objdump -d -Mintel ./a.out | grep 'main>:'
000000000000063a <main>:

$ qemu-x86_64 -g 3333 ./a.out
warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
```
and in another console:
```
$ gdb ./a.out -q -ex 'target remote localhost:3333'
Reading symbols from ./a.out...(no debugging symbols found)...done.
Remote debugging using localhost:3333
warning: remote target does not support file transfer, attempting to access files from local filesystem.
Reading symbols from /lib64/ld-linux-x86-64.so.2...Reading symbols from /usr/lib/debug//lib/x86_64-linux-gnu/ld-2.27.so...done.
done.
0x0000004000a04090 in _start () from /lib64/ld-linux-x86-64.so.2
(gdb) p main
Cannot access memory at address 0x63a
(gdb) p my_symbol
Cannot access memory at address 0x64a
```

**Comment by CptGibbon** [comment]
I don't want to write this off as a qemu/gdb issue. I'm seeing the exact same behavior, symbol addresses getting misreported, but only when pwndbg is in use. Vanilla gdb reports the same symbols at their correct position. The binaries in question are all non-position-independent, so it's not a PIE issue either.

Perhaps this is related to #765, which I'm also seeing, although only when single-stepping MIPS code and again only when pwndbg is in use.
