### ISSUE TITLE
Cyclic utlity no longer working

### ISSUE THREAD

**Issue by AdamVanScyoc** [pwndbg/pwndbg#607]
### Description
The "cyclic" utility, accessed from within an open GDB (pwndbg) session, has apparently regressed and no longer works.

`pwndbg> cyclic 1`
`Traceback (most recent call last):
  File "/usr/local/bin/cyclic", line 7, in <module>
    from pwnlib.commandline.common import main
ModuleNotFoundError: No module named 'pwnlib'
`

### Steps to reproduce
Open a pwndbg/gdb session with a valid binary, run `start`, and simple try to execute cyclic with a valid integer:
`cyclic 1`

### My setup
`uname -a`
`Linux kali 4.19.0-kali1-amd64 #1 SMP Debian 4.19.13-1kali1 (2019-01-03) x86_64 GNU/Linux
`

`pwndbg> version`
`Gdb:      8.2.1`
`Python:   3.7.3rc1 (default, Mar 13 2019, 11:01:15)  [GCC 8.3.0]`
`Pwndbg:   1.1.0 build: 09e1b37`
`Capstone: 4.0.1024`
`Unicorn:  1.0.1`

**Comment by AdamVanScyoc** [comment]
My mistake; needed to clone and pull latest version of the checksec script from here: https://github.com/slimm609/checksec.sh

**Comment by disconnect3d** [comment]
Hey,

cyclic is a command installed with pwntools (https://github.com/Gallopsled/pwntools). I have checked it and it works on my machine.

It seems like some python virtual(?) environment problem - can you try e.g. reinstalling pwntools?

Since this is not a pwndbg issue, I am closing it.
