### ISSUE TITLE
IDA Integration: <type 'exceptions.RuntimeError'>:Function can be called from the main thread only

### ISSUE THREAD

**Issue by NyaMisty** [pwndbg/pwndbg#626]
### Description

From IDA 7.2, all function marked as THREAD_SAFE in SDK will be checked if they are called on the main thread

### Steps to reproduce

Pwndbg together with IDA 7,2

### My setup

Newest Pwndbg (commit #af4d6fbe5af12ce2b25476ee65020613483809bc), IDA Pro 7.2 windows

### Possible Fix
I've changed the L133 of ida_script.py from
```server.register_function(decompile)  # overwrites idaapi/ida_hexrays.decompie```
to
```server.register_function(wrap(decompile))  # overwrites idaapi/ida_hexrays.decompie```
also there is a small typo "decompie" we can fix them as well ;)

**Comment by disconnect3d** [comment]
Hey, thanks for reporting the issue. Can you send a PR with that fix?

**Comment by NyaMisty** [comment]
Sure~ PR already sent, I'll close issue.
