### ISSUE TITLE
Don't activate the IDA view when stepping in the pwndbg

### ISSUE THREAD

**Issue by NyaMisty** [pwndbg/pwndbg#627]
### Description

By default the pwndbg will execute Jump(ea) function when we step to a new instruction. However the idc.Jump(ea) function calls the 
`inline bool jumpto(ea_t ea, int opnum=-1, int uijmp_flags=UIJMP_ACTIVATE)`
internally with the default parameter. You can see the UIJMP_ACTIVATE is the default flag and this will instruct the IDA to activate the target view, which will grab the focus (at least on Windows)
Because of this, every time I step in the pwndbg, the focus will shifted into IDA and I have to focus back to pwndbg manually which is quite annoying

### Steps to reproduce

Use the pwndbg with IDA Pro and then do stepping in pwndbg

### My setup

newest pwndbg with IDA Pro 7.2 on Windows

### Possible Fix
We can change the L230 of pwndbg/ida.py
from 
```return _ida.Jump(addr)```
to
```return _ida.jumpto(addr, -1, 0)```
which means we manually set the flag to 0, instead of UIJMP_ACTIVATE.

**Comment by disconnect3d** [comment]
Yay, I literally had a love-hate relationship with pwndbg<->ida integration as sometimes I had this issue and sometimes I hadn't. I never had time to investigate it deeply why it happens so here we are!

Please, send a PR and thanks a lot for this!

**Comment by NyaMisty** [comment]
Haha, time is money. And Hex-Rays team does need to improve their documentation. :D
