### ISSUE TITLE
Display readable errors when debugging with stripped libc

### ISSUE THREAD

**Issue by orenht** [pwndbg/pwndbg#634]
### Description

This is related to #509, I believe it's the same problem he had there.
When you debug a program that loads a libc without debug symbols, various heap commands don't work (because you need to display the inner variables).
When I enter a command such as `heap`, it throws an exception:
```
pwndbg> heap
'heap': Prints out chunks starting from the address specified by `addr`.
Traceback (most recent call last):
  File "/opt/pwndbg/pwndbg/commands/__init__.py", line 135, in __call__
    return self.function(*args, **kwargs)
  File "/opt/pwndbg/pwndbg/commands/__init__.py", line 226, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/opt/pwndbg/pwndbg/commands/__init__.py", line 234, in _OnlyWhenHeapIsInitialized
    if pwndbg.heap.current.is_initialized():
  File "/opt/pwndbg/pwndbg/heap/ptmalloc.py", line 573, in is_initialized
    return self.global_max_fast != 0
  File "/opt/pwndbg/pwndbg/heap/ptmalloc.py", line 200, in global_max_fast
    return pwndbg.memory.u(addr)
  File "/opt/pwndbg/pwndbg/memory.py", line 245, in u
    }[size](addr)
  File "/opt/pwndbg/pwndbg/memory.py", line 228, in u64
    return readtype(pwndbg.typeinfo.uint64, addr)
  File "/opt/pwndbg/pwndbg/memory.py", line 87, in readtype
    return int(gdb.Value(addr).cast(gdb_type.pointer()).dereference())
TypeError: Could not convert Python object: None.


```

It would be nice if it was showing a nice error message that says something along the lines of:

> Your libc is stripped and debug symbols are unavailable (searched in directories <1> <2> <3>). Commands manipulating the inner workings of libc will not work. 

### Steps to reproduce

debug a program with a stripped libc without debug symbols, and run the `heap` command.

### My setup

Platform: Linux-4.19.0-kali3-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
Gdb:      8.2.1
Python:   3.7.3rc1 (default, Mar 13 2019, 11:01:15)  [GCC 8.3.0]
Pwndbg:   1.1.0 build: 45a624e
Capstone: 4.0.1024
Unicorn:  1.0.1
This GDB was configured as follows:
   configure --host=x86_64-linux-gnu --target=x86_64-linux-gnu
             --with-auto-load-dir=$debugdir:$datadir/auto-load
             --with-auto-load-safe-path=$debugdir:$datadir/auto-load
             --with-expat
             --with-gdb-datadir=/usr/share/gdb (relocatable)
             --with-jit-reader-dir=/usr/lib/gdb (relocatable)
             --without-libunwind-ia64
             --with-lzma
             --with-babeltrace
             --with-intel-pt
             --disable-libmcheck
             --without-mpfr
             --with-python=/usr (relocatable)
             --without-guile
             --with-separate-debug-dir=/usr/lib/debug (relocatable)
             --with-system-gdbinit=/etc/gdb/gdbinit

**Comment by disconnect3d** [comment]
Hey, thanks for reporting this. Yeah, we should definetely improve it.

Would you @orenht or @mzr like to try to improve it and send a PR? (I ask @mzr too as I know he works a bit on libc stuff recently :P).

**Comment by mzr** [comment]
Currently pwndbg doesn't support heap commands without libc's debug symbols. I agree that there should be some clear message saying that. 

In order to make it work right now, one solution is to find debug symbols for the given libc manually. It is possible for commonly known libc builds (eg Ubuntu has package `libc6-dbg` with separate debug symbols for corresponding libc package). Having that, you can merge debug symbols with given libc using `objcopy` or use `set debug-file-directory` command. ([doc](https://sourceware.org/gdb/onlinedocs/gdb/Separate-Debug-Files.html))

One way of implementing checking for debug symbols could be some decorator `OnlyWithLibcDebugSymbols` similar to `OnlyWhenHeapIsInitialized`. PR #635.

**Comment by disconnect3d** [comment]
Added in #635  - thanks!
