### ISSUE TITLE
FileNotFoundError not defined for python2

### ISSUE THREAD

**Issue by stnevans** [pwndbg/pwndbg#645]
### Description
When a binary has debug symbols but the file cannot be found, a FileNotFoundError occurs if python3 is in use. The issue is that python2 doesn't seem to have FileNotFoundError. 
The relevant code is here:
https://github.com/pwndbg/pwndbg/blob/6747be234132b0a7ea2a93c8aea39f0e3bb0ccbf/pwndbg/commands/context.py#L250-L253

### Steps to reproduce
Use python2. Follow the steps in #644. 

### My setup
Gdb:      8.2
Python:   2.7.12 (default, Nov 12 2018, 14:36:49)  [GCC 5.4.0 20160609]
Pwndbg:   1.1.0 build: 3408e99

Backtrace
```
pwndbg> context
Traceback (most recent call last):
  File "/home/user/Desktop/github/pwndbg/pwndbg/commands/__init__.py", line 136, in __call__
    return self.function(*args, **kwargs)
  File "/home/user/Desktop/github/pwndbg/pwndbg/commands/__init__.py", line 227, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/home/user/Desktop/github/pwndbg/pwndbg/commands/context.py", line 112, in context
    result.extend(func())
  File "/home/user/Desktop/github/pwndbg/pwndbg/commands/context.py", line 292, in context_code
    filename, formatted_source = get_filename_and_formatted_source()
  File "/home/user/Desktop/github/pwndbg/pwndbg/commands/context.py", line 252, in get_filename_and_formatted_source
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined
```

It seems like we should just use IOError instead of FileNotFoundError, but I'm not very familiar with python2 vs python3. Would that work @disconnect3d ?

**Comment by stnevans** [comment]
I'm also not totally sure: are we trying to support python2 and python3? Or just python3?

**Comment by disconnect3d** [comment]
We are targeting both Py2 and Py3 for now. I am thinking more towards supporting only Python 3 but we should discuss it first, so at least one more release will support both Py2 and Py3.

> It seems like we should just use IOError instead of FileNotFoundError, but I'm not very familiar with python2 vs python3. Would that work @disconnect3d ?

`IOError` is more broad, but it should be fine here.

**Comment by disconnect3d** [comment]
Fixed in https://github.com/pwndbg/pwndbg/commit/60a1a722f44d12a8133a274d494c7b4b462600b2
(should have made a better commit log :()
