### ISSUE TITLE
ropper command gives unintuitive addresses

### ISSUE THREAD

**Issue by mzr** [pwndbg/pwndbg#647]
When the debugged process is running, ropper command dumps memory using `gcore` and then passes that core dump to ropper like this: `ropper --file coredump`.
It results in the addresses of gadgets being offsets in the coredump file.

`ropgadget`, and `rop` commands seem to handle that well.

I don't see an easy way to fix that. There is `-I` flag in ropper which lets us specify base address, but it's set as a base address for the whole binary being analyzed. Handling that correctly probably would require calling `ropper -I` individually on every dumped memory section.

**Comment by disconnect3d** [comment]
Can't reproduce. This works for me on:
```
pwndbg> version
Gdb:      12.1
Python:   3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Pwndbg:   2024.02.14 build: e144da77
Capstone: 5.0.1280
Unicorn:  2.0.1
```

Screen - on PIE binary (/bin/ls):

<img width="738" alt="image" src="https://github.com/pwndbg/pwndbg/assets/10009354/22c3cadf-731b-46e1-ad30-e1aadb0d7795">
