### ISSUE TITLE
pwndbg.com seems fishy

### ISSUE THREAD

**Issue by alichtman** [pwndbg/pwndbg#661]
### Description

I went to the website linked in the repo one-line description, and saw this:

<img width="881" alt="image" src="https://user-images.githubusercontent.com/20600565/61201215-b0070280-a698-11e9-9bfe-47743618ecff.png">

Should this link be removed?

**Comment by disconnect3d** [comment]
Thanks for reporting this, link removed!

We forgot to renewal the payment for the domain and it got snatched by someone :(.
