### ISSUE TITLE
subprocess.CalledProcessError: Command '['/usr/local/bin/checksec', '--file', '/tmp/xxx']' returned non-zero exit status 2.

### ISSUE THREAD

**Issue by t3ls** [pwndbg/pwndbg#662]
```
pwndbg> checksec 
Traceback (most recent call last):
  File "/root/pwndbg/pwndbg/commands/__init__.py", line 109, in __call__
    return self.function(*args, **kwargs)
  File "/root/pwndbg/pwndbg/commands/__init__.py", line 189, in _OnlyWithFile
    return function(*a, **kw)
  File "/root/pwndbg/pwndbg/commands/checksec.py", line 16, in checksec
    print(pwndbg.wrappers.checksec.get_raw_out())
  File "/root/pwndbg/pwndbg/commands/__init__.py", line 189, in _OnlyWithFile
    return function(*a, **kw)
  File "/root/pwndbg/pwndbg/wrappers/__init__.py", line 28, in _OnlyWithCommand
    return function(*a, **kw)
  File "/root/pwndbg/pwndbg/memoize.py", line 48, in __call__
    value = self.func(*args, **kwargs)
  File "/root/pwndbg/pwndbg/wrappers/checksec.py", line 20, in get_raw_out
    return pwndbg.wrappers.call_cmd(cmd)
  File "/root/pwndbg/pwndbg/wrappers/__init__.py", line 35, in call_cmd
    return subprocess.check_output(cmd, stderr=STDOUT).decode('utf-8')
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/bin/checksec', '--file', '/tmp/forgot']' returned non-zero exit status 2.
```

when checksec running in python3 pwntools environment, raise a failure. Here's the reason:
```
root@kali:/tmp# checksec --file forgot
usage: checksec [-h] elf [elf ...]
checksec: error: unrecognized arguments: --file
```

So modify pwndbg/pwndbg/wrappers/checksec.py: 19 with:
`cmd = [get_raw_out.cmd_path, local_path]`

Then it will be solved

**Comment by disconnect3d** [comment]
Seems like it may be clash of checksec from checksec.sh repo and from pwntools...

Can you see if this is the case?

**Comment by t3ls** [comment]
> Seems like it may be clash of checksec from checksec.sh repo and from pwntools...
> 
> Can you see if this is the case?

Nope, I think it just the checksec from python3-pwntools doesn't accept the `--file` arg. So simply modify the command with `if else` would be ok

**Comment by disconnect3d** [comment]
That's exactly what I mean, the https://github.com/slimm609/checksec.sh does accept and require the `--file` flag while pwntools' checksec does not.

We should probably detect which one is there and either pass the flag or not :f.

**Comment by t3ls** [comment]
> That's exactly what I mean, the https://github.com/slimm609/checksec.sh does accept and require the `--file` flag while pwntools' checksec does not.
> 
> We should probably detect which one is there and either pass the flag or not :f.

Agree with you, so I rechecked the checksec.py in python3-pwntools (https://github.com/Gallopsled/pwntools), detect the arg parse bug. Unfortunately, the project is not maintained anymore. I will close this issue.

**Comment by LhauLhuna** [comment]
I have this problem please help me
Environment:


Request Method: GET
Request URL: http://192.168.137.128/monitoring/sensor/

Django Version: 2.2.6
Python Version: 3.7.3
Installed Applications:
['registration',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'core',
 'ckeditor',
 'monitoring',
 'information']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback:

File "/home/pi/Dvm/fototrampa/lib/python3.7/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/home/pi/Dvm/fototrampa/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File "/home/pi/Dvm/fototrampa/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/pi/Dvm/fototrampa/src/monitoring/views.py" in OneMinuteCron
  7. 	ReadDistanceSensor()

File "/home/pi/Dvm/fototrampa/src/monitoring/service.py" in ReadDistanceSensor
  11.                 stderr=subprocess.STDOUT).decode('UTF-8')

File "/usr/lib/python3.7/subprocess.py" in check_output
  395.                **kwargs).stdout

File "/usr/lib/python3.7/subprocess.py" in run
  487.                                      output=stdout, stderr=stderr)

Exception Type: CalledProcessError at /monitoring/sensor/
Exception Value: Command '['sudo', '/home/pi/Dvm/fototrampa/ultrasonico.py', '23', '24']' returned non-zero exit status 1.

### Description

I create a web page to monitoring sensors

### Steps to reproduce

This is the function that I used but if I change the process to run or call it doesn't generate this error returned non-zero exit status 1 that I can do to fix it I need to use check_output
def ReadDistanceSensor():
        for sensor in DistanceSensor.objects.all():
                pinT = str(sensor.gpio_pinT)
                pinE = str(sensor.gpio_pinE)
                reading = subprocess.check_output(
                ['sudo', '/home/pi/Dvm/fototrampa/ultrasonico.py', pinT, pinE],
                stderr=subprocess.STDOUT).decode('UTF-8')

                newreading = DistanceSensorReading(reading=reading)
                newreading.save()
                sensor.readings.add(newreading)
                sensor.save()
        return True### My setup
