### ISSUE TITLE
Incorrect conversion from gdb.Value to python int

### ISSUE THREAD

**Issue by ripples-alive** [pwndbg/pwndbg#669]
### Description

When debugging certain binary, pwndbg may show incorrect register value, missing high 32 bit for 64 bit register.
e.g.

```
pwndbg> regs rax
 RAX  0x555c4160
pwndbg> i r rax
rax            0x5555555c4160   93824992690528
pwndbg> telescope $rax
<Could not read memory at 0x555c4160>
pwndbg> regs rsp
 RSP  0xffffffffffffc2f0
pwndbg> i r rsp
rsp            0x7fffffffc2f0   0x7fffffffc2f0
pwndbg> telescope $rsp
<Could not read memory at 0xffffc2f0>
pwndbg>
```

**If I strip the binary, everything goes well.**

After checking code of pwndbg, I found that the bug happens when trying to convert a `gdb.Value` instance to python `int`.

```
pwndbg> python
>print(hex(pwndbg.regs.rsp))
>rsp = pwndbg.regs.value
>print(type(rsp))
>print(rsp.type)
>print(rsp)
>print(hex(rsp))
>print(int(rsp))
>print(long(rsp))
>print(str(rsp))
>print(hex(pwndbg.arch.ptrmask))
>print(hex(int(rsp) & pwndbg.arch.ptrmask))
>end
0xffffffffffffc2f0
<class 'gdb.Value'>
u64
140737488339696
0x7fffffffc2f0
-15632
-15632
140737488339696
0xffffffffffffffff
0xffffffffffffc2f0
```

Seems the `int(value)` works as converting to 32 bit c type int instead of python type int. Maybe we need to use `int(str(value))` to get the correct value.

### Steps to reproduce

Here is an example binary which can reproduce the bug.

[babi.zip](https://github.com/pwndbg/pwndbg/files/3508243/babi.zip)

1. Execute `babi` with gdb & break at `0x5555555D0C97`.
1. Execute the attached `test.py`.
1. Breakpoint will hit with the bug.

*PS: stop in `libc` or `main` function won't see the bug.*

### My setup

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```

```
pwndbg> version
Gdb:      8.1.0.20180409-git
Python:   3.6.8 (default, Jan 14 2019, 11:02:34)  [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
Pwndbg:   1.1.0 build: 7f5d8e7
Capstone: 4.0.1024
Unicorn:  1.0.1
```

**Comment by stnevans** [comment]
For whatever reason, when I run babi with test.py, babi errors before hitting the breakpoint.
```
thread 'main' panicked at 'groups: Sys(EPERM)', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'uid: Sys(EPERM)', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
What commit are you on? The output of version seems to refer to a commit that doesn't exist on the mainline.  Could you test on the latest if you aren't already there?

**Comment by ripples-alive** [comment]
Sorry, I forget that I've modified pwndbg, which cause the commit id incorrect. I tested again on the latest default `dev` branch and updated the info above.
`babi` may need root permission to execute. It's a challenge from DEF CON CTF 2019 Final and should do no harm. You may run it inside docker to avoid risk.

**Comment by stnevans** [comment]
Thanks for the quick response! I am able to reproduce it when running babi as root.

The problem seems to come from inthook. When doing int, we cast everything to long or ulong, but long and ulong are not ptrsize.

**Comment by stnevans** [comment]
@ripples-alive if you want an immediate fix, replace xint in inthook.py with this:
```python
class xint(with_metaclass(IsAnInt, builtins.int)):
    def __new__(cls, value, *a, **kw):
        if isinstance(value, gdb.Value):
            if pwndbg.typeinfo.is_pointer(value):
                if pwndbg.typeinfo.ptrsize == 4:
                    value = value.cast(pwndbg.typeinfo.uint32)
                elif pwndbg.typeinfo.ptrsize == 8:
                    value = value.cast(pwndbg.typeinfo.uint64)
            else:
                if pwndbg.typeinfo.ptrsize == 4:
                    value = value.cast(pwndbg.typeinfo.int32)
                elif pwndbg.typeinfo.ptrsize == 8:
                    value = value.cast(pwndbg.typeinfo.int64)
        elif isinstance(value, gdb.Symbol):
            symbol = value
            value = symbol.value()
            if symbol.is_function:
                if pwndbg.typeinfo.ptrsize == 4:
                    value = value.cast(pwndbg.typeinfo.uint32)
                elif pwndbg.typeinfo.ptrsize == 8:
                    value = value.cast(pwndbg.typeinfo.uint64)

        elif not isinstance(value, (six.string_types, six.integer_types)) \
                or isinstance(cls, enum.EnumMeta):
            # without check for EnumMeta math operations with enums were failing e.g.:
            #     pwndbg> py import re; flags = 1 | re.MULTILINE
            return _int.__new__(cls, value, *a, **kw)

        return _int(_int(value, *a, **kw))
```
I'll open a pr to fix this, but it might take a bit of time to get merged in depending on if we decide to change the design at all.

**Comment by ripples-alive** [comment]
It works. Thx.
