### ISSUE TITLE
Add gdbserver dependency for Fedora

### ISSUE THREAD

**Issue by martinclauss** [pwndbg/pwndbg#674]
Please add `gdb-gdbserver` package as a dependency for Fedora:

https://github.com/pwndbg/pwndbg/blob/dev/setup.sh#L32

Thanks!

**Comment by geoffbeier** [comment]
I was just kicking the tires and ran into this too on F30. I submitted PR #676 to add it.

**Comment by disconnect3d** [comment]
Thanks!
