### ISSUE TITLE
Allow hexdump by module name, like vmmap 

### ISSUE THREAD

**Issue by korniltsev** [pwndbg/pwndbg#678]
### Description

I find myself doing `vmmap heap + hexdump heap_start_addr` from time to time during CTF heap debugging. 
I wonder if you consider `hexdump module_name` useful? I could do a PR if so.

### My setup

```
Gdb:      8.1.0.20180409-git
Python:   3.6.8 (default, Aug 20 2019, 17:12:48)  [GCC 8.3.0]
Pwndbg:   1.1.0 build: 1158a30
Capstone: 4.0.1024
Unicorn:  1.0.1
```

**Comment by stnevans** [comment]
I think it would be a reasonable feature to add if you would be willing to do so!

**Comment by disconnect3d** [comment]
Added with #683
