### ISSUE TITLE
I have a problem with the process check_output

### ISSUE THREAD

**Issue by LhauLhuna** [pwndbg/pwndbg#679]
Environment:

Request Method: GET
Request URL: http://192.168.137.128/monitoring/sensor/

Django Version: 2.2.6
Python Version: 3.7.3
Installed Applications:
['registration',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'core',
 'ckeditor',
 'monitoring',
 'information']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback:

File "/home/pi/Dvm/fototrampa/lib/python3.7/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/home/pi/Dvm/fototrampa/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File "/home/pi/Dvm/fototrampa/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/pi/Dvm/fototrampa/src/monitoring/views.py" in OneMinuteCron
  7. 	ReadDistanceSensor()

File "/home/pi/Dvm/fototrampa/src/monitoring/service.py" in ReadDistanceSensor
  11.                 stderr=subprocess.STDOUT).decode('UTF-8')

File "/usr/lib/python3.7/subprocess.py" in check_output
  395.                **kwargs).stdout

File "/usr/lib/python3.7/subprocess.py" in run
  487.                                      output=stdout, stderr=stderr)

Exception Type: CalledProcessError at /monitoring/sensor/
Exception Value: Command '['sudo', '/home/pi/Dvm/fototrampa/ultrasonico.py', '23', '24']' returned non-zero exit status 1.

### Description

I create a web page to monitoring sensors

### Steps to reproduce

This is the function that I used but if I change the process to run or call it doesn't generate this error returned non-zero exit status 1 that I can do to fix it I need to use check_output
def ReadDistanceSensor():
        for sensor in DistanceSensor.objects.all():
                pinT = str(sensor.gpio_pinT)
                pinE = str(sensor.gpio_pinE)
                reading = subprocess.check_output(
                ['sudo', '/home/pi/Dvm/fototrampa/ultrasonico.py', pinT, pinE],
                stderr=subprocess.STDOUT).decode('UTF-8')

                newreading = DistanceSensorReading(reading=reading)
                newreading.save()
                sensor.readings.add(newreading)
                sensor.save()
        return True### My setup

**Comment by stnevans** [comment]
Are you sure this issue is opened in the right repo? This repository is for pwndbg, low-level debugging enhancements for gdb.

**Comment by disconnect3d** [comment]
Yeah, this seems unrelated. Closing.

**Comment by LhauLhuna** [comment]
I am not very sure but I already solved my problem thanks anyway and an apology for my confusion
