### ISSUE TITLE
qemu local_path bug

### ISSUE THREAD

**Issue by Jinmo** [pwndbg/pwndbg#681]
### Description

It seems like some commands e.g. plt, got tries to use ELF file's content as path.

### Steps to reproduce

```
$ qemu-arm -g 23946 ./target
$ gdb-multiarch ./target
(gdb) target remote :23946
(gdb) plt # or
(gdb) got
```

### My setup

Ubuntu 18.04, branch c6473ba (master)

### Analysis (and temporary patch)

plt/got command uses `get_elf_info` at [elf.py](https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/elf.py#L95), which uses get_file at file.py.

It seems like the path itself should be used in [file.py L36](https://github.com/pwndbg/pwndbg/blob/c6473ba7aea797f7b4d2251febf419382564d3f8/pwndbg/file.py#L36):

https://github.com/pwndbg/pwndbg/blob/203f10710e8a9a195a7bade59661ed7f3e3e641c/pwndbg/file.py#L35-L36

to
```py
    if pwndbg.qemu.root() and recurse:
        return os.path.join(pwndbg.qemu.binfmt_root, path)
```

I'm not sure if it's ok in all cases, since I think relative path should be also searched, but it works on plt/got case since absolute path is used (e.g. if path is 'a/b', I'm not sure if binfmt_root + '/a/b' and 'a/b' shoud be searched.)

**Comment by disconnect3d** [comment]
Hey, sorry for so long time with no reply. Can you send a PR with the proposed change so we could test this on different setups?
