### ISSUE TITLE
Pwndbg.re does not use TLS, contains personal information

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#689]
Currently, Pwndbg.re throws a warning for users with the HTTPS Everywhere extension, and is insecure against MITM redirects.

I recommend transferring the domain to CloudFlare, which provides free SSL/TLS and has the same redirect capabilities as other registrars.

Additionally, the domain registration information contains personal information -- switching to CloudFlare will also provide protection against this.

You can find more information on CloudFlare's free encryption tools here: https://www.cloudflare.com/ssl/

**Comment by disconnect3d** [comment]
I will figure out how to transfer it there and do it.

**Comment by disconnect3d** [comment]
I am afraid this cannot be done as shown below 😢.
![image](https://user-images.githubusercontent.com/10009354/70477470-3b19e680-1ad9-11ea-8057-d4e9c6d3b621.png)

**Comment by disconnect3d** [comment]
I will see if I can setup a https redirect on ovh.
