### ISSUE TITLE
vis_heap_chunks() output is inaccurate

### ISSUE THREAD

**Issue by CptGibbon** [pwndbg/pwndbg#706]
The following screenshot shows the vis_heap_chunks() command output when introspecting the default heap, which has 3 0x20-sized chunks allocated on it.

![vis_heap_chunks errors](https://user-images.githubusercontent.com/16000770/74610386-acce6c00-50ea-11ea-8411-1837aac693c4.png)

The first command incorrectly shows the quadword at address 0x405040 as belonging to the 3rd (magenta) chunk, when it actually belongs to the 2nd (cyan) chunk. This issue is only present in the dev branch. The output also shows the quadword at address 0x405060 as belonging to the top chunk, when it belongs to the 3rd chunk. This issue is present in both dev & stable branches.

The second command does not show the last quadword of the yellow chunk's user data, despite it being correctly marked as belonging to the yellow chunk in the first command output. This issue is present in both dev & stable branches.

**Comment by CptGibbon** [comment]
I have a PR ready, let me know if you want it submitted and against which branch.

**Comment by disconnect3d** [comment]
Can you give some more context so the issue can be reproduced? E.g. an example minimal working binary and your libc version? 

Also, we accept PRs to the `dev` branch.

**Comment by CptGibbon** [comment]
Here's a minimal working binary, it just requests 3 minimum-sized chunks.
```
#include <stdlib.h>
void main(void) {
    malloc(1);
    malloc(1);
    malloc(1);
}
```
You can link against any version of GLIBC, ignoring the main thread's tcache in versions >= 2.26. The issue only concerns allocated chunks near the top chunk and how they're coloured by vis_heap_chunks().

Allow the binary to make its 3 requests under GDB then issue the `vis_heap_chunks` command without any arguments. Pwndbg will print output similar to the screenshot in the original issue comment, just without the chunk contents ("AAAA" etc) and possibly preceded by a tcache chunk depending on which version of GLIBC you linked against.
