### ISSUE TITLE
cyclic error 

### ISSUE THREAD

**Issue by srajith** [pwndbg/pwndbg#729]
### Description
```pwn cyclic throws "TypeError: 'in <string>' requires string as left operand, not int" ```

### Steps to reproduce
---
cyclic -l "0x6161616c"

### My setup

![pwn](https://user-images.githubusercontent.com/40263349/77217719-82892780-6b4a-11ea-80c6-9b985368ec75.png)
![version](https://user-images.githubusercontent.com/40263349/77217721-89b03580-6b4a-11ea-8bc8-b30e337b8c9d.png)

**Comment by disconnect3d** [comment]
This is a pwntools command, not pwndbg. Please refer/report to https://github.com/Gallopsled/pwntools/

**Comment by srajith** [comment]
in pwndbg when i do cyclic -l etc still i get the same error
