### ISSUE TITLE
ImportError: most likely due to a circular import

### ISSUE THREAD

**Issue by ld1ng** [pwndbg/pwndbg#730]
GNU gdb (Debian 9.1-2) 9.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
Traceback (most recent call last):
  File "/root/Desktop/pwndbg/gdbinit.py", line 36, in <module>
    import pwndbg # isort:skip
  File "/root/Desktop/pwndbg/pwndbg/__init__.py", line 12, in <module>
    import pwndbg.android
  File "/root/Desktop/pwndbg/pwndbg/android.py", line 12, in <module>
    import pwndbg.file
  File "/root/Desktop/pwndbg/pwndbg/file.py", line 19, in <module>
    import pwndbg.qemu
  File "/root/Desktop/pwndbg/pwndbg/qemu.py", line 14, in <module>
    import psutil
  File "/usr/local/python3/lib/python3.8/site-packages/psutil/__init__.py", line 101, in <module>
    from . import _pslinux as _psplatform
  File "/usr/local/python3/lib/python3.8/site-packages/psutil/_pslinux.py", line 26, in <module>
    from . import _psutil_linux as cext
ImportError: cannot import name '_psutil_linux' from partially initialized module 'psutil' (most likely due to a circular import) (/usr/local/python3/lib/python3.8/site-packages/psutil/__init__.py)
(gdb)

**Comment by disconnect3d** [comment]
Hmm seems like a dependency error?

Any chance you could investigate it further @Liding81 ?

**Comment by davidpolverari** [comment]
I have the same issue on Kali 2020.1 fully updated. Even tried installing all dependencies with `pip install -Ur requirements.txt` on an venv and using that venv on GDB, by appending to sys.path inside GDB and sourcing the `pwndbg/gdbinit.py`, but the same errors happen.

**Comment by disconnect3d** [comment]
Can you guys check out this solution: https://github.com/giampaolo/psutil/issues/1288#issuecomment-401303133 ? Can it be that your distro/some tools u use ship with a specific psutil version that breaks pwndbg?

**Comment by davidpolverari** [comment]
First of all, thanks for the awesome tool and for the help! Removing psutil worked, but there's no other psutil installed by the distro that I could find. Besides installing with pip --user, I also removed everything and installed the requirements on a venv, and had the same problems. The only psutil installed was the one from requirements.txt.

**Comment by davidpolverari** [comment]
BTW: on Debian Buster (stable), it works perfectly. But I couldn't trace the root of the problem on Kali.

**Comment by disconnect3d** [comment]
I am not sure if we can help here. If anybody has this issue again, please ask to re-open this (or open another issue). Though, it seems more like a problem with some packages/dependencies on kali?

**Comment by davidpolverari** [comment]
Yes, looks like it is problem on Kali/Debian Testing. Thanks for your help.
