### ISSUE TITLE
heap: This command only works with libc debug symbols.

### ISSUE THREAD

**Issue by zhe6652** [pwndbg/pwndbg#731]
### Description
Hi, I am using Kali Linux , when I use heap related commands in pwndbg, I get error msg like this: 

> vis_heap_chunks: This command only works with libc debug symbols.
> They can probably be installed via the package manager of your choice.
> See also: https://sourceware.org/gdb/onlinedocs/gdb/Separate-Debug-Files.html

> E.g. on Ubuntu/Debian you might need to do the following steps (for 64-bit and 32-bit binaries):
> sudo apt-get install libc6-dbg
> sudo dpkg --add-architecture i386
> sudo apt-get install libc-dbg:i386

### what did I do

1. I did what the prompt asked me to do, I installed libc6-dbg, and libc6-dbg:i386 (It told me that there is no libc-dbg:i386), but it still does not working.

2. I set verbose mode on in gdb ,and it seems that gdb load debug information correctly, here are the output:
> Starting program: /usr/bin/ls 
> Using PIE (Position Independent Executable) displacement 0x555555554000 for "/usr/bin/ls".
> Reading symbols from /lib64/ld-linux-x86-64.so.2...
> Reading symbols from /usr/lib/debug/.build-id/a2/2b4ae056ad8cdd0ad900b001533e9a1c8a061a.debug...
> Reading in symbols for rtld.c...done.
> Reading in symbols for dl-minimal.c...done.
> Reading symbols from system-supplied DSO at 0x7ffff7fd3000...
> (No debugging symbols found in system-supplied DSO at 0x7ffff7fd3000)

3. I modified the function of 'OnlyWithLibcDebugSyms' to not check libc debug syms, and i got another error msg, it seems that pwndbg can not read my libc debug symbols.
### My setup

Ah, I just know you are currently supporting only Ubuntu installations until I read the comment,But Is there some way I can get pwndbg working on Kali? I love both the amazing features of pwndbg and Kali Linux, Thanks.

version:
Gdb:      9.1
Python:   3.8.2 (default, Feb 25 2020, 13:04:52)  [GCC 9.2.1 20200220]
Pwndbg:   1.1.0
Capstone: 4.0.1024
Unicorn:  1.0.1

###  16.04.1-Ubuntu x86_64 GNU/Linux  gives the same reults
I just tried install pwndbg on Ubuntu,and it still get the same error...
<img width="582" alt="截屏2020-03-22下午2 16 29" src="https://user-images.githubusercontent.com/24725680/77243710-0e34ae00-6c48-11ea-88a7-aba5d0cb3ab3.png">

<img width="918" alt="截屏2020-03-22下午2 17 20" src="https://user-images.githubusercontent.com/24725680/77243716-12f96200-6c48-11ea-81a6-2b54a8923806.png">

**Comment by h4dla3** [comment]
the command working without any error  in kali 

```
pwndbg> version 
Gdb:      9.1
Python:   3.8.3rc1 (default, Apr 30 2020, 07:33:30)  [GCC 9.3.0]
Pwndbg:   1.1.0 build: 609284c
Capstone: 4.0.1024
Unicorn:  1.0.1
pwndbg> 

```

![Screenshot_2020-05-19_02-37-14](https://user-images.githubusercontent.com/55387011/82384396-b9cf6400-9a27-11ea-8bf9-13b032e66685.png)

**Comment by h4dla3** [comment]
i got the error

![Capture](https://user-images.githubusercontent.com/55387011/82530616-a14d6f80-9b35-11ea-9963-a65f1a8cf802.PNG)

to fix 
try  this

![Screenshot_2020-05-21_02-43-12](https://user-images.githubusercontent.com/55387011/82531812-f7231700-9b37-11ea-9941-d906265675b0.png)

i'm using ^ glibc-all-in-one in the picture 
to download with glibc-all-in-one  ~~  ./download 2.23-0ubuntu10_amd64

u can use
[glibc-all-in-one](https://github.com/matrix1001/glibc-all-in-one)
or 
[libc-databse](https://github.com/niklasb/libc-database)
or
[google](google.com)


then use patchelf 

> patchelf --set-interpreter /path to /ld*.so ./yourbin

> patchelf --replace-needed libc.so.6 /path to/libc*.so ./yourbin

or with pwntools 

> r = process(["/path to/ld.so", "./tes"], env={"LD_PRELOAD":"/path to/libc.so.6"})

im using pathelf

![Screenshot_2020-05-21_02-43-38](https://user-images.githubusercontent.com/55387011/82532030-626ce900-9b38-11ea-8f1e-53252dd91690.png)

![Screenshot_2020-05-21_03-03-20](https://user-images.githubusercontent.com/55387011/82532570-9268bc00-9b39-11ea-986d-69957e22ba90.png)
