### ISSUE TITLE
Hope add basic support for RISC-V

### ISSUE THREAD

**Issue by zoniony** [pwndbg/pwndbg#735]
As of GDB 8.3 RISCV is supported.hope add basic support for RISC-V

**Comment by disconnect3d** [comment]
Is this arch supported by capstone? If so, we could easily add it.

If not, maybe we should drop capstone nad use GDB's disassembler etc in such cases ;).

**Comment by disconnect3d** [comment]
I believe this was added in https://github.com/pwndbg/pwndbg/commit/e92a45ca263178efe775d17d8ed3cff7ba5fe1e2 and will be further enhanced with capstone in #829.

Since it _should work now_ I am closing this issue for now.
