### ISSUE TITLE
Pwndbg throw an exception when debugging linux kernel

### ISSUE THREAD

**Issue by plummm** [pwndbg/pwndbg#736]
### Description
Pwndbg run extremely slow when attaching kernel by `target remote :1234`, then throw an exception.

### My setup

> gdb -q vmlinux                                
> pwndbg> set exception-verbose on
> Set whether to print a full stacktracefor exceptions raised in Pwndbg commands to True
> pwndbg> target remote :1234
> Remote debugging using :1234
> ERROR: Could not find ELF base!
> ERROR: Could not find ELF base!
> ERROR: Could not find ELF base!
> ERROR: Could not find ELF base!
> ERROR: Could not find ELF base!
> ERROR: Could not find ELF base!
> ERROR: Could not find ELF base!
> native_safe_halt () at ./arch/x86/include/asm/irqflags.h:61
> 61      }
> ERROR: Could not find ELF base!
> ERROR: Could not find ELF base!
> Traceback (most recent call last):
>   File "/home/user/projects/pwndbg/pwndbg/commands/__init__.py", line 136, in __call__
>     return self.function(*args, **kwargs)
>   File "/home/user/projects/pwndbg/pwndbg/commands/__init__.py", line 227, in _OnlyWhenRunning
>     return function(*a, **kw)
>   File "/home/user/projects/pwndbg/pwndbg/commands/telescope.py", line 121, in telescope
>     pwndbg.chain.format(addr)))
>   File "/home/user/projects/pwndbg/pwndbg/chain.py", line 104, in format
>     rest.append(M.get(link, symbol))
>   File "/home/user/projects/pwndbg/pwndbg/color/memory.py", line 52, in get
>     page = pwndbg.vmmap.find(int(address))
>   File "/home/user/projects/pwndbg/pwndbg/memoize.py", line 48, in __call__
>     value = self.func(*args, **kwargs)
>   File "/home/user/projects/pwndbg/pwndbg/vmmap.py", line 78, in find
>     for page in get():
>   File "/home/user/projects/pwndbg/pwndbg/memoize.py", line 48, in __call__
>     value = self.func(*args, **kwargs)
>   File "/home/user/projects/pwndbg/pwndbg/vmmap.py", line 51, in get
>     pages.extend(monitor_info_mem())
>   File "/home/user/projects/pwndbg/pwndbg/memoize.py", line 48, in __call__
>     value = self.func(*args, **kwargs)
>   File "/home/user/projects/pwndbg/pwndbg/vmmap.py", line 255, in monitor_info_mem
>     dash_idx = line.index('-')
> ValueError: substring not found

Gdb:      8.1.0.20180409-git
Python:   3.6.9 (default, Nov  7 2019, 10:44:02)  [GCC 8.3.0]
Pwndbg:   1.1.0 build: 0cdcd6f
Capstone: 4.0.1024
Unicorn:  1.0.2
linux: 7eaecf7963c1

**Comment by disconnect3d** [comment]
Hey,

can you show the output of this command?:
```
monitor info mem
```

As a workaround, please comment out this line:
```
File "/home/user/projects/pwndbg/pwndbg/vmmap.py", line 51, in get
pages.extend(monitor_info_mem())
```

**Comment by disconnect3d** [comment]
To elaborate a bit more - the issue with debugging linux kernel is that we don't have a proper place to fetch memory pages information from, so... we do it from any  sources we can and one of those sources is QEMU's `monitor info mem` command. This works *for some architectures* but the output is huge and the cost of this command is not cool.

Its not so well written currently: the result should be cached and the command should be executed by the user on-demand probably, or, maybe when we hit some memory page that we "didnt know about".

**Comment by disconnect3d** [comment]
Btw the comments here might give some more context on the `monitor info mem` and its problems: https://github.com/pwndbg/pwndbg/pull/685

**Comment by disconnect3d** [comment]
This has been fixed already in recent versions. First of all, we now use gdb-pt-dump to process QEMU pages information and second we have a fallback to use the `monitor info mem` command. The latter is slower, but I think we can't do better on Pwndbg side.
