### ISSUE TITLE
slow when remote debugging 

### ISSUE THREAD

**Issue by aj3423** [pwndbg/pwndbg#741]
### Description

1. I'm remote debugging with Android phone. There is a delay after every single step, about 1 second.
![slow](https://user-images.githubusercontent.com/4710875/80149551-6f55f580-85e9-11ea-8ea3-e7782333de7c.gif)

2.  When configured not output anything, it still delays about 200ms.
```
set context-sections ''
set dereference-limit 0
set emulate off
set heap-dereference-limit 0
set ida-enabled off
```
![slow no context](https://user-images.githubusercontent.com/4710875/80149571-767d0380-85e9-11ea-8cc2-a41666a9d4f2.gif)

3. It's very quick without using pwndbg
![quick](https://user-images.githubusercontent.com/4710875/80149603-84cb1f80-85e9-11ea-9117-b16d827fdabe.gif)
And it's quick even with printing all registers and asm instructions.

There is also no delay debugging local program, only delay for remote debugging. Anyway to trace the delay?

### Steps to reproduce

  Remote debug Android phone, use `ni` to step trace

### My setup
Kali Linux
Android Aarch64 phone,  connected via USB cable
Gdb:      9.1
Python:   3.8.2 (default, Apr  1 2020, 15:52:55)  [GCC 9.3.0]
Pwndbg:   1.1.0 build: 3cf9b31
Capstone: 4.0.1024
Unicorn:  1.0.1

**Comment by disconnect3d** [comment]
I think the vast performance hit is due to functions that are executed on each stop (and so decorated with `@pwndbg.<something>.stop` iirc.

It would be worth enabling some profiling and see what takes the most time...
Also `set debug-events on` might be handy here, though i am not sure.

**Comment by aj3423** [comment]
Tried to trace the lag with `set debug-events on`, finally found the problem is reading from remote memory
```
instructions = pwndbg.disasm.near(pc, lines, emulate=emulate, show_prev_insns=not nearpc.repeat)
and 
pwndbg.vmmap.find(pc)
```
both reads memory from remote
```
result = gdb.selected_inferior().read_memory(addr, count)
```
Seems it's problem of reading remote memory,  the way to reduce delay is to reduce memory reading...

**Comment by disconnect3d** [comment]
(btw the first version of ur post was also very valuable imho, but anyway)

We could get a great improvement here if we disabled unicorn/capstone and rely on GDB's instruction disassembler.

This way, we wouldn't be able to "follow the values" and enhance the display with e.g. addresses that will be used in e.g. a mov instruction that is 5 instructions further, but, it will increase the speed.

Also.. I am not sure why we use registers exploring in that case but maybe it makes sense (I dislike this functionality overall).

**Comment by aj3423** [comment]
Sometimes even the `one` function(read 1 byte) can cost 100ms, but most time it doesn't.  It's very fast to show 10 lines of code with `x /10i $pc`, almost instantly, or show registers wit `info reg`. I guess it also reads memory from remote, the difference is it's c++, maybe it's speed problem with pythong binding, not much we can do ...
