### ISSUE TITLE
Fail to run setup.sh in Ubuntu 20.04

### ISSUE THREAD

**Issue by BeLeap** [pwndbg/pwndbg#745]
### Description

I can't execute setup.sh.
I think it would be because python2 is deprecated.
<img width="1620" src="https://user-images.githubusercontent.com/46488521/80378705-049e0600-88d8-11ea-9d38-2d4f1e5e401a.png" />

### Steps to reproduce

Run setup.sh in Ubuntu 20.04.(Maybe WSL)

### My setup

<img width="1620" src="https://user-images.githubusercontent.com/46488521/80378431-9ce7bb00-88d7-11ea-8d65-2e73d6c9d800.png" />
<img width="1620" src="https://user-images.githubusercontent.com/46488521/80378545-c56fb500-88d7-11ea-8415-6ef179992dd7.png" />
<img width="1620" src="https://user-images.githubusercontent.com/46488521/80378955-6494ac80-88d8-11ea-9d14-9cf22c72f7c9.png" />

**Comment by zachriggle** [comment]
I see the same on my end:

```

Step 85/93 : RUN bash -ex ./setup.sh
 ---> Running in 47f3658b4268
+ set -ex
+ '[' -f /.dockerenv ']'
+ hash sudo
+ PYTHON=
+ INSTALLFLAGS=
+ osx
+ uname
+ grep -i Darwin
+ '[' '' == --user ']'
+ PYTHON='sudo '
+ linux
+ uname
+ grep -i Linux
++ grep '^ID=' /etc/os-release
++ cut -d= -f2
++ sed -e 's/"//g'
+ distro=ubuntu
+ case $distro in
+ install_apt
+ sudo apt-get update
sudo: setrlimit(RLIMIT_CORE): Operation not permitted
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
...
Get:28 http://archive.ubuntu.com/ubuntu focal-backports/multiverse amd64 c-n-f Metadata [116 B]
Traceback (most recent call last):
  File "/usr/lib/cnf-update-db", line 26, in <module>
    col.create(db)
  File "/usr/lib/python3/dist-packages/CommandNotFound/db/creator.py", line 93, in create
    self._fill_commands(con)
  File "/usr/lib/python3/dist-packages/CommandNotFound/db/creator.py", line 127, in _fill_commands
    self._parse_single_commands_file(con, fp)
  File "/usr/lib/python3/dist-packages/CommandNotFound/db/creator.py", line 165, in _parse_single_commands_file
    suite=tagf.section["suite"]
KeyError: 'suite'
```

**Comment by blurbdust** [comment]
After removing the `python-pip` install from `setup.sh` and adding `testresources` to `requirements.txt` it seems to be working fine for me on Ubuntu 20.04 LTS.

https://github.com/blurbdust/pwndbg/commit/1c89b462b8d2d84de629617bdcb1182d098efd33

**Comment by disconnect3d** [comment]
This should work now.

**Comment by melroy89** [comment]
FYI. This worked for me (using Ubuntu for Arm):

```
sudo apt purge command-not-found
sudo apt --purge autoremove
sudo bash -c 'apt update && apt full-upgrade && apt autoremove && apt clean'
```

It's not ideal.
