### ISSUE TITLE
`find_fake_fast` fails when providing a size argument

### ISSUE THREAD

**Issue by dlmarrero** [pwndbg/pwndbg#758]
### Description

Providing a size argument to the `find_fake_fast` command causes a TypeError at [heap.py:519](https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/commands/heap.py#L519).

### Steps to reproduce

1. Run gdb on a program that utilizes the heap
2. Once the heap is initialized, run `find_fake_fast &__malloc_hook 0x7f`

`find_fake_fast` working correctly as of commit 1158a3086d2eaa137e3ce30810539c1aa578e87a
![image](https://user-images.githubusercontent.com/25566997/81937222-583f6d80-95c1-11ea-9a79-ed2526dd15d8.png)

Same command, same program, updated to commit 609284cee279de345dcb0706e11a0b56abe349f4
![image](https://user-images.githubusercontent.com/25566997/81937802-1662f700-95c2-11ea-9fa6-b709c8eb24b3.png)

### My setup

Gdb:      7.11.1
Python:   3.5.2 (default, Oct  8 2019, 13:06:37)  [GCC 5.4.0 20160609]
Pwndbg:   1.1.0 build: 609284c
Capstone: 4.0.1024
Unicorn:  1.0.1

**Comment by disconnect3d** [comment]
Fixed in #760.
