### ISSUE TITLE
Better telescope enchancements

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#771]
When we store a very long cyclic buffer in memory and then display the addresses with telescope, the first few values are fine but later we get a very long string. As in:
```
0e:0070│        0x5555557572c0 ◂— 0x616161616161616b ('kaaaaaaa')
0f:0078│        0x5555557572c8 ◂— 0x616161616161616c ('laaaaaaa')
10:0080│        0x5555557572d0 ◂— 0x616161616161616d ('maaaaaaa')
11:0088│        0x5555557572d8 ◂— 0x616161616161616e ('naaaaaaa')
12:0090│        0x5555557572e0 ◂— 0x616161616161616f ('oaaaaaaa')
13:0098│        0x5555557572e8 ◂— 0x6161616161616170 ('paaaaaaa')
14:00a0│        0x5555557572f0 ◂— 0x6161616161616171 ('qaaaaaaa')
15:00a8│        0x5555557572f8 ◂— 0x6161616161616172 ('raaaaaaa')
16:00b0│        0x555555757300 ◂— 0x6161616161616173 ('saaaaaaa')
17:00b8│        0x555555757308 ◂— 0x6161616161616174 ('taaaaaaa')
18:00c0│        0x555555757310 ◂— 0x6161616161616175 ('uaaaaaaa')
19:00c8│        0x555555757318 ◂— 'vaaaaaaawaaaaaaaxaaaaaaayaaaaaaazaaaaaabbaaaaaabcaaaaaabdaaaaaabeaaaaaabfaaaaaabgaaaaaabhaaaaaabiaaaaaabjaaaaaabkaaaaaablaaaaaabmaaaaaabnaaaaaaboaaaaaabpaaaaaabqaaaaaabraaaaaabsaaaaaabtaaaaaab'
1a:00d0│        0x555555757320 ◂— 'waaaaaaaxaaaaaaayaaaaaaazaaaaaabbaaaaaabcaaaaaabdaaaaaabeaaaaaabfaaaaaabgaaaaaabhaaaaaabiaaaaaabjaaaaaabkaaaaaablaaaaaabmaaaaaabnaaaaaaboaaaaaabpaaaaaabqaaaaaabraaaaaabsaaaaaabtaaaaaab'
```

I guess telescope finds out the string is too long to display it so it just displays its 8 bytes, but if it is shorter than some constant it prints the whole string? If my assumption is correct, we could make it keep the information about string length and not displaying the whole string and instead displaying it in parts as it does it on the first few rows?

**Comment by zachriggle** [comment]
The cut-off for this is `pwndbg.strings.length`, which is inferred from `show print elements`.

https://github.com/pwndbg/pwndbg/blob/677dfa2a1947fed41bcae315eb5656234150e43f/pwndbg/strings.py#L20-L55

You can change the value with `set print elements` and it will be picked up on the next debugger stop.

To fix this in the ideal case ("keep printing strings as 8-byte strings if we are continuing") ends up being a complicated issue with a lot of moving parts, I don't think there's an easy way to get the behavior you want.

I'd just recommend setting `set print elements 32` or something in your `~/.gdbinit`

**Comment by disconnect3d** [comment]
Yeah, that will do the trick, thx.
