### ISSUE TITLE
Clear caches on `events.clear_objfiles`

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#773]
For the last several releases, GDB has supported the following events that may allow us to make `pwndbg.events` more efficient: https://sourceware.org/gdb/onlinedocs/gdb/Events-In-Python.html#Events-In-Python

If we add support for these, we will need to add workarounds for older GDB versions that don't support them.  We should also add `memoize` functions for these.

Support for all of these events tarted with GDB v7.9,  which corresponds to Ubuntu 16.04.  Since these have been available for 4 years, we can either stub them out (i.e. fire them on every prompt event) or just require GDB 7.9 (released in 2015) to use Pwndbg.

### events.memory_changed

This will allow us to memoize memory addresses (e.g. `pwndbg.memory.read`), which is useful when debugging over a high-latency link (e.g. tunneling a gdbserver connection over SSH).

Workaround can just be to fire this event on every prompt, or to not memoize at all (which is the current behavior).

Currently we have this in `events` but nothing uses it.  We just need to add stubs and apply the memoize to `mem.py`.

### events.register_changed

This allows us to be more precise in caching register values.  Currently, we do double-caching:

https://github.com/pwndbg/pwndbg/blob/677dfa2a1947fed41bcae315eb5656234150e43f/pwndbg/regs.py#L283-L285

Workaround can just be to fire the event when either of the two current events fire.

Currently we have `pwndbg.events.register_changed` but nothing uses it.  I think all that's needed is to stub out the workaround and apply this judiciously to `regs.py`.

### events.clear_objfiles

This event seems like it only occurs when a new process shows, we should probably clear all memos when this occurs.

**Comment by disconnect3d** [comment]
> or just require GDB 7.9 (released in 2015) to use Pwndbg

I'd be even up for bumping the required version even more, like 9.x as it's not that big deal to compile GDB from scratch :P.

**Comment by zachriggle** [comment]
I'd prefer to keep out-of-the-box support for Xenial (7.11) for now.

*Zach Riggle*

**Comment by gsingh93** [comment]
It seems like we're already making use of `memory_changed` and `register_changed`. @disconnect3d do we still want to add support for `events.clear_objfiles`?

**Comment by disconnect3d** [comment]
Seems like "clearing caches" on clear_objfile may make sense.

**Comment by disconnect3d** [comment]
Also, new process may not be the only way to clear_objfiles, I think there was something to unload symbols from file. Maybe that triggers the event as well?

**Comment by disconnect3d** [comment]
It doesn't seem we should care about `clear_objfiles` for now. Let's skip it for now since there doesn't seem to be any caching issues.

The other two were already implemented.

**Comment by disconnect3d** [comment]
I'm also clearing the testing of reg/mem changed events in https://github.com/pwndbg/pwndbg/pull/2134 since Ubuntu 20.04 GDB (`GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2`) always has those events.
