### ISSUE TITLE
source code section unavailable if current line is in the first chunk of the list command

### ISSUE THREAD

**Issue by anthraxx** [pwndbg/pwndbg#78]
when debugging through code and the current function is indeed one that it at the top of a .c file (that does not use tons of includes) the section is lost because of a too aggressive check:

https://github.com/pwndbg/pwndbg/blob/master/pwndbg/commands/context.py#L160

Which edge-case does that try to solve? As I'm hitting that in several cases, I think it does harm more then it maybe solves something? Would be cool to know which case it does try to fix so we could adjust that check to be less aggressive and preserve the section of the mentioned scenario.

**Comment by zachriggle** [comment]
It solves the issue where the current `$PC` is known to be in a file, but does not correspond to any line in the file -- so GDB sets it to the top of the file.

**Comment by anthraxx** [comment]
@zachriggle I see, not sure how this could be solved without breaking the above mentioned scenario. Does that happen that often?

**Comment by zachriggle** [comment]
I'm not sure, since it hides it when it happens ^_^.

I wouldn't have gone out of my way to add the check if it wasn't affecting me in some way.

What files are you debugging where the first line of source in a file is important (i.e. not a function declaration)?

**Comment by anthraxx** [comment]
its nut just about the very first line. the check looks if the first line of the source listing is the first line of the file. that also applies if you break on the first function in a file not having many includes so that the first line of the file is actually included in the listing.
It happens quite often in some of my projects, I noticed it because i tried to break on one of them to debug and did see nothing :sweat_smile:

**Comment by zachriggle** [comment]
It seems the best way to fix this is to check the current line, rather than whether or not the first line appears in the listing.

Would you agree that if the *current* line is claimed to be Line 1, something is wrong?

This way you can get listings which happen to include Line 1.

**Comment by anthraxx** [comment]
@zachriggle yes, i guess that sounds safe to assume and should not happen under normal conditions
