### ISSUE TITLE
The `heap` command claims I don't have libc debug symbols installed.

### ISSUE THREAD

**Issue by elongl** [pwndbg/pwndbg#785]
### Description
I remember there was an active discussion on this issue previously,
but I can no longer find it and I'm still facing this problem.

When trying to use the `heap` command, I'm getting
```
heap: This command only works with libc debug symbols.
They can probably be installed via the package manager of your choice.
See also: https://sourceware.org/gdb/onlinedocs/gdb/Separate-Debug-Files.html

E.g. on Ubuntu/Debian you might need to do the following steps (for 64-bit and 32-bit binaries):
sudo apt-get install libc6-dbg
sudo dpkg --add-architecture i386
sudo apt-get install libc-dbg:i386
```

I can assure you I already have these installed,
```
libc6-dbg is already the newest version (2.31-0ubuntu9).
ote, selecting 'libc6-dbg:i386' instead of 'libc-dbg:i386'
libc6-dbg:i386 is already the newest version (2.31-0ubuntu9).
```

I do use the latest pwndbg version.

### Steps to reproduce
Use the `heap` command.

### My setup
OS: Ubuntu 20.04 LTS (Focal Fossa)
Gdb:      9.1
Python:   3.8.2 (default, Apr 27 2020, 15:53:34)  [GCC 9.3.0]
Pwndbg:   1.1.0 build: 5efff78

**EDIT**: I just noticed that on certain programs it does work for me.
I just compiled my own simple program and it does seem to work.
What could cause this?

**Comment by disconnect3d** [comment]
> I just compiled my own simple program and it does seem to work.
> What could cause this?

I think it might not work on binaaries statically linked with libc.

**Comment by elongl** [comment]
@disconnect3d 
It wasn't statically linked, but I loaded a different glibc than my system's using `LD_PRELOAD`,
therefore I truly didn't have its symbols.

Sorry for the false issue, my bad.

**Comment by disconnect3d** [comment]
Np, you are welcome! :)

EDIT:
> but I loaded a different glibc than my system's using LD_PRELOAD,
therefore I truly didn't have its symbols.

Yeah... I think there might be some way to retrieve the proper info when not having symbols e.g. by having one allocated pointer or inspecting the heap. Though someone would have to implement that :(
