### ISSUE TITLE
remote target do not reset is_remote

### ISSUE THREAD

**Issue by GrosQuildu** [pwndbg/pwndbg#789]
### Description

When debugging qemu kernel with `gdb ./vmlinux` followed by `target remote :1234`, `pwndbg.remote.is_remote` function falsely returns `False`.

### My setup

Gdb:      8.1.0.20180409-git
Python:   3.6.9 (default, Apr 18 2020, 01:56:04)  [GCC 8.4.0]
Pwndbg:   1.1.0 build: 5efff78
Capstone: 4.0.1024
Unicorn:  1.0.2

### Discussion
[`pwndbg.remote.is_remote`](https://github.com/pwndbg/pwndbg/blob/ca649da0e34cb150b5f4614c25efb284a28e5d39/pwndbg/remote.py#L18) is memoized with `reset_on_objfile`. As it seems, `target` do not cause a reset. Because of that [`is_qemu`](https://github.com/pwndbg/pwndbg/blob/09e1b37c8a69ee99aa8bffbfe84598aeab531e9d/pwndbg/qemu.py#L21) and `is_qemu_kernel` return False and pwndbg tries to [`auxv.walk_stack`](https://github.com/pwndbg/pwndbg/blob/33350ab8f6962f5d2fa4036c5999410535d4275c/pwndbg/auxv.py#L153) which loops very slowly (in [`auxv._get_execfn`](https://github.com/pwndbg/pwndbg/blob/33350ab8f6962f5d2fa4036c5999410535d4275c/pwndbg/auxv.py#L265)) byte-by-byte. So we hangs.

Removing memoization from `is_remote` solves the problem, but idk how it impact performance in other situations.

**Comment by disconnect3d** [comment]
It works for me when I do `qemu-x86_64 -g 1234 /bin/ls` and `target remote localhost:1234`.

**Comment by GrosQuildu** [comment]
I used `qemu-system-i386` and kernel v3.7.1. But check what `is_remote` returns after `target remote` and if its correct.

**Comment by disconnect3d** [comment]
Also works for me (`is_remote` and `is_qemu` both returns `True`) for the following setup:

```
pwndbg> version
Gdb:      8.1.0.20180409-git
Python:   3.6.9 (default, Apr 18 2020, 01:56:04)  [GCC 8.4.0]
Pwndbg:   1.1.0 build: 8c601c4
Capstone: 4.0.1024
Unicorn:  1.0.2
```

Qemu kernel
```
qemu-system-x86_64 \
    -s \
	-nographic \
	-monitor /dev/null \
	-kernel ./bzImage \
	-initrd ./initramfs.cpio.gz \
	-append "console=ttyS0"
```

Doing `gdb /bin/ls` and then `target remote localhost:1234`:
```
pwndbg> pi pwndbg.remote.is_remote(), pwndbg.qemu.is_qemu()
(True, True)
```

ps: note that i don't have vmlinux here :/

**Comment by GrosQuildu** [comment]
Well, ok. Somebody hits the same problem then we will see. Closing.
