### ISSUE TITLE
Pwndbg may hide the stdout output from the console

### ISSUE THREAD

**Issue by albertlab0** [pwndbg/pwndbg#790]
### Steps to reproduce
1.  Use attached ELF64 on Linux , in pwndbg set a breakpoint on main
2. Step through the code until exit
3.  "Hello World" never shows up in console

### My setup
config output:
debug-events                       False                                                       display internal event debugging info
dereference-limit                  5                                                           max number of pointers to dereference in a chain
emulate                            True                                                        Unicorn emulation of code near the current instruction
exception-debugger                 False                                                       whether to debug exceptions raised in Pwndbg commands
exception-verbose                  False                                                       whether to print a full stacktracefor exceptions raised in Pwndbg commands
heap-dereference-limit             8                                                           number of bins to dereference
hexdump-bytes                      64                                                          number of bytes printed by hexdump command
hexdump-width                      16                                                          line width of hexdump command
ida-enabled                        True                                                        whether to enable ida integration
ida-rpc-host                       '127.0.0.1'                                                 ida xmlrpc server address
ida-rpc-port                       31337                                                       ida xmlrpc server port
ida-timeout                        2                                                           time to wait for ida xmlrpc in seconds
left-pad-disasm                    True                                                        whether to left-pad disassembly
nearpc-lines                       10                                                          number of additional lines to print for the nearpc command
nearpc-show-args                   True                                                        show call arguments below instruction
show-flags                         False                                                       whether to show flags registers
show-retaddr-reg                   False                                                       whether to show return address register
syntax-highlight                   True                                                        Source code / assembly syntax highlight
telescope-lines                    8                                                           number of lines to printed by the telescope command
telescope-skip-repeating-val       True                                                        whether to skip repeating values of the telescope command

Gdb:      9.1
Python:   3.8.2 (default, Apr 27 2020, 15:53:34)  [GCC 9.3.0]
Pwndbg:   1.1.0 build: 8c601c4
Capstone: 4.0.1024
Unicorn:  1.0.2

[bug.zip](https://github.com/pwndbg/pwndbg/files/4807062/bug.zip)

My guess is the output was flushed away during debug window repaint.

**Comment by albertlab0** [comment]
Attaching the attachment file.
[bug.zip](https://github.com/pwndbg/pwndbg/files/4807019/bug.zip)

**Comment by disconnect3d** [comment]
Hey, what do you mean by `step through the code until exit`? Did you use `step`, `si`, `next` or `ni` instructions?

I have double checked this with `ni` instruction and all works as expected: tthe output appears properly. It might appear it does not appear as it is displayed before our context output and I think we can't change that (we display context when GDB prompt is displayed).

Here a proof/screenshot when I go through the code with `ni` (ps: I have `set context-sections disasm` configured so I can fit all on one screen):
![image](https://user-images.githubusercontent.com/10009354/86188535-3719e880-bb3f-11ea-9b6e-e9ca076a42f8.png)

Please re-open this issue if I overlooked something/checked it badly.
