### ISSUE TITLE
telescope should not fold single values, should probably be configurable

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#803]
In this screenshot, we should simply display the 0x28 and 0x90 and 0x108 offset in the stack trace.  The ellipsis isn't particularly useful here, and actually adds to cognitive load due to having to check how many values are skipped.

This should probably be behind a config, e.g. `telescope-fold-minimum` which is expressed in pointer widths.  This will allow people to control the setting to their choosing (or disable folding it with a value of 0 or -1 or something).

![](https://user-images.githubusercontent.com/10009354/85929449-471e9780-b8b5-11ea-86c6-d4191845f781.png)

**Comment by PhyzXeno** [comment]
I found a way that can solve this temporarily,  in command/ directory open telescope.py and we can find words like "Collapse repeating values", just change line 111 "if not skip" into “if skip”, we will get the problem fixed.

**Comment by anthraxx** [comment]
I've added a PR which does exactly this using the config `telescope-skip-repeating-val-minimum` (int). This config is related to the already existing config to avoid skipping all together `telescope-skip-repeating-val` (bool). I think its clearer to preserve the existing bool config (and not break existing configs) and have the minimum be a plain minimum without magic values for special meaning like `-1`.

**Comment by anthraxx** [comment]
I've added a label for the amount of collapsed lines to reduce cognitive load

![telescope](https://user-images.githubusercontent.com/203012/113359098-57353d00-9347-11eb-8e7e-858bf6195848.png)
