### ISSUE TITLE
New release?  It's been 6+ months since the last one.

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#804]
It would be nice if we could cut a new release, since the last tag is from December.

Separately, have we been practicing back ports at all?  It seems like the release process is "just tag dev" instead of having a merge strategy with a buffer release like Pwntools does.  This actively saves lots of work, and might be worth investigating.

**Comment by zachriggle** [comment]
This might be a good time to start leveraging Github Actions to automatically cut releases every month or so.

@arusekk has done a great job making the release process pain-free, and Github Actions supports a cron job so we could literally just make it auto-create a tag each month on the 1st.

**Comment by Arusekk** [comment]
@zachriggle confused repos?

**Comment by zachriggle** [comment]
Nope just mentioning that you've done great things to automate the Pwntools releases, and that same stuff could be cribbed for Pwndbg's releases as well

**Comment by anthraxx** [comment]
@disconnect3d I agree, can we get a release soonish? :D 

I could take a look at getting github actions running via a PR.
We really should issues release more often so packages like the Arch package can ship more modern stuff to users :cat:

**Comment by disconnect3d** [comment]
Yes, I will do it now :P.

**Comment by disconnect3d** [comment]
2020.07.23 released.

> Separately, have we been practicing back ports at all? It seems like the release process is "just tag dev" instead of having a merge strategy with a buffer release like Pwntools does. This actively saves lots of work, and might be worth investigating.

We didn't do any back ports. Since pwndbg is not used as a library and we work with any sane GDB version, I don't think there is much need to care about back ports (and, to be honest, we would need more manpower for this :P).

Anyway, this being said, I think we can close the `stable` branch and keep just one `main` branch and cut off releases from that.

@zachriggle @anthraxx  thoughts?

**Comment by zachriggle** [comment]
By "back ports" I don't mean per GDB version.  Rather, when we got a bug-fix in, do we have a separate "stable" branch those fixes go into (if they effect the previous release) such that the released code gets updated (and a new release cut) with no new features included (just bug fixes) until the following release.

**Comment by anthraxx** [comment]
closing the `stable` branch may seem to make it easier, but this would make an automatic release process basically like cutting-edge releases as you either would not want to merge a crazy huge PR just before the end of the month or you do it and have basically untested fresh code in a release.
a `stable` branch that would be used to cut releases from would add more control over when we rebase `master` into and deem introduced features or code changes as field tested.

**Comment by disconnect3d** [comment]
Closed `stable`, we don't really use it.

Released current dev to https://github.com/pwndbg/pwndbg/releases/tag/2021.06.22

Closing this for now, please reopen if you think it needs more discussion
