### ISSUE TITLE
Function arguments: Infer type and display accordingly

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#806]
Currently we have excellent infrastructure for determining the arguments and argument names for standard libc routines, like `getenv`.

However, we don't leverage the type information we have to determine whether to display the values as an address vs a string.

```
 ► 0x555555582d40 <main+368>    call   getenv <getenv>
        name: 0x5555556320ab ◂— 0x5f594c5849534f50 ('POSIXLY_')
```

It would be nice if the entire string, is displayed.

```
pwndbg> ds 0x5555556320ab
5555556320ab 'POSIXLY_CORRECT'
```

I think this is because we just telescope the value regardless, but it would be neat to have better information.  For example, `functions.py` has this for `getenv`:

```
 'getenv': Function(type='char', derefcnt=1, name='getenv', args=[Argument(type='char', derefcnt=1, name='name')]),
```

**Comment by disconnect3d** [comment]
Some of this was already implemented. Closing.
