### ISSUE TITLE
Telescope: Better string detection

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#807]
Similar to or in lieu of #806, it would be nice if the default behavior of `telescope` were able to detect e.g. `[A-Za-z0-9-_]+{8,}` and decide to display the entire string, rather than the first 4 or 8 bytes of the string.

This should only occur if the ASCII values are also NOT a valid pointer value (so as not to do unexpected things when e.g. `0x4141414141414141` is used, but it's also a valid address.

```
0x5555556320ab ◂— 0x5f594c5849534f50 ('POSIXLY_')
```
```
pwndbg> ds 0x5555556320ab
5555556320ab 'POSIXLY_CORRECT'
```

**Comment by gsingh93** [comment]
Dup of https://github.com/pwndbg/pwndbg/issues/368

**Comment by gsingh93** [comment]
I'm wondering if we should close this in favor of just improving how telescope handles strings: https://github.com/pwndbg/pwndbg/issues/368
