### ISSUE TITLE
Disable search-memory-packet back only on broken GDB version

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#808]
Tl;dr: Use the workaround from https://github.com/pwndbg/pwndbg/pull/322/files only for broken gdb versions

**Comment by gsingh93** [comment]
According to the referenced bug, the issue may have been fixed back in 2020. If so, I'd guess it's in GDB 10, which means 18.04 and 20.04 are still affected (with versions 8.1 and 9.2), but not 22.04 (with version 12).

**Comment by disconnect3d** [comment]
We should check if this is about GDB or GDBServer version or both and if we should only use the workaround if we detect a version that needs it.

**Comment by disconnect3d** [comment]
Fwiw we have removed the `set remote search-memory-packet off ` setting in 77380eb63c6cfdb721f2a2c4448f9d544fa03bd7 accidentally I think :/.

**Comment by disconnect3d** [comment]
This has been fixed in https://github.com/pwndbg/pwndbg/pull/1619. Also, if someone wants to reproduce the search bug/workaround, GDB 9.x is needed as shown in https://github.com/pwndbg/pwndbg/pull/1618.

**Comment by disconnect3d** [comment]
In case someone ever looks here, this workaround has been removed from our codebase in https://github.com/pwndbg/pwndbg/pull/2892 since we only support GDB 12+ now, which does not require this workaround anymore.
