### ISSUE TITLE
OverflowError on the 64-bit integer due to Python2 int subclassing

### ISSUE THREAD

**Issue by kevinpark1217** [pwndbg/pwndbg#813]
### Description

Integer casts like below works great until the value is bigger than the `C long` type.
```python
# pwndbg/regs.py: 299
value = int(value)
```
The ideal solution would be to for Python to use `unsigned long` type of C in order to utilize the full 64 bit addressing capability. But far as my knowledge goes, I don't think we can force Python to do that. Thus, the solution would be to use `long()` casts instead of the `int()` casts.

![Screenshot from 2020-08-12 00:48:45](https://user-images.githubusercontent.com/10012884/89984013-ae669000-dc46-11ea-8d63-11706d434559.png)

### Steps to reproduce

Adding a debug print right before the cast in `pwndbg/regs.py` shows the issue.  
`int()` is unable to handle numbers in the range of 2^63-1 and 2^64-1  due to the integer signing issue.
```python
print("{}: {}".format(attr, value))
```
![Screenshot from 2020-08-12 01:02:41](https://user-images.githubusercontent.com/10012884/89985106-7fe9b480-dc48-11ea-88c5-bb5b63b153ec.png)

### My setup

```
OS: Ubuntu 20.04
Gdb: 8.3.1
Python: Python 2.7.18rc1
```

**Comment by kevinpark1217** [comment]
This issue can be resolved with replacing all of the affected `int()` casts with `long()`.
Since the codebase utilizes `pwndbg/inthook.py` for hooking integer casts, I will create `pwndbg/longhook.py` for long casting as well.

**Comment by kevinpark1217** [comment]
After investigating, trying to fix this issue might create more problems with python2 & python3 compatibility. So, I think it might be better to just drop support for Python2, and move on [like it's mentioned here](https://github.com/pwndbg/pwndbg/issues/726#issuecomment-600756614). @disconnect3d

**Comment by disconnect3d** [comment]
Yeah, lets do that. I should prepare a PR with it in a few days.

**Comment by disconnect3d** [comment]
Dropped py2 support in https://github.com/pwndbg/pwndbg/pull/817, so closing this issue.

If for whatever reason this happens again, open another issue or re-open this one
