### ISSUE TITLE
"aslr" Command Always Showing "ASLR OFF "

### ISSUE THREAD

**Issue by ghost** [pwndbg/pwndbg#814]
### Description
"aslr" command should show current ASLR setting when it's typed without any option or argument. But it always shows "ASLR OFF" no matter what the current ASLR setting is. For some reasons, modifying "vmmap.aslr=False" to "vmmap.aslr = True" on line 438 of pwndbg/vmmap.py seems to fix the bug.

### Steps to reproduce
Launch gdb and type "aslr"  at the prompt.

### My setup
Gdb:      9.2
Python:   3.8.5 [GCC 10.2.0]
Pwndbg:   1.1.0 
Capstone: 4.0.1024
Unicorn:  1.0.2
Operating System:  Kali GNU/Linux 2020.3 64 bits

**Comment by disconnect3d** [comment]
Why is this a bug? Most likely, you have the `disable-randomization` GDB parameter set to `on`.

This can be seen:
```
(gdb) show disable-randomization
Disabling randomization of debuggee's virtual address space is on.
```

and is also one of the methods the `aslr` command fetches this status.

I have extended the output of the command and its help a bit in #818 

Please re-open if you had another issue with more details.
