### ISSUE TITLE
Emacs GUD + pwndbg

### ISSUE THREAD

**Issue by fberlakovich** [pwndbg/pwndbg#819]
I often use Emacs to edit the sourcefiles I want to debug at a later time. Pwndbg on the other hand provides excellent debugging features which imo are superiour over Emacs GUD debugging features.

It woud be nice to combine Emacs GUD with pwndbg to have the different pwndbg contexts in separate Emacs GUD windows. This would not only allow to reuse Emacs' windowing system, but also integrate debugging and sourcecode modification.

Currently I am using pwndbg + splitmind to see as many contexts at once as possible.

**Comment by zachriggle** [comment]
Can you provide more information on emacs GUD and split mind? I'm not familiar with these projects.

**Comment by fberlakovich** [comment]
Emacs GUD (Grand Unified Debugger) is a major mode for emacs that integrates with command line debuggers to allow debugging directly from emacs. As far as I understand GUD, it is simply an abstraction layer over several different debuggers.

[Splitmind](https://github.com/pwndbg/pwndbg/blob/dev/FEATURES.md#splitting--layouting-context) is a utilility to distribute pwndbg's contexts over the screen. Splitmind is really nice in general, but sometimes it would be helpful to change the window configuration while debugging a program. Also wrapping lines can sometimes mess up the layout. But who knows, maybe I am holding it wrong ;).

**Comment by fberlakovich** [comment]
For people looking for something similar: https://github.com/snare/voltron. With voltron it would probably be even possible to do what I initially suggested in this issue in Emacs without pwndbg/Emacs modifications, just with a little bit of automation. Voltron can make use of all the pwndbg goodies, but in separate windows, e.g. with `voltron view command "context reg"`.

**Comment by disconnect3d** [comment]
Thanks for more info. Pwndbg windows can also be [split into different terminals](https://github.com/pwndbg/pwndbg/blob/dev/FEATURES.md#splitting--layouting-context).

I am going to close this issue since we are not going to work on any Emacs support. However, if anyone would like such support and would be up for maintaining and advertising it, I am up for merging such features.
