### ISSUE TITLE
Installation on macOS

### ISSUE THREAD

**Issue by shinokada** [pwndbg/pwndbg#827]
### Description

After following the doc to install on macOS, `pwddbg` seems not working with gdb.

```
git clone https://github.com/pwndbg/pwndbg
cd pwndbg
./setup.sh
```

> ❯ ./setup.sh --with-python=/Users/shinokada/.pyenv/versions/py385/bin/python
> + '[' -f /.dockerenv ']'
> + PYTHON=
> + INSTALLFLAGS=
> + osx
> + uname
> + grep -i Darwin
> + INSTALLFLAGS=--user
> + linux
> + uname
> + grep -i Linux
> + hash gdb
> + git submodule update --init --recursive
> ++ gdb -batch -q --nx -ex 'pi import platform; print(".".join(platform.python_version_tuple()[:2]))'
> + PYVER=3.8
> ++ gdb -batch -q --nx -ex 'pi import sys; print(sys.executable)'
> + PYTHON+=/usr/local/opt/python@3.8/bin/python3.8
> + PYTHON+=3.8
> + linux
> + uname
> + grep -i Linux
> + /usr/local/opt/python@3.8/bin/python3.83.8 -m pip -V
> ./setup.sh: line 134: /usr/local/opt/python@3.8/bin/python3.83.8: No such file or directory
> + /usr/local/opt/python@3.8/bin/python3.83.8 -m ensurepip --user --upgrade
> ./setup.sh: line 135: /usr/local/opt/python@3.8/bin/python3.83.8: No such file or directory

I am not able to install on macOS as you can see in the last four lines above.

**Comment by Pure-T** [comment]
I have the same problem. But I've found a way fix it.

Just comment out 134 lines of the `setup.sh` file 

```
PYTHON+=$(gdb -batch -q --nx -ex 'pi import sys; print(sys.executable)')
# PYTHON+="${PYVER}"
```

**Comment by MaximeFrancoeur** [comment]
> 

the solution of @Pure-T work well on Mac Monterey OS.
