### ISSUE TITLE
telescope don't work, when give $reg + 0xOFFSET statment

### ISSUE THREAD

**Issue by kotee4ko** [pwndbg/pwndbg#833]
### Steps to reproduce

Gdb session history:
disass main
b *0x00000000004009d5
r
r
r
r
r
r
r
r
r
r
r
c
r
c
r
c
r
c
r
plt
got
r
ni
ni
nextret 
ni
tele 0x603490
vis
context
exec ropper --file ./ch40 | grep rsi
ropper --file ./ch40 | grep rsi
ropper -- --file ./ch40 | grep rsi
ropper -- --file ./ch40 
context
ropper -- --file ./ch40 
ropper -- --help
ropper -- --file ./ch40 --search "?si"
ropper -- --file ./ch40 --search "rsi"
ropper -- --file ./ch40 --search rsi
ropper -- --file ./ch40 --search "mov ?si"
context
disass
disassmain
disass main
man fopen
context
ropper -- --file ./ch40 --search "mov ?si"
ropper -- --file ./ch40 --search "mov ?di"
x/i 0x601010
x/i 0x600d90
disass 0x640
vmmap
disass 0x640+0x400000
disass 0x660+0x400000
set var $rip = 0x000000000040085b
ni
ropper -- --file ./ch40 --search "mov rdi"
ropper -- --file ./ch40 --search "mov rax"
x/xg $rbp - 0x418
disass 0x640+0x400000
ropper -- --file ./ch40 --search "mov rbp"
set var $rip =0x00000000004006e0
ni
ropper -- --file ./ch40 --search "mov rbp"
set var $rip = 0x000000000040077a
ni
r
r
r
r
r
run  ./ch40 
r
file ./ch40 
r
set args /tmp/BBBB
r
ni
set var $rip = 0x000000000040077a
ni
r
nextret 
ni
ropper -- --file ./ch40 --search "mov rax"
ropper -- --file ./ch40 --search "mov eax"
nextret 
ropper -- --file ./ch40 --search "mov eax"
nextret 
r
r
nextret 
ropper -- --file ./ch40 --search "?rbp?"
ropper -- --file ./ch40 --search "%rbp"
ropper -- --file ./ch40 --search "mov rbp"
ropper -- --file ./ch40 --search "push"
set var $rip = 0x00000000004008a4
ni
set var $rip = 0x00000000004008a4
ni
r
nextret 
ni
set var $rip = 0x00000000004008a4
ni
r
nextret 
ni
disass 0x00000000004008a4
set var $rip = 0x0000000000400882
ni
proc
set var $rip = 0x0000000000400882
ni
set var $rip = 0x0000000000400882
r
nextret 
ni
nextret 
plt
r
nextcall 
nextret 
ni
set var $rip = 0x400600
ni
ni
r
nextret 
ni
plt
got
got --help
gotplt 
gotplt -h
list functions
list functions_allocate 
list functions_deallocate 
ls
disass
disass main
set var $rip = 0x000000000040093b
si
ni
man fseek
ni
r
plt
set var $rip = 0x4005f0
ni
ni
nextret 
ni
ropper -- --file ./ch40 --search "?bp"
ropper -- --file ./ch40 --search "mov ?bp"
set var $rip = 0x00000000004006e0
ni
ropper -- --file ./ch40 --search "mov ?bp"
ni
ropper -- --file ./ch40 --search "mov ?bp"
ni
set var $rip = 0x00000000004006e0
ni
disass
b *0x00000000004008b3
r
ni
r
disass
b *0x00000000004009b1
r
c
si
ni
nextj
nextjmp 
si
nextjmp 
nextret 
stack
i f
ni
x/xg $rbp - 0x40c
tele #rbp - 0x40c
tele $rbp - 0x40c
set exception-verbose on
tele $rbp - 0x40c
bugreport --run-browser
version

### My setup

Platform: Linux-5.8.0-1-amd64-x86_64-with-glibc2.29
Gdb:      9.2
Python:   3.8.5 (default, Aug  2 2020, 15:09:07)  [GCC 10.2.0]
Pwndbg:   1.1.0 build: 487caa1
Capstone: 4.0.1024
Unicorn:  1.0.2
This GDB was configured as follows:
   configure --host=x86_64-pc-linux-gnu --target=x86_64-pc-linux-gnu
             --with-auto-load-dir=$debugdir:$datadir/auto-load
             --with-auto-load-safe-path=$debugdir:$datadir/auto-load
             --with-expat
             --with-gdb-datadir=/usr/local/share/gdb (relocatable)
             --with-jit-reader-dir=/usr/local/lib/gdb (relocatable)
             --without-libunwind-ia64
             --with-lzma
             --with-babeltrace
             --with-intel-pt
             --with-mpfr
             --with-xxhash
             --with-python=/usr
             --without-guile
             --enable-source-highlight
             --with-separate-debug-dir=/usr/local/lib/debug (relocatable)

("Relocatable" means the directory can be moved with the GDB installation
tree, and GDB will still find it.)
```
pwndbg> tele #rbp - 0x40c
Exception occurred: telescope: Invalid character '#' in expression. (<class 'gdb.error'>)
For more info invoke `set exception-verbose on` and rerun the command
or debug it by yourself with `set exception-debugger on`
pwndbg> tele $rbp - 0x40c
Exception occurred: telescope: A syntax error in expression, near `'. (<class 'gdb.error'>)
For more info invoke `set exception-verbose on` and rerun the command
or debug it by yourself with `set exception-debugger on`
pwndbg> set exception-verbose on
Set whether to print a full stacktrace for exceptions raised in Pwndbg commands to True
pwndbg> tele $rbp - 0x40c
Traceback (most recent call last):
  File "/opt/pwndbg/pwndbg/commands/__init__.py", line 77, in invoke
    args, kwargs = self.split_args(argument)
  File "/opt/pwndbg/pwndbg/commands/__init__.py", line 291, in split_args
    return tuple(), vars(self.parser.parse_args(argv))
  File "/usr/lib/python3.8/argparse.py", line 1780, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 1812, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 2021, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "/usr/lib/python3.8/argparse.py", line 1977, in consume_positionals
    take_action(action, args)
  File "/usr/lib/python3.8/argparse.py", line 1870, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/usr/lib/python3.8/argparse.py", line 2401, in _get_values
    value = self._get_value(action, arg_string)
  File "/usr/lib/python3.8/argparse.py", line 2434, in _get_value
    result = type_func(arg_string)
  File "/opt/pwndbg/pwndbg/commands/__init__.py", line 203, in fix_int_reraise
    return fix(*a, reraise=True, **kw)
  File "/opt/pwndbg/pwndbg/commands/__init__.py", line 190, in fix
    raise e
  File "/opt/pwndbg/pwndbg/commands/__init__.py", line 185, in fix
    return gdb.parse_and_eval(arg)
gdb.error: A syntax error in expression, near `'.

If that is an issue, you can report it on https://github.com/pwndbg/pwndbg/issues
(Please don't forget to search if it hasn't been reported before)
To generate the report and open a browser, you may run `bugreport --run-browser`
PS: Pull requests are welcome
pwndbg> bugreport --run-browser
Traceback (most recent call last):
  File "/opt/pwndbg/pwndbg/commands/__init__.py", line 130, in __call__
    return self.function(*args, **kwargs)
  File "/opt/pwndbg/pwndbg/commands/version.py", line 140, in bugreport
    current_setup = 'Platform: %s\n' % platform()
  File "/usr/lib/python3.8/platform.py", line 1205, in platform
    libcname, libcversion = libc_ver(sys.executable)
  File "/usr/lib/python3.8/platform.py", line 193, in libc_ver
    with open(executable, 'rb') as f:
FileNotFoundError: [Errno 2] Нет такого файла или каталога: '/usr/bin/python'

If that is an issue, you can report it on https://github.com/pwndbg/pwndbg/issues
(Please don't forget to search if it hasn't been reported before)
To generate the report and open a browser, you may run `bugreport --run-browser`
PS: Pull requests are welcome
pwndbg> version
Gdb:      9.2
Python:   3.8.5 (default, Aug  2 2020, 15:09:07)  [GCC 10.2.0]
Pwndbg:   1.1.0 build: 487caa1
Capstone: 4.0.1024
Unicorn:  1.0.2
```

**Comment by disconnect3d** [comment]
Hey,

you need to use `tele $rbp-0x40c` or `tele '$rbp - 0x40c'` instead. This is bcoz telescope also gets a `count` arguments:
```
pwndbg> telescope --help
usage: telescope [-h] [address] [count]

Recursively dereferences pointers starting at the specified address ($sp by default)

positional arguments:
  address     The address to telescope at.
  count       The number of lines to show. (default: 8)

optional arguments:
  -h, --help  show this help message and exit
```

This being said I am closing this for now. However, if you (or anyone, really) would like to improve this situation, feel free to contribute & send a pull request (that would handle this error case better by either suggesting a solution or trying to work it around and check if the whole argument can be passed to `address` argument).
