### ISSUE TITLE
Can not launch radare2

### ISSUE THREAD

**Issue by d0ntrash** [pwndbg/pwndbg#840]
### Description
After installing the newest version of radare2 (4.6.0) and the r2ghidra-dec package I can no longer launch r2 inside pwndbg.
Error: "[r] Cannot open '0x3ffcda40'"

### Steps to reproduce
Install radare 4.6.0
Install r2ghidra-dec
Run Gdb 
Run "r2"

### My setup

OS (VM): 5.7.0-kali1-amd64
Radare2: 4.6.0
Gdb:      9.2 
Python:   3.8.6 (default, Sep 25 2020, 09:36:53)  [GCC 10.2.0]
Pwndbg:   1.1.0 build: 9250cc5
Capstone: 4.0.1024
Unicorn:  1.0.1

**Comment by disconnect3d** [comment]
Fixed by #842
