### ISSUE TITLE
Bug on Hexdump file does not allow to run pwndbg properly

### ISSUE THREAD

**Issue by FilipeCapela98** [pwndbg/pwndbg#841]
### Description

Someone left an "f" on line 86 of Hexdump, not allowing pwndbg to run correctly since python casts an exception.

hexline.append(f'{config_byte_separator}')

**Comment by zer0-1s** [comment]
just delete the f？

**Comment by disconnect3d** [comment]
It isn't a bug. It's a Python 3.6+ f-string literal. However, since we still support Py2 I am going to fix this.

**Comment by zachriggle** [comment]
@disconnect3d what's the plan to deprecate Py2 support?  I thought we did this already since the last few Ubuntu releases all use a Py3 interpreter for GDB
