### ISSUE TITLE
Can't successfully connect to gdb with tmux

### ISSUE THREAD

**Issue by PaleNeutron** [pwndbg/pwndbg#843]
### Description
```
Waiting for debugger: debugger exited! (maybe check /proc/sys/kernel/yama/ptrace_scope
```
Always got this after `gdb.attach`

But gdb is successfully attached.

### Steps to reproduce
```python
from pwn import *
import logging


fn = "./stack_overflow"
context(log_level='debug')
context.terminal = ['tmux','splitw','-h']
context.binary=fn

sh = process(fn)
gdb.attach(sh)
```
### My setup
Gdb:      7.12.0.20161007-git
Python:   3.5.3 (default, Jul  9 2020, 13:00:10)  [GCC 6.3.0 20170516]
Pwndbg:   1.1.0 build: b209c2b
Capstone: 4.0.1024
Unicorn:  1.0.2

Distributor ID: Debian
Description:    Debian GNU/Linux 9.11 (stretch)
Release:        9.11
Codename:       stretch

**Comment by disconnect3d** [comment]
Can you provide some more info? Does this fail when tmux terminal line is commented out?
Does this fail only if pwndbg is loaded in gdb or in general? If it fails w/o pwndbg, then this is not a pwndbg bug but could be pwntools bug.

**Comment by PaleNeutron** [comment]
Sorry, I have tried use this without `pwndbg` and it still exist.

It's my mistake and I'll report it to `pwntools`.

Thank you for help.
