### ISSUE TITLE
IDA Integration: Randomized port selection for multiple IDBs / debugged processes, auto-copy IDA script

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#845]
Currently, the IDA Pro integration requires a specific port, `31337` for all of its XML-RPC communications.

It would be nice if the following additions were made:

* An additional configuration setting that selects a random port based on the PID of the debugged process
  * This more easily allows debugging multiple separate processes in different IDBs
  * This also allows easier debugging of multiple copies of the same process, by selecting the correct port
* An additional configuration setting that copies the IDAPython initialization script to the system clipboard.  This should also support dynamically setting the port based on the above suggested configuration.
  * xclip on Linux
  * pbcopy on macOS
  * clip on Windows

**Comment by zachriggle** [comment]
Following up on this, apparently there is a `~/.idapro/idapythonrc.py` that is automatically loaded when an IDB is opened.

We could leverage this for the IDAPython XML-RPC server by suggesting that it get imported from `idapythonrc.py` and determine port dynamically based on the input file's original SHA/MD5 (which IDA has an API to determine).

```py
# Load Pwndbg integration automatically
import os

pwndbg_script = '/path/to/pwndbg/ida_script.py'
if os.path.isfile(pwndbg_script):
    exec(open(pwndbg_script, 'rt').read())
```

We can do the same for the Pwndbg side of things, though this will break for patched binaries (since IDAPython returns the original e.g. MD5, not the current one AFAIK).

This would mean that simply opening an IDB would start the server on a dynamic port per-file, and the `pwndbg.ida` module could adjust the default port to be the corresponding one, and things would "just work".

This ultimately allows multiple different IDBs/Pwndbg instances to be run automatically without fiddling with the port configuration manually.

This MAY introduce the issue that setting up port-forwarding via e.g. Docker is harder due to the dynamic port, so it may be good idea to, if the file-specific port is not open, to try the current-default 31337.

It may be useful to add a command to Pwndbg that automatically installs the above-suggested `exec` statement, e.g.

```
pwndbg> install-idapython-integration
```

This would greatly reduce the overhead for using IDA integration, since it currently requires copy-pasting a file contents.

**Comment by disconnect3d** [comment]
TL;DR: Closing all IDA integration issues for now. We implemented Binja integration recently and an abstraction for `IntegrationProvider`. I would be happy of accepting a new version of IDA sync if anyone is interested in implementing it (since the old script and code most likely do not work at all).

https://github.com/pwndbg/pwndbg/issues/218#issuecomment-2518778108
