### ISSUE TITLE
Switch back to pwndbg.com

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#846]
It looks like pwndbg.com is available again for registration.  I suggest that we snatch it up and convert official links back to that domain.  I don't mind fronting the cost for 5 years of domain so we don't lose it again.

<img width="833" alt="Screen Shot 2020-10-20 at 2 02 17 PM" src="https://user-images.githubusercontent.com/111640/96632134-de807e00-12dc-11eb-8aed-1bfa9d6d87c4.png">

If @disconnect3d agrees I'll buy the name and try to set everything up in Google Domains, with TLS and all the goodies that GitHub supports in the same way that https://pwntools.com works.

We can either keep the registration for pwndbg.re or not, that's up to @disconnect3d too.

**Comment by disconnect3d** [comment]
Yeah, let's move to pwndbg.com; I can make pwndbg.re redirect there too :P.

**Comment by zachriggle** [comment]
The following links are active and should be working:

* http://pwndbg.com
* https://pwndbg.com

I was only able to perform the initial registration for 1 year, so I just need to not ignore their warning emails this time if my payment stuff changes and they don't have a way to bill me 🤞

**Comment by zachriggle** [comment]
@disconnect3d can you update the README and the Github project slug to reflect the new URLs?

**Comment by disconnect3d** [comment]
Done
