### ISSUE TITLE
python3.8: UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 3455: invalid start byte 

### ISSUE THREAD

**Issue by kotee4ko** [pwndbg/pwndbg#849]
```
pwndbg> proc
exe        '/opt/DSSHD-alpha-v1.4/opt/openssh-portable/sshd'
Exception occurred: procinfo: 'utf-8' codec can't decode byte 0x85 in position 3455: invalid start byte (<class 'UnicodeDecodeError'>)
For more info invoke `set exception-verbose on` and rerun the command
or debug it by yourself with `set exception-debugger on`
pwndbg> set exception-verbose on
Set whether to print a full stacktrace for exceptions raised in Pwndbg commands to True
pwndbg> proc
exe        '/opt/DSSHD-alpha-v1.4/opt/openssh-portable/sshd'
Traceback (most recent call last):
  File "/opt/pwndbg/pwndbg/commands/__init__.py", line 130, in __call__
    return self.function(*args, **kwargs)
  File "/opt/pwndbg/pwndbg/commands/__init__.py", line 221, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/opt/pwndbg/pwndbg/commands/procinfo.py", line 218, in procinfo
    for c in proc.connections:
  File "/opt/pwndbg/pwndbg/memoize.py", line 44, in __call__
    value = self.func(*args, **kwargs)
  File "/opt/pwndbg/pwndbg/commands/procinfo.py", line 185, in connections
    for x in func():
  File "/opt/pwndbg/pwndbg/net.py", line 142, in unix
    data = pwndbg.file.get("/proc/net/unix").decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 3455: invalid start byte
```

### Steps to reproduce

Gdb session history:
attach 201622
proc
set exception-verbose on
proc

### My setup

Platform: Linux-5.8.0-1-amd64-x86_64-with-glibc2.29
Gdb:      9.2
Python:   3.8.5 (default, Aug  2 2020, 15:09:07)  [GCC 10.2.0]
Pwndbg:   1.1.0 build: 487caa1
Capstone: 4.0.1024
Unicorn:  1.0.2
This GDB was configured as follows:
   configure --host=x86_64-pc-linux-gnu --target=x86_64-pc-linux-gnu
             --with-auto-load-dir=$debugdir:$datadir/auto-load
             --with-auto-load-safe-path=$debugdir:$datadir/auto-load
             --with-expat
             --with-gdb-datadir=/usr/local/share/gdb (relocatable)
             --with-jit-reader-dir=/usr/local/lib/gdb (relocatable)
             --without-libunwind-ia64
             --with-lzma
             --with-babeltrace
             --with-intel-pt
             --with-mpfr
             --with-xxhash
             --with-python=/usr
             --without-guile
             --enable-source-highlight
             --with-separate-debug-dir=/usr/local/lib/debug (relocatable)

("Relocatable" means the directory can be moved with the GDB installation
tree, and GDB will still find it.)

P.S. 
running with ```LC_ALL=en_US.UTF-8 PYTHONIOENCODING=UTF-8``` from https://github.com/pwndbg/pwndbg/issues/412
have no result :(

P.S.S The bug appears with time. On fresh system it doesn't

**Comment by zachriggle** [comment]
We should probably have some helper code somewhere that makes opportunistic `utf-8` decoding, while falling back to `latin-1` if that fails (since `latin-1` has a 1:1 byte-to-glyph mapping).

Looks like this happens while processing `/proc/net/unix` and apparently we can't be sure it's well-formatted and UTF-8 valid.

**Comment by kotee4ko** [comment]
Can you hint me which part of code work with this, please?

**Comment by zachriggle** [comment]
I would look at the stack trace.  Pwndbg.file.get(...).decode seems to be exploding.  I recall there is an "ignore" flag that can be passed to decode, but this seems like a place for Latin-1 instead of utf8 (in the event of a failure as seen here).

It would be nice to break out a separate function that tries utf8 first, then falls back to Latin-1.

**Comment by kotee4ko** [comment]
As for me the fix was to add `replace` arg to decode() foo.
```
  GNU nano 5.1                                   /opt/pwndbg/pwndbg/net.py                                             

-_line 142:     data = pwndbg.file.get("/proc/net/unix").decode()
+_line 142:     data = pwndbg.file.get("/proc/net/unix").decode("utf-8", "replace")
```
