### ISSUE TITLE
Question about dependency (libglib2.0-dev)

### ISSUE THREAD

**Issue by davidpolverari** [pwndbg/pwndbg#853]
I noticed that pwndbg's `setup.sh` installs `libglib2.0-dev` among other dependencies:

`sudo apt-get -y install git gdb python3-dev python3-pip python3-setuptools libglib2.0-dev libc6-dbg`

Perhaps I'm missing something, but I could not find out what pwndbg uses it for. I wonder whether this dependency was added because of the name similarity from glibc (as GNU libc is known and maybe is packaged outside Debian) with the libglib (low-level library extracted from GTK for more general use). Is it really needed for any one feature of pwndbg?

**Comment by disconnect3d** [comment]
@zachriggle maybe you know this? :D

We should probably try running pwndbg without it and if it works, we can remove it?

**Comment by zachriggle** [comment]
No idea, likely for the debugging information in a common library.

**Comment by zachriggle** [comment]
Based on the Git commit history, it looks like it's necessary for Unicorn emulation.

$ git log -S libglib --oneline
cdbff11 Update installation instructions
effc1d0 Add Unicorn dependency
