### ISSUE TITLE
libc symbols

### ISSUE THREAD

**Issue by Th3F0x-code** [pwndbg/pwndbg#865]
Does anyone have any idea how to solve this problem? i've tried everything but nothing works (i'm on manjaro linux)
```heap: This command only works with libc debug symbols.
They can probably be installed via the package manager of your choice.
See also: https://sourceware.org/gdb/onlinedocs/gdb/Separate-Debug-Files.html

E.g. on Ubuntu/Debian you might need to do the following steps (for 64-bit and 32-bit binaries):
sudo apt-get install libc6-dbg
sudo dpkg --add-architecture i386
sudo apt-get install libc-dbg:i386

**Comment by disconnect3d** [comment]
We look for the `global_max_fast` symbol: https://github.com/pwndbg/pwndbg/blob/26a18f1d70cd3685010f771030a3602a7368601d/pwndbg/heap/ptmalloc.py#L555-L556

If it is not found, we skip processing any heap related commands.

You would need to install/set up libc with debug symbols somehow to fix this.

**Comment by disconnect3d** [comment]
Not an expert, but this might help? https://wiki.archlinux.org/index.php/Debug_-_Getting_Traces

Also @vesim987 may have some more insight here or/and confirm if ^ should work.

**Comment by DoubleMice** [comment]
@Th3F0x-code hi bro, I don't have any idea yet, have you solve it?
