### ISSUE TITLE
Exception occurred: context:  (<class 'StopIteration'>)

### ISSUE THREAD

**Issue by nohkoomote** [pwndbg/pwndbg#873]
### Description

Sorry for my lack of information.

I get this error when debugging.
Exception occurred: context:  (<class 'StopIteration'>)

Breakpoint 1, 0x08048534 in main ()
Traceback (most recent call last):
  File "/opt/pwndbg/pwndbg/commands/__init__.py", line 130, in __call__
    return self.function(*args, **kwargs)
  File "/opt/pwndbg/pwndbg/commands/__init__.py", line 221, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/opt/pwndbg/pwndbg/commands/context.py", line 334, in context
    result[target].extend(func(target=out,
  File "/opt/pwndbg/pwndbg/commands/context.py", line 479, in context_disasm
    cs = next(iter(pwndbg.disasm.get_disassembler_cached.cache.values()))
StopIteration

Gdb session history:
disass main
break *main+88
break *main+112
run
set exception-verbose on
run

### My setup

Description:	Ubuntu 20.04.1 LTS
Platform: Linux-5.4.0-58-generic-x86_64-with-glibc2.29
Gdb:      9.2
Python:   3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
Pwndbg:   1.1.0 build: c31c720
Capstone: 4.0.1024
Unicorn:  1.0.2
This GDB was configured as follows:
   configure --host=x86_64-linux-gnu --target=x86_64-linux-gnu
             --with-auto-load-dir=$debugdir:$datadir/auto-load
             --with-auto-load-safe-path=$debugdir:$datadir/auto-load
             --with-expat
             --with-gdb-datadir=/usr/share/gdb (relocatable)
             --with-jit-reader-dir=/usr/lib/gdb (relocatable)
             --without-libunwind-ia64
             --with-lzma
             --with-babeltrace
             --without-intel-pt
             --with-mpfr
             --without-xxhash
             --with-python=/usr (relocatable)
             --without-guile
             --disable-source-highlight
             --with-separate-debug-dir=/usr/lib/debug (relocatable)
             --with-system-gdbinit=/etc/gdb/gdbinit

**Comment by disconnect3d** [comment]
I can't really reproduce this. Can you provide more info?

**Comment by ins0** [comment]
@disconnect3d  Just run into the same problem.

> b *0x0804867f
> r
Breakpoint 1, 0x0804867f in do_stuff ()
Exception occurred: context:  (<class 'StopIteration'>)

hope this helps - along with the binary - pwndbg is at latest dev master - deps are up to date from `setup.sh`.
let me know if you need more infos when reproduce fails on your machine.

[binary.zip](https://github.com/pwndbg/pwndbg/files/5762171/binary.zip)

**Comment by el-muscovado** [comment]
@nohkoomote I had this same issue on parrot, I fixed it by removing my pwndbg install and then reinstalling it with `git clone https://github.com/pwndbg/pwndbg`

**Comment by disconnect3d** [comment]
I believe it was fixed in https://github.com/pwndbg/pwndbg/commit/4d213a1f90dd1b2f285947cf959f617f85ca5d98
