### ISSUE TITLE
start event is trigger 3 times when starting

### ISSUE THREAD

**Issue by cebrusfs** [pwndbg/pwndbg#88]
I noticed that `start` event will be trigger 3 time. The first time is by `_start_newobjfile` on `new_objfile` event. The second and the third time is by `pwndbg.events.after_reload()` which is called by `prompt_hook()` in `pwndbg/__init__.py`.

`pwndbg.events.after_reload()` will call all the function that registered by `start`, `new_objfile`, `stop` events. It will call all start function directly for the second time.
However, `_start_newobjfile` is registered in `new_objfile` event and it will be called the second time and it will call `StartEvent.on_new_objfile()`. It will call all `start` function the third time.

Some condition handling`self.running` in `StartEvent` does not work for avoiding the duplicate invoking because `prompt_hook()` will be called after `stop` event and `stop` event will set `StartEvent.running` to `False`.

```python
   def after_reload():
      if gdb.selected_inferior().pid:
          for f in registered[gdb.events.start]:
              f()
          for f in registered[gdb.events.new_objfile]:
              f()
          for f in registered[gdb.events.stop]:
              f()
```

It seems that you have tried some ways to handle the reload and start event. But it is chaos now.
I don't know which functions depend on these events and what you want to do with this issue.
It is better that create an issue for discussing rather than directly give you a dirty patch.

**Comment by zachriggle** [comment]
Check out the last few commits in the `dev` branch.  It looks like a mixture of:

1. A typo.  `on_stop` should have been `on_exit`.  We were resetting the internal state on every single-step/breakpoint instead of only when the binary exited.
2. Lack of foresight.  We need to call the `.stop` events after reload first.

The `reload` command is still really busted, but it should at least fix the `start` event.

**Comment by zachriggle** [comment]
This was fixed a while ago now.  Thanks!

**Comment by zachriggle** [comment]
See:

63d47e1105d71b05dfc022dc08825727b978a534

309df7a44705ee6276a6810e2d5edb8d012ea504

**Comment by cebrusfs** [comment]
I use the current master to test. The start event will be trigger twice now. The first time is by `start` event. The second time is by the `prompt_hook()`.

It seems that `prompt_hook()` tries to handle the change of the inferior and the thread, but the execution of this detection is after the start event. Do you think it is a good idea to force updating the prompt_hook() checking when execution the start event? I have tested that `gdb` can get the correct inferior and thread object when triggering the first time of start event.

**Comment by zachriggle** [comment]
How about now? Sorry for dropping the ball on this for a month. DEFCON and vacation.

**Comment by cebrusfs** [comment]
After DEFCON CTF, I'm on vacation. There is also an on-site CTF at the end of this month.
Because of these, I think I will be available on Sep.
