### ISSUE TITLE
Stop annoying restart service dialog.

### ISSUE THREAD

**Issue by pwndumb** [pwndbg/pwndbg#882]
**Is your feature request related to a problem? Please describe.**
is not a problem, just a improvement.
The install script make a use of apt program. The new version of debian pop a annoying restart service dialog. 
**Describe the solution you'd like**
I believe that putting this options will stop this annoying dialog. 
sudo DEBIAN_FRONTEND=noninteractive apt install -y --assume-yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"

**Comment by disconnect3d** [comment]
Hey,

Thanks for the issue. Can you show a screen of that annoying dialog? Can you check if `sudo DEBIAN_FRONTEND=noninteractive apt install -y --assume-yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"` really fixes the problem and if so, send a PR with it?
