### ISSUE TITLE
Build and publish AppImages

### ISSUE THREAD

**Issue by TheAssassin** [pwndbg/pwndbg#891]
This tool works fine. However, for first-time users, quite some set-up is typically required. First, you typically have to build a few dependencies, most notably some up-to-date gdb. Of course it's optional, but surely a good idea. Then, one can pip-install the dependencies from a `requirements.txt`. However, that's normally not a great idea; advanced Python users will always prefer to use a virtual environment of any kind. Then, one should be able to integrate the script in gdb's init config.

The provided setup script isn't great either. It makes many assumptions about how this tool should be installed: it just installs the dependencies, into the user's Python 3 environment, which is typically used by many other tools. pwndbg itself is not even installed there, but shall remain in the Git clone directory.
Of course, one could change the script to maintain a virtualenv (it's not hard at all) somewhere in the home directory, and then set up the environment to make gdb use the dependencies from there. However, there's a better solution that doesn't require any of these workarounds.

I propose to build and ship an [AppImage](https://appimage.org/) for pwndbg. Building an AppImage would have, among others, these advantages:

- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](https://docs.appimage.org/user-guide/run-appimages.html#download-make-executable-run), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional [desktop integration](https://docs.appimage.org/user-guide/run-appimages.html#integrating-appimages-into-the-desktop)
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using [AppImageUpdate](https://docs.appimage.org/introduction/software-overview.html#appimageupdate)
- Can optionally sign your AppImages (inside the file) using gpg2
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the [`--appimage-extract`](https://docs.appimage.org/user-guide/run-appimages.html#mount-or-extract-appimages) parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

AppImages could be built both for releases as well as for the main branch (so-called continuous release scheme). Automating AppImage building is relatively simple and straightforward. You can bundle all tools you need (e.g., a suitable up-to-date GDB version). This way, this project will be a lot easier to set up and use: you will just have to call `./pwndbg-x86_64.AppImage`.

The only tricky part here is bundling Python along with gdb. But I could imagine that if you let linuxdeploy-plugin-{python,conda} set up a Python environment, then build gdb against it, it should work. I've done that before.

I can provide some guidance on how to build AppImages and integrate this into GitHub actions. You can also reach out to the AppImage team, see https://docs.appimage.org/contact.html for more information.

**Comment by TheAssassin** [comment]
I wrote a build script that prepares an AppDir with a Python environment, then builds the latest GDB against it, deploys pwndbg into it and builds an AppImage for it:

```sh
> ./pwndbg-2020.07.23-31-g96df189-x86_64.AppImage 
GNU gdb (GDB) 10.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
pwndbg: loaded 193 commands. Type pwndbg [filter] for a list.
pwndbg: created $rebase, $ida gdb functions (can be used with print/break)
pwndbg> 
```

I think this shows pretty well how much easier it can be to use pwndbg. Just download the AppImage, make it executable, and run it.

The script works around a few annoyances coming from the lack of proper packaging of pwndbg (i.e., `requirements.txt` rather than a proper `setup.py`). It can always be improved, though, should pwndbg ever receive some non-`requirements.txt`/non-`setup.sh` stuff.

The AppImage will definitely need more testing on different distros to make sure it works properly (probably the distros listed in `setup.sh`). Right now it works fine on a couple Ubuntu versions I have on hand.

I'll probably file a PR soon.

**Comment by disconnect3d** [comment]
Sorry for answering so late but the main question is: do we *really* need an AppImage for Pwndbg?

Many people either install via `setup.sh`, use a Docker container or things like Nix (e.g. https://github.com/arcz/pwnix) and some distros package Pwndbg themselves like Arch (https://security.archlinux.org/package/pwndbg).

If we add AppImage build to this repo, we will have to manage it, which I'd prefer not to do. @TheAssassin are you a Pwndbg user? Couldn't you just manage an unofficial Pwndbg AppImage yourself?

Also, the `upload` build step in the AppImages PR is unacceptable:
```
  upload:
    name: Create release and upload artifacts
    runs-on: ubuntu-18.04
    needs:
      - appimage
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Inspect directory after downloading artifacts
        run: ls -alFR
      - name: Create release and upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
            chmod +x pyuploadtool-x86_64.AppImage
            ./pyuploadtool-x86_64.AppImage **/pwndbg*.AppImage*
```

The `wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage` combined with passing in a `GITHUB_TOKEN` is something that asks for a disaster - I mean, the upload tool should probably not be fetched from a third party, and if it is so, it should be verified with a hash or better, with a signature.

I will leave this issue open for a while and see if there is any more input and maybe ask Twitter about it to hear the community's voice? Let's see how it goes.

**Comment by TheAssassin** [comment]
I occassionally use pwndbg, yes, but only since I set this AppImage build up. It makes using pwndbg drastically easier. It doesn't modify stuff in my home directory, and I don't have to integrate it into my normal gdb. Instead, pwndbg behaves like a standalone tool, which I really like from a user perspective.

The goal is to get an official build up and running. I don't know who would use/trust a third-party build of such a tool. Of course, you'd have to manage this a bit, but there's plenty of other users of the build tools and you could always ask the AppImage community for help. These kinds of AppImage build scripts typically don't break often.
I _could_ of course manage my own build repo, too, but I probably won't do that. Instead I prettified my build scripts and sent a PR to contribute them upstream.

That `setup.sh` to me falls into the category "shady setup scripts". Of course it gets things up and running, but it makes assumptions about my system (like, no other GDB plugins ever needed), and it's an actual step I have to run rather than just downloading the tool and running it. Also, whenever I need another GDB plugin, I'd have to invest some "setup time" again to edit some file or change some symlink or something like that. From a user perspective, however, tools like pwndbg and gef are kind of standalone tools built on top of GDB rather than plugins for GDB.

I also don't think that any sort of package management is equal to shipping something as standalone and up-to-date as an AppImage, however that's already a LOT better than some `setup.sh`. The Arch package for instance seems to go in the same direction as my AppImage build, but it's only available on Arch, obviously. Same goes for the Nix setup. Many people don't use Nix, and many people don't want to.

The key difference of the AppImage is it's self-contained and portable. No third-party tools required: download, make executable, run. No installation, nothing.

A similar solution would be to build an official Docker container, something that you could just `docker pull` and `docker run --rm`. However, then, you have a system dependency, namely Docker. AppImages just need FUSE, which most desktops and servers have installed by default.

Many security and pentesting tools are kind of hard to use, or at least require setup effort. In the case of pwndbg (and the same goes for gef), I don't think these would be needed. Both could behave like standalone tools rather than GDB plugins, even though they are. That's IMO just an implementation detail. My goal is, when you need pwndbg, you just call its AppImage. When you need some other gdb-based tool, you call that AppImage instead.

I'd like to hear what your community thinks about having pwndbg be more like a standalone tool. I mean, I only occasionally use it. I don't know whether people actually prefer to be able to edit the scripts on the fly, etc. (Not that that would be really hard with an AppImage, you could quickly extract it and then run it from the created AppDir). The deployment should always also reflect people's use cases. But that's really the only case where the AppImage might be less useful than cloning the repo somewhere I could think of spontaneously.

________

> Also, the upload build step in the AppImages PR is unacceptable:

It's not any worse than using a third-party GitHub action. You don't hash-check these either. The tool is updated from time to time, so fetching the latest version is a good idea. You don't have to use it, though. It's just a convenience feature to provide up-to-date AppImages on every commit, as well as on release builds. I see where you are coming from, and that step is totally optional. You could still build AppImages just for integration testing.

The build scripts portable anyway. Release builds could be built on any Linux machine that has the dependencies installed, even in a Docker container, then uploaded manually.

**Comment by disconnect3d** [comment]
I am closing this issue as I am not going to support AppImage build myself.
