### ISSUE TITLE
Feature: Show context only on stop, not on every prompt (i.e. don't show context after running a command)

### ISSUE THREAD

**Issue by WeSeekAfterKnowledge** [pwndbg/pwndbg#906]
Currently, every time we show the prompt, we show the context.

It would be nice if we don't show it again after entering a single command, as this makes it hard to keep track of what commands have been executed (since there's always a context in the middle).

Is there a fiddly bit for this behavior already?  If not, we should make one such that context only shows on stop.  The user can always print it again with `context`.

**Comment by mebeim** [comment]
> we should make one such that context only shows on stop. The user can always print it again with context.

Hmm, this is the current behavior for me on a fresh pwndbg installation (commit 44471dfd911f969f9b311fb7dcf9f0a0770ff12f) :thinking:

**Comment by WeSeekAfterKnowledge** [comment]
Can't repro this anymore, not sure what the issue was.  Closing.
