### ISSUE TITLE
pip sudo

### ISSUE THREAD

**Issue by Total-Control-9985** [pwndbg/pwndbg#916]
### Description
WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv

### My setup
Ubuntu 20.04
Gdb:      9.2
Python:   3.8.5 (default, Jan 27 2021, 15:41:15)  [GCC 9.3.0]
Pwndbg:   1.1.0 build: 44471df
Capstone: 4.0.1024
Unicorn:  1.0.2

**Comment by disconnect3d** [comment]
Feel free to propose a setup.sh that allows one to use a virtual environment. I will be happy to merge such, if it doesn't break the current workflow too.

**Comment by disconnect3d** [comment]
Closing it for now.

**Comment by gogo2464** [comment]
almost solved : https://github.com/pwndbg/pwndbg/issues/940
