### ISSUE TITLE
ERROR: Could not find ELF base! while debugging heap note pwnables

### ISSUE THREAD

**Issue by h4x5p4c3** [pwndbg/pwndbg#917]
My setup :

pwndbg: loaded 195 commands. Type pwndbg [filter] for a list.
pwndbg: created $rebase, $ida gdb functions (can be used with print/break)
Reading symbols from ./0ctfbabyheap...
(No debugging symbols found in ./0ctfbabyheap)
pwndbg> version
Gdb:      10.1
Python:   3.9.4 (default, Apr 20 2021, 15:51:38)  [GCC 10.2.0]
Pwndbg:   1.1.0 build: 44471df
Capstone: 4.0.1024
Unicorn:  1.0.2
Starting program: /home/h4x5p4c3/Downloads/tmp/0ctfbabyheap
ERROR: Could not find ELF base!
===== Baby Heap in 2017 =====
1. Allocate
2. Fill
3. Free
4. Dump
5. Exit

required files : https://github.com/guyinatuxedo/nightmare/tree/master/modules/28-fastbin_attack/0ctf_babyheap

**Comment by CptGibbon** [comment]
git bisect says this was introduced in 707fe12e3db018240a44c8c2c6b0a7e321401660
It only seems to happen when the debugee is run for the 1st time, subsequent runs within the same session don't print the error.
