### ISSUE TITLE
link_map structure should get walked

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#92]
For dynamically-linked binaries run under qemu-user, we have no mechanism to autodetect other libraries.

We should support extracting the `link_map` from the linker, via the GOT/PLT, or via DT_DEBUG segments.

This will only be possible if we can get a local copy of the ELF on disk, since we can't find those, since the headers are not resident in memory.

**Comment by disconnect3d** [comment]
Not sure if we need this feature anymore.
