### ISSUE TITLE
Colorization of pwndbg output on blog posts

### ISSUE THREAD

**Issue by caprinux** [pwndbg/pwndbg#925]
A method to colorize pwndbg output on a jekyll blog, i.e. extracting pwndbg highlighting

**Comment by WeSeekAfterKnowledge** [comment]
Your best bet is something like `ansifilter` and a script, e.g.:

`gdb .... | ansifilter --fragment -H` to generate an HTML fragment you can easily include.

**Comment by disconnect3d** [comment]
Or, implementing some kind of "copy with colors" in your terminal emulator. I did something like this for terminator back then to be able to copy pwndbg output with colors to LaTeX for my master thesis, heh.

**Comment by disconnect3d** [comment]
> Your best bet is something like ansifilter and a script, e.g.:

Actually, one can modify the `context` command so it overwrites the `print` function and dumps the colored output into a file, or, to pass it directly to `ansifilter` (or sth similar).

I don't think we will implement such feature info Pwndbg, however, its an interesting extension. If you ever work on that @caprinux please dump here a link, so we can include it e.g. in a README.

**Comment by caprinux** [comment]
Gotcha, thanks!

**Comment by disconnect3d** [comment]
Closing this issue as its unlikely we will add such feature directly to pwndbg
