### ISSUE TITLE
Add support for Akita ARM board

### ISSUE THREAD

**Issue by doctorjei** [pwndbg/pwndbg#930]
I have been working with the "akita" ARM profile in QEMU. When I try to boot from a ROM file, A "KeyError: 'iwmmxt' exception occurs. This does not happen with regular gdb-multiarch.

=Expected behavior=
It works. Here's the result in vanilla gdb-multiarch:

    (gdb) tar remote localhost:1234
    Remote debugging using localhost:1234
    warning: No executable has been specified and target does not support
    determining executable automatically.  Try using the "file" command.
    0x00000000 in ?? ()
    (gdb) x/i $pc
    => 0x0: andeq   r0, r0, r0
    (gdb) _

=Actual behavior=
KeyError. Here's the stack trace:

    pwndbg> target remote localhost:1234
    Remote debugging using localhost:1234
    warning: No executable has been specified and target does not support
    determining executable automatically.  Try using the "file" command.
    0x00000000 in ?? ()
    Exception occurred: Error: 'iwmmxt' (<class 'KeyError'>)
    For more info invoke `set exception-verbose on` and rerun the command
    or debug it by yourself with `set exception-debugger on`
    Python Exception <class 'KeyError'> 'iwmmxt':
    Exception occurred: Error: 'iwmmxt' (<class 'KeyError'>)
    For more info invoke `set exception-verbose on` and rerun the command
    or debug it by yourself with `set exception-debugger on`
    Python Exception <class 'KeyError'> 'iwmmxt':
    Exception occurred: Error: 'iwmmxt' (<class 'KeyError'>)
    For more info invoke `set exception-verbose on` and rerun the command
    or debug it by yourself with `set exception-debugger on`
    Python Exception <class 'KeyError'> 'iwmmxt':
    pwndbg> set architecture arm
    The target architecture is assumed to be arm
    Exception occurred: Error: 'iwmmxt' (<class 'KeyError'>)
    For more info invoke `set exception-verbose on` and rerun the command
    or debug it by yourself with `set exception-debugger on`
    Python Exception <class 'KeyError'> 'iwmmxt':
    pwndbg> set exception-verbose on
    Set whether to print a full stacktrace for exceptions raised in Pwndbg commands to True
    Traceback (most recent call last):
      File "/home/jjb/pwndbg/pwndbg/events.py", line 165, in caller
        func()
      File "/home/jjb/pwndbg/pwndbg/regs.py", line 447, in update_last
        M.last = {k:M[k] for k in M.common}
      File "/home/jjb/pwndbg/pwndbg/regs.py", line 340, in common
        return arch_to_regs[pwndbg.arch.current].common
    KeyError: 'iwmmxt'`

In both cases, starting up the qemu machine was done with this line:
`qemu-system-arm -M akita --bios C750DUMP.ROM -s -S`

**Comment by disconnect3d** [comment]
I think you would have to add this architecture to pwndbg and describe its register set etc similarly to https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/regs.py#L136-L153
