### ISSUE TITLE
ERROR :: Exception occurred: dq: Cannot convert value to long. (<class 'gdb.error'>)

### ISSUE THREAD

**Issue by 0xlilith** [pwndbg/pwndbg#932]
### Description

ERROR: `Exception occurred: dq: Cannot convert value to long. (<class 'gdb.error'>)`
 i am getting this error while running the `dq` command

### Steps to reproduce
i have a variable named target which has a string value "XXXXXX" and when i try to read its address using the dq command i get the error. 

Gdb session history:
vis
dq target 
dq target 
dq target
dump target
help dump
help dq
dump N qwords
help dump
xinfo target 

### My setup

Platform: Linux-5.11.0-22-generic-x86_64-with-glibc2.33
Gdb:      10.1.90.20210411-git
Python:   3.9.5 (default, May 11 2021, 08:20:37)  [GCC 10.3.0]
Pwndbg:   1.1.0 build: a79c85b
Capstone: 4.0.1024
Unicorn:  1.0.2
This GDB was configured as follows:
   configure --host=x86_64-linux-gnu --target=x86_64-linux-gnu
             --with-auto-load-dir=$debugdir:$datadir/auto-load
             --with-auto-load-safe-path=$debugdir:$datadir/auto-load
             --with-expat
             --with-gdb-datadir=/usr/share/gdb (relocatable)
             --with-jit-reader-dir=/usr/lib/gdb (relocatable)
             --without-libunwind-ia64
             --with-lzma
             --with-babeltrace
             --with-intel-pt
             --with-mpfr
             --with-xxhash
             --with-python=/usr (relocatable)
             --with-python-libdir=/usr/lib (relocatable)
             --with-debuginfod
             --without-guile
             --enable-source-highlight
             --with-separate-debug-dir=/usr/lib/debug (relocatable)
             --with-system-gdbinit=/etc/gdb/gdbinit
             --with-system-gdbinit-dir=/etc/gdb/gdbinit.d

**Comment by disconnect3d** [comment]
The `dq` command expects an address, not a symbol. Use `dq &target`.

There was a discussion here how it should work: https://github.com/pwndbg/pwndbg/issues/788

**Comment by disconnect3d** [comment]
Anyway, the error is not nice, I'll think of how to fix that.

**Comment by 0xlilith** [comment]
okie thank you <#
