### ISSUE TITLE
Heap inspection without libc debug symbols

### ISSUE THREAD

**Issue by umutoztunc** [pwndbg/pwndbg#937]
The commands for heap inspection currently requires libc debug symbols. However, when the binary is modified with `patchelf` to use a specific interpreter like this file:

```console
$ file target
target: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter ./ld-2.27.so, for GNU/Linux 3.2.0, BuildID[sha1]=b722ce3ea0937340d3a56165c760ac5ef9ae0014, not stripped

$ ldd target
	linux-vdso.so.1 (0x00007fff3b7b4000)
	./libc-2.27.so (0x00007f774a9c4000)
	./ld-2.27.so => /lib64/ld-linux-x86-64.so.2 (0x00007f774afbd000
```

Then, pwndbg is unable to use heap commands even though `libc6-dbg` and `libc6-dbg:i386` are installed:

```
pwndbg> heap
heap: This command only works with libc debug symbols.
They can probably be installed via the package manager of your choice.
See also: https://sourceware.org/gdb/onlinedocs/gdb/Separate-Debug-Files.html

E.g. on Ubuntu/Debian you might need to do the following steps (for 64-bit and 32-bit binaries):
sudo apt-get install libc6-dbg
sudo dpkg --add-architecture i386
sudo apt-get install libc-dbg:i386
```

This is also mentioned in #924.

The solution I found is to use `patchelf` to change interpreter. However, when I try to use `gef`, I realized that it is able to run heap commands on this file without changing the interpreter:

![image](https://user-images.githubusercontent.com/32958854/128200829-f16dc11a-17dd-4732-b601-3ed3aa8e780e.png)

GEF can simply work in all conditions without requiring debug symbols. I have investigated how they do this a little bit. Here is their [heap_base](https://github.com/hugsy/gef/blob/251761696b043088a5ebd31c35ad93205c06ba7a/gef.py#L9939) function:

![image](https://user-images.githubusercontent.com/32958854/128202211-7c01dd7a-c491-4469-95c7-38cdd7d90e2b.png)

It looks like they are parsing the heap base address from the memory. I suggest implementing the same strategy.

This is also useful for systems like arch linux where there is no debug symbols package available and you have to build the package with debugging options yourself.

**Comment by disconnect3d** [comment]
Hey, yeah, it would be awesome to address/fix this. Would you maybe like to try implementing this and sending a PR?

In case you need any help, you can hit me on our Discord server :).

**Comment by umutoztunc** [comment]
Sure! I will implement it soon.

**Comment by ghsi10** [comment]
Is there anyone working on it?

**Comment by disconnect3d** [comment]
@ghsi10 @umutoztunc didn't implement it in the end, so feel free to work on it if you want to :)

**Comment by ghsi10** [comment]
It seems a bit complex to me as a first step... But I think it's a really important feature.

**Comment by umutoztunc** [comment]
We were brainstorming on the discord server about different ways to approach this and their respective pros and cons. I think first having a lookup table for precomputed symbols is a great idea. However, if we use file hashes as keys, people can just modify 1 byte to make it not work. Maybe grepping the version as string from the file is more reliable way of doing this but it can be fooled again. Another thing to consider is how to handle the lookup thing, are we going to host a server for it or are we just going to include everything with our binary as offline?

The way GEF does is not reliable as we discussed on the discord. However, we can still implement it as a fallback method as a last resort which is better than nothing. I still want to implement this sometime if we can decide the way to go. I am planning to start thinking about it soon since I was busy for the last couple of months.

**Comment by gsingh93** [comment]
@disconnect3d @lebr0nli can this be closed now? Or is there more work to be done on using heap commands without debug symbols?

**Comment by disconnect3d** [comment]
Yes, this works now with `set resolve-heap-via-heuristic on`. There are still some improvements we can make to this, but it should generally work in more cases than in GEF afaik.
