### ISSUE TITLE
Feature: Telescope / argv / envp / string printing for all-ASCII-printable strings

### ISSUE THREAD

**Issue by WeSeekAfterKnowledge** [pwndbg/pwndbg#938]
The `argv` and `envp` commands would be much more useful if their length were extended (by default) when reading strings and ALL of the characters of the string are printable -- not just nonnull.

Here's an example where `argv[0]` and `argv[1]` are truncated, despite them only containing printable, ASCII, non-null characters.  I think we infer from some GDB setting how far to read for strings (since we wouldn't want to print `"A"*4096` to the screen) but I think we should relax it a bit.

The default behavior is clearly weird, since we show ALL of `'EDITOR=nano'` but only the first four bytes of `argv[0]` (which was e.g. `/home/user/challenges/somechall/binary`).

```
pwndbg> argc
2
pwndbg> argv
00:0000│   0xffffcc24 —▸ 0xffffcde9 ◂— 0x6d6f682f ('/hom')
01:0004│   0xffffcc28 —▸ 0xffffce20 ◂— 0x61616161 ('aaaa')
02:0008│   0xffffcc2c ◂— 0x0
pwndbg> envp
00:0000│   0xffffcc30 —▸ 0xffffce31 ◂— 0x49424544 ('DEBI')
01:0004│   0xffffcc34 —▸ 0xffffce50 ◂— 'EDITOR=nano'
02:0008│   0xffffcc38 —▸ 0xffffce5c ◂— 0x454d4f48 ('HOME')
03:000c│   0xffffcc3c —▸ 0xffffce70 ◂— 'HOSTNAME=ctf'
...
```

**Comment by gsingh93** [comment]
Dup of https://github.com/pwndbg/pwndbg/issues/368
