### ISSUE TITLE
Cannot get GDB to work with pwndbg and Capstone

### ISSUE THREAD

**Issue by afreeborn** [pwndbg/pwndbg#94]
Hello,

When I try to run GDB, I get the following stack trace below. This was from a fresh clone from Git and running sudo ./setup.sh. Here's my environment:

uname -a
Linux ubux64DVRF 4.4.0-28-generic #47-Ubuntu SMP Fri Jun 24 10:09:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

GNU gdb (Ubuntu 7.11-0ubuntu1) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Traceback (most recent call last):
  File "/home/andy/Downloads/pwndbg/gdbinit.py", line 13, in <module>
    import pwndbg # isort:skip
  File "/home/andy/Downloads/pwndbg/pwndbg/__init__.py", line 9, in <module>
    import pwndbg.android
  File "/home/andy/Downloads/pwndbg/pwndbg/android.py", line 5, in <module>
    import pwndbg.color
  File "/home/andy/Downloads/pwndbg/pwndbg/color.py", line 11, in <module>
    import pwndbg.enhance
  File "/home/andy/Downloads/pwndbg/pwndbg/enhance.py", line 18, in <module>
    import pwndbg.disasm
  File "/home/andy/Downloads/pwndbg/pwndbg/disasm/__init__.py", line 34, in <module>
    'arm':     Cs(CS_ARCH_ARM, CS_MODE_ARM),
  File "/usr/local/lib/python3.5/dist-packages/capstone/__init__.py", line 661, in __init__
    raise CsError(CS_ERR_VERSION)
capstone.CsError: <exception str() failed>
(gdb) quit

**Comment by afreeborn** [comment]
If I comment out the raise error line (raise CsError(CS_ERR_VERSION)) in "/usr/local/lib/python3.5/dist-packages/capstone/__init__.py" on line 661, pwndbg works. I'm not sure what the issue may be.

**Comment by zachriggle** [comment]
You have conflicting versions of Capstone installed.  Remove all versions of Capstone from your system, and re-run `setup.sh`.
