### ISSUE TITLE
recommend to use virtualenv in the readme 

### ISSUE THREAD

**Issue by gogo2464** [pwndbg/pwndbg#940]
**Is your feature request related to a problem? Please describe.**
When I installed pwndbg I did not worry on what was in the file setup.sh. Then I did not use virtualenv and I did not know that pip has been used. Pip like that may break the system and is not recommended.

**Describe the solution you'd like**
A recommendation in the readme to use virtualenv or at least a warning about pip.

**Describe alternatives you've considered**

**Additional context**

**Comment by disconnect3d** [comment]
@gogo2464 hey, thanks for the issue; I agree its better to use a virtualenv but then it requires the user to always run in virtualenv when they start GDB (to use Pwndbg). This is fine, but we have to inform on this properly.

Can you maybe send a PR with those things described properly in the README?

**Comment by gogo2464** [comment]
Nice assign me to this issue. Or why not even modify the bash script to use virtualenv. I will see.

**Comment by gogo2464** [comment]
@disconnect3d I have made 2 prs. choose the one you prefer.

**Comment by disconnect3d** [comment]
We decided to not use virtualenv or/and the user can choose by themself

**Comment by viciu** [comment]
@gogo2464 pls check https://github.com/pwndbg/pwndbg/issues/1035
