### ISSUE TITLE
uplaod pwndbg to the repo pypi to allow people to do pip install pwndbg

### ISSUE THREAD

**Issue by gogo2464** [pwndbg/pwndbg#943]
**Is your feature request related to a problem? Please describe.**
People could be frustruated when installed the file with setup.sh. This is basically a bash file made to install with pip. Trough the issue with virtualenv is now solved, we should also allow more expert dev to easily install from pipy repo with pip. The idea is that an expert in python could know immediately how to install.

**Describe the solution you'd like**
pip install pwndbg should do the stuff.

**Describe alternatives you've considered**
Also keep the bash file but do not keep it as only way to install. The readme should show the option to install with bash file as an easy way for people who do not master pip.

**Additional context**

**Comment by gogo2464** [comment]
Assign me to this issue please. I have already started.

**Comment by gogo2464** [comment]
I did it! I made some change in the code. I will submit the PR!

Just see https://pypi.org/project/pwndbg/0.1/

**Comment by gogo2464** [comment]
I have deleted the pwndbg from pipy because you are not the owner. Please could you make an account @zachriggle please?

**Comment by disconnect3d** [comment]
Hey, I agree that being able to install pwndbg via pypi is an awesome feature. Let's do that :).

However, I don't think we want to rename pwndbg -> pwndbglib as suggested in the PR. The package isn't going to be used outside of being a GDB plugin and even if, I don't think we want to change the namespace.

**Comment by gogo2464** [comment]
I see what you mean. I actually need to do that because a file know as pwndbg must be set at the root of the project.

**Comment by disconnect3d** [comment]
>  a file know as pwndbg must be set at the root of the project.

Wait, why?

**Comment by gogo2464** [comment]
I mean a folder know as pwndbg must be set at the root of the project. Not a file. This folder will contain some files to generate the file to upload to pypi. See https://medium.com/@joel.barmettler/how-to-upload-your-python-package-to-pypi-65edc5fe9c56

**Comment by WeSeekAfterKnowledge** [comment]
It is not possible for Pwndbg to be installable via `pip`, because we have additional dependencies on system packages that have to be installed via the package manager (apt, yum, etc).

Because of this, Pwndbg will continue to require running `setup.py`.  Feel free to work with package maintainers to get Pwndbg added as a real package.  Arch linux has this already: 
https://archlinux.org/packages/community/any/pwndbg/
