### ISSUE TITLE
pwndbg prints an error when calling 'disasm' and pwntools is not installed.

### ISSUE THREAD

**Issue by ekse** [pwndbg/pwndbg#95]
The pwndbg setup.sh does not install pwntools. Calling disasm without it installs just prints an error.

```
pwndbg> disasm
Traceback (most recent call last):
  File "/home/ekse/git/pwndbg/pwndbg/commands/__init__.py", line 54, in __call__
    return self.function(*args, **kwargs)
  File "/home/ekse/git/pwndbg/pwndbg/commands/shell.py", line 76, in handler
    os.execvp(cmd, (cmd,) + a)
  File "/usr/lib/python3.5/os.py", line 615, in execvp
    _execvpe(file, args)
  File "/usr/lib/python3.5/os.py", line 660, in _execvpe
    raise last_exc.with_traceback(tb)
  File "/usr/lib/python3.5/os.py", line 650, in _execvpe
    exec_func(fullname, *argrest)
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by zachriggle** [comment]
Correct, the `disasm` tool shells out to Pwntools.  This will also happen if there's no e.g. `which` binary and you invoke the `which` command.

Adding a "Command not found" message would be even more confusing, IMHO.

**Comment by ekse** [comment]
I think an error message "executable not found, please install pwntools"  for these commands would be better. This error when calling 'disasm' is confusing since it is really similar to the gdb command 'disassemble'.

**Comment by zachriggle** [comment]
Fixed with 2d7ddf224e0d23a32a471ab38b08a1a3e7bf6628

**Comment by anthraxx** [comment]
actually a problem is that binjitsus 'disasm' command is a very generic name and currently conflicts with f.e. the ```distorm``` package hat already provides a binary names such.

**Comment by zachriggle** [comment]
It doesn't conflict at all, it just shells out to the command.

It does whatever the command installed on your system does.  No functionality is tied to any particular implementation.

**Comment by zachriggle** [comment]
Edit: Unless you mean the fact that Pwntools/Binjitsu provides any tool of that name at all is a problem, in which case I contest the claim.

See https://github.com/Gallopsled/pwntools/issues/573 for more information. tl;dr WONTFIX.

**Comment by anthraxx** [comment]
yes, that's what i meant. no need to get so harsh about this, did I ever offend you? I just try to show you a different point of view to a particular situation.

**Comment by zachriggle** [comment]
Nope, no offense at all ^_^.  It's just not something that I intend to fix, as it's not a problem.

**Comment by anthraxx** [comment]
well you're right, this place is the wrong one to discuss this as it does not belong here and everything here is fine. This topic is exactly the link you posted, thx
