### ISSUE TITLE
xinfo command doesn't like anonymous page names

### ISSUE THREAD

**Issue by CptGibbon** [pwndbg/pwndbg#957]
The naming of anonymous memory pages introduced in 462eb53 is cool but it doesn't play nicely with the `xinfo` command.
The following figure shows `xinfo` behaving correctly when displaying info on a regular mapping, followed by an error when used with an anonymous mapping.

![xinfo](https://user-images.githubusercontent.com/16000770/133327381-c4f9d13b-5d20-4fd3-80b5-01aad51a5387.png)

`xinfo` uses `page.is_memory_mapped_file()` to determine whether a page is file backed, this in turn is based on the object name:
https://github.com/pwndbg/pwndbg/blob/648c7f014e25a2944ee40891000fb43031182e51/pwndbg/memory.py#L409-L411

Because 462eb53 names anonymous pages that previously had no name, the above function reports them as memory mapped files which `xinfo` tries to open.

A possible solution could be to enclose the anonymous page names in square brackets, which `is_memory_mapped_file()` ignores.

**Comment by disconnect3d** [comment]
Yeah, I saw a similar code with `'['` check before. I think we should rename anon pages to `[<address>]` instead
