### ISSUE TITLE
The integer argument in ArgparsedCommand will be consider as hex

### ISSUE THREAD

**Issue by cebrusfs** [pwndbg/pwndbg#98]
Give you an example.
```
> hexdump $sp 9
+0000 0x7fffffffdc70  d0 74 ff f7  ff 7f 00 00  18                        |.t..|....|.   |    |
+0009 0x7fffffffdc79
> hexdump $sp 10
+0000 0x7fffffffdc70  d0 74 ff f7  ff 7f 00 00  18 dd ff ff  ff 7f 00 00  |.t..|....|....|....|
+0010 0x7fffffffdc80
```

Because in `pwndbg/commands/__init__.py`, you will try to call `fix_int` if the argument type is `int`, then the `fix_int()` use `gdb.parse_and_eval()` to fix the integer (maybe you want to do some symbol resolution via gdb), but it will consider the integer is hex.
```
> python print(gdb.parse_and_eval('10'))
0x10
```
I think the input should be checked. If it is a pure integer string, then just convert it as integer (or use `try except` to convert it first.) You accept this kind of patch, I can make a PR for this.

gdb version (Ubuntu 16.04 build-in):
```
$ gdb --version
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
```

**Comment by zachriggle** [comment]
We set the radix to 16 on purpose.

You can unset this if you like :)

**Comment by zachriggle** [comment]
https://github.com/pwndbg/pwndbg/blob/master/pwndbg/__init__.py#L123

**Comment by cebrusfs** [comment]
Ok, I don't know that is a feature.
Thanks for providing code for reference.

So do you all use hex for normally used? even when typing command?

**Comment by zachriggle** [comment]
Yep! If you need decimal you can type eg "10.0" or something like that.

The reason I do this is because of how Windbg works. Hex is default,
everything else uses the "0n1234" notation for decimal 1234.

**Comment by cebrusfs** [comment]
Got it! I'm pretty uninformed. I have never known there is some tool make this as default.
Thanks for explaining. :)
