### ISSUE TITLE
关于升级gdb，然后pwndbg不兼容的问题

### ISSUE THREAD

**Issue by eeeeeeeeeeeeeeeea** [pwndbg/pwndbg#980]
Please make sure you have checked that the issue persists on LATEST pwndbg version.

Below is a template for BUG REPORTS.
Don't include it if this is a FEATURE REQUEST.
-->

**Comment by caprinux** [comment]
问题在哪里呢？ 你可以提供截图吗？
我们需要知道问题在哪里才可以帮助你。：）

**Comment by eeeeeeeeeeeeeeeea** [comment]
![gdb](https://user-images.githubusercontent.com/82768425/139012468-07f297c7-89f6-4943-b911-0f069fd14a66.jpg)
是这个样子的，好像是pwndbg的配置文件的问题

**Comment by caprinux** [comment]
你可以在GDB里面执行
`pi import sys; print(sys.version)`
然后拍个照片吗

**Comment by eeeeeeeeeeeeeeeea** [comment]
![gdb](https://user-images.githubusercontent.com/82768425/139013588-3452fc2f-451a-4a55-a6f6-1ca350ba178d.jpg)

**Comment by caprinux** [comment]
![image](https://user-images.githubusercontent.com/76640319/139013663-05560695-3f5b-4476-afea-89db7a4f8351.png)

你要一起执行

**Comment by eeeeeeeeeeeeeeeea** [comment]
![gdb](https://user-images.githubusercontent.com/82768425/139013934-68a6c37a-7d84-4694-a166-7d212d1efd02.jpg)

**Comment by caprinux** [comment]
你的python应该是python3不是python2.
你在安装GDB的时候要加上
`--with-python=/usr/bin/python3`

**Comment by eeeeeeeeeeeeeeeea** [comment]
![gdb](https://user-images.githubusercontent.com/82768425/139015140-11ba2b96-f300-4570-baf5-b4f30353caad.jpg)
按理说是python2呀，emmm

**Comment by caprinux** [comment]
GDB的扩展，比如说pwndbg和gef，都需要python3来运作。
如果你从源头安装的话，GDB会利用 /usr/bin/python， 可是你的/usr/bin/python 是 python2，不适合pwndbg。
所以你安装的时候需要加上 `--with-python=/usr/bin/python3` GDB 才后懂得利用 python3。

_对不起我的华语不怎么好哈哈_

**Comment by eeeeeeeeeeeeeeeea** [comment]
牛，谢谢谢谢，师傅是台湾的？这环境问题搞了好几天了，麻了，gdb低版本我在调试的时候有时候会没有符号表(比如是call 0x55***********)，而我用ubuntu20，同一个脚本调试，就是call printf，这个问题是gdb版本的问题嘛，

**Comment by caprinux** [comment]
不是的哈哈，我是新加坡人 :)
我不太清楚你在问的问题，可是听起来，可能是你GDB的版本（请问是什么版本呢？）但也可能是你在debug的应用的问题。
我的个人建议就是用最更新的版本10.2 或 11.1，问题少很多。
你可以在这里找到全部的版本 https://ftp.gnu.org/gnu/gdb/
我不太清楚问题的细节，如果有截图或应用就可以更缜密的解析问题。

**Comment by eeeeeeeeeeeeeeeea** [comment]
？？？我有个朋友在新加坡高三hhh，我再调一下试试，估计是gdb的问题，我用peda调试有符号表的，师傅能给个联系方式嘛hhhh

**Comment by eeeeeeeeeeeeeeeea** [comment]
谢谢啦

**Comment by caprinux** [comment]
没问题！你可以在 Discord 找到我 我的用户名是 @capri#7268，如果你需要联络我就可以在discord上发给我一个简讯。
你也可以加入我们pwndbg的官方的社会！

如果没有别的问题就可关这个议题：）
