### ISSUE TITLE
Linting and Auto Format

### ISSUE THREAD

**Issue by oneNutW0nder** [pwndbg/pwndbg#990]
Opening this up for discussion on linting and format styles. When browsing through the code `pylint` is not shy about showing all of the linting issues:

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/29211904/145149129-62075d71-d7ba-4bb1-83fb-1be08d538a02.png">

This is just an example from `pwndbg/chain.py`. To be clear, I am not suggesting that we resolve all of the linter issues but I think there should be something defined moving forward. We can create a standard linting configuration with `pylint` through the use of a `.pylintrc` file (https://pylint.pycqa.org/en/latest/user_guide/run.html).

I would also like to suggest the use of a code formatting tool like `black` to automatically keep the code formatted in a standardized way. 

I look forward to the discussion 😄

**Comment by oneNutW0nder** [comment]
Relevant information about `git blame` issues that may come up: https://stackoverflow.com/questions/53502654/how-do-i-run-a-code-formatter-over-my-source-without-modifying-git-history

There are solutions to this issue below the most up voted comment.

**Comment by gsingh93** [comment]
It would definitely be helpful to have some autoformatting configuration. While I'm trying to add features to the code, my editor keeps autoformatting everything (which is a good thing), but then I end up with a bunch of changes unrelated to the feature I'm adding, which makes for a messy PR.

I really don't care which tool or configuration we use, as long as there's something that always gives us the same style code everywhere without any extra thought.

My current configuration uses `yapf` with this config:
```
[style]
based_on_style = facebook
split_before_bitwise_operator = true
split_before_logical_operator = true
```

I can go ahead and make a PR adding a `.style.yapf` file with this configuration, and on that PR if anyone has objections to this configuration or thinks using another tool like `black` is a better idea, we can switch to that (although I'm not as familiar with `black`'s configuration options).

I'm not familiar with [Github Action workflows](https://docs.github.com/en/actions/using-workflows#creating-a-workflow-file), but we can then add that to help keep all the code consistent.

**Comment by gsingh93** [comment]
Ah, it looks like there's already a `setup.cfg` that provides `pep8` formatting. So I can skip adding the `yapf` config, and maybe the only action left for this issue is to get a Github Action for it working.

**Comment by disconnect3d** [comment]
We are currently running `isort`, `black` and `pyflake8`. I think we can close this for now.

https://github.com/pwndbg/pwndbg/blob/d4850beecc8825308d24a5c371e9fa7147898c3b/.github/workflows/lint.yml#L27-L33
