### ISSUE TITLE
Python Exception <class 'gdb.MemoryError'> Cannot access memory at address 0x0

### ISSUE THREAD

**Issue by D1ag0n-Young** [pwndbg/pwndbg#995]
When debugging a program, I found that many commands are not available after loading, such as heapinfo, etc., prompting the following information:

```bash
Python Exception <class'gdb.MemoryError'> Cannot access memory at address 0x0:
Python Exception <class'gdb.error'> Error occurred in Python: Cannot access memory at address 0x0:
Error occurred in Python: Error occurred in Python: Cannot access memory at address 0x0
```
Where is this reason? There is a memory area mapped by the mmap function in the program. Does it have anything to do with this? 
Attach the program（The environment is libc-2.31.so）
[attachment.zip](https://github.com/pwndbg/pwndbg/files/7778059/attachment.zip)

**Comment by gsingh93** [comment]
I can't reproduce this, the `heap` command works fine for me:
```
pwndbg> heap
Allocated chunk | PREV_INUSE
Addr: 0x555555559000
Size: 0x291

Allocated chunk | PREV_INUSE
Addr: 0x555555559290
Size: 0xa1

Top chunk | PREV_INUSE
Addr: 0x555555559330
Size: 0x20cd1
```

There have been a lot of changes in the last year, so this probably got fixed. If you can still reproduce it, feel free to reopen this issue.
